### ISSUE TITLE
Unknown error, GetSpecificPortMappingEntry() failed

### ISSUE THREAD

**Issue by maxiedaniels** [miniupnp/miniupnp#100]
UPNPC isn't working with my router for some reason... I've updated to the latest build..

This is what it's saying. Any ideas? Thanks!
```
List of UPNP devices found on the network :
 desc: http://192.168.1.64:80/description.xml
 st: urn:schemas-upnp-org:device:basic:1

 desc: http://192.168.1.64:80/description.xml
 st: uuid:2f402f80-da50-11e1-9b23-00178814ba4e

 desc: http://192.168.1.64:80/description.xml
 st: upnp:rootdevice

UPnP device found. Is it an IGD ? : http://192.168.1.64:80/
Trying to continue anyway
Local LAN ip address : 192.168.1.76
GetExternalIPAddress failed.
GetSpecificPortMappingEntry() failed with code -1 (Miniupnpc Unknown Error)
```

**Comment by miniupnp** [comment]
192.168.1.64 doesn't look like a IGD.
What it your router IP and brand/model ?

**Comment by miniupnp** [comment]
I'm closing now.
Feel free to reopen with the following information : IP / brand / model of your router, content of the root description (would have been http://192.168.1.64:80/description.xml if 192.168.1.64 was your router)

**Comment by maxiedaniels** [comment]
That's the weird part. My router is 192.168.1.1.

**Comment by miniupnp** [comment]
UPnP on your router may not be enabled.
And the device with IP 192.168.1.64 has UPnP
