### ISSUE TITLE
parsing LAN address broken with IPv6 enabled

### ISSUE THREAD

**Issue by stromnet** [miniupnp/miniupnp#102]
Hi,

when building miniupnpd with IPv6 enabled the local IPv4 address parsing fails. I suspect d916ce286a23bf2e6a06fd939621621f21d81188 is to blame, around line 781.

**Comment by miniupnp** [comment]
in which context do you have the bug ?
please note that with IPv6 enabled, you should use interface names (such as eth0) instead of IPv4 adresses for many options

**Comment by stromnet** [comment]
Actually, I probably reported the wrong error here... 
It all begun with the error "NAT-PMP/PCP packet sender %s not from a LAN, ignoring", with an IP (v4) which is present in the interface specified in the configuration file (yes, I had an interface, not IP). This was with IPv6 enabled.

I then changed the conf to use IP address instead, at which time I got the problems reported in this ticket, which I assume was expected.

I digged a bit further now, and just found the actual issue. The interface was a FreeBSD vlan interface with carp, which means it has two IPs, in my case 172.28.2.125/25 and an alias 172.28.2.1/32 (from carp).
miniupnpd picked up 172.28.2.1**/32**, and naturally get_lan_for_peer did not find any lanaddrs when it tried to match against an IP in the network. 

I think it works when I use "vlan11/25" as interface name.. The iPad I'm using for test refuses to send any PMP requests now so I cannot really verify this, but adding some printf's indicates that the lan addr is setup as expected (and I don't see anything in the immediate code around which indicates otherwise).

**Comment by miniupnp** [comment]
have a look at testgetifaddr / getifaddr.c and see if there is something to change here !

**Comment by stromnet** [comment]
# ./testgetifaddr vlan11
    Interface vlan11 has IP address 172.28.2.1.
    addr=172.28.2.1 mask=255.255.255.255
    Interface vlan11 has IPv6 address [2001:xxxx:2::125].


This is with IPv6 enabled. This is my current config:

    # ifconfig vlan11
    vlan11: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=103<RXCSUM,TXCSUM,TSO4>
	ether 00:22:4d:6b:b1:5b
	inet6 fe80::222:xxxx:xx%vlan11 prefixlen 64 scopeid 0x8 
	inet 172.28.2.1 netmask 0xffffffff broadcast 172.28.2.1 vhid 11 
	inet6 2001:xxx:2::1 prefixlen 64 vhid 11 
	inet 172.28.2.125 netmask 0xffffff80 broadcast 172.28.2.127 
	inet6 2001:xxx:2::125 prefixlen 64 
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	media: Ethernet autoselect (1000baseT <full-duplex>)
	status: active
	vlan: 11 parent interface: em0
	carp: MASTER vhid 11 advbase 1 advskew 0


I guess getifaddr would have to be reworked totally in order to return multiple IPs/masks. One workaround would be to find the smallest mask, but that is just error prone (and invalid, in case the alias/mask is for another network).

For my purposes, it works good enough with specifying vlan11/25 in the configuration file. As long as that isn't removed, I don't have an explicit need for autodetection in this edge case.

**Comment by miniupnp** [comment]
the current code is assuming 1 IF = 1 IP (v4)
that would be a big work to change that.
