### ISSUE TITLE
miniupnpc native build warnings on fedora 21

### ISSUE THREAD

**Issue by amjuarez** [miniupnp/miniupnp#107]
Hello! 

Thanks for this project. We've faced a small issue with miniupnpc native library. When we are compiling it on fedora 21 linux and gcc 4.9, we're getting a warning from 'features.h' header '_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE'. According to 'man feature_test_macros',  _DEFAULT_SOURCE must be used instead of _BSD_SOURCE in glibc version 2.20 and higher, on earlier versions it has no effect. Portable application can use this options together. Can you please fix it? We are using this library in our application and it has '-Werror' flag set, so we are getting compile time errors.

If you want we can make a pull request which will fix this issue.

**Comment by miniupnp** [comment]
so we need to change
CFLAGS += -D_BSD_SOURCE -D_POSIX_C_SOURCE=200112L
to
CFLAGS += -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_POSIX_C_SOURCE=200112L
that's right ?

**Comment by amjuarez** [comment]
Yes, that's correct. Thank you.
