### ISSUE TITLE
miniupnpc-1.9.20150206.tar.gz does not have testportlistingparse.c

### ISSUE THREAD

**Issue by Nikoli** [miniupnp/miniupnp#111]
http://miniupnp.free.fr/files/miniupnpc-1.9.20150206.tar.gz does not have testportlistingparse.c

```
x86_64-pc-linux-gnu-gcc -Wl,--hash-style=gnu -Wl,-O1 -Wl,--as-needed  testportlistingparse.o minixml.o portlistingparse.o   -o testportlistingparse
x86_64-pc-linux-gnu-gcc: error: testportlistingparse.o: No such file or directory
<builtin>: recipe for target 'testportlistingparse' failed
make: *** [testportlistingparse] Error 1
```

P.S.  Seems commit e280c3dd3abb7fd636c06503d0f7041256717387 is for miniupnpc-1.9.20150206 release, but why git tag is missing?

**Comment by miniupnp** [comment]
problem is fixed with http://miniupnp.tuxfamily.org/files/download.php?file=miniupnpc-1.9.20150427.tar.gz

**Comment by Nikoli** [comment]
Confirm, thanks.
