### ISSUE TITLE
Version in upnpc output

### ISSUE THREAD

**Issue by sanderjo** [miniupnp/miniupnp#115]
I see no version in the output upnpc:
```
$ ./upnpc-static 
upnpc : miniupnpc library test client. (c) 2005-2014 Thomas Bernard
Go to http://miniupnp.free.fr/ or http://miniupnp.tuxfamily.org/
for more information.
```

It would be helpful for me if upnpc would tell it's version to distinguish between the different versions I have on different system: built-in by Ubuntu, or self-compiled from github. To get an idea I played a bit with Makefile and upnpc.c.

Option 1: Just VERSION as already defined in Makefile:
```
$ ./upnpc-static 
upnpc : miniupnpc library test client, version 1.9. (c) 2005-2015 Thomas Bernard
```

Option 2: VERSION plus the date in Changelog (CHANGELOGVERSION, as Changelog is more granular than VERSION)
```
$ ./upnpc-static 
upnpc : miniupnpc library test client, version 1.9 (changelog: 2015/04/27). (c) 2005-2015 Thomas Bernard
```

Option 3 VERSION and CHANGELOGVERSION combined to one number:
```
$ ./upnpc-static 
upnpc : miniupnpc library test client, version 1.9-20150427. (c) 2005-2015 Thomas Bernard
```
FWIW: Snippet from Makefile
```
VERSION = $(shell cat VERSION)
CHANGELOGVERSION = $(shell awk 'NR==1 { print $$4 }' Changelog.txt)
# CHANGELOGVERSION = $(shell awk 'NR==1 { print $$4 }' Changelog.txt | tr -d '/')
```

So ... how about this? I can implement it and send a pull request.

**Comment by jweyrich** [comment]
Nice! IMHO it would be great to have version information spitted out by all _principal_ binaries.
