### ISSUE TITLE
IPv6: AddPortMapping(4567, 4567, 2001:470:AAA5:100c::100) failed with code 402 (Invalid Args)

### ISSUE THREAD

**Issue by sanderjo** [miniupnp/miniupnp#117]
I'm not sure this is a real issue, or a misunderstandig from my side:

A `upnpc -6 -r 4567 tcp` (so: ipv6) results in an error message:
```
AddPortMapping(4567, 4567, 2001:470:AAA5:100c::100) failed with code 402 (Invalid Args)
```
My upnpc client is talking to a router running openwrt with miniupnpd running on it. Port 4567 is not used on the router.

Am I doing something wrong? Can't '-6' be used this way? Or is it indeed a bug, on the client or the router side?

```
$ ./upnpc-static -6 -r 4567 tcp
upnpc : miniupnpc library test client, version 1.9.
 (c) 2005-2014 Thomas Bernard.
Go to http://miniupnp.free.fr/ or http://miniupnp.tuxfamily.org/
for more information.
List of UPNP devices found on the network :
 desc: http://[2001:470:AAA4:100c::2]:5000/rootDesc.xml
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

Found valid IGD : http://[2001:470:AAA4:100c::2]:5000/ctl/IPConn
Local LAN ip address : 2001:470:AAA5:100c::100
ExternalIPAddress = 83.128.233.31
AddPortMapping(4567, 4567, 2001:470:AAA5:100c::100) failed with code 402 (Invalid Args)
GetSpecificPortMappingEntry() failed with code 714 (NoSuchEntryInArray)
```
FYI: "AAA" is the replacement for my real ipv6 address.

**Comment by miniupnp** [comment]
short answer : "-6" cannot be used this way.

upnpc should not use IPV6 argument to call AddPortMapping()

**Comment by sanderjo** [comment]
And how can "-6" be used in the correct way?

**Comment by miniupnp** [comment]
AddPortMapping() is only for IPv4. so don't use -r together with -6

**Comment by sanderjo** [comment]
Yes, I understand, but/so what is a usage for the "-6" option? Not "-r", but ... ?

**Comment by miniupnp** [comment]
it should work with any other command.
But it may depend on your router.
The more logical is to use -6 together with IPv6 specific commands : -A -U -C -K -D -S -G
