### ISSUE TITLE
GetConnectionTypeInfo failed after upnpc -D

### ISSUE THREAD

**Issue by pepperav** [miniupnp/miniupnp#118]
Hi, 
I was trying the -D command and after a

    upnpc -D 67

if type

    upnpc -l

I get this: 

    List of UPNP devices found on the network : 
	desc: http://192.168.0.10:50000/rootDesc.xml 
	st: upnp:rootdevice 

	UPnP device found. Is it an IGD ? : http://192.168.0.10:50000/ 
	Trying to continue anyway 
	Local LAN ip address : 192.168.0.225 
	GetConnectionTypeInfo failed. 
	Status : Connected, uptime=1849296s, LastConnectionError : ERROR_NONE 
	Time started : Sat Apr 18 10:37:54 2015 
	GetLinkLayerMaxBitRates failed. 
	GetExternalIPAddress failed. (errorcode=401) 
	i protocol exPort->inAddr:inPort description remoteHost leaseTime 
	GetGenericPortMappingEntry() returned 401 (Invalid Action)

my router (192.168.0.1) is a Netgear DG834 and terminal is a Mac OS. 

What I wrong? 
Thank you

**Comment by sanderjo** [comment]
You don't get an UPnP answer from 192.168.0.1. So is UPnP enabled on your Netgear DG834?

**Comment by pepperav** [comment]
Yes. UPnP is enabled. I've used it perfectly before writing

    upnpc -D 67

thinking to delete rule number 67.
After this command, when type

    upnpc -l

I get that message.
How can I set 192.168.0.1 as IGD ?
tnx

**Comment by miniupnp** [comment]
obviously upnpc cannot detect your netgear router. It probably doesn't answer the SSDP M-SEARCH packets upnpc is sending.

**Comment by pepperav** [comment]
Understood. In your opinion, can a router reboot fix the issue?

**Comment by miniupnp** [comment]
better ask NetGear !
Anyway, I'm surprised you haven't already tried to reboot your router.
To check what UPNP devices are active on your LAN, you shoud use tcpdump/wireshark/etc. to check what are the SSDP packets going around (UDP port 1900, multicast address 239.255.255.250)
