### ISSUE TITLE
Need to work around iptables/conntrack multicast rigidity 

### ISSUE THREAD

**Issue by nhed** [miniupnp/miniupnp#119]
Suppose I have a router that already has a UPnP daemon running, and suppose I want to periodically run a UPnP client on same router to see if an upstream router exists that supports UPnP.

- UDP Multicast packets leave the box with an ephemeral source port and a multicast destination<br>
   `192.168.20.21:5555 -> 239.255.255.250:1900`
- UDP Unicast response packets are sent from the upstream router<br>
   `192.168.20.1:1900 -> 192.168.20.21:5555`
- These UDP packets are dropped by `iptables` as they do not match the outgoing traffic.  To the best of my knowledge I don't think that there is a way to convince connection tracking to correlate unicast responses to multicast probes.

_Things that won't work:_
- ❌ If I didn't have a UPnP daemon running I could simply set the `sameport` option and create an iptables rule to allow all traffic destined to port 1900.  But as I have the daemon, I can't
- ❌I could follow the advice [at this post](http://serverfault.com/questions/250797/stateful-matching-of-multicast-responses-in-iptables) and create a rule to allow all traffic FROM port 1900, but that sounds like a very bad thing for a router to do, allowing any and all UDP traffic as long as the source port is 1900

✔️❓ Short of enhancing `conntrack`, the easiest solution that I can think of is let the user specify the local port (other than `sameport`), and then the user can construct iptables rules to match

I intend to implement this now and submit a PR.  Please respond with any comments suggestions

**Comment by miniupnp** [comment]
I really don't understand why you don't add a rule to allow UDP traffic from 192.168.20.1:1900 to any host within the same subnet.
If you think it is a very bad thing for the router to do, you should probably turn off UPNP.

**Comment by nhed** [comment]
If you mean a static rule (as suggested in the linked article) - I don't know that my upstream router is at that address, so I would have to allow `*:1900->*:*` - pretty wide

If you mean to use UPnP on the LAN (discover upstream router) to facilitate UPnP probing on the WAN? Yes, doable but cumbersome and I would worry about leaving crud behind.   I am interested in using UPnP for games and such but rather minimize chained dependency

**Comment by nhed** [comment]
also, Thomas, I tried subscribing to the forum, and somehow my user got created with me never receiving email.  Sent you email w/o response, wonder if you can help

**Comment by miniupnp** [comment]
How is that possible you don't know your router address ?
netstat -r -n

**Comment by miniupnp** [comment]
also I don't understand your network setup. Have you multiple chained NAT routers ? It's a pretty crazy setup, and UPNP IGD was clearly NOT designed to work with such setup.
"UPnP probing on the WAN" is such a nonsense...

**Comment by nhed** [comment]
yes two routers...   A router owned by the ISP (verizon fios for example) which they can push software updates whenever they want and who knows what else...  Some users choose to not trust the ISP and put their own router behind the ISP provides router.  With verizon FIOS anyway you can't replace the ISPs router because the upstream interface is not a simple Ethernet

**Comment by nhed** [comment]
But you don't have to buy-in to my use case to accept my PR, as it is just taking the 'sameport' parameter which gives the user some control over the local port (what's the use case for that?) And making that control more explicit

**Comment by miniupnp** [comment]
PR #120 merged.
