### ISSUE TITLE
How to check for IGD:2 ?

### ISSUE THREAD

**Issue by sanderjo** [miniupnp/miniupnp#121]
How can I check if a NAT with UPnP supports IGD:2?

Is the ```InternetGatewayDevice:1``` telling it's only IGD:1, and not IGD:2?

```
$ upnpc -S
upnpc : miniupnpc library test client. (c) 2005-2014 Thomas Bernard
Go to http://miniupnp.free.fr/ or http://miniupnp.tuxfamily.org/
for more information.
List of UPNP devices found on the network :
 desc: http://192.168.1.1:5000/rootDesc.xml
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

Found valid IGD : http://192.168.1.1:5000/ctl/IPConn
Local LAN ip address : 192.168.1.147
FirewallEnabled: 0 & Inbound Pinhole Allowed: 0
GetFirewallStatus:
   Firewall Enabled: No
   Inbound Pinhole Allowed: No
Bytes:   Sent: 637921376	Recv: 4294967295
Packets: Sent:  4167822	Recv: 30422288
```

FWIW: the UPnP NAT is miniupnpd on OpenWRT barrier breaker 14.07. If the above assumption is correct, it would mean OpenWRT barrier breaker 14.07 does not support IGD:2?

**Comment by miniupnp** [comment]
Indeed InternetGatewayDevice:1 is IGD:1, not IGD:2
you should also try 
$ ./listdevices |grep InternetGatewayDevice
