### ISSUE TITLE
How to customize chain names?

### ISSUE THREAD

**Issue by nachopro** [miniupnp/miniupnp#128]
Hi, I'm working with Shorewall. miniupnpd has a hardcoded chain names that are no compatibles with Shorewall. Exists some workaround?

Thanks!

**Comment by nachopro** [comment]
So sorry, I'm using a too old miniupnpd version :/

https://github.com/miniupnp/miniupnp/blob/master/miniupnpd/miniupnpd.conf#L47

**Comment by miniupnp** [comment]
this problem was fixed in 2008 !!!
http://miniupnp.tuxfamily.org/forum/viewtopic.php?t=493
please always use the latest miniupnpd version !!!
