### ISSUE TITLE
UPnP and PCP cannot refresh mapping

### ISSUE THREAD

**Issue by kennysong** [miniupnp/miniupnp#131]
I'm currently using the Tomato router [firmware K26RT-AC](http://tomato.groov.pl/?page_id=164) version [130-EN](http://tomato.groov.pl/download/K26RT-AC/), which uses miniupnpd as its implementation of NAT-PMP, PCP, and UPnP.

It seems that sending an PCP MAP request or UPnP AddPortMapping request that matches an existing mapping (created by the protocol) does not refresh the mapping lifetime. The mapping is deleted after the first mapping's requested lifetime expires.

For example, if we send a successful PCP MAP request with a lifetime of 2 minutes, followed by an identical PCP MAP request after 1 minute, the mapping disappears in 2 minutes when it should live until 3 minutes, as per [the RFC spec](https://tools.ietf.org/html/rfc6887#section-11.2.1). (Same behavior for UPnP)

Additionally, the Tomato admin console shows that the PCP nonce is updated on the second request, but the lifetime is not. 

NAT-PMP extends the lifetime on new requests correctly.

**Comment by miniupnp** [comment]
I guess you're right.
is there the message "port xxx tcp already redirected to xx.xx.xx.xx:xxx, replacing" in syslog ?

**Comment by kennysong** [comment]
Doesn't seem like it. The log for two PCP MAP requests are:

```
Jun 29 11:04:49 unknown daemon.err miniupnpd[4027]: PCP MAP: added mapping UDP 50001->192.168.1.44:50001 'PCP MAP f3c67cb0b78fdcc8495215a7'
Jun 29 11:05:45 unknown daemon.warn miniupnpd[4027]: SendSSDPNotify(): truncated output (514>=512)
Jun 29 11:06:04 unknown daemon.err miniupnpd[4027]: PCP MAP: added mapping UDP 50001->192.168.1.44:50001 'PCP MAP 05efa0590463a24b796344e4'
Jun 29 11:06:45 unknown daemon.warn miniupnpd[4027]: SendSSDPNotify(): truncated output (514>=512)
Jun 29 11:06:49 unknown daemon.notice miniupnpd[4027]: remove port mapping 50001 UDP because it has expired
```

There are no log messages for UPnP AddPortMapping.

**Comment by kennysong** [comment]
Reusing the same nonce in both PCP MAP requests has the same behavior:

```
Jul  7 14:48:01 unknown daemon.err miniupnpd[6102]: PCP MAP: added mapping UDP 50001->192.168.1.44:50001 'PCP MAP b4fa17bad12427542537f405'
Jul  7 14:49:14 unknown daemon.err miniupnpd[6102]: PCP MAP: added mapping UDP 50001->192.168.1.44:50001 'PCP MAP b4fa17bad12427542537f405'
Jul  7 14:50:01 unknown daemon.notice miniupnpd[6102]: remove port mapping 50001 UDP because it has expired
```
