### ISSUE TITLE
Cannot delete a PCP mapping

### ISSUE THREAD

**Issue by kennysong** [miniupnp/miniupnp#132]
As in #131, I'm using a Tomato router [firmware K26RT-AC](http://tomato.groov.pl/?page_id=164) version [130-EN](http://tomato.groov.pl/download/K26RT-AC/), which uses miniupnpd as its implementation of NAT-PMP, PCP, and UPnP.

~~I can't delete a PCP mapping with a PCP MAP request, since it seems that the miniupnp PCP server enforces a minimum lifetime of 7200 seconds (the response will always have a lifetime between 7200 seconds and 24 hours). However, [RFC 6887](https://tools.ietf.org/html/rfc6887#section-11.1) states that a lifetime of 0 seconds should indicate that the mapping be deleted.~~

The previous error was a bug in my own code. However, I am now seeing a new problem with deleting a mapping; the PCP response message will have a result code of 8 (no resources). I've tested this on two Tomato routers with the same result.

The syslog outputs,

```
Jul  6 15:23:07 unknown daemon.err miniupnpd[1125]: PCP MAP: added mapping UDP 50001->192.168.1.44:50001 'PCP MAP a98e11c1e0a95ad359fdc9a1'
Jul  6 15:23:07 unknown daemon.warn miniupnpd[1125]: SendSSDPNotify(): truncated output (515>=512)
Jul  6 15:23:23 unknown daemon.err miniupnpd[1125]: Failed to remove PCP mapping internal port 50001, protocol UDP
```

**Comment by miniupnp** [comment]
I will have a look at it. I've not worked much on PCP support so..

**Comment by ptatrai** [comment]
There can be 2 valid reasons to return an error:
1. Have you send request from the same IP address as the one you want to remove mapping to?
2. Have you used the same mapping nonce as the one from original MAP request?
>If operating in the Simple Threat Model (Section 18.1), and the
>Internal port, Protocol, and Internal Address match an existing
>explicit dynamic mapping, but the Mapping Nonce does not match, the
>request MUST be rejected with a NOT_AUTHORIZED error with the
>Lifetime of the error indicating duration of that existing mapping.
>The PCP server only needs to remember one Mapping Nonce value for
>each explicit dynamic mapping.)`

**Comment by kennysong** [comment]
The nonce was it! Deletion works when reusing the same nonce used to create the mapping.

@ptatrai It seems from your quote that the PCP response code should have been NOT_AUTHORIZED (2), not NO_RESOURCES (8) though.

**Comment by miniupnp** [comment]
I think the nonce is checked through strcmp(desc, pcp_msg_info->desc)

**Comment by ptatrai** [comment]
Yes, you are right. And it's correct behaviour according RFC. The only issue is that server returns wrong error code as @kennysong mentioned. It should return NOT_AUTHORIZED if client is trying to delete mapping and client IP and nonce doesn't match. NO_RESOURCES should be returned if the mapping to be deleted doesn't exist, I assume.

**Comment by miniupnp** [comment]
@kennysong tell me if my commit really fixes the problem

**Comment by kennysong** [comment]
@miniupnp Thanks! I'm not familiar enough with the Tomato firmware to be able to update miniupnp on it without risking bricking the router. However, I took a look at your fix and it looks correct.
