### ISSUE TITLE
MiniSSDPd: device add/remove/update notification

### ISSUE THREAD

**Issue by annulen** [miniupnp/miniupnp#139]
My control point needs to update user interface when list of available devices changes. This can be done by periodic polling of MiniSSDPd for device list, however, event-based approach should be more efficient.

I see several ways how it could be implemented:
* Client issues request for notification, and MiniSSDPd replies when its device list has actually changed (something akin to HTTP long polling)
* MiniSSDPd writes to all client sockets when any device list change happens (this changes message flow direction between client and MiniSSDP, but seems easier to implement)
* Use different socket for notifications
* Use eventfd (on sufficiently modern Linux) or kqueue for notifications, pass file descriptor of event to client via existing socket connection.

**Comment by annulen** [comment]
I can implement this myself if you choose which way it should be implemented and give me

**Comment by miniupnp** [comment]
I'm thinking about it.
I think the best option would be that clients connect to the usual socket, but issue a special command to "wait for events" so that socket become notification socket.

**Comment by annulen** [comment]
Wire protocol for events needs to be chosen (probably event type + device list in usual format).
I'm not sure if there should be a way to switch it back to normal mode, or reconnect is just enough.

**Comment by annulen** [comment]
ping

**Comment by miniupnp** [comment]
I had no time to take a look.
about your question : reconnect is just enough :)

**Comment by miniupnp** [comment]
@annulen see code in https://github.com/miniupnp/miniupnp/blob/master/minissdpd/showminissdpdnotif.c

**Comment by annulen** [comment]
Cool, thanks!
