### ISSUE TITLE
Miniupnpc doesn't compile on Freebsd 10.2

### ISSUE THREAD

**Issue by crypto750** [miniupnp/miniupnp#151]
$ gmake
/bin/sh updateminiupnpcstrings.sh
Detected OS [FreeBSD] version [10.2-RELEASE]
MiniUPnPc version [1.9]
setting OS_STRING macro value to FreeBSD/10.2-RELEASE in miniupnpcstrings.h.
setting MINIUPNPC_VERSION_STRING macro value to 1.9 in miniupnpcstrings.h.
cc -fPIC -O -Wall -W -Wstrict-prototypes -fno-common -DMINIUPNPC_SET_SOCKET_TIMEOUT -DMINIUPNPC_GET_SRC_ADDR -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_POSIX_C_SOURCE=200112L -ansi   -c -o miniwget.o miniwget.c
cc -fPIC -O -Wall -W -Wstrict-prototypes -fno-common -DMINIUPNPC_SET_SOCKET_TIMEOUT -DMINIUPNPC_GET_SRC_ADDR -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_POSIX_C_SOURCE=200112L -ansi   -c -o minixml.o minixml.c
cc -fPIC -O -Wall -W -Wstrict-prototypes -fno-common -DMINIUPNPC_SET_SOCKET_TIMEOUT -DMINIUPNPC_GET_SRC_ADDR -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_POSIX_C_SOURCE=200112L -ansi   -c -o igd_desc_parse.o igd_desc_parse.c
cc -fPIC -O -Wall -W -Wstrict-prototypes -fno-common -DMINIUPNPC_SET_SOCKET_TIMEOUT -DMINIUPNPC_GET_SRC_ADDR -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_POSIX_C_SOURCE=200112L -ansi   -c -o minisoap.o minisoap.c
cc -fPIC -O -Wall -W -Wstrict-prototypes -fno-common -DMINIUPNPC_SET_SOCKET_TIMEOUT -DMINIUPNPC_GET_SRC_ADDR -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_POSIX_C_SOURCE=200112L -ansi   -c -o miniupnpc.o miniupnpc.c
cc -fPIC -O -Wall -W -Wstrict-prototypes -fno-common -DMINIUPNPC_SET_SOCKET_TIMEOUT -DMINIUPNPC_GET_SRC_ADDR -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_POSIX_C_SOURCE=200112L -ansi   -c -o upnpreplyparse.o upnpreplyparse.c
cc -fPIC -O -Wall -W -Wstrict-prototypes -fno-common -DMINIUPNPC_SET_SOCKET_TIMEOUT -DMINIUPNPC_GET_SRC_ADDR -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_POSIX_C_SOURCE=200112L -ansi   -c -o upnpcommands.o upnpcommands.c
cc -fPIC -O -Wall -W -Wstrict-prototypes -fno-common -DMINIUPNPC_SET_SOCKET_TIMEOUT -DMINIUPNPC_GET_SRC_ADDR -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_POSIX_C_SOURCE=200112L -ansi   -c -o upnperrors.o upnperrors.c
cc -fPIC -O -Wall -W -Wstrict-prototypes -fno-common -DMINIUPNPC_SET_SOCKET_TIMEOUT -DMINIUPNPC_GET_SRC_ADDR -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_POSIX_C_SOURCE=200112L -ansi   -c -o connecthostport.o connecthostport.c
cc -fPIC -O -Wall -W -Wstrict-prototypes -fno-common -DMINIUPNPC_SET_SOCKET_TIMEOUT -DMINIUPNPC_GET_SRC_ADDR -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_POSIX_C_SOURCE=200112L -ansi   -c -o portlistingparse.o portlistingparse.c
cc -fPIC -O -Wall -W -Wstrict-prototypes -fno-common -DMINIUPNPC_SET_SOCKET_TIMEOUT -DMINIUPNPC_GET_SRC_ADDR -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_POSIX_C_SOURCE=200112L -ansi   -c -o receivedata.o receivedata.c
cc -fPIC -O -Wall -W -Wstrict-prototypes -fno-common -DMINIUPNPC_SET_SOCKET_TIMEOUT -DMINIUPNPC_GET_SRC_ADDR -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_POSIX_C_SOURCE=200112L -ansi   -c -o upnpdev.o upnpdev.c
cc -fPIC -O -Wall -W -Wstrict-prototypes -fno-common -DMINIUPNPC_SET_SOCKET_TIMEOUT -DMINIUPNPC_GET_SRC_ADDR -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_POSIX_C_SOURCE=200112L -ansi   -c -o minissdpc.o minissdpc.c
minissdpc.c:146:17: error: variable has incomplete type 'struct timeval'
        struct timeval timeout;
                       ^
minissdpc.c:146:9: note: forward declaration of 'struct timeval'
        struct timeval timeout;
               ^
minissdpc.c:392:12: warning: implicit declaration of function 'strncasecmp' [-Wimplicit-function-declaration]
                                        if(0==strncasecmp(reply+a, "location", 8))
                                              ^
minissdpc.c:479:23: error: use of undeclared identifier 'PF_INET6'
        sudp = socket(ipv6 ? PF_INET6 : PF_INET, SOCK_DGRAM, 0);
                             ^
minissdpc.c:479:34: error: use of undeclared identifier 'PF_INET'
        sudp = socket(ipv6 ? PF_INET6 : PF_INET, SOCK_DGRAM, 0);
                                        ^
minissdpc.c:580:34: error: use of undeclared identifier 'IP_MULTICAST_TTL'
        if(setsockopt(sudp, IPPROTO_IP, IP_MULTICAST_TTL, &ttl, sizeof(ttl)) < 0)
                                        ^
minissdpc.c:607:23: error: use of undeclared identifier 'INADDR_NONE'
                        if(mc_if.s_addr != INADDR_NONE)
                                           ^
minissdpc.c:610:37: error: use of undeclared identifier 'IP_MULTICAST_IF'
                                if(setsockopt(sudp, IPPROTO_IP, IP_MULTICAST_IF, (const char *)&mc_if, sizeof(mc_if)) < 0)
                                                                ^
minissdpc.c:617:21: error: variable has incomplete type 'struct ip_mreqn'
                                struct ip_mreqn reqn;   /* only defined with -D_BSD_SOURCE or -D_GNU_SOURCE */
                                                ^
minissdpc.c:617:12: note: forward declaration of 'struct ip_mreqn'
                                struct ip_mreqn reqn;   /* only defined with -D_BSD_SOURCE or -D_GNU_SOURCE */
                                       ^
minissdpc.c:620:37: error: use of undeclared identifier 'IP_MULTICAST_IF'
                                if(setsockopt(sudp, IPPROTO_IP, IP_MULTICAST_IF, (const char *)&reqn, sizeof(reqn)) < 0)
                                                                ^
minissdpc.c:440:45: warning: unused parameter 'ttl' [-Wunused-parameter]
                    int ipv6, unsigned char ttl,
                                            ^
2 warnings and 8 errors generated.
<builtin>: recipe for target 'minissdpc.o' failed
gmake: *** [minissdpc.o] Error 1

**Comment by miniupnp** [comment]
does b7654b557fbe2926ab10cd9e40430f9172db68e6 fix it ?

**Comment by crypto750** [comment]
Unfortunately not.

cc -fPIC -O -Wall -W -Wstrict-prototypes -fno-common -DMINIUPNPC_SET_SOCKET_TIMEOUT -DMINIUPNPC_GET_SRC_ADDR -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_POSIX_C_SOURCE=200112L -ansi   -c -o minissdpc.o minissdpc.c
minissdpc.c:154:17: error: variable has incomplete type 'struct timeval'
        struct timeval timeout;
                       ^
minissdpc.c:154:9: note: forward declaration of 'struct timeval'
        struct timeval timeout;
               ^
minissdpc.c:400:12: warning: implicit declaration of function 'strncasecmp' [-Wimplicit-function-declaration]
                                        if(0==strncasecmp(reply+a, "location", 8))
                                              ^
minissdpc.c:487:23: error: use of undeclared identifier 'PF_INET6'
        sudp = socket(ipv6 ? PF_INET6 : PF_INET, SOCK_DGRAM, 0);
                             ^
minissdpc.c:487:34: error: use of undeclared identifier 'PF_INET'
        sudp = socket(ipv6 ? PF_INET6 : PF_INET, SOCK_DGRAM, 0);
                                        ^
minissdpc.c:588:34: error: use of undeclared identifier 'IP_MULTICAST_TTL'
        if(setsockopt(sudp, IPPROTO_IP, IP_MULTICAST_TTL, &ttl, sizeof(ttl)) < 0)
                                        ^
minissdpc.c:615:23: error: use of undeclared identifier 'INADDR_NONE'
                        if(mc_if.s_addr != INADDR_NONE)
                                           ^
minissdpc.c:618:37: error: use of undeclared identifier 'IP_MULTICAST_IF'
                                if(setsockopt(sudp, IPPROTO_IP, IP_MULTICAST_IF, (const char *)&mc_if, sizeof(mc_if)) < 0)
                                                                ^
minissdpc.c:448:45: warning: unused parameter 'ttl' [-Wunused-parameter]
                    int ipv6, unsigned char ttl,
                                            ^
2 warnings and 6 errors generated.
<builtin>: recipe for target 'minissdpc.o' failed
gmake: *** [minissdpc.o] Error 1

**Comment by miniupnp** [comment]
does it works if #include <sys/time.h> is added ?

**Comment by crypto750** [comment]
>>does it works if #include is added ?

I'll need you to make a commit to check :) Sorry, I don't code much.

**Comment by crypto750** [comment]
I managed to add #include <sys/time.h>

cc -fPIC -O -Wall -W -Wstrict-prototypes -fno-common -DMINIUPNPC_SET_SOCKET_TIMEOUT -DMINIUPNPC_GET_SRC_ADDR -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_POSIX_C_SOURCE=200112L -ansi   -c -o minissdpc.o minissdpc.c
minissdpc.c:401:12: warning: implicit declaration of function 'strncasecmp' [-Wimplicit-function-declaration]
                                        if(0==strncasecmp(reply+a, "location", 8))
                                              ^
minissdpc.c:488:23: error: use of undeclared identifier 'PF_INET6'
        sudp = socket(ipv6 ? PF_INET6 : PF_INET, SOCK_DGRAM, 0);
                             ^
minissdpc.c:488:34: error: use of undeclared identifier 'PF_INET'
        sudp = socket(ipv6 ? PF_INET6 : PF_INET, SOCK_DGRAM, 0);
                                        ^
minissdpc.c:589:34: error: use of undeclared identifier 'IP_MULTICAST_TTL'
        if(setsockopt(sudp, IPPROTO_IP, IP_MULTICAST_TTL, &ttl, sizeof(ttl)) < 0)
                                        ^
minissdpc.c:616:23: error: use of undeclared identifier 'INADDR_NONE'
                        if(mc_if.s_addr != INADDR_NONE)
                                           ^
minissdpc.c:619:37: error: use of undeclared identifier 'IP_MULTICAST_IF'
                                if(setsockopt(sudp, IPPROTO_IP, IP_MULTICAST_IF, (const char *)&mc_if, sizeof(mc_if)) < 0)
                                                                ^
minissdpc.c:449:45: warning: unused parameter 'ttl' [-Wunused-parameter]
                    int ipv6, unsigned char ttl,
                                            ^
2 warnings and 5 errors generated.
<builtin>: recipe for target 'minissdpc.o' failed
gmake: *** [minissdpc.o] Error 1

**Comment by miniupnp** [comment]
man strncasecmp
to know which .h to include for strncasecmp()

**Comment by crypto750** [comment]
I added these:
#include < strings.h >
#include < xlocale.h >

the warning on strncasecmp is gone, but:

cc -fPIC -O -Wall -W -Wstrict-prototypes -fno-common -DMINIUPNPC_SET_SOCKET_TIMEOUT -DMINIUPNPC_GET_SRC_ADDR -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_POSIX_C_SOURCE=200112L -ansi   -c -o minissdpc.o minissdpc.c
minissdpc.c:490:23: error: use of undeclared identifier 'PF_INET6'
        sudp = socket(ipv6 ? PF_INET6 : PF_INET, SOCK_DGRAM, 0);
                             ^
minissdpc.c:490:34: error: use of undeclared identifier 'PF_INET'
        sudp = socket(ipv6 ? PF_INET6 : PF_INET, SOCK_DGRAM, 0);
                                        ^
minissdpc.c:591:34: error: use of undeclared identifier 'IP_MULTICAST_TTL'
        if(setsockopt(sudp, IPPROTO_IP, IP_MULTICAST_TTL, &ttl, sizeof(ttl)) < 0)
                                        ^
minissdpc.c:618:23: error: use of undeclared identifier 'INADDR_NONE'
                        if(mc_if.s_addr != INADDR_NONE)
                                           ^
minissdpc.c:621:37: error: use of undeclared identifier 'IP_MULTICAST_IF'
                                if(setsockopt(sudp, IPPROTO_IP, IP_MULTICAST_IF, (const char *)&mc_if, sizeof(mc_if)) < 0)
                                                                ^
minissdpc.c:451:45: warning: unused parameter 'ttl' [-Wunused-parameter]
                    int ipv6, unsigned char ttl,
                                            ^
1 warning and 5 errors generated.
<builtin>: recipe for target 'minissdpc.o' failed
gmake: *** [minissdpc.o] Error 1

**Comment by miniupnp** [comment]
see commit f68edea0fa23eea1661ccfe01c44fae8795a2de9
I don't understand what is the problem with PF_INET
sys/types.h sys/socket.h netinet/in.h are included..

**Comment by crypto750** [comment]
I tested on Freebsd 9.3, same problem.

**Comment by miniupnp** [comment]
any help is welcome !

**Comment by miniupnp** [comment]
the problem may come from -D_POSIX_C_SOURCE=200112L

**Comment by crypto750** [comment]
You're right, when I removed -D_POSIX_C_SOURCE=200112L from Makefile, it compiled.
Thank you for fixing it.

**Comment by miniupnp** [comment]
yes but I guess _POSIX_C_SOURCE is needed for another OS. it should not prevent PF_INET6

**Comment by miniupnp** [comment]
what about d6700c5d1ff56333801afff6a017cc86363f2401  ?

**Comment by crypto750** [comment]
doesn't compile with d6700c5

cc -fPIC -O -Wall -W -Wstrict-prototypes -fno-common -DMINIUPNPC_SET_SOCKET_TIMEOUT -DMINIUPNPC_GET_SRC_ADDR -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -ansi   -c -o minissdpc.o minissdpc.c
minissdpc.c:489:23: error: use of undeclared identifier 'PF_INET6'
        sudp = socket(ipv6 ? PF_INET6 : PF_INET, SOCK_DGRAM, 0);
                             ^
minissdpc.c:489:34: error: use of undeclared identifier 'PF_INET'
        sudp = socket(ipv6 ? PF_INET6 : PF_INET, SOCK_DGRAM, 0);
                                        ^
minissdpc.c:590:34: error: use of undeclared identifier 'IP_MULTICAST_TTL'
        if(setsockopt(sudp, IPPROTO_IP, IP_MULTICAST_TTL, &ttl, sizeof(ttl)) < 0)
                                        ^
minissdpc.c:617:23: error: use of undeclared identifier 'INADDR_NONE'
                        if(mc_if.s_addr != INADDR_NONE)
                                           ^
minissdpc.c:620:37: error: use of undeclared identifier 'IP_MULTICAST_IF'
                                if(setsockopt(sudp, IPPROTO_IP, IP_MULTICAST_IF, (const char *)&mc_if, sizeof(mc_if)) < 0)
                                                                ^
minissdpc.c:450:45: warning: unused parameter 'ttl' [-Wunused-parameter]
                    int ipv6, unsigned char ttl,


Compiles if I simply remove -D_POSIX_C_SOURCE=200112L

**Comment by miniupnp** [comment]
Maybe the crap at the top of miniupnpc.c is necessary to get it compiling everywhere...

```
#define __EXTENSIONS__ 1
#if !defined(__APPLE__) && !defined(__sun)
#if !defined(_XOPEN_SOURCE) && !defined(__OpenBSD__) && !defined(__NetBSD__)
#ifndef __cplusplus
#define _XOPEN_SOURCE 600
#endif
#endif
#ifndef __BSD_VISIBLE
#define __BSD_VISIBLE 1
#endif
#endif
```

**Comment by crypto750** [comment]
If you push a new commit, I'll test it on Freebsd.

**Comment by miniupnp** [comment]
what about 2889f0a6caa14a2fec6a3fbf87f246817dc671d4 ?

**Comment by crypto750** [comment]
same error

**Comment by miniupnp** [comment]
and 6728b12965ff4924e6c26e77d1dcddd4d871b8a3 ?

**Comment by crypto750** [comment]
6728b12 compiled.
