### ISSUE TITLE
get_lan_for_peer broken for IPv6 on BSD?

### ISSUE THREAD

**Issue by razzfazz** [miniupnp/miniupnp#160]
The pfSense folks are seeing an issue where miniupnpd doesn't accept IPv6 requests; see [here](https://redmine.pfsense.org/issues/4321#change-22410). Looking over the relevant code, I think the problem is that the BSD version of get_src_for_route_to will always return failure if the src and/or src_len parameters are NULL (as they are in get_lan_for_peer): The condition in the if statement in miniupnp/miniupnpd/bsd/getroute.c:87 will never evaluate to true in this case, and as a result "found" will never be set to 1, and the function will always return -1, causing get_lan_for_peer to fail.

**Comment by miniupnp** [comment]
once you applied the patch, can you give me the output of
```
$ ./testgetroute 8.8.8.8
$ ./testgetroute 2a00:1450:4007:806::101f
```

**Comment by razzfazz** [comment]
$ ./testgetroute 8.8.8.8
testgetroute: calling get_src_for_route_to(0x7fffffffea70, NULL, NULL, 0x7fffffffea44)
testgetroute: read l=192 seq=1 pid=86966
testgetroute: type=1 sa_len=16 sa_family=2 0.0.0.0:0
testgetroute: type=2 sa_len=16 sa_family=2 [my WAN address]:0
testgetroute: type=4 sa_len=0 sa_family=0 unknown address family 0
testgetroute: get_src_for_route_to() returned 0
testgetroute: index=-1
testgetroute: calling get_src_for_route_to(0x7fffffffea70, 0x7fffffffea74, 0x7fffffffea48(4), 0x7fffffffea44)
testgetroute: read l=192 seq=1 pid=86966
testgetroute: type=1 sa_len=16 sa_family=2 0.0.0.0:0
testgetroute: type=2 sa_len=16 sa_family=2 [my WAN address]:0
testgetroute: type=4 sa_len=0 sa_family=0 unknown address family 0
testgetroute: get_src_for_route_to() returned 0
testgetroute: src=[my WAN address]:0
testgetroute: index=-1

**Comment by razzfazz** [comment]
$ ./testgetroute 2a00:1450:4007:806::101f
testgetroute: calling get_src_for_route_to(0x7fffffffea40, NULL, NULL, 0x7fffffffea34)
[hangs here]

Attaching a debugger shows that the hang is in the read() call inside get_src_for_route_to().

**Comment by razzfazz** [comment]
Testgetroute with IPv6 seems to hang even before this change.

**Comment by razzfazz** [comment]
I think the following might be the problem (miniupnpd/bsd/getroute.c:59):

	memcpy(m_rtmsg.m_space, dst, sizeof(struct sockaddr));

In the case of an IPv6 address, this doesn't actually copy the whole sockaddr_in6, and for IPv4 it only happens to work because sockaddr and sockaddr_in have the same size.

**Comment by miniupnp** [comment]
@razzfazz I spotted the problem. please try the last patch :)

**Comment by razzfazz** [comment]
Still hangs for IPv6. I think the problem is that on FreeBSD, sockaddr and friends actually have a length field (first byte of the struct) that you're not filling out correctly, so you're still passing in invalid struct to the read() call (length field is zero).

**Comment by miniupnp** [comment]
you're right !

**Comment by razzfazz** [comment]
submitted a pull request

**Comment by razzfazz** [comment]
new output:

$ ./testgetroute 2a00:1450:4007:806::101f
testgetroute: calling get_src_for_route_to(0x7fffffffea60, NULL, NULL, 0x7fffffffea9c)
testgetroute: read l=224 seq=1 pid=25024
testgetroute: type=1 sa_len=28 sa_family=28 [::]:0
testgetroute: type=2 sa_len=255 sa_family=255 unknown address family 255
testgetroute: type=4 sa_len=0 sa_family=0 unknown address family 0
testgetroute: get_src_for_route_to() returned 0
testgetroute: index=-1
testgetroute: calling get_src_for_route_to(0x7fffffffea60, 0x7fffffffea68, 0x7fffffffea90(16), 0x7fffffffea9c)
testgetroute: read l=224 seq=1 pid=25024
testgetroute: type=1 sa_len=28 sa_family=28 [::]:0
testgetroute: type=2 sa_len=255 sa_family=255 unknown address family 255
testgetroute: type=4 sa_len=0 sa_family=0 unknown address family 0
testgetroute: get_src_for_route_to() returned 0
testgetroute: src=[::]:0
testgetroute: index=-1

**Comment by razzfazz** [comment]
The sa_len value for the type=1 response is almost certainly wrong.

**Comment by razzfazz** [comment]
Something's fishy here... The read() call returned 256 bytes, but the (parsed) length of the responses is greater than that.

**Comment by razzfazz** [comment]
The issue is that the sockaddr entries in m_rtmsg.m_space are actually naturally aligned; so it's not sufficient to just blindly increase by the size of each structure; you'll have to go to the next aligned address.

**Comment by razzfazz** [comment]
Updated the push request with a fix.

**Comment by razzfazz** [comment]
Output with the fixes in #162:

$ ./testgetroute 2a00:1450:4007:806::101f
testgetroute: calling get_src_for_route_to(0x7fffffffea40, NULL, NULL, 0x7fffffffea34)
testgetroute: read l=224 seq=1 pid=39940
testgetroute: type=1 sa_len=28 sa_family=28 [::]:0
testgetroute: type=2 sa_len=28 sa_family=28 [router address]:0
testgetroute: type=4 sa_len=0 sa_family=0 unknown address family 0
testgetroute: get_src_for_route_to() returned 0
testgetroute: index=-1
testgetroute: calling get_src_for_route_to(0x7fffffffea40, 0x7fffffffea48, 0x7fffffffea38(16), 0x7fffffffea34)
testgetroute: read l=224 seq=1 pid=39940
testgetroute: type=1 sa_len=28 sa_family=28 [::]:0
testgetroute: type=2 sa_len=28 sa_family=28 [router address]:0
testgetroute: type=4 sa_len=0 sa_family=0 unknown address family 0
testgetroute: get_src_for_route_to() returned 0
testgetroute: src=[router address]:0
testgetroute: index=-1

**Comment by miniupnp** [comment]
hum I still wonder why index=-1

**Comment by miniupnp** [comment]
```
$ route -n get -inet6 '2a00:1450:4007:806::101f'
```

**Comment by razzfazz** [comment]
Index=-1 because this is not a locally reachable destination.

**Comment by razzfazz** [comment]
If I use an address on any of the local network segments, I do seem to get the correct index. For remote addresses, the routing socket only returns the address of the gateway.

**Comment by miniupnp** [comment]
I should study the route source code, because it does get the network interface :)

**Comment by razzfazz** [comment]
By the way, what the "src" parameter actually intended to return? The current code will return the gateway address (from the RTA_GATEWAY response) for remote addresses but the link prefix (from the RTA_DST response) for local addresses...

**Comment by razzfazz** [comment]
Filed issue #163.
