### ISSUE TITLE
__BSD_VISIBLE needs to be defined for INADDR_LOOPBACK on FreeBSD

### ISSUE THREAD

**Issue by ysangkok** [miniupnp/miniupnp#161]
Currently, minihttptestserver.c does not compile on FreeBSD.

**Comment by miniupnp** [comment]
isn't -D_BSD_SOURCE sufficient to enable __BSD_VISIBLE ?

**Comment by ysangkok** [comment]
@miniupnp Nope. I just tested this, it didn't compile. There could be another way though, I am not a FreeBSD expert.

**Comment by miniupnp** [comment]
add at the top of the file :
```
#ifndef INADDR_LOOPBACK
#define INADDR_LOOPBACK         0x7f000001
#endif
```
I think it is the best fix

**Comment by ysangkok** [comment]
@miniupnp That works.

**Comment by ysangkok** [comment]
Thank you!
