### ISSUE TITLE
get_src_for_route_to() src parameter returns wrong address on BSD

### ISSUE THREAD

**Issue by razzfazz** [miniupnp/miniupnp#163]
The current BSD code for get_src_for_route_to() will return the gateway address (from the RTA_GATEWAY response) for remote addresses but the link prefix (from the RTA_DST response) for local addresses; seems like it really should behave consistently in both cases.

**Comment by razzfazz** [comment]
Incidentally, neither of these two matches the behavior on Linux, where the function returns the preferred source address for a given route.

**Comment by razzfazz** [comment]
It sounds like the Linux behavior is really what's intended here.

**Comment by razzfazz** [comment]
Fix in push request #164.

**Comment by miniupnp** [comment]
fixed with #164
