### ISSUE TITLE
DeviceProtection actions are missing parameters

### ISSUE THREAD

**Issue by razzfazz** [miniupnp/miniupnp#179]
The three actions for the DeviceProtection service are missing the parameters defined in the spec.

**Comment by razzfazz** [comment]
As an additional wrinkle, it looks like upnpdescgen.c assumes that the names of the parameters are always derived from the related state variables -- this is not actually the case. The "argument" structure should have a parameter name added rather than just inferring it (possibly with prepended "New") from the variable name.

**Comment by razzfazz** [comment]
Looks like there's already a workaround via the magicargs array. Let me use that and open a pull request.

**Comment by miniupnp** [comment]
Indeed DeviceProtection is not finished...

**Comment by razzfazz** [comment]
Fix in pull request #180.
