### ISSUE TITLE
On a dual-stack host, miniupnpd only sends notifications via IPv6

### ISSUE THREAD

**Issue by razzfazz** [miniupnp/miniupnp#183]
If compiled with IPv6 support enabled, miniupnpd only sends NOTIFY packets via IPv6; i.e., it no longer advertises or responds via IPv4 at all.

**Comment by razzfazz** [comment]
This is running on FreeBSD, in case it would make a difference.

**Comment by razzfazz** [comment]
Looks like it's binding to both v4 and v6 sockets as expected:

```
root     miniupnpd  75708 10 tcp6   *:2189                *:*
root     miniupnpd  75708 12 tcp4   *:2189                *:*
root     miniupnpd  75708 13 udp4   *:1900                *:*
root     miniupnpd  75708 14 udp6   *:1900                *:*
```

So perhaps the code that generates the replies is at fault?

**Comment by miniupnp** [comment]
hum. What's in the log ? (run with -d to enable debug output)
also is V6SOCKETS_ARE_V6ONLY defined in config.h ? (but i don't think that changes anything for SSDP)

**Comment by razzfazz** [comment]
Hm, on closer examination, I think the issue is on my end. Let me close this for now.
