### ISSUE TITLE
ipv6 pinholes didn`t  updated

### ISSUE THREAD

**Issue by vvsvic** [miniupnp/miniupnp#188]
When I make pcp request twice, miniupnpd adds second equal rule to the iptables.

**Comment by miniupnp** [comment]
indeed, CreatePCPMap_FW() should check if existing and update if needed :
https://github.com/miniupnp/miniupnp/blob/master/miniupnpd/pcpserver.c#L988

**Comment by miniupnp** [comment]
i think I should add a find_inbound_pinhole() function

**Comment by vvsvic** [comment]
Thank you for fast commit.
Maybe, will be better to return -2 as "not found" from iptpinhole.c:find_pinhole() ? It will be same as in other functions.

**Comment by miniupnp** [comment]
OK : 6f8951d40dffaf1a50c5921ecc9c5998bbef116c
