### ISSUE TITLE
MINIUPNPD-PCP-PEER and `miniupnpd`

### ISSUE THREAD

**Issue by egberts** [miniupnp/miniupnp#190]
In the `iptables_init.sh`, I see a 3rd IP chain being used labeled as `MINIUPNPD-PCP-PEER`.

Is this also not configurable from `miniupnpd.conf` or is this a label for the "other" daemon (other than `miniupnpd`?

**Comment by miniupnp** [comment]
it is currently not configurable through miniupnpd.conf
