### ISSUE TITLE
miniupnpd: Does NAT-PMP support in fact work?

### ISSUE THREAD

**Issue by calmh** [miniupnp/miniupnp#196]
I'm having some trouble to get port maps correctly set up using NAT-PMP using miniupnpd 1.8.20140523-4 (Ubuntu 16.04). Specifically, the responses to port mapping requests seem to be malformed. I have a tshark dump in:

 https://gist.github.com/calmh/67cbe9a848cef6ea1e50162c3f7045d7

The interesting parts are the request on lines 179 etc:

```
NAT Port Mapping Protocol, Map TCP Request
    Version: 0
    Opcode: Map TCP Request (2)
    Reserved: 0
    Internal Port: 22002
    Requested External Port: 28174
    Requested Port Mapping Lifetime: 3600
```

compares to the (successfull) response on lines 242 etc:

```
NAT Port Mapping Protocol, Map TCP Response
    Version: 0
    Opcode: Map TCP Response (130)
    Result Code: Success (0)
    Seconds Since Start of Epoch: 317972
    Internal Port: 242
    Mapped External Port: 14
    Port Mapping Lifetime: 3600
```

Note that the internal and external port numbers have been garbled. Specifically, 242 == 22002%256 and 14 == 28174%256, so it seems like the numbers are getting truncated to the least significant 8 bits somewhere.

This causes an issue because the application interprets this as having gotten a port mapping on port 14 (!) while in actual fact miniupnpd did set it up on port 28174 as requested.

**Comment by calmh** [comment]
Duplicate of #89

**Comment by miniupnp** [comment]
please ask your distrib to update the package.
