### ISSUE TITLE
call to getaddrinfo fails in obscure situation.

### ISSUE THREAD

**Issue by ntadmin** [miniupnp/miniupnp#198]
I'm reporting this so that it is logged, but it may either be insoluble or not worth solving.

On some mips devices (in my case the Netgear DGND3700v2) the cross-compile tools provide include files which result in upnpc failing as follows (this error is triggered in connecthostport.c):

```
    List of UPNP devices found on the network : 
     desc: http://192.168.1.254:56688/rootDesc.xml 
     st: urn:schemas-upnp-org:device:InternetGatewayDevice:1 

    getaddrinfo() error : Bad value for ai_flags 
    No valid UPNP Internet Gateway Device found.
```

This is because:
- The cross compiler include files declare AI_NUMERICSERV as per nromal
- The code for the library it produces does not recognise AI_NUMERICSERV

Perhaps the easiest solution would be to provide a compile time option -DNO_AI_NUMERICSERV?

**Comment by miniupnp** [comment]
you could also fix the library headers used by the cross compiler !

**Comment by ntadmin** [comment]
Yes, that would also be an approach! I'm slightly wary of doing that, but I quite appreciate that this may not need any changes on your part. Just reporting it so that if someone else reports similar odd behaviour you know where to look :-)

I will probably simply patch the miniupnpc file for the build, rather than mess with the header file which is also used to build the c libraries for the firmware ...
