### ISSUE TITLE
Set _GNU_SOURCE in asyncsendto.c

### ISSUE THREAD

**Issue by ffontaine** [miniupnp/miniupnp#204]
A #define on _GNU_SOURCE should be added at the very beginning of asyncsendto.c file as this file uses in6_pktinfo which is protected by __USE_GNU in libc/inet/netinet/in.h. Currently, this flag is set by the Makefile in CFLAGS however CFLAGS could be overwritten by the build system. When this bug will be fixed, minissdpd could be integrated cleanly in buildroot.

**Comment by miniupnp** [comment]
If you think that is the proper way to do it... won't it break things on non linux systems ?

**Comment by ffontaine** [comment]
I don't think it will break the build as this define will just be ignored by non linux systems.
An other and possibly better option would be to update the Makefile to pass -D_GNU_SOURCE just for this one file as suggested by Khem here: https://patchwork.ozlabs.org/patch/654128.

**Comment by miniupnp** [comment]
-D_GNU_SOURCE is already passed for the whole build of minissdpd : 
https://github.com/miniupnp/miniupnp/blob/master/minissdpd/Makefile#L19
I don't see the point in passing it just for asyncsendto.c
