### ISSUE TITLE
pymoduletest.py on Windows

### ISSUE THREAD

**Issue by gvanem** [miniupnp/miniupnp#221]
This Python test script fails on Windows due to `WSAStartup()` not having been called. I built everything using MSVC-2015 issued:
```
python.exe pymoduletest.py
inital(default) values :
 discoverdelay 200
 lanaddr
 multicastif None
 minissdpdsocket None
Discovering... delay=200ms
Socket error: socket, 10093
0 device(s) detected
Empty devlist
Exception : No UPnP device discovered
```
Not sure where `WSASartup()` is best called. In `initminiupnpc()`? Anyway, with this patch it works:
```
--- a/miniupnpcmodule.c 2016-12-02 11:32:00
+++ b/miniupnpcmodule.c 2016-12-02 13:17:48
@@ -12,6 +12,10 @@
 #include "upnpcommands.h"
 #include "upnperrors.h"

+#ifdef _WIN32
+#include <winsock2.h>
+#endif
+
 /* for compatibility with Python < 2.4 */
 #ifndef Py_RETURN_NONE
 #define Py_RETURN_NONE return Py_INCREF(Py_None), Py_None
@@ -669,6 +673,9 @@
     PyObject* m;

 #ifdef _WIN32
+    WSADATA wsaData;
+    int nResult = WSAStartup(MAKEWORD(2,2), &wsaData);
+
     UPnPType.tp_new = PyType_GenericNew;
 #endif
     if (PyType_Ready(&UPnPType) < 0)
```

**Comment by Abdullah2993** [comment]
I'm failing to build the pythonmodule. Mind helping me with https://github.com/miniupnp/miniupnp/issues/224

**Comment by miniupnp** [comment]
I'm wondering if that is OK to call WSAStartup() it if is already called somewere.

**Comment by gvanem** [comment]
> I'm wondering if that is OK to call WSAStartup() it if is already called somewhere.

No it doesn't seems to hurt. Winsock has a reentry-test for that. Thanks for the fix!
