### ISSUE TITLE
OpenBSD miniupnpd/Ubuntu upnpC pinholing issue (most likely not respecting wildcards)

### ISSUE THREAD

**Issue by gizahNL** [miniupnp/miniupnp#228]
I've managed to compile miniupnpd with IPv6 pinholing without compiling in IGD2 to avoid isues with windows boxen.

Now am testing ipv6 pinholing support using the upnpc client installed on my ubuntu laptop. However I'm running into some issues, either the daemon creates the wrong rule or the client has no proper support for sending pinhole requests using wildcard source addresses. 
According to the -WANIPv6FirewallControl-v1 spec both A_ARG_TYPE_IPv6Address and A_ARG_TYPE_Port can be wildcarded by providing an empty string in the first case and a 0 in the latter. 
The upnpc cli requires input of both. Assuming a 0 in the source IP field would count as a wildcard (* is not accepted), the resulting firewall rule is not expected.

```
gijs@chaostop:~$ upnpc -6 -A 0 0  2001:984:a1fc:1:5ec5:d4ff:fecc:66a4 4444 tcp 600
upnpc : miniupnpc library test client. (c) 2005-2014 Thomas Bernard
Go to http://miniupnp.free.fr/ or http://miniupnp.tuxfamily.org/
for more information.
List of UPNP devices found on the network :
 desc: http://[2001:984:a1fc:1::1]:5556/rootDesc.xml
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

Found valid IGD : http://[2001:984:a1fc:1::1]:5556/ctl/IPConn
Local LAN ip address : 2001:984:a1fc:1:5ec5:d4ff:fecc:66a4
AddPinhole: ([0]:0 -> [2001:984:a1fc:1:5ec5:d4ff:fecc:66a4]:4444) / Pinhole ID = 2

```

firewall rules:
```
pfctl -a "miniupnpd" -s rules                            
pass in quick inet6 proto tcp from 2001:984:a1fc::1 to 2001:984:a1fc:1:5ec5:d4ff:fecc:66a4 port = 4444 flags S/SA label "pinhole-2 ts-1485805857: IGD2 pinhole"

```
 2001:984:a1fc::1 is the WAN facing IPv6 address, in PF either 'from' and the address should be omitted in case no source port is specified or the address should be replaced by 'any'  in case a source port is specified. 

I'm not sure whether the problem resides in the client (both latest compiled from source and ubuntu default) or in the miniupnpd handling of wildcards on OpenBSD/PF

On a side note, building with IPv6, V6SOCKETS_ARE_V6ONLY (without this windows won't see miniupnpd in my case) and  ENABLE_6FC_SERVICE but without IGD2 seems to correctly expose WANIPv6FirewallControl without running into the compatibility issues with windows (i.e.: in windows the device is still represented in the IGD1 way, and seems to function normally). This might technically be out of spec, but might be a solution for people who want IPv6 pinholing and don't want to wait for microsoft to get their shit together.

**Comment by miniupnp** [comment]
you should recompile upnpc with -DDEBUG to enable very verbose output
are you sure you cannot use empty string as source ip string ? "" or '' ?

**Comment by gizahNL** [comment]
With double quotations I'm able to indeed send an empty string as shown by debug output. however the source adress is still mapped to the WAN facing interface


```
Body :
<?xml version="1.0"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:AddPinhole xmlns:u="urn:schemas-upnp-org:service:WANIPv6FirewallControl:1"><RemoteHost> </RemoteHost><RemotePort>0</RemotePort><Protocol>6</Protocol><InternalPort>8890</InternalPort><InternalClient>2001:984:a1fc:1:5ec5:d4ff:fecc:66a4</InternalClient><LeaseTime>600</LeaseTime></u:AddPinhole></s:Body></s:Envelope>

HTTP status code = 200, Reason phrase = OK
header='Content-Type', value='text/xml; charset="utf-8"'
header='Connection', value='close'
header='Content-Length', value='310'
Content-Length: 310
header='Server', value='OpenBSD/6.0 UPnP/1.1 MiniUPnPd/2.0'
header='Ext', value=''
End of HTTP content
HTTP 200 SOAP Response :
<?xml version="1.0"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:AddPinholeResponse xmlns:u="urn:schemas-upnp-org:service:WANIPv6FirewallControl:1"><UniqueID>1</UniqueID></u:AddPinholeResponse></s:Body></s:Envelope>

AddPinhole: ([ ]:0 -> [2001:984:a1fc:1:5ec5:d4ff:fecc:66a4]:8890) / Pinhole ID = 1
```

miniupnpd side with debugging turned on

```
miniupnpd[91124]: HTTP REQUEST from [2001:984:a1fc:1:5ec5:d4ff:fecc:66a4]:32986 : POST /ctl/IP6FCtl (HTTP/1.1)
miniupnpd[91124]: Host: [2001:984:a1fc:1::1]:5556
miniupnpd[91124]: SOAPAction: urn:schemas-upnp-org:service:WANIPv6FirewallControl:1#AddPinhole
miniupnpd[91124]: resolved ' ' to '2001:984:a1fc::1'
miniupnpd[91124]: Checking internal IP@ and port (Security policy purpose)
miniupnpd[91124]: AddPinhole: (inbound) from [2001:984:a1fc::1]:0 to [2001:984:a1fc:1:5ec5:d4ff:fecc:66a4]:8890 with proto 6 during 600 sec
```

my guess is is that miniupnpd is trying to use DNS to resolve the empty string...

**Comment by miniupnp** [comment]
hum it is not passing an empty string, but a single space string " "
the test here https://github.com/miniupnp/miniupnp/blob/master/miniupnpd/upnpsoap.c#L1608 is on empty string...

**Comment by miniupnp** [comment]
have you tried '*' also ?

**Comment by miniupnp** [comment]
the code there does handle '*' or '' (empty string) wildcards : 
https://github.com/miniupnp/miniupnp/blob/master/miniupnpd/pf/pfpinhole.c#L124

**Comment by gizahNL** [comment]
mmmm, you are right about the space... and "" omitting space does give the desired rule... 

"*" did result again in the wrong rule:

```
miniupnpd[51378]: HTTP REQUEST from [2001:984:a1fc:1:5ec5:d4ff:fecc:66a4]:33282 : POST /ctl/IP6FCtl (HTTP/1.1)
miniupnpd[51378]: Host: [2001:984:a1fc:1::1]:5556
miniupnpd[51378]: SOAPAction: urn:schemas-upnp-org:service:WANIPv6FirewallControl:1#AddPinhole
miniupnpd[51378]: resolved '*' to '2001:984:a1fc::1'
miniupnpd[51378]: Checking internal IP@ and port (Security policy purpose)
miniupnpd[51378]: AddPinhole: (inbound) from [2001:984:a1fc::1]:0 to [2001:984:a1fc:1:5ec5:d4ff:fecc:66a4]:8892 with proto 6 during 600 sec
```

For now I will be able to test with "", but it might give some issues with non compliant clients or other users like me ;) I would assume anything that doesn't contain at least one dot (can be trailing if tld) should not be resolved DNS wise (if that is what is happening). Spaces, and zeroes should probably be treated as wildcards ;)

**Comment by miniupnp** [comment]
yes, there is some arg sanitization to do

**Comment by gizahNL** [comment]
on a sidenote, even with USE_IFNAME_IN_RULES (and it working correctly for other rules) this does not seem to work with pinhole rules. Minor issue, and should not create problems in my case.

**Comment by miniupnp** [comment]
so before closing this issue : 
1. sanitize <RemoteHost> args
2. check USE_IFNAME_IN_RULES works in pfpinhole.c

**Comment by miniupnp** [comment]
@gizahNL 

> on a sidenote, even with USE_IFNAME_IN_RULES (and it working correctly for other rules) this does not seem to work with pinhole rules. Minor issue, and should not create problems in my case.

I think I found the issue : https://github.com/miniupnp/miniupnp/blob/master/miniupnpd/upnppinhole.c#L144
