### ISSUE TITLE
miniupnpd-current IPv6 LOCATION does not match unicast source address

### ISSUE THREAD

**Issue by gizahNL** [miniupnp/miniupnp#229]
Running on OpenBSD (though I think this one might be OS agnostic) 
IPv6 responses send from link local address do not match location url to source address.

According to UDA 2.0 appendix A2.3-j location urls shall match unicast source address, this /might/ coincidentally also be the reason windows machines don't pick up on the IPv6 part: windows does a search on link local, gets a respond with a GUA location address and fails to make any more requests. 

SSDP M-SEARCH from [fe80::50dd:dbe5:441f:c800%vlan1]:51275 ST: upnp:rootdevice
miniupnpd[75989]: Single search found
miniupnpd[75989]: SendSSDPResponse(): 0 bytes to [fe80::50dd:dbe5:441f:c800%vlan1]:51275 ST: HTTP/1.1 200 OK
CACHE-CONTROL: max-age=120
ST: upnp:rootdevice
USN: uuid:6b9a5b44-114c-49c2-af26-3bfdc38d40ce::upnp:rootdevice
EXT:
SERVER: OpenBSD/6.0 UPnP/2.0 MiniUPnPd/2.0
LOCATION: http://[2001:984:a1fc:1::1]:5556/rootDesc.xml
OPT: "http://schemas.upnp.org/upnp/1/0/"; ns=01
01-NLS: 1486040242
BOOTID.UPNP.ORG: 1486040242
CONFIGID.UPNP.ORG: 1337

**Comment by miniupnp** [comment]
have you built with "strict" option ?
https://github.com/miniupnp/miniupnp/blob/master/miniupnpd/minissdp.c#L958

**Comment by miniupnp** [comment]
as far as I remember the current code is as it is because many HTTP clients have issues connecting to link-local addresses. 
with UPNP_STRICT defined, the UDA is followed

**Comment by gizahNL** [comment]
when compiling with strict, no correct address is returned.

SSDP M-SEARCH from [fe80::385a:4145:8f30:fa7a%vlan1]:35974 ST: urn:schemas-upnp-org:device:InternetGatewayDevice:1
miniupnpd[22168]: read l=256 seq=1 pid=22168   sizeof(struct rt_msghdr)=96
miniupnpd[22168]: offset=  0 type= 1 sa_len=28 sa_family=24 [fe80::]:0
miniupnpd[22168]: offset= 32 type= 2 sa_len=28 sa_family=24 [::1]:0
miniupnpd[22168]: offset= 64 type= 4 sa_len=28 sa_family=24 [ffc0::]:0
miniupnpd[22168]: offset= 96 type=16 sa_len=32 sa_family=18 index=9 type=24 lo0
miniupnpd[22168]: offset=128 type=32 sa_len=28 sa_family=24 [::1]:0
miniupnpd[22168]: Single search found
miniupnpd[22168]: SendSSDPResponse(): 0 bytes to [fe80::385a:4145:8f30:fa7a%vlan1]:35974 ST: HTTP/1.1 200 OK
CACHE-CONTROL: max-age=120
ST: urn:schemas-upnp-org:device:InternetGatewayDevice:1
USN: uuid:6b9a5b44-114c-49c2-af26-3bfdc38d40ce::urn:schemas-upnp-org:device:InternetGatewayDevice:1
EXT:
SERVER: OpenBSD/6.0 UPnP/2.0 MiniUPnPd/2.0
#LOCATION: http://[::1]:5556/rootDesc.xml
OPT: "http://schemas.upnp.org/upnp/1/0/"; ns=01
01-NLS: 1486046410
BOOTID.UPNP.ORG: 1486046410
CONFIGID.UPNP.ORG: 1337

**Comment by gizahNL** [comment]
Hmmm, the machine also seems to not be responding on FF05::C, whether my firewall is turned on or not. I have no idea on how to check whether miniupnpd has actually opened a socket and is listening for multicast traffic

**Comment by miniupnp** [comment]
hum I think for link local addresses destination I should use the link local address of the right link (vlan1 for you)

**Comment by miniupnp** [comment]
netstat -a ?

**Comment by gizahNL** [comment]
Pv6 Multicast Interface Table is empty
IPv6 Multicast Routing Table is empty
# top
# netstat -a
Active Internet connections (including servers)
Proto   Recv-Q Send-Q  Local Address          Foreign Address        (state)
ip           0      0  *.*                    *.*                    1
Active Internet connections (including servers)
Proto   Recv-Q Send-Q  Local Address          Foreign Address        (state)
tcp          0      0  heteigenwijsje.n.https gijs-desktop.lan.49969 TIME_WAIT
tcp          0      0  ns.lan.ssh             10.0.1.230.33836       ESTABLISHED
tcp          0     44  ns.lan.ssh             10.0.1.230.33818       ESTABLISHED
tcp          0      0  *.ssh                  *.*                    LISTEN
tcp          0      0  *.5556                 *.*                    LISTEN
tcp          0      0  heteigenwijsje.n.www   *.*                    LISTEN
tcp          0      0  localhost.www          *.*                    LISTEN
tcp          0      0  *.https                *.*                    LISTEN
tcp          0      0  localhost.953          *.*                    LISTEN
tcp          0      0  heteigenwijsje.n.domai *.*                    LISTEN
tcp          0      0  localhost.krb524       *.*                    LISTEN
tcp          0      0  localhost.8021         *.*                    LISTEN
tcp          0      0  localhost.smtp         *.*                    LISTEN
tcp          0      0  10.0.15.1.domain       *.*                    LISTEN
tcp          0      0  10.0.14.1.domain       *.*                    LISTEN
tcp          0      0  ns.lan.domain          *.*                    LISTEN
tcp          0      0  localhost.domain       *.*                    LISTEN
tcp          0      0  tor.9030               *.*                    LISTEN
tcp          0      0  tor.9001               *.*                    LISTEN
tcp          0      0  localhost.9040         *.*                    LISTEN
tcp          0      0  localhost.9999         *.*                    LISTEN
tcp          0      0  localhost.8118         *.*                    LISTEN
tcp          0      0  tor.www                *.*                    LISTEN
Active Internet connections (including servers)
Proto   Recv-Q Send-Q  Local Address          Foreign Address        (state)
udp          0      0  heteigenwijsje.n.43611 excalibur.prolix.ntp  
udp          0      0  heteigenwijsje.n.41015 ntp1.mediamatic..ntp  
udp          0      0  heteigenwijsje.n.3702  ntp1.edutel.nl.ntp    
udp          0      0  heteigenwijsje.n.33662 y.ns.gin.ntt.net.ntp  
udp          0      0  heteigenwijsje.n.21097 google-public-dn.domai
udp          0      0  heteigenwijsje.n.4345  google-public-dn.domai
udp          0      0  heteigenwijsje.n.17539 google-public-dn.domai
udp          0      0  heteigenwijsje.n.29031 google-public-dn.domai
udp          0      0  *.bootps               *.*                   
udp          0      0  *.53918                *.*                   
udp          0      0  ns.lan.5351            *.*                   
udp          0      0  ns.lan.13818           *.*                   
udp          0      0  *.ssdp                 *.*                   
udp          0      0  10.0.15.1.domain       *.*                   
udp          0      0  10.0.14.1.domain       *.*                   
udp          0      0  ns.lan.domain          *.*                   
udp          0      0  localhost.domain       *.*                   
udp          0      0  *.40353                *.*                   
udp          0      0  10.0.128.1.domain      *.*                   
udp          0      0  *.14250                *.*                   
udp          0      0  heteigenwijsje.n.1194  *.*                   
udp          0      0  heteigenwijsje.n.domai *.*                   
udp          0      0  localhost.krb524       *.*                   
udp          0      0  *.syslog               *.*                   
Active Internet connections (including servers)
Proto   Recv-Q Send-Q  Local Address          Foreign Address        (state)
tcp6         0      0  2001:984:a1fc::2.9001  tor.noreply.org.40178  ESTABLISHED
tcp6         0      0  2001:984:a1fc::2.9001  longclaw.riseup..38630 ESTABLISHED
tcp6         0      0  2001:984:a1fc::2.9001  despari.informat.36126 ESTABLISHED
tcp6         0      0  *.ssh                  *.*                    LISTEN
tcp6         0      0  localhost.smtp         *.*                    LISTEN
tcp6         0      0  2001:984:a1fc::1.domai *.*                    LISTEN
tcp6         0      0  *.https                *.*                    LISTEN
tcp6         0      0  *.www                  *.*                    LISTEN
tcp6         0      0  *.5556                 *.*                    LISTEN
tcp6         0      0  2001:984:a1fc::2.9001  *.*                    LISTEN
tcp6         0      0  localhost.5546         *.*                    LISTEN
tcp6         0      0  fe80::1%lo0.smtp       *.*                    LISTEN
Active Internet connections (including servers)
Proto   Recv-Q Send-Q  Local Address          Foreign Address        (state)
udp6         0      0  *.ssdp                 *.*                   
udp6         0      0  *.10728                *.*                   
udp6         0      0  *.32129                *.*                   
udp6         0      0  *.dhcpv6-c             *.*                   
udp6         0      0  2001:984:a1fc::1.domai *.*                   
udp6         0      0  *.5351                 *.*                   
udp6         0      0  *.syslog               *.*                   
Active Internet connections (including servers)
Proto   Recv-Q Send-Q  Local Address          Foreign Address        (state)
ip6          0      0  *.*                    *.*                    58
Active UNIX domain sockets
Address            Type   Recv-Q Send-Q              Inode               Conn               Refs            Nextref Addr
0xffff800000f38200 stream      0      0                0x0 0xffff800000f38280                0x0                0x0
0xffff800000f38180 stream      0      0                0x0 0xffff800000f38100                0x0                0x0
0xffff800000f38100 stream      0      0                0x0 0xffff800000f38180                0x0                0x0
0xffff800000f38080 stream      0      0                0x0 0xffff800000f38000                0x0                0x0
0xffff800000f38000 stream      0      0                0x0 0xffff800000f38080                0x0                0x0
0xffff800000f35180 stream      0      0                0x0 0xffff800000f35100                0x0                0x0
0xffff800000f35100 stream      0      0                0x0 0xffff800000f35180                0x0                0x0
0xffff800000f35080 stream      0      0                0x0 0xffff800000f35000                0x0                0x0
0xffff800000f35000 stream      0      0                0x0 0xffff800000f35080                0x0                0x0
0xffff800000f20300 stream      0      0                0x0 0xffff800000f20f00                0x0                0x0
0xffff800000f20f00 stream      0      0                0x0 0xffff800000f20300                0x0                0x0
0xffff800000f20e00 stream      0      0                0x0 0xffff800000f20e80                0x0                0x0
0xffff800000f20e80 stream      0      0                0x0 0xffff800000f20e00                0x0                0x0
0xffff800000f20d80 stream      0      0                0x0 0xffff800000f20100                0x0                0x0
0xffff800000f20100 stream      0      0                0x0 0xffff800000f20d80                0x0                0x0
0xffff800000f8bf80 stream      0      0 0xffffff015d456e98                0x0                0x0                0x0 /tmp/ssh-SGdRYwdOIP/agent.3225
0xffff800000f20400 stream      0      0                0x0 0xffff800000ec6300                0x0                0x0
0xffff800000ec6300 stream      0      0                0x0 0xffff800000f20400                0x0                0x0
0xffff800000f52b00 stream      0      0 0xffffff016fa20c28                0x0                0x0                0x0 /tmp/ssh-XIBtK5tk0V/agent.57402
0xffff800000efeb80 stream      0      0                0x0 0xffff800000efe280                0x0                0x0
0xffff800000efe280 stream      0      0                0x0 0xffff800000efeb80                0x0                0x0
0xffff800000f45600 stream      0      0                0x0 0xffff800000f44d00                0x0                0x0
0xffff800000f44d00 stream      0      0                0x0 0xffff800000f45600                0x0                0x0
0xffff800000f8bd80 stream      0      0                0x0 0xffff800000f20880                0x0                0x0
0xffff800000f20880 stream      0      0                0x0 0xffff800000f8bd80                0x0                0x0
0xffff800000f52480 stream      0      0 0xffffff0192106b88                0x0                0x0                0x0 /var/run/unbound.sock
0xffff800000f45a80 stream      0      0                0x0 0xffff800000f45500                0x0                0x0
0xffff800000f45500 stream      0      0                0x0 0xffff800000f45a80                0x0                0x0
0xffff800000f45100 stream      0      0                0x0 0xffff800000f52600                0x0                0x0
0xffff800000e6f880 stream      0      0                0x0 0xffff800000e6f900                0x0                0x0
0xffff800000e6f480 stream      0      0                0x0 0xffff800000e6f380                0x0                0x0
0xffff800000e6f380 stream      0      0                0x0 0xffff800000e6f480                0x0                0x0
0xffff800000f52880 stream      0      0 0xffffff016b893db8                0x0                0x0                0x0 /var/run/cron.sock
0xffff800000f52580 stream      0      0 0xffffff016b8939d0                0x0                0x0                0x0 /var/run/apmdev
0xffff800000f38b00 stream      0      0 0xffffff016f1e08c8                0x0                0x0                0x0 /var/run/smtpd.sock
0xffff800000f38a80 stream      0      0                0x0 0xffff800000f38a00                0x0                0x0
0xffff800000f38a00 stream      0      0                0x0 0xffff800000f38a80                0x0                0x0
0xffff800000f38980 stream      0      0                0x0 0xffff800000f38900                0x0                0x0
0xffff800000f38900 stream      0      0                0x0 0xffff800000f38980                0x0                0x0
0xffff800000f38880 stream      0      0                0x0 0xffff800000f38800                0x0                0x0
0xffff800000f38800 stream      0      0                0x0 0xffff800000f38880                0x0                0x0
0xffff800000f38780 stream      0      0                0x0 0xffff800000f38700                0x0                0x0
0xffff800000f38700 stream      0      0                0x0 0xffff800000f38780                0x0                0x0
0xffff800000f38680 stream      0      0                0x0 0xffff800000f38600                0x0                0x0
0xffff800000f38600 stream      0      0                0x0 0xffff800000f38680                0x0                0x0
0xffff800000f38580 stream      0      0                0x0 0xffff800000f38500                0x0                0x0
0xffff800000f38500 stream      0      0                0x0 0xffff800000f38580                0x0                0x0
0xffff800000f38480 stream      0      0                0x0 0xffff800000f38400                0x0                0x0
0xffff800000f38400 stream      0      0                0x0 0xffff800000f38480                0x0                0x0
0xffff800000f38380 stream      0      0                0x0 0xffff800000f38300                0x0                0x0
0xffff800000f38300 stream      0      0                0x0 0xffff800000f38380                0x0                0x0
0xffff800000f38280 stream      0      0                0x0 0xffff800000f38200                0x0                0x0
0xffff800000f20980 stream      0      0                0x0 0xffff800000f20900                0x0                0x0
0xffff800000f20900 stream      0      0                0x0 0xffff800000f20980                0x0                0x0
0xffff800000e6f900 stream      0      0                0x0 0xffff800000e6f880                0x0                0x0
0xffff800000f52600 stream      0      0                0x0 0xffff800000f45100                0x0                0x0
0xffff800000f20b00 stream      0      0                0x0 0xffff800000f20a80                0x0                0x0
0xffff800000f20a80 stream      0      0                0x0 0xffff800000f20b00                0x0                0x0
0xffff800000f20a00 stream      0      0 0xffffff016e8a7928                0x0                0x0                0x0 /var/run/ntpd.sock
0xffff800000e6f580 dgram       0      0 0xffffff016d39c210                0x0                0x0                0x0 /dev/log
0xffff800000e6af80 dgram       0      0                0x0 0xffff800000e6ae80 0xffff800000e6ae80                0x0
0xffff800000e6ae80 dgram       0      0                0x0 0xffff800000e6af80 0xffff800000e6af80                0x0
#

**Comment by miniupnp** [comment]
udp6 0 0 *.ssdp .

**Comment by gizahNL** [comment]
Yes, that I saw, though I don't know whether it has made itself a member of the multicast group, I know it responds to SSDP traffic when sent to the link-local multicast group, but it doesn't when it's send to the site-local group, which I'm now sure is unfiltered as I tried with PF turned off.

**Comment by miniupnp** [comment]
well it adds membership here : 
https://github.com/miniupnp/miniupnp/blob/master/miniupnpd/minissdp.c#L88

**Comment by gizahNL** [comment]
yes, but it does not respond, nor does the debug seem to indicate receiving any m-searches on IPv6 when they are solely output to FF05::C

**Comment by miniupnp** [comment]
multicast is not frequently used, it is also possible there is a bug in OpenBSD (or that miniupnpd is not using the OpenBSD api correctly)

**Comment by miniupnp** [comment]
does tshark/tcpdump on the Openbsd box sees theses FF05::C destined M-SEARCH's ?

**Comment by gizahNL** [comment]
mmm it does not...  Wireshark on my sending box does show them...

**Comment by gizahNL** [comment]
mmm it seems openwrt is the culprit there, for some reason when connected through wifi it doesn't pass all packets. Even though it is running in pure AP mode. 

Cabled it /does/ indeed respond to FF05::C, and then it does set the correct LOCATION address. So that bug seems to only exist with link-local

**Comment by miniupnp** [comment]
@gizahNL can you test with linklocal now ?
