### ISSUE TITLE
upnpc ipv6: does not respect source address specification  

### ISSUE THREAD

**Issue by gizahNL** [miniupnp/miniupnp#230]
I'm trying to debug both my firewall and whether miniupnpd correctly responds to messages send to FF05::C, however upnpc ignores my IPv6 source address set using command line:
./upnpc-static  -6 -m [2001:984:a1fc:1:8d38:2e84:ebef:8e49] -S 
or
./upnpc-static  -6 -m 2001:984:a1fc:1:8d38:2e84:ebef:8e49 -S

both yield:
upnpc : miniupnpc library test client, version 2.0.
 (c) 2005-2016 Thomas Bernard.
Go to http://miniupnp.free.fr/ or http://miniupnp.tuxfamily.org/
for more information.
Sending M-SEARCH request to [FF02::C] with ST: urn:schemas-upnp-org:device:InternetGatewayDevice:1

And in wireshark show utilization of the link-local address

**Comment by miniupnp** [comment]
I think this need to be fixed for IPv6

**Comment by gizahNL** [comment]
my guess is that IPv6 has not been tested as well as IPv4 ;) :/ 

Unfortunately my experience with writing code is exactly 0

**Comment by gizahNL** [comment]
well by compiling my IPv6 adress into upnpc.c I have managed to get an request to FF05:C exactly once... Afterwards it goes happily back to only using linklocal.... Unfortunately wireshark was not running at this time, so I have no idea whether miniupnpd correctly responded 
Does it cache responses somewhere? This might explain why the same command does not yield the same behavior everytime.

**Comment by miniupnp** [comment]
with ipv6 -m option should be an interface.
-m eth0
Both link-local and "site-local" multicast addresses are used (FF02::C and FF05:C) are tried,
but linklocal first... That's the logic : 1st try to discover UPnP Device on the link with FF02::C and if none is found, try with the site local address

**Comment by gizahNL** [comment]
aha, well then I can test FF05::C behavior by just blocking FF02::C on my firewall ;) 

Commandline feedback when the program is ran without arguments does hint at a capability of manually setting IPv6 :P

**Comment by miniupnp** [comment]
to prevent miniupnpc to send request on link local address, just force linklocal = 0 in ssdpDiscoverDevices()
https://github.com/miniupnp/miniupnp/blob/master/miniupnpc/minissdpc.c#L505
https://github.com/miniupnp/miniupnp/blob/master/miniupnpc/minissdpc.c#L868

**Comment by miniupnp** [comment]
`  -m address/interface : provide ip address (ip v4) or interface name (ip v4 or v6) to use for sending SSDP multicast packets.`
I think that's clear that IP addresses are accepted only for IP v4

**Comment by gizahNL** [comment]
yes you are right... i was reading the statements wrong there ;) 

Will try with link local disabled because I suspect either my firewall to block FF05::C or miniupnpd not to be responding correctly there..
