### ISSUE TITLE
OpenBSD/PF miniupnpd creates rules with 'any' as IP destination field

### ISSUE THREAD

**Issue by gizahNL** [miniupnp/miniupnp#231]
Even when compiled with multiple IP support and (when only using external IP for miniupnpd) ext_ip= defined in miniupnpd.conf miniupnpd creates redirection rules with any as destination IP. This can break connections to other IPs that are either on the same box or are routed to from the box. 

pfctl -a miniupnpd -s rules 
pass in quick on pppoe0 inet proto tcp from any to any port = 26629 flags any label "uTorrent (TCP)" rdr-to 10.0.1.201 port 26629
pass in quick on pppoe0 inet proto udp from any to any port = 26629 label "uTorrent (UDP)" rdr-to 10.0.1.201 port 26629

 WAN network interface
ext_ifname=pppoe0
ext_ip=80.127.116.99
listening_ip=vlan1 /*adding the external IP on this line as per example has no effect */
http_port=5556
enable_natpmp=yes
lease_file=/var/log/upnp.leases
bitrate_up=524288000
bitrate_down=524288000
secure_mode=yes
system_uptime=yes
notify_interval=60
clean_ruleset_interval=600
uuid=6b9a5b44-114c-49c2-af26-3bfdc38d40ce
allow 1024-65535 10.0.1.1/24 1024-65535
deny 0-65535 0.0.0.0/0 0-65535

**Comment by gizahNL** [comment]
compiled with leasefile, strict, ipv6, 6FC_SERVICE and ENABLE_DP_SERVICE

**Comment by miniupnp** [comment]
well in fact the MULTIPLE_EXTERNAL_IP code is not maintained

**Comment by miniupnp** [comment]
@gizahNL is the issue critical to you ?

**Comment by gizahNL** [comment]
sorry to get back this late,. Also without multiple IP support build in the issue is (in my case miniupnpd only needs to do pmp for 1 ip) 
I would suggest adding logic that parses miniupnpd.conf, and if ext_ip is defined to use that in the to field, in stead of any. 

Though the risk is obviously quite small ( something in my network needs to randomly map to something that is already running on another IP, within the higher portrange) it does exist ;)

**Comment by miniupnp** [comment]
@gizahNL could you test the patch 53e8185 ?
