### ISSUE TITLE
Compiled windows executable has no instructions, how do you run it?

### ISSUE THREAD

**Issue by Question2** [miniupnp/miniupnp#233]
upnpc-exe-win32-20150918.zip 	100004 	18/09/2015 14:50:41 +0200 	Windows executable

I downloaded the above compiled version from the mini upnp site, it contains two executables. But the readme file only has instructions for compiling an uncompiled version, and contains absolutely no instructions or information on how to use the program, the difference between the two executable files or what they even do.

I was told that this allows you to port forward a router without needing admin access to the router, is this correct?

**Comment by miniupnp** [comment]
just run the program (command line) to get documentation
I can't tell anything about your router, please read its documentation to know if it is compatible with UPNP
