### ISSUE TITLE
upnpc does not work on mine device Im geting error 399 what that mean ?

### ISSUE THREAD

**Issue by vido89** [miniupnp/miniupnp#235]
Im truing to add port mapping on my router via upnp and upnpc but it does nor work any help
```

upnpc -u http://192.168.1.254:52869/gateinfoSCPD.xml -l
upnpc : miniupnpc library test client. (c) 2005-2014 Thomas Bernard
Go to http://miniupnp.free.fr/ or http://miniupnp.tuxfamily.org/
for more information.
upnpDiscover() error code=0
Found valid IGD : http://192.168.1.254:52869/
Local LAN ip address : 192.168.10.190
GetConnectionTypeInfo failed.
GetStatusInfo failed.
  Time started : Tue Feb 21 03:13:40 2017
GetLinkLayerMaxBitRates failed.
GetExternalIPAddress failed. (errorcode=399)
 i protocol exPort->inAddr:inPort description remoteHost leaseTime
GetGenericPortMappingEntry() returned 399 (UnknownError)
```

**Comment by miniupnp** [comment]
399 is an invalid error code.
also "Found valid IGD : http://192.168.1.254:52869/" is suspicious.
Please show  http://192.168.1.254:52869/gateinfoSCPD.xml

**Comment by miniupnp** [comment]
-u arg must be root description URL

**Comment by vido89** [comment]
Here is gateinfoSCPD.xml
`<scpd><specVersion><major>1</major><minor>0</minor></specVersion><actionList><action><name>MagicOn</name></action></actionList><serviceStateTable><stateVariable><name>OSMajorVersion</name><dataType>i4</dataType></stateVariable><stateVariable><name>OSMinorVersion</name><dataType>i4</dataType></stateVariable><stateVariable><name>OSBuildNumber</name><dataType>i4</dataType></stateVariable><stateVariable><name>OSMachineName</name><dataType>string</dataType></stateVariable></serviceStateTable></scpd>`

**Comment by miniupnp** [comment]
yes this is not the root description document.
what's the root description URL and what happens when passed as -u argument to upnpc ?

**Comment by vido89** [comment]
Is this root description gateconnSCPD.xml
`
<scpd><specVersion><major>1</major><minor>0</minor></specVersion><actionList><action><name>SetConnectionType</name><argumentList><argument><name>NewConnectionType</name><direction>in</direction><relatedStateVariable>ConnectionType</relatedStateVariable></argument></argumentList></action><action><name>GetConnectionTypeInfo</name><argumentList><argument><name>NewConnectionType</name><direction>out</direction><relatedStateVariable>ConnectionType</relatedStateVariable></argument><argument><name>NewPossibleConnectionTypes</name><direction>out</direction><relatedStateVariable>PossibleConnectionTypes</relatedStateVariable></argument></argumentList></action><action><name>RequestConnection</name></action><action><name>ForceTermination</name></action><action><name>GetStatusInfo</name><argumentList><argument><name>NewConnectionStatus</name><direction>out</direction><relatedStateVariable>ConnectionStatus</relatedStateVariable></argument><argument><name>NewLastConnectionError</name><direction>out</direction><relatedStateVariable>LastConnectionError</relatedStateVariable></argument><argument><name>NewUptime</name><direction>out</direction><relatedStateVariable>Uptime</relatedStateVariable></argument></argumentList></action><action><name>GetNATRSIPStatus</name><argumentList><argument><name>NewRSIPAvailable</name><direction>out</direction><relatedStateVariable>RSIPAvailable</relatedStateVariable></argument><argument><name>NewNATEnabled</name><direction>out</direction><relatedStateVariable>NATEnabled</relatedStateVariable></argument></argumentList></action><action><name>GetGenericPortMappingEntry</name><argumentList><argument><name>NewPortMappingIndex</name><direction>in</direction><relatedStateVariable>PortMappingNumberOfEntries</relatedStateVariable></argument><argument><name>NewRemoteHost</name><direction>out</direction><relatedStateVariable>RemoteHost</relatedStateVariable></argument><argument><name>NewExternalPort</name><direction>out</direction><relatedStateVariable>ExternalPort</relatedStateVariable></argument><argument><name>NewProtocol</name><direction>out</direction><relatedStateVariable>PortMappingProtocol</relatedStateVariable></argument><argument><name>NewInternalPort</name><direction>out</direction><relatedStateVariable>InternalPort</relatedStateVariable></argument><argument><name>NewInternalClient</name><direction>out</direction><relatedStateVariable>InternalClient</relatedStateVariable></argument><argument><name>NewEnabled</name><direction>out</direction><relatedStateVariable>PortMappingEnabled</relatedStateVariable></argument><argument><name>NewPortMappingDescription</name><direction>out</direction><relatedStateVariable>PortMappingDescription</relatedStateVariable></argument><argument><name>NewLeaseDuration</name><direction>out</direction><relatedStateVariable>PortMappingLeaseDuration</relatedStateVariable></argument></argumentList></action><action><name>GetSpecificPortMappingEntry</name><argumentList><argument><name>NewRemoteHost</name><direction>in</direction><relatedStateVariable>RemoteHost</relatedStateVariable></argument><argument><name>NewExternalPort</name><direction>in</direction><relatedStateVariable>ExternalPort</relatedStateVariable></argument><argument><name>NewProtocol</name><direction>in</direction><relatedStateVariable>PortMappingProtocol</relatedStateVariable></argument><argument><name>NewInternalPort</name><direction>out</direction><relatedStateVariable>InternalPort</relatedStateVariable></argument><argument><name>NewInternalClient</name><direction>out</direction><relatedStateVariable>InternalClient</relatedStateVariable></argument><argument><name>NewEnabled</name><direction>out</direction><relatedStateVariable>PortMappingEnabled</relatedStateVariable></argument><argument><name>NewPortMappingDescription</name><direction>out</direction><relatedStateVariable>PortMappingDescription</relatedStateVariable></argument><argument><name>NewLeaseDuration</name><direction>out</direction><relatedStateVariable>PortMappingLeaseDuration</relatedStateVariable></argument></argumentList></action><action><name>AddPortMapping</name><argumentList><argument><name>NewRemoteHost</name><direction>in</direction><relatedStateVariable>RemoteHost</relatedStateVariable></argument><argument><name>NewExternalPort</name><direction>in</direction><relatedStateVariable>ExternalPort</relatedStateVariable></argument><argument><name>NewProtocol</name><direction>in</direction><relatedStateVariable>PortMappingProtocol</relatedStateVariable></argument><argument><name>NewInternalPort</name><direction>in</direction><relatedStateVariable>InternalPort</relatedStateVariable></argument><argument><name>NewInternalClient</name><direction>in</direction><relatedStateVariable>InternalClient</relatedStateVariable></argument><argument><name>NewEnabled</name><direction>in</direction><relatedStateVariable>PortMappingEnabled</relatedStateVariable></argument><argument><name>NewPortMappingDescription</name><direction>in</direction><relatedStateVariable>PortMappingDescription</relatedStateVariable></argument><argument><name>NewLeaseDuration</name><direction>in</direction><relatedStateVariable>PortMappingLeaseDuration</relatedStateVariable></argument></argumentList></action><action><name>DeletePortMapping</name><argumentList><argument><name>NewRemoteHost</name><direction>in</direction><relatedStateVariable>RemoteHost</relatedStateVariable></argument><argument><name>NewExternalPort</name><direction>in</direction><relatedStateVariable>ExternalPort</relatedStateVariable></argument><argument><name>NewProtocol</name><direction>in</direction><relatedStateVariable>PortMappingProtocol</relatedStateVariable></argument></argumentList></action><action><name>GetExternalIPAddress</name><argumentList><argument><name>NewExternalIPAddress</name><direction>out</direction><relatedStateVariable>ExternalIPAddress</relatedStateVariable></argument></argumentList></action></actionList><serviceStateTable><stateVariable sendEvents="no"><name>ConnectionType</name><dataType>string</dataType><defaultValue>Unconfigured</defaultValue></stateVariable><stateVariable sendEvents="yes"><name>PossibleConnectionTypes</name><dataType>string</dataType><allowedValueList><allowedValue>Unconfigured</allowedValue><allowedValue>IP_Routed</allowedValue><allowedValue>IP_Bridged</allowedValue></allowedValueList></stateVariable><stateVariable sendEvents="yes"><name>ConnectionStatus</name><dataType>string</dataType><defaultValue>Unconfigured</defaultValue><allowedValueList><allowedValue>Unconfigured</allowedValue><allowedValue>Connecting</allowedValue><allowedValue>Authenticating</allowedValue><allowedValue>PendingDisconnect</allowedValue><allowedValue>Disconnecting</allowedValue><allowedValue>Disconnected</allowedValue><allowedValue>Connected</allowedValue></allowedValueList></stateVariable><stateVariable sendEvents="no"><name>Uptime</name><dataType>ui4</dataType><defaultValue>0</defaultValue><allowedValueRange><minimum>0</minimum><maximum/><step>1</step></allowedValueRange></stateVariable><stateVariable sendEvents="no"><name>RSIPAvailable</name><dataType>boolean</dataType><defaultValue>0</defaultValue></stateVariable><stateVariable sendEvents="no"><name>NATEnabled</name><dataType>boolean</dataType><defaultValue>1</defaultValue></stateVariable><stateVariable sendEvents="yes"><name>X_Name</name><dataType>string</dataType></stateVariable><stateVariable sendEvents="no"><name>LastConnectionError</name><dataType>string</dataType><defaultValue>ERROR_NONE</defaultValue><allowedValueList><allowedValue>ERROR_NONE</allowedValue><allowedValue>ERROR_ISP_TIME_OUT</allowedValue><allowedValue>ERROR_COMMAND_ABORTED</allowedValue><allowedValue>ERROR_NOT_ENABLED_FOR_INTERNET</allowedValue><allowedValue>ERROR_BAD_PHONE_NUMBER</allowedValue><allowedValue>ERROR_USER_DISCONNECT</allowedValue><allowedValue>ERROR_ISP_DISCONNECT</allowedValue><allowedValue>ERROR_IDLE_DISCONNECT</allowedValue><allowedValue>ERROR_FORCED_DISCONNECT</allowedValue><allowedValue>ERROR_SERVER_OUT_OF_RESOURCES</allowedValue><allowedValue>ERROR_RESTRICTED_LOGON_HOURS</allowedValue><allowedValue>ERROR_ACCOUNT_DISABLED</allowedValue><allowedValue>ERROR_ACCOUNT_EXPIRED</allowedValue><allowedValue>ERROR_PASSWORD_EXPIRED</allowedValue><allowedValue>ERROR_AUTHENTICATION_FAILURE</allowedValue><allowedValue>ERROR_NO_DIALTONE</allowedValue><allowedValue>ERROR_NO_CARRIER</allowedValue><allowedValue>ERROR_NO_ANSWER</allowedValue><allowedValue>ERROR_LINE_BUSY</allowedValue><allowedValue>ERROR_UNSUPPORTED_BITSPERSECOND</allowedValue><allowedValue>ERROR_TOO_MANY_LINE_ERRORS</allowedValue><allowedValue>ERROR_IP_CONFIGURATION</allowedValue><allowedValue>ERROR_UNKNOWN</allowedValue></allowedValueList></stateVariable><stateVariable sendEvents="yes"><name>ExternalIPAddress</name><dataType>string</dataType></stateVariable><stateVariable sendEvents="no"><name>RemoteHost</name><dataType>string</dataType></stateVariable><stateVariable sendEvents="no"><name>ExternalPort</name><dataType>ui2</dataType></stateVariable><stateVariable sendEvents="no"><name>InternalPort</name><dataType>ui2</dataType></stateVariable><stateVariable sendEvents="no"><name>PortMappingProtocol</name><dataType>string</dataType><allowedValueList><allowedValue>TCP</allowedValue><allowedValue>UDP</allowedValue></allowedValueList></stateVariable><stateVariable sendEvents="no"><name>InternalClient</name><dataType>string</dataType></stateVariable><stateVariable sendEvents="no"><name>PortMappingDescription</name><dataType>string</dataType></stateVariable><stateVariable sendEvents="no"><name>PortMappingEnabled</name><dataType>boolean</dataType></stateVariable><stateVariable sendEvents="no"><name>PortMappingLeaseDuration</name><dataType>ui4</dataType></stateVariable><stateVariable sendEvents="yes"><name>PortMappingNumberOfEntries</name><dataType>ui2</dataType></stateVariable></serviceStateTable></scpd>`

Im not sure what's root desc. URL but

`-u url : bypass discovery process by providing the XML root description url.`

**Comment by miniupnp** [comment]
this is not ROOT description of the UPNP IGD. This  is the XML description of one of the service.
-u option is meant for user knowing what they are doing. This is obviously not your case...

**Comment by miniupnp** [comment]
To understand UPNP device discovery, you should study 
http://upnp.org/specs/arch/UPnP-arch-DeviceArchitecture-v2.0.pdf (chapter 1)

**Comment by vido89** [comment]
I did tried miranda but discovery does not work

**Comment by miniupnp** [comment]
UPNP discovery relies on IP Multicast
I don't know your network setup, but I guess your machine 192.168.10.190 doesn't receive multicast packets from 192.168.1.254
I guess most UPnP IGD are neither designed nor tested to work on networks with "internal" routers

Please don't blame third party software for fault in your network setup design.

**Comment by vido89** [comment]
Yes thats correct but I did tried with second router zyxel, same setup and and it wirk just as it should but with this one zte just does not want to work, there is no rootxml i thought I can skip root and send request directly to xml file but it seams that does not work

**Comment by miniupnp** [comment]
you're not understanding how UPnP works.
there MUST be a root device.
The XML description of the root device contains URL of sub-devices and services.

To make it short, the discovery process of UPNP is about sharing UPNP Device root description URL.
miniupnpc allows to skip the discovery process provided you already know the URL...

**Comment by vido89** [comment]
Yes I know but there is no root xml M-SEARCH does not return anything, upnp is enabled I can access to 4 xml files and thats it

**Comment by miniupnp** [comment]
As I already said, I guess most UPnP device won't properly receive/send multicast packets across sub networks (I guess your have 192.168.1.0/24 and 192.168.10.0/24)
I won't bet on ZTE properly testing their routers 

As the UPnP DA state, the multicast TTL must be configurable and default to 2.
miniupnpc is compliant with the standard on this subject. I guess your ZTE router is not.
You may or may not have a better experience on the 192.168.1.0/24 LAN

**Comment by miniupnp** [comment]
TCP/IP stacks multicast TTL default is 1.
you need `setsockopt(sudp, IPPROTO_IP, IP_MULTICAST_TTL,` to change it.
I could bet ZTE developpers have not done it !
to be honest, miniupnpc/miniupnpd are compliant only since 2012 : https://github.com/miniupnp/miniupnp/commit/76da6770169053d6ad79b16d1b2a4481c3e49051
