### ISSUE TITLE
AddPortMapping requests with NewInternalClient set to empty string fail

### ISSUE THREAD

**Issue by streamholder** [miniupnp/miniupnp#236]
I recently installed a pfSense machine at my house, and I noticed some of my UPnP video-games stopped working correctly (for reference, it is Rainbow Six Siege v4.0).

I noticed that UPnP rules were not being correctly created for the game, and that I was getting these log lines:

> Failed to convert hostname '' to ip address

I fired up Wireshark, filtered with `http`, and I found out that when sending AddPortMapping requests, the game doesn't fill out the NewInternalClient field (that should be set, in this case, to my computer's local IP address).

I understand that this is a violation of the specification, and that as such "fixing the issue" could appear inadvisable, but it should be noticed that other commercial firewall products (at least TP-Link and Huawei, but probably pretty much every one of them, since the game works fine everywhere) automatically "correct" the problem assuming the requesting client's IP address as the NewInternalClient field.

I'm having this tested by a friend of mine on his network on another commercial UPnP implementation, I'll update the issue with his pcapng as soon as he gets back to me.
[My packet capture (miniupnp)](https://github.com/miniupnp/miniupnp/files/836030/cattura-riccardo.pcapng.zip)

**Comment by streamholder** [comment]
Further info: an eventual fix (possibly with a configuration or even build flag) should be inserted just before this line

https://github.com/miniupnp/miniupnp/blob/master/miniupnpd/upnpsoap.c#L413

checking whether `strlen(int_ip) == 0` (or `*int_ip == 0`), and in case that is true, changing the pointer to the client's IP address.

I would have at it myself but I haven't got the slightest clue on how to build software on FreeBSD (and have no other facility to set up this kind of thing).

**Comment by miniupnp** [comment]
> I would have at it myself but I haven't got the slightest clue on how to build software on FreeBSD (and have no other facility to set up this kind of thing).

just `make`

**Comment by streamholder** [comment]
Ok - as soon as I have some free time I'm gonna try to write a patch and submit it to the project.

**Comment by miniupnp** [comment]
@streamholder could you test my patch ?
```
$ git clone https://github.com/miniupnp/miniupnp.git
$ cd miniupnp/miniupnpd
$ make
```

**Comment by streamholder** [comment]
I currently have no access to the network where the problem presented (out of town). I will test it either on Friday or Saturday. Thank you for the patch.

**Comment by miniupnp** [comment]
@streamholder any news ?

**Comment by streamholder** [comment]
Yes, sorry. My gaming PC broke down so I haven't been able to test this just yet. I really don't know when I will have the change to do it.
