### ISSUE TITLE
windows UWP builds

### ISSUE THREAD

**Issue by belveder79** [miniupnp/miniupnp#238]
I was wondering if anyone tried to build the code with a more recent Visual Studio 2015 or higher for Universal Windows Platform (UWP). I tried to do that yesterday, but failed due to some stuff not being defined globally, mainly it is something like 

MIB_IPFORWARDROW

Any way to rewrite the code using something different?

**Comment by miniupnp** [comment]
miniupnpc is using the GetBestRoute() function https://msdn.microsoft.com/it-it/library/windows/desktop/aa365924.aspx

I don't know which UWP API could replace it.
You thould try to disable code (minissdpc.c from line 541 to 603)

**Comment by miniupnp** [comment]
UWP developpers may not be interested in using miniupnpc, I think everything needed to control UPnP devices is included in UWP API : https://docs.microsoft.com/fr-fr/windows/uwp/devices-sensors/enumerate-devices-over-a-network
