### ISSUE TITLE
genconfig.sh: freebsd: /etc/rc.conf.local

### ISSUE THREAD

**Issue by proller** [miniupnp/miniupnp#24]
freebsd using not only /etc/rc.conf for configuration.
full list available at /etc/defaults/rc.conf:
rc_conf_files="/etc/rc.conf /etc/rc.conf.local"

best way to get all params:
. /etc/defaults/rc.conf
(its include all other confs)

**Comment by miniupnp** [comment]
I have no FreeBSD machine. If someone can submit a patch that would help :)
