### ISSUE TITLE
PyPI is not up-to-date

### ISSUE THREAD

**Issue by fabaff** [miniupnp/miniupnp#241]
The latest available release on PyPI is [1.9](https://pypi.python.org/pypi/miniupnpc/1.9) while the repos claims it's [2.0](https://github.com/miniupnp/miniupnp/releases/tag/miniupnpd_2_0). Would be nice to be able to get 2.0 from PyPI as well.

Thanks in advance.

**Comment by miniupnp** [comment]
Well, please contact the maintainers of PyPI ...

**Comment by miniupnp** [comment]
@fabaff if I can be of any help to update the PyPI package, tell me what to do :)

**Comment by miniupnp** [comment]
@niamster  does your commits fix this issue ?

**Comment by niamster** [comment]
@miniupnp, not really. My commit makes possible to install the package directly from the GIT repository [bypassing pypi infrastructure].
@chenhouwu is the publisher and if he agrees to pass the package ownership, you should be able to update it

**Comment by miniupnp** [comment]
Well I don't understand much about all this... So just tell me if I need to do something to help :)

**Comment by niamster** [comment]
Let's wait a bit for the answer from @chenhouwu. If it doesn't respond I'll try to contact pypi [support](https://sourceforge.net/p/pypi/support-requests/) to change the ownership (apparently there's no other way).

**Comment by chenhouwu** [comment]
I can add more maintainers.
please give me your pypi username

**Comment by niamster** [comment]
Thanks @chenhouwu . I've just created a fresh account: `niamster`

**Comment by chenhouwu** [comment]
@niamster maintainer added to the role of the pkg

**Comment by niamster** [comment]
Thanks @chenhouwu 
@fabaff @miniupnp I'll push a release this weekend

**Comment by miniupnp** [comment]
@niamster is that ok?

**Comment by niamster** [comment]
@miniupnp sorry yes, the package is published (as v2.0.1 as I had to update setup.py).
