### ISSUE TITLE
cant portforward 

### ISSUE THREAD

**Issue by necony286** [miniupnp/miniupnp#242]
upnpc -a 192.168.1.110 20000 20000 TCP
upnpc : miniupnpc library test client. (c) 2005-2014 Thomas Bernard
Go to http://miniupnp.free.fr/ or http://miniupnp.tuxfamily.org/
for more information.
List of UPNP devices found on the network :
 desc: http://192.168.1.1:80/DeviceDescription.xml
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

Found valid IGD : http://192.168.1.1:80/UD/?9
Local LAN ip address : 192.168.1.110
ExternalIPAddress = 100.*myexternalip*
AddPortMapping(20000, 20000, 192.168.1.110) failed with code 718 (ConflictInMappingEntry)
GetSpecificPortMappingEntry() failed with code 714 (NoSuchEntryInArray)

tp link w8951nd (5.0.0 Build 140624 Rel.26732)
kali debian rolling

**Comment by necony286** [comment]
when i try to change the port 
upnpc -a 192.168.1.110 4286 4286 TCP
upnpc : miniupnpc library test client. (c) 2005-2014 Thomas Bernard
Go to http://miniupnp.free.fr/ or http://miniupnp.tuxfamily.org/
for more information.
List of UPNP devices found on the network :
 desc: http://192.168.1.1:80/DeviceDescription.xml
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

Found valid IGD : http://192.168.1.1:80/UD/?9
Local LAN ip address : 192.168.1.110
ExternalIPAddress = 100.96.12.181
InternalIP:Port = 192.168.1.110:4286
external 100.96.12.181:4286 TCP is redirected to internal 192.168.1.110:4286 (duration=0)
root@kali:~# nc -lvp 4286
listening on [any] 4286 ...
^C
root@kali:~#

**Comment by necony286** [comment]
its on briged virtualbox

**Comment by miniupnp** [comment]
where's the bug ?
port 20000 is not available, 4286 is...
