### ISSUE TITLE
No IGD UPnP Device found on the network !

### ISSUE THREAD

**Issue by jojodipa1** [miniupnp/miniupnp#248]
so any help pls !! 
upnpc -a 192.168.1.36 4444 4444 TCP
upnpc : miniupnpc library test client. (c) 2005-2014 Thomas Bernard
Go to http://miniupnp.free.fr/ or http://miniupnp.tuxfamily.org/
for more information.
No IGD UPnP Device found on the network !

**Comment by miniupnp** [comment]
It's impossible to help you without detailed informations.
And please test with the latest miniupnpc version

**Comment by trungtt1981** [comment]
Anyone knows why?

miniupnp/miniupnpc$ ./listdevices 
searching all UPnP devices
no device found.

**Comment by miniupnp** [comment]
either because there is indeed no UPNP device on the network,
or because SSDP packets (UDP port 1900, multicast) which are used for discovery are blocked somehow

**Comment by trungtt1981** [comment]
Thanks much for your response.
So, I have to follow this link to enable the daemon, right?

https://github.com/miniupnp/miniupnp/blob/master/miniupnpd/INSTALL

**Comment by trungtt1981** [comment]
sudo /etc/init.d/miniupnpd start
[....] Starting miniupnpd (via systemctl): miniupnpd.serviceFailed to start miniupnpd.service: Unit miniupnpd.service not found.
 failed!

**Comment by brandonros** [comment]
Obviously this has nothing to do with this software but I'm just posting this out of frustration.

![image](https://user-images.githubusercontent.com/8949910/142777734-128abbc1-6cae-4944-94d4-e3b98e25e0e0.png)

My ARRIS TG9452 model router clearly says it has UPnP enabled.

```
 $ upnpc -l
upnpc : miniupnpc library test client, version 2.2.3.
 (c) 2005-2021 Thomas Bernard.
Go to http://miniupnp.free.fr/ or https://miniupnp.tuxfamily.org/
for more information.
No IGD UPnP Device found on the network !
```

**Comment by pali** [comment]
Have you configured firewall correctly?

**Comment by pmorch** [comment]
For me the problem was a local firewall (on the machine running miniupnp). After I open TCP port 2189, I could see the UPNP device.
