### ISSUE TITLE
MiniUPnP 2.0.1 Python build breaks on non-x86_64 platforms

### ISSUE THREAD

**Issue by ivilata** [miniupnp/miniupnp#252]
I tried to build <https://pypi.org/project/miniupnpc/2.0.1/> with ``pip install miniupnpc`` on a Debian i386 host, and I got a bunch of errors like the following ones:

    /usr/bin/ld: i386:x86-64 architecture of input file `libminiupnpc.a(miniupnpc.o)' is incompatible with i386 output

    /usr/bin/ld: libminiupnpc.a(upnperrors.o): file class ELFCLASS64 incompatible with ELFCLASS32

The problem is that the latest 2.0.1 version (which is oddly only in PyPi but not here in GitHub) includes a ``libminiupnpc.a`` library with objects already built for 64-bit Linux.  This breaks compilation on every other platform (i386, ARM…), which looks like a pretty severe issue to me.

Thanks for having a look at the issue and for the really useful project!

**Comment by miniupnp** [comment]
ping @niamster

**Comment by niamster** [comment]
A new version of the package is published (v2.0.2)

**Comment by miniupnp** [comment]
@ivilata  reopen if v2.0.2 does not fix the issue
