### ISSUE TITLE
UPnP device has been found but was not recognized as an IGD

### ISSUE THREAD

**Issue by xgibbousx** [miniupnp/miniupnp#253]
Hello,

I am running UPNP_GetValidIGD() and getting back "3 = an UPnP device has been found but was not recognized as an IGD".  UPnP is enabled on my router, is being detected, but apparently was not recognized as an IGD.

My questions are as follows:

1. Why would UPnP be detected but not recognized as an IGD?
2. What would be some potential troubleshooting steps to take here?
3. Could this be caused by bad parameters being passed into UPNP_GetValidIGD()?

Please let me know what other information I could provide to help debug the situation.

Thank you very much!

**Comment by miniupnp** [comment]
please provide logs... What is your router ? Brand / model / UPnP device root description.

**Comment by xgibbousx** [comment]
From upnpDiscover():
-----------------------

**devlist:**

1. descURL: http://192.168.1.1:1990/40442a83-6024-4be9-9786-576867e60e64/WFADevice.xml
2. st: upnp:rootdevice
3. buffer: ht...

From UPNP_GetValidIGD():
------------------------------

**urls:**

+ controlURL: http://192.168.1.1:1990/
+ ipcondescURL: http://192.168.1.1:1990/
+ controlURL_CIF: http://192.168.1.1:1990/
+ controlURL_6FC: http://192.168.1.1:1990/
+ rootdescURL: http://192.168.1.1:1990/40442a83-6024-4be9-9786-576867e60e64/WFADevice.xml

**data:**
+ presentationurl: ""
+ cureltname: "eventSubURL"
+ urlbase: ""
+ presentationurl: ""
+ level: 0

CIF
+ controlurl: ""
+ eventsuburl: ""
+ scpdurl: ""
+ servicetype:	""

first
+ controlurl: ""
+ eventsuburl: ""
+ scpdurl ""
+servicetype ""

second
+ controlurl: ""
+ eventsuburl:	""
+ scpdurl: ""
+ servicetype: ""

IPv6FC
+ controlurl: ""
+ eventsuburl:	""
+ scpdurl: ""
+ servicetype: ""

tmp
+ controlurl: "control?WFAWLANConfig"
+ eventsuburl:	 "event?WFAWLANConfig"
+ scpdurl: "x_wfawlanconfig.xml"
+ servicetype: "urn:schemas-wifialliance-org:service:WFAWLANConfig:1"

lanaddr: "192.168.1.100"

------------------------------------

**Root Description**

`<root xmlns="urn:schemas-upnp-org:device-1-0">
<specVersion>
<major>1</major>
<minor>0</minor>
</specVersion>
<device>
<deviceType>urn:schemas-wifialliance-org:device:WFADevice:1</deviceType>
<friendlyName>WFADevice</friendlyName>
<manufacturer>Broadcom Corporation</manufacturer>
<manufacturerURL>http://www.broadcom.com</manufacturerURL>
<modelDescription>Wireless Device</modelDescription>
<modelName>WPS</modelName>
<modelNumber>X1</modelNumber>
<serialNumber>0000001</serialNumber>
<UDN>uuid:2dcb3162-71d8-e4ba-f444-543b64d35d54</UDN>
<serviceList>
<service>
<serviceType>
urn:schemas-wifialliance-org:service:WFAWLANConfig:1
</serviceType>
<serviceId>urn:wifialliance-org:serviceId:WFAWLANConfig1</serviceId>
<SCPDURL>x_wfawlanconfig.xml</SCPDURL>
<controlURL>control?WFAWLANConfig</controlURL>
<eventSubURL>event?WFAWLANConfig</eventSubURL>
</service>
</serviceList>
</device>
</root>`

-------------------------------

**Brand/Model**

Linksys EA9500

**Comment by miniupnp** [comment]
<deviceType>urn:schemas-wifialliance-org:device:WFADevice:1</deviceType> : 
a WFA device is not an IGD, so indeed the return code 3 is correct.

Make sure you have an IGD answering to M-SEARCH requests

**Comment by xgibbousx** [comment]
Thank you.

Does this mean that miniupnp doesn't work with my router?

**Comment by xgibbousx** [comment]
Hi,

Any update on the above questions?

The answers to them will help me greatly.

Thank you again!

**Comment by miniupnp** [comment]
1) miniupnpc only works with UPnP IGD.
2) I believe your router is supposed to support the UPnP IGD spec.
Please test with http://www.majorgeeks.com/files/details/universal_plug_and_play_tester_(upnptest).html
