### ISSUE TITLE
PCP : Server epoch not reset after address change

### ISSUE THREAD

**Issue by zrm** [miniupnp/miniupnp#254]
When the external IP address of the device changes, miniupnpd continues to use the old address in responses to NAT-PMP EXTERNAL_IP, PCP MAP, etc.

It seems that the address change is detected, because it causes multicast EXTERNAL_IP messages to be transmitted (with the old address), but the address is not updated and the defunct address continues to be used.

Also, the multicast announcements should be sent on startup (or on startup after a few seconds delay to give the network time to come up) for the same reason they are on address changes, but aren't.

Tested with PCP and NAT-PMP on Linux (using the miniupnpd packaged with Debian).

**Comment by miniupnp** [comment]
please test with the latest sources from github before reporting a bug.
Debian is notorious for using old versions

**Comment by zrm** [comment]
Fair enough. Behavior is better in the current version. The address is updated but the epoch time is not reset.

RFC6887 Section 8.5: "Similarly, if the external IP address(es) of the NAT (controlled by the PCP server) changes, the Epoch time MUST be reset."

Also same issue regarding multicast announcements not being sent at startup.

**Comment by miniupnp** [comment]
so there are 2 issues with PCP implementation : 
1) Server epoch not reset after address change
2) PCP announcements not being sent at startup

**Comment by miniupnp** [comment]
@zrm now epoch is reset, but you need to kill -USR1 for miniupnpd to detect the change...

**Comment by zrm** [comment]
Is it not straight forward to have the code that resets the epoch just call the code that handles SIGUSR1?

Or even just have it do "kill(getpid(), SIGUSR1)"?

**Comment by miniupnp** [comment]
I think you don't get it.
Address change is not detected. So if your network interface address change you should `kill -USR1 $(cat /var/run/miniupnpd.pid)`
The code that handles SIGUSR1 will reset the epoch

**Comment by zrm** [comment]
Oh sorry, I meant to run the SIGUSR1 code from the code that detects the address change, not the code that resets the epoch (which is what we want to run it for).

> Address change is not detected.

It does seem to be detected in the newer versions. When the address changes it actually sends multicast NAT-PMP EXTERNAL_IP messages containing the new address (and the old epoch).

**Comment by miniupnp** [comment]
you are right, the detection is done in ifacewatcher.c : 
https://github.com/miniupnp/miniupnp/blob/master/miniupnpd/linux/ifacewatcher.c#L338

**Comment by miniupnp** [comment]
natpmp.c should be fixed as well : 
https://github.com/miniupnp/miniupnp/blob/master/miniupnpd/natpmp.c#L433

**Comment by miniupnp** [comment]
the startup announcement are still missing
