### ISSUE TITLE
add reconnect option to get new ip

### ISSUE THREAD

**Issue by treaki** [miniupnp/miniupnp#255]
Hi,

some programs, like jdownloader [01], are able to issue a reconnect through upnp router control. Could you add an option to issue this command using your upnpc command line tool. It would be really useful if i didn't had to login to my fritzbox [02] or start jdownloader or even stand up and walk to the box to issue a reconnect....

thanks a lot in advance

annotations:

01: http://jdownloader.org/
02: https://avm.de/produkte/fritzbox/ or https://en.avm.de/products/fritzbox/ in english

**Comment by miniupnp** [comment]
I don't understand which "reconnect" upnp command you're refering to.
