### ISSUE TITLE
NAT reflection/loopback/hairpinning

### ISSUE THREAD

**Issue by Elinvention** [miniupnp/miniupnp#257]
Please, add support for NAT reflection/loopback/hairpinning.

**Comment by miniupnp** [comment]
what do you mean ?

**Comment by Elinvention** [comment]
I mean this: https://forum.lede-project.org/t/upnp-nat-reflection/6491

**Comment by miniupnp** [comment]
I'm not sure it has something to do with UPNP. Just configure your router so that the "external IP" and the NAT can be reached from the LAN.

**Comment by bbogey** [comment]
I would need this as well. I can access WAN ip from LAN, but not the ones what are port forwarded. What kind of rule I should add so I can access WAN ports from LAN, also the port forwarded ones?
 
Here example of working rule including hairpin(reflection) I can connect from LAN via WAN IP.
But how to get this working with upnp?

`    0     0 SNAT       tcp  --  *      *       192.168.1.0/24       192.168.1.33         tcp dpt:25525 /* !fw3: minecraft (reflection) */ to:192.168.1.1
    0     0 SNAT       udp  --  *      *       192.168.1.0/24       192.168.1.33         udp dpt:25525 /* !fw3: minecraft (reflection) */ to:192.168.1.1
    0     0 DNAT       tcp  --  *      *       192.168.1.0/24       91.xx.xx.xx        tcp dpt:25525 /* !fw3: minecraft (reflection) */ to:192.168.1.33:25525
    0     0 DNAT       udp  --  *      *       192.168.1.0/24       91.xx.xx.xx        udp dpt:25525 /* !fw3: minecraft (reflection) */ to:192.168.1.33:25525
    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:25525 /* !fw3: minecraft */ to:192.168.1.33:25525
    0     0 DNAT       udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:25525 /* !fw3: minecraft */ to:192.168.1.33:25525`

**Comment by MrStonedOne** [comment]
@miniupnp this requires extra rules per-portfoward, which is why it has to be supported on miniupnp.
