### ISSUE TITLE
[miniupnpd] sendto(udp_notify=6, 192.168.1.1): Invalid argument

### ISSUE THREAD

**Issue by enihcam** [miniupnp/miniupnp#260]
> Sep 26 23:37:05 miniupnpd[360]: sendto(udp_notify=6, 192.168.1.1): Invalid argument
Sep 26 23:37:05 miniupnpd[360]: sendto(udp_notify=6, 192.168.1.1): Invalid argument
Sep 26 23:37:05 miniupnpd[360]: sendto(udp_notify=6, 192.168.1.1): Invalid argument
Sep 26 23:37:05 miniupnpd[360]: sendto(udp_notify=6, 192.168.1.1): Invalid argument
Sep 26 23:37:05 miniupnpd[360]: sendto(udp_notify=6, 192.168.1.1): Invalid argument
Sep 26 23:37:05 miniupnpd[360]: sendto(udp_notify=6, 192.168.1.1): Invalid argument
Sep 26 23:37:05 miniupnpd[360]: sendto(udp_notify=6, 192.168.1.1): Invalid argument
Sep 26 23:37:05 miniupnpd[360]: sendto(udp_notify=6, 192.168.1.1): Invalid argument
Sep 26 23:37:05 miniupnpd[360]: sendto(udp_notify=6, 192.168.1.1): Invalid argument
Sep 26 23:37:05 miniupnpd[360]: sendto(udp_notify=6, 192.168.1.1): Invalid argument
Sep 26 23:37:05 miniupnpd[360]: sendto(udp_notify=6, 192.168.1.1): Invalid argument
Sep 26 23:37:06 miniupnpd[360]: try_sendto(sock=6, len=460, dest=239.255.255.250:1900): sendto: Invalid argument
Sep 26 23:37:06 miniupnpd[360]: try_sendto(sock=6, len=460, dest=239.255.255.250:1900): sendto: Invalid argument
Sep 26 23:37:06 miniupnpd[360]: try_sendto(sock=6, len=476, dest=239.255.255.250:1900): sendto: Invalid argument
Sep 26 23:37:06 miniupnpd[360]: try_sendto(sock=6, len=458, dest=239.255.255.250:1900): sendto: Invalid argument
Sep 26 23:37:06 miniupnpd[360]: try_sendto(sock=6, len=405, dest=239.255.255.250:1900): sendto: Invalid argument
Sep 26 23:37:06 miniupnpd[360]: try_sendto(sock=6, len=444, dest=239.255.255.250:1900): sendto: Invalid argument
Sep 26 23:37:06 miniupnpd[360]: try_sendto(sock=6, len=405, dest=239.255.255.250:1900): sendto: Invalid argument
Sep 26 23:37:06 miniupnpd[360]: try_sendto(sock=6, len=464, dest=239.255.255.250:1900): sendto: Invalid argument
Sep 26 23:37:06 miniupnpd[360]: try_sendto(sock=6, len=405, dest=239.255.255.250:1900): sendto: Invalid argument
Sep 26 23:37:06 miniupnpd[360]: try_sendto(sock=6, len=468, dest=239.255.255.250:1900): sendto: Invalid argument
Sep 26 23:37:06 miniupnpd[360]: try_sendto(sock=6, len=396, dest=239.255.255.250:1900): sendto: Invalid argument
Sep 26 23:37:06 miniupnpd[360]: try_sendto failed to send 11 packets

**Comment by miniupnp** [comment]
It is difficult to help you without any context

**Comment by enihcam** [comment]
@miniupnp When I upgraded miniupnpd to 2.0.20170421, the issue occurred.
Kernel version is 4.13.7
Glibc version is 2.26

Let me know what else do you need. Thanks!

**Comment by miniupnp** [comment]
OS, configuration, network interfaces...

**Comment by enihcam** [comment]
@miniupnp 

Archlinux

`
/etc/systemd/network $ cat *.*
[NetDev]
Name=br0
Kind=bridge
[Match]
Driver=r8152

[Link]
NamePolicy=kernel database onboard slot path
MACAddressPolicy=random
GenericReceiveOffload=true
GenericSegmentationOffload=true
LargeReceiveOffload=true
TCPSegmentationOffload=true
UDPSegmentationOffload=true
WakeOnLan=off
[Match]
Driver=igb

[Link]
NamePolicy=kernel database onboard slot path
MACAddressPolicy=random
GenericReceiveOffload=true
GenericSegmentationOffload=true
LargeReceiveOffload=true
TCPSegmentationOffload=true
UDPSegmentationOffload=true
WakeOnLan=off
[Match]
Driver=igb

[Network]
Bridge=br0
DHCP=no
IPv6AcceptRA=no
LinkLocalAddressing=no
LLDP=false
LLMNR=false
[Match]
Name=br0

[Network]
Address=192.168.1.1/24
DHCP=no
IPForward=ipv4
IPv6AcceptRA=no
LinkLocalAddressing=no
LLDP=false
LLMNR=resolve
MulticastDNS=resolve
`

`
/etc/miniupnpd $ cat miniupnpd.conf
# WAN network interface
ext_ifname=ppp0
# If the WAN interface has several IP addresses, you
# can specify the one to use below
#ext_ip=

# LAN network interfaces IPs / networks
# There can be multiple listening IPs for SSDP traffic, in that case
# use multiple 'listening_ip=...' lines, one for each network interface.
# It can be IP address or network interface name (ie. "eth0")
# It is mandatory to use the network interface name in order to enable IPv6
# HTTP is available on all interfaces.
# When MULTIPLE_EXTERNAL_IP is enabled, the external IP
# address associated with the subnet follows. For example:
#  listening_ip=192.168.0.1/24 88.22.44.13
listening_ip=br0
# CAUTION: mixing up WAN and LAN interfaces may introduce security risks!
# Be sure to assign the correct interfaces to LAN and WAN and consider
# implementing UPnP permission rules at the bottom of this configuration file

# Port for HTTP (descriptions and SOAP) traffic. Set to 0 for autoselect.
#http_port=0
# Port for HTTPS. Set to 0 for autoselect (default)
#https_port=0

# Path to the UNIX socket used to communicate with MiniSSDPd
# If running, MiniSSDPd will manage M-SEARCH answering.
# default is /var/run/minissdpd.sock
#minissdpdsocket=/var/run/minissdpd.sock

# Enable NAT-PMP support (default is no)
#enable_natpmp=yes

# Enable UPNP support (default is yes)
#enable_upnp=no

# PCP
# Configure the minimum and maximum lifetime of a port mapping in seconds
# 120s and 86400s (24h) are suggested values from PCP-base
#min_lifetime=120
#max_lifetime=86400

# Chain names for netfilter (not used for pf or ipf).
# default is MINIUPNPD for both
#upnp_forward_chain=forwardUPnP
#upnp_nat_chain=UPnP
#upnp_nat_postrouting_chain=UPnP-Postrouting

# Lease file location
#lease_file=/var/log/upnp.leases

# To enable the next few runtime options, see compile time
# ENABLE_MANUFACTURER_INFO_CONFIGURATION (config.h)

# Name of this service, default is "`uname -s` router"
#friendly_name=MiniUPnPd router

# Manufacturer name, default is "`uname -s`"
#manufacturer_name=Manufacturer corp

# Manufacturer URL, default is URL of OS vendor
#manufacturer_url=http://miniupnp.free.fr/

# Model name, default is "`uname -s` router"
#model_name=Router Model

# Model description, default is "`uname -s` router"
#model_description=Very Secure Router - Model

# Model URL, default is URL of OS vendor
#model_url=http://miniupnp.free.fr/

# Bitrates reported by daemon in bits per second
# by default miniupnpd tries to get WAN interface speed
#bitrate_up=1000000
#bitrate_down=10000000

# Secure Mode, UPnP clients can only add mappings to their own IP
#secure_mode=yes

# Default presentation URL is HTTP address on port 80
# If set to an empty string, no presentationURL element will appear
# in the XML description of the device, which prevents MS Windows
# from displaying an icon in the "Network Connections" panel.
#presentation_url=http://www.mylan/index.php

# Report system uptime instead of daemon uptime
#system_uptime=yes

# Notify interval in seconds. default is 30 seconds.
#notify_interval=240

# Unused rules cleaning.
# never remove any rule before this threshold for the number
# of redirections is exceeded. default to 20
#clean_ruleset_threshold=10
# Clean process work interval in seconds. default to 0 (disabled).
# a 600 seconds (10 minutes) interval makes sense
clean_ruleset_interval=600

# Log packets in pf (default is no)
#packet_log=no

# Anchor name in pf (default is miniupnpd)
#anchor=miniupnpd

# ALTQ queue in pf
# Filter rules must be used for this to be used.
# compile with PF_ENABLE_FILTER_RULES (see config.h file)
#queue=queue_name1

# Tag name in pf
#tag=tag_name1

# Make filter rules in pf quick or not. default is yes
# active when compiled with PF_ENABLE_FILTER_RULES (see config.h file)
#quickrules=no

# UUID, generate your own UUID with "uuidgen"
uuid=a522276e-0085-4757-b5e8-481526196a39

# Daemon's serial and model number when reporting to clients
# (in XML description)
#serial=12345678
#model_number=1

# UPnP permission rules
# (allow|deny) (external port range) IP/mask (internal port range)
# A port range is <min port>-<max port> or <port> if there is only
# one port in the range.
# IP/mask format must be nnn.nnn.nnn.nnn/nn
# It is advised to only allow redirection of port >= 1024
# and end the rule set with "deny 0-65535 0.0.0.0/0 0-65535"
# The following default ruleset allows specific LAN side IP addresses
# to request only ephemeral ports. It is recommended that users
# modify the IP ranges to match their own internal networks, and
# also consider implementing network-specific restrictions
# CAUTION: failure to enforce any rules may permit insecure requests to be made!
allow 1024-65535 192.168.1.0/24 1024-65535
deny 0-65535 0.0.0.0/0 0-65535
`

**Comment by miniupnp** [comment]
It is difficult to read. But you are using a bridged interface. Does it support IPV4 multicast ?

**Comment by miniupnp** [comment]
you said 
>  I upgraded miniupnpd to 2.0.20170421 
With what version was it working ?

**Comment by enihcam** [comment]
@miniupnp i followed the syntax, but sorry i didn't know why it did not work. yes, i'm using br0 and yes IPV4 multicast is enabled.

`
~ $ netstat -g
IPv6/IPv4 Group Memberships
Interface       RefCnt Group
--------------- ------ ---------------------
lo              1      all-systems.mcast.net
enp1s0          1      all-systems.mcast.net
enp0s20u1       1      all-systems.mcast.net
enp2s0          1      all-systems.mcast.net
enp3s0          1      all-systems.mcast.net
br0             1      224.0.0.251
br0             1      239.255.255.250
br0             1      all-systems.mcast.net
ppp0            1      all-systems.mcast.net
lo              1      ff02::1
lo              1      ff01::1
enp1s0          1      ff02::1
enp1s0          1      ff01::1
enp0s20u1       1      ff02::1
enp0s20u1       1      ff01::1
enp2s0          1      ff02::1
enp2s0          1      ff01::1
enp3s0          1      ff02::1
enp3s0          1      ff01::1
br0             1      ff02::1
br0             1      ff01::1
ppp0            1      ff02::1
ppp0            1      ff01::1

~ $ ip maddr show
1:      lo
        inet  224.0.0.1
        inet6 ff02::1
        inet6 ff01::1
2:      enp1s0
        link  33:33:00:00:00:01
        link  01:00:5e:00:00:01
        inet  224.0.0.1
        inet6 ff02::1
        inet6 ff01::1
3:      enp0s20u1
        link  33:33:00:00:00:01
        link  01:00:5e:00:00:01
        inet  224.0.0.1
        inet6 ff02::1
        inet6 ff01::1
4:      enp2s0
        link  33:33:00:00:00:01
        link  01:00:5e:00:00:01
        inet  224.0.0.1
        inet6 ff02::1
        inet6 ff01::1
5:      enp3s0
        link  33:33:00:00:00:01
        link  01:00:5e:00:00:01
        inet  224.0.0.1
        inet6 ff02::1
        inet6 ff01::1
6:      br0
        link  33:33:00:00:00:01
        link  01:00:5e:00:00:01
        link  01:00:5e:7f:ff:fa
        link  01:00:5e:00:00:fb
        inet  224.0.0.251
        inet  239.255.255.250
        inet  224.0.0.1
        inet6 ff02::1
        inet6 ff01::1
7:      ppp0
        inet  224.0.0.1
        inet6 ff02::1
        inet6 ff01::1
`

The previous version without any issues is 2.0.20161216

**Comment by enihcam** [comment]
I also found these:

`
Oct 24 08:12:53 localhost miniupnpd[360]: SSDP packet sender 192.168.1.128:61167 not from a LAN, ignoring
Oct 24 08:12:54 localhost miniupnpd[360]: SSDP packet sender 192.168.1.128:61167 not from a LAN, ignoring
Oct 24 08:12:54 localhost miniupnpd[360]: SSDP packet sender 192.168.1.128:61167 not from a LAN, ignoring
Oct 24 08:12:54 localhost miniupnpd[360]: SSDP packet sender 192.168.1.128:61167 not from a LAN, ignoring
Oct 24 08:12:54 localhost miniupnpd[360]: SSDP packet sender 192.168.1.128:61167 not from a LAN, ignoring
Oct 24 08:12:54 localhost miniupnpd[360]: SSDP packet sender 192.168.1.128:61167 not from a LAN, ignoring
Oct 24 08:12:55 localhost miniupnpd[360]: SSDP packet sender 192.168.1.128:55859 not from a LAN, ignoring
Oct 24 08:12:55 localhost miniupnpd[360]: SSDP packet sender 192.168.1.128:55859 not from a LAN, ignoring
Oct 24 08:12:55 localhost miniupnpd[360]: SSDP packet sender 192.168.1.128:55859 not from a LAN, ignoring
Oct 24 08:12:56 localhost miniupnpd[360]: SSDP packet sender 192.168.1.128:55859 not from a LAN, ignoring
Oct 24 08:12:58 localhost miniupnpd[360]: SSDP packet sender 192.168.1.128:55859 not from a LAN, ignoring
Oct 24 08:12:58 localhost miniupnpd[360]: SSDP packet sender 192.168.1.128:55859 not from a LAN, ignoring
Oct 24 08:12:59 localhost miniupnpd[360]: SSDP packet sender 192.168.1.128:55859 not from a LAN, ignoring
Oct 24 08:13:00 localhost miniupnpd[360]: SSDP packet sender 192.168.1.128:55859 not from a LAN, ignoring
Oct 24 08:13:00 localhost miniupnpd[360]: SSDP packet sender 192.168.1.128:55859 not from a LAN, ignoring
Oct 24 08:13:00 localhost miniupnpd[360]: SSDP packet sender 192.168.1.128:55859 not from a LAN, ignoring
Oct 24 08:13:00 localhost miniupnpd[360]: SSDP packet sender 192.168.1.128:55859 not from a LAN, ignoring
Oct 24 08:13:00 localhost miniupnpd[360]: SSDP packet sender 192.168.1.128:55859 not from a LAN, ignoring
Oct 24 08:13:00 localhost miniupnpd[360]: SSDP packet sender 192.168.1.128:55859 not from a LAN, ignoring
Oct 24 08:13:01 localhost miniupnpd[360]: SSDP packet sender 192.168.1.128:55859 not from a LAN, ignoring
Oct 24 08:13:01 localhost miniupnpd[360]: SSDP packet sender 192.168.1.128:55859 not from a LAN, ignoring
Oct 24 08:13:02 localhost miniupnpd[360]: SSDP packet sender 192.168.1.128:55859 not from a LAN, ignoring
Oct 24 08:13:03 localhost miniupnpd[360]: SSDP packet sender 192.168.1.128:55859 not from a LAN, ignoring
Oct 24 08:13:03 localhost miniupnpd[360]: SSDP packet sender 192.168.1.128:55859 not from a LAN, ignoring
Oct 24 08:13:03 localhost miniupnpd[360]: SSDP packet sender 192.168.1.128:55859 not from a LAN, ignoring
Oct 24 08:13:03 localhost miniupnpd[360]: SSDP packet sender 192.168.1.128:55859 not from a LAN, ignoring
Oct 24 08:13:03 localhost miniupnpd[360]: SSDP packet sender 192.168.1.128:55859 not from a LAN, ignoring
Oct 24 08:13:03 localhost miniupnpd[360]: SSDP packet sender 192.168.1.128:55859 not from a LAN, ignoring
Oct 24 08:13:04 localhost miniupnpd[360]: SSDP packet sender 192.168.1.128:55859 not from a LAN, ignoring
`

**Comment by miniupnp** [comment]
your comments are nearly impossible to read...
If you know a version that's working for you and a version that's not, you can use "git bisect" to find exactly which commit is responsible.

Also if I understand well ppp0 is the "external" network interface (connected to internet), br0 is the "internal" one (connected to lan)
What is (are) the IPv4 address(es) of br0 ?

**Comment by enihcam** [comment]
Sorry. Here is my IP info:

> $ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 4000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: enp1s0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq master br0 state DOWN group default qlen 4000
    link/ether 16:bd:fc:41:a6:56 brd ff:ff:ff:ff:ff:ff
3: enp0s20u1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 4000
    link/ether d6:a0:21:53:19:71 brd ff:ff:ff:ff:ff:ff
4: enp2s0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq master br0 state DOWN group default qlen 4000
    link/ether d6:d6:3e:64:cc:4a brd ff:ff:ff:ff:ff:ff
5: enp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq master br0 state UP group default qlen 4000
    link/ether 1e:39:a0:a5:a8:ab brd ff:ff:ff:ff:ff:ff
6: br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 4000
    link/ether 02:94:e6:bb:5e:2b brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.1/24 brd 192.168.1.255 scope global br0
       valid_lft forever preferred_lft forever
7: ppp0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1492 qdisc fq_codel state UNKNOWN group default qlen 4000
    link/ppp
    inet 104.83.114.53 peer 101.87.232.1/32 scope global ppp0
       valid_lft forever preferred_lft forever

**Comment by miniupnp** [comment]
well the ip of br0 is 192.168.1.1 so 192.168.1.128 is from a LAN, but I'm not able to check your configuration as your comment is unreadable

**Comment by miniupnp** [comment]
please check what are the messages when launched with -d option : 
`# ./miniupnpd -d`

**Comment by miniupnp** [comment]
I'm closing now.
You can reopen if you have more precise information. Like if you cant tell which commit introduced the regression

**Comment by enihcam** [comment]
@miniupnp I found the repo steps:
1. Start miniupnpd service in a box with ppp0 and br0 (In my case: there is an external AP is behind br0)
2. Add a port via UPnP
3. Remove br0 (In my case: plug off the AP)
4. Error message flood

Expected:
No message flood.

**Comment by miniupnp** [comment]
I'm sorry, miniupnpd doesn't support LAN interfaces being removed (or not present at startup)
You should kill miniupnpd when br0 is removed, and restart it whe, br0 is up again.
