### ISSUE TITLE
why no igd upnp device found on the network

### ISSUE THREAD

**Issue by ikelirawan** [miniupnp/miniupnp#262]
ro ot@kali:~# upnpc -a ..:..: 4444 4444 tcp
upnpc : miniupnpc library test client. (c) 2005-2014 Thomas Bernard
Go to http://miniupnp.free.fr/ or http://miniupnp.tuxfamily.org/
for more information.
No IGD UPnP Device found on the network !

somebody help me

**Comment by miniupnp** [comment]
We can't help you. There is probably no UPnP IGD on your network.
