### ISSUE TITLE
how to properly use upnpDiscover

### ISSUE THREAD

**Issue by Memnarch** [miniupnp/miniupnp#265]
Hi,
I just tried using upnpDiscover, but apparently i used it wrong(or something else is going on). In my case, i veryfied, that i can find my router by using the type 

` "urn:schemas-upnp-org:device:InternetGatewayDevice:1"`

 on the windows API IUPnPDeviceFinder. But since i need a solution which is more flexible in terms of the underlying platform, i ended up here. I called it like this:
`upnpDiscover(10000, nullptr, nullptr, UPNP_LOCAL_PORT_SAME, 0, 2, &error);`
Error was 0, and resultlist was empty. This is the output Miniupnpc printed on my commandline:

> ifIndex=11 nextHop=100a8c0
>         Num Entries: 2
> 
>         Interface Index[0]:     11
>         IP Address[0]:          192.168.0.11
>         Subnet Mask[0]:         255.255.255.0
>         BroadCast[0]:           1.0.0.0 (1)
>         Reassembly size[0]:     65535
>         Type and State[0]:
> 
>         Interface Index[1]:     1
>         IP Address[1]:          127.0.0.1
>         Subnet Mask[1]:         255.0.0.0
>         BroadCast[1]:           1.0.0.0 (1)
>         Reassembly size[1]:     65535
>         Type and State[1]:
> Sending M-SEARCH request to 239.255.255.250 with ST: urn:schemas-upnp-org:device:InternetGatewayDevice:1
> NODATA or TIMEOUT
> Sending M-SEARCH request to 239.255.255.250 with ST: urn:schemas-upnp-org:service:WANIPConnection:1
> NODATA or TIMEOUT
> Sending M-SEARCH request to 239.255.255.250 with ST: urn:schemas-upnp-org:service:WANPPPConnection:1
> NODATA or TIMEOUT
> Sending M-SEARCH request to 239.255.255.250 with ST: upnp:rootdevice
> NODATA or TIMEOUT
> 

SO what do i have to look for to get it working properly?

**Comment by miniupnp** [comment]
what is the output of the listdevices executable ?

**Comment by Memnarch** [comment]
Okay that is strange. On one call, i got this:
```
searching all UPnP devices
ifIndex=11 nextHop=100a8c0
        Num Entries: 2

        Interface Index[0]:     11
        IP Address[0]:          192.168.0.11
        Subnet Mask[0]:         255.255.255.0
        BroadCast[0]:           1.0.0.0 (1)
        Reassembly size[0]:     65535
        Type and State[0]:

        Interface Index[1]:     1
        IP Address[1]:          127.0.0.1
        Subnet Mask[1]:         255.0.0.0
        BroadCast[1]:           1.0.0.0 (1)
        Reassembly size[1]:     65535
        Type and State[1]:
Sending M-SEARCH request to 239.255.255.250 with ST: ssdp:all
M-SEARCH Reply:
  ST: upnp:rootdevice
  USN: uuid:caf7bb0f-4944-3e02-a1d6-0655dac3e012::upnp:rootdevice
  Location: http://192.168.0.1:33443/rootDesc.xml
M-SEARCH Reply:
  ST: urn:schemas-upnp-org:device:InternetGatewayDevice:1
  USN: uuid:caf7bb0f-4944-3e02-a1d6-0655dac3e012::urn:schemas-upnp-org:device:InternetGatewayDevice:1
  Location: http://192.168.0.1:33443/rootDesc.xml
M-SEARCH Reply:
  ST: urn:schemas-upnp-org:device:WANConnectionDevice:1
  USN: uuid:492f6828-5b92-396e-a151-7a8e5ef39857::urn:schemas-upnp-org:device:WANConnectionDevice:1
  Location: http://192.168.0.1:33443/rootDesc.xml
M-SEARCH Reply:
  ST: urn:schemas-upnp-org:device:WANDevice:1
  USN: uuid:221c3b78-8e10-395c-bbd3-e3c1f8b670af::urn:schemas-upnp-org:device:WANDevice:1
  Location: http://192.168.0.1:33443/rootDesc.xml
M-SEARCH Reply:
  ST: urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1
  USN: uuid:221c3b78-8e10-395c-bbd3-e3c1f8b670af::urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1
  Location: http://192.168.0.1:33443/rootDesc.xml
M-SEARCH Reply:
  ST: urn:schemas-upnp-org:service:WANIPConnection:1
  USN: uuid:492f6828-5b92-396e-a151-7a8e5ef39857::urn:schemas-upnp-org:service:WANIPConnection:1
  Location: http://192.168.0.1:33443/rootDesc.xml
M-SEARCH Reply:
  ST: urn:schemas-upnp-org:service:WANCableLinkConfig:1
  USN: uuid:492f6828-5b92-396e-a151-7a8e5ef39857::urn:schemas-upnp-org:service:WANCableLinkConfig:1
  Location: http://192.168.0.1:33443/rootDesc.xml
M-SEARCH Reply:
  ST: urn:schemas-upnp-org:service:Layer3Forwarding:1
  USN: uuid:caf7bb0f-4944-3e02-a1d6-0655dac3e012::urn:schemas-upnp-org:service:Layer3Forwarding:1
  Location: http://192.168.0.1:33443/rootDesc.xml
M-SEARCH Reply:
  ST: uuid:caf7bb0f-4944-3e02-a1d6-0655dac3e012
  USN: uuid:caf7bb0f-4944-3e02-a1d6-0655dac3e012
  Location: http://192.168.0.1:33443/rootDesc.xml
M-SEARCH Reply:
  ST: uuid:caf7bb0f-4944-3e02-a1d6-0655dac3e012
  USN: uuid:caf7bb0f-4944-3e02-a1d6-0655dac3e012
  Location: http://192.168.0.1:33443/rootDesc.xml
M-SEARCH Reply:
  ST: uuid:492f6828-5b92-396e-a151-7a8e5ef39857
  USN: uuid:492f6828-5b92-396e-a151-7a8e5ef39857
  Location: http://192.168.0.1:33443/rootDesc.xml
M-SEARCH Reply:
  ST: uuid:221c3b78-8e10-395c-bbd3-e3c1f8b670af
  USN: uuid:221c3b78-8e10-395c-bbd3-e3c1f8b670af
  Location: http://192.168.0.1:33443/rootDesc.xml
M-SEARCH Reply:
  ST: uuid:221c3b78-8e10-395c-bbd3-e3c1f8b670af
  USN: uuid:221c3b78-8e10-395c-bbd3-e3c1f8b670af
  Location: http://192.168.0.1:33443/rootDesc.xml
M-SEARCH Reply:
  ST: uuid:492f6828-5b92-396e-a151-7a8e5ef39857
  USN: uuid:492f6828-5b92-396e-a151-7a8e5ef39857
  Location: http://192.168.0.1:33443/rootDesc.xml
M-SEARCH Reply:
  ST: uuid:492f6828-5b92-396e-a151-7a8e5ef39857
  USN: uuid:492f6828-5b92-396e-a151-7a8e5ef39857
  Location: http://192.168.0.1:33443/rootDesc.xml
M-SEARCH Reply:
  ST: uuid:caf7bb0f-4944-3e02-a1d6-0655dac3e012
  USN: uuid:caf7bb0f-4944-3e02-a1d6-0655dac3e012
  Location: http://192.168.0.1:33443/rootDesc.xml
NODATA or TIMEOUT
  1: uuid:221c3b78-8e10-395c-bbd3-e3c1f8b670af
     http://192.168.0.1:33443/rootDesc.xml
     uuid:221c3b78-8e10-395c-bbd3-e3c1f8b670af
  2: uuid:492f6828-5b92-396e-a151-7a8e5ef39857
     http://192.168.0.1:33443/rootDesc.xml
     uuid:492f6828-5b92-396e-a151-7a8e5ef39857
  3: uuid:caf7bb0f-4944-3e02-a1d6-0655dac3e012
     http://192.168.0.1:33443/rootDesc.xml
     uuid:caf7bb0f-4944-3e02-a1d6-0655dac3e012
  4: urn:schemas-upnp-org:service:Layer3Forwarding:1
     http://192.168.0.1:33443/rootDesc.xml
     uuid:caf7bb0f-4944-3e02-a1d6-0655dac3e012::urn:schemas-upnp-org:service:Layer3Forwarding:1
  5: urn:schemas-upnp-org:service:WANCableLinkConfig:1
     http://192.168.0.1:33443/rootDesc.xml
     uuid:492f6828-5b92-396e-a151-7a8e5ef39857::urn:schemas-upnp-org:service:WANCableLinkConfig:1
  6: urn:schemas-upnp-org:service:WANIPConnection:1
     http://192.168.0.1:33443/rootDesc.xml
     uuid:492f6828-5b92-396e-a151-7a8e5ef39857::urn:schemas-upnp-org:service:WANIPConnection:1
  7: urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1
     http://192.168.0.1:33443/rootDesc.xml
     uuid:221c3b78-8e10-395c-bbd3-e3c1f8b670af::urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1
  8: urn:schemas-upnp-org:device:WANDevice:1
     http://192.168.0.1:33443/rootDesc.xml
     uuid:221c3b78-8e10-395c-bbd3-e3c1f8b670af::urn:schemas-upnp-org:device:WANDevice:1
  9: urn:schemas-upnp-org:device:WANConnectionDevice:1
     http://192.168.0.1:33443/rootDesc.xml
     uuid:492f6828-5b92-396e-a151-7a8e5ef39857::urn:schemas-upnp-org:device:WANConnectionDevice:1
 10: urn:schemas-upnp-org:device:InternetGatewayDevice:1
     http://192.168.0.1:33443/rootDesc.xml
     uuid:caf7bb0f-4944-3e02-a1d6-0655dac3e012::urn:schemas-upnp-org:device:InternetGatewayDevice:1
 11: upnp:rootdevice
     http://192.168.0.1:33443/rootDesc.xml
     uuid:caf7bb0f-4944-3e02-a1d6-0655dac3e012::upnp:rootdevice
```
And on later calls i got this:
`searching all UPnP devices
ifIndex=11 nextHop=100a8c0
        Num Entries: 2

        Interface Index[0]:     11
        IP Address[0]:          192.168.0.11
        Subnet Mask[0]:         255.255.255.0
        BroadCast[0]:           1.0.0.0 (1)
        Reassembly size[0]:     65535
        Type and State[0]:

        Interface Index[1]:     1
        IP Address[1]:          127.0.0.1
        Subnet Mask[1]:         255.0.0.0
        BroadCast[1]:           1.0.0.0 (1)
        Reassembly size[1]:     65535
        Type and State[1]:
Sending M-SEARCH request to 239.255.255.250 with ST: ssdp:all
NODATA or TIMEOUT
no device found.`

**Comment by Memnarch** [comment]
By looking into the RootDesc.xml, i found these entries:
`<deviceType>urn:schemas-upnp-org:device:WANDevice:1</deviceType><friendlyName>WANDevice</friendlyName><manufacturer>MiniUPnP</manufacturer><manufacturerURL>http://miniupnp.free.fr/</manufacturerURL><modelDescription>WAN Device</modelDescription><modelName>WAN Device</modelName><modelNumber>20151230</modelNumber><modelURL>http://miniupnp.free.fr/</modelURL><serialNumber>215040005576</serialNumber><UDN>uuid:221c3b78-8e10-395c-bbd3-e3c1f8b670af</UDN><UPC>000000000000</UPC>`
So it seems they are using some MiniUPNP code.

**Comment by miniupnp** [comment]
just use tcpdump or similar to see which messages are sent/received on port 1900 UDP.
You should see the router advertising regularly (every 120 minutes at least ?)
and responding when a M-SEARCH request is sent.

**Comment by Memnarch** [comment]
SOrry for letting you wait so long. I used wireshark and i am sure i know why things go downhill. While UPNPC-STatic seems to send on IPv4, my stupid router responds on IPv6 as it seems... oO
![grafik](https://user-images.githubusercontent.com/1398184/36641169-81d0fa56-1a2b-11e8-86bd-106cc5b987ee.png)

**Comment by miniupnp** [comment]
I see nothing on PORT 1900

**Comment by Memnarch** [comment]
Ok so this time i come with a proper wireshark log(i hope so, last attachment)
using upnpc-static.exe, modified to have a timeout of 30sec when using upnpdiscover instead of 2:
`upnpc-static.exe -l`
it looks like this(*.10 is me, *.1 is the router):
![grafik](https://user-images.githubusercontent.com/1398184/39010284-7538b3a8-440e-11e8-9f16-c0b5c52340bc.png)

And this is the log itself:
[SSDP.zip](https://github.com/miniupnp/miniupnp/files/1929269/SSDP.zip)

**Comment by Memnarch** [comment]
Ooookay something interesting:
Windows has a SSDP-Service. AFter disabling it, discovery works much better. Seems it is already fetching all the Data from port 1900?

**Comment by Memnarch** [comment]
YEP that piece of s....service seems to be the problem. Retried with other SSDP-Discoverytools and when that service is disabled, stuff starts to work.

Funny sidenode: For some reason the delete command does not work on a portmapping so i update it with a timeout of 1ms so it gets removed oO

**Comment by miniupnp** [comment]
miniupnpc is using setsockopt( IP_MULTICAST_IF) to select which interface to use under windows...
https://github.com/miniupnp/miniupnp/blob/master/miniupnpc/minissdpc.c#L579
Tell me if you find something that helps on your configuration

**Comment by Memnarch** [comment]
Thanks!
I'll look into that.

**Comment by miniupnp** [comment]
your problem is not with receiving Multicast, but sending.
the miniupnpc client is sending a **multicast** SSDP M-SEARCH, the router should respond with a **unicast** HTTP OK
Alternatively, the client could not send any M-SEARCH and just listen to **multicast** SSDP NOTIFY which are sent periodically by the router (every 30s or so). minissdpd is doing that, but miniupnpc not (not by itself ;)

**Comment by miniupnp** [comment]
http://www.upnp.org/specs/arch/UPnP-arch-DeviceArchitecture-v1.1.pdf
1.3 Search (p29)
