### ISSUE TITLE
No IGD UPnP Device found on the network

### ISSUE THREAD

**Issue by brianj64** [miniupnp/miniupnp#266]
I have this error message sometimes. This is on a ASUS RT-AC68U router with UPnP and NAT-PMP enabled. 

The specific issue i have is that miniupnpc sometimes finds a IGD UPnP device, and sometimes not. **This is seemingly random.** 

This is using the Windows upnpc executable. 
Both shared and static do not work.

**Comment by miniupnp** [comment]
How can you tell it is a miniupnpc issue and not an issue from your router ?

**Comment by brianj64** [comment]
I don't think this is an issue specific to miniupnpc, the same problem with not being able to find the router happens to UPnP PortMapper

**Comment by brianj64** [comment]
Just a FYI: Updated ASUSwrt-Merlin build and this completely fixed UPnP functionality. The MiniUPnPd build that my router now uses is "MiniUPnP d 20171004" which doesn't have the hanging problem.
