### ISSUE TITLE
upnpc -m doesnt work correctly when used with minissdpd

### ISSUE THREAD

**Issue by nihilus** [miniupnp/miniupnp#269]
As the title says, I start up minissdpd -i br0 but occasionally I need to probe usb0, however upnpc -l -m usb0 will show the answers from minissdpd which is only listening on br0.

**Comment by miniupnp** [comment]
you can trick miniupnpc into not using minissdpd  : 
`$ upnpc -m usb0 -p /dev/null -l`

**Comment by nihilus** [comment]
sneaky trick, cool. Maybe it should be documented somewhere?

**Comment by miniupnp** [comment]
it may be relevant to disable minissdpd usage if -m option is used...

**Comment by nihilus** [comment]
Yes, it would be relevant especially for scripting.
