### ISSUE TITLE
miniupnpc CMake build fails on Windows

### ISSUE THREAD

**Issue by Enhex** [miniupnp/miniupnp#270]
using Windows 10, Visual Studio 2017.

After generating a project with CMake, I get the following errors:
```
1>------ Build started: Project: upnpc-static, Configuration: Debug x64 ------
1>upnpc.obj : error LNK2019: unresolved external symbol __imp_freeUPNPDevlist referenced in function main
1>upnpc.obj : error LNK2019: unresolved external symbol __imp_upnpDiscover referenced in function main
1>upnpc.obj : error LNK2019: unresolved external symbol __imp_UPNP_GetValidIGD referenced in function main
1>upnpc.obj : error LNK2019: unresolved external symbol __imp_UPNP_GetIGDFromUrl referenced in function main
1>upnpc.obj : error LNK2019: unresolved external symbol __imp_FreeUPNPUrls referenced in function main
1>upnpc.obj : error LNK2019: unresolved external symbol __imp_FreePortListing referenced in function NewListRedirections
1>upnpc.obj : error LNK2019: unresolved external symbol __imp_UPNP_GetTotalBytesSent referenced in function GetConnectionStatus
1>upnpc.obj : error LNK2019: unresolved external symbol __imp_UPNP_GetTotalBytesReceived referenced in function GetConnectionStatus
1>upnpc.obj : error LNK2019: unresolved external symbol __imp_UPNP_GetTotalPacketsSent referenced in function GetConnectionStatus
1>upnpc.obj : error LNK2019: unresolved external symbol __imp_UPNP_GetTotalPacketsReceived referenced in function GetConnectionStatus
1>upnpc.obj : error LNK2019: unresolved external symbol __imp_UPNP_GetStatusInfo referenced in function DisplayInfos
1>upnpc.obj : error LNK2019: unresolved external symbol __imp_UPNP_GetConnectionTypeInfo referenced in function DisplayInfos
1>upnpc.obj : error LNK2019: unresolved external symbol __imp_UPNP_GetExternalIPAddress referenced in function DisplayInfos
1>upnpc.obj : error LNK2019: unresolved external symbol __imp_UPNP_GetLinkLayerMaxBitRates referenced in function DisplayInfos
1>upnpc.obj : error LNK2019: unresolved external symbol __imp_UPNP_AddPortMapping referenced in function SetRedirectAndTest
1>upnpc.obj : error LNK2019: unresolved external symbol __imp_UPNP_AddAnyPortMapping referenced in function SetRedirectAndTest
1>upnpc.obj : error LNK2019: unresolved external symbol __imp_UPNP_DeletePortMapping referenced in function RemoveRedirect
1>upnpc.obj : error LNK2019: unresolved external symbol __imp_UPNP_DeletePortMappingRange referenced in function RemoveRedirectRange
1>upnpc.obj : error LNK2019: unresolved external symbol __imp_UPNP_GetSpecificPortMappingEntry referenced in function SetRedirectAndTest
1>upnpc.obj : error LNK2019: unresolved external symbol __imp_UPNP_GetGenericPortMappingEntry referenced in function ListRedirections
1>upnpc.obj : error LNK2019: unresolved external symbol __imp_UPNP_GetListOfPortMappings referenced in function NewListRedirections
1>upnpc.obj : error LNK2019: unresolved external symbol __imp_UPNP_GetFirewallStatus referenced in function GetFirewallStatus
1>upnpc.obj : error LNK2019: unresolved external symbol __imp_UPNP_GetOutboundPinholeTimeout referenced in function GetPinholeOutboundTimeout
1>upnpc.obj : error LNK2019: unresolved external symbol __imp_UPNP_AddPinhole referenced in function SetPinholeAndTest
1>upnpc.obj : error LNK2019: unresolved external symbol __imp_UPNP_UpdatePinhole referenced in function GetPinholeAndUpdate
1>upnpc.obj : error LNK2019: unresolved external symbol __imp_UPNP_DeletePinhole referenced in function RemovePinhole
1>upnpc.obj : error LNK2019: unresolved external symbol __imp_UPNP_CheckPinholeWorking referenced in function GetPinholeAndUpdate
1>upnpc.obj : error LNK2019: unresolved external symbol __imp_UPNP_GetPinholePackets referenced in function GetPinholePackets
1>upnpc.obj : error LNK2019: unresolved external symbol __imp_strupnperror referenced in function ListRedirections
1>E:\MiniUPnP\miniupnpc-build\Debug\upnpc-static.exe : fatal error LNK1120: 29 unresolved externals
1>Done building project "upnpc-static.vcxproj" -- FAILED.
2>------ Skipped Build: Project: INSTALL, Configuration: Debug x64 ------
2>Project not selected to build for this solution configuration 
========== Build: 0 succeeded, 1 failed, 3 up-to-date, 1 skipped ==========
```

Also the CMake script fails to find `IPHLPAPI_LIBRARY` and `WINSOCK2_LIBRARY`, had to enter them manually.

The provided `miniupnpc_vs2015.sln` does work, but only after running `updateminiupnpcstrings.sh` which isn't documented anywhere.

**Comment by androm3da** [comment]
For a while I convinced myself that this was due to `MINIUPNPC_STATICLIB` not being defined during the build and I attributed that to how the `COMPILE_DEFINITIONS` was parsed by visual studio (see details).  But I tried changing it to be spaces and it didn't help.  Now I'm not sure what the problem is.

https://cmake.org/cmake/help/v3.0/prop_tgt/COMPILE_DEFINITIONS.html

**Comment by androm3da** [comment]
Actually, I think that `MINIUPNP_STATICLIB` and/or MINIUPNP_LIBSPEC are a factor.  I couldn't get all of the targets to build correctly with simple tweaks.

Visual Studio linker complains when the declspec is on the definition (should only be on the declaration).

Here's a build that fails this same way as your bug report: https://ci.appveyor.com/project/androm3da/miniupnp/build/job/5u18xjn9102y4uk5

**Comment by miniupnp** [comment]
why don't you use projects files from the source tree ? 
https://github.com/miniupnp/miniupnp/tree/master/miniupnpc/msvc

**Comment by Enhex** [comment]
I'm reporting the problem I encountered to make sure it doesn't go unnoticed, though as @androm3da mentioned it already appears in the CI build.

**Comment by androm3da** [comment]
@Enhex -- That's a CI build of my fork that adds the `cmake` to the CI config.  Once it's green I can offer this upstream though.

@miniupnp -- can CMake be configured to use those project files?  I'm using `miniupnp` in another CMake project.  That project's cmake references miniupnp's and during its build is where I first encountered the problem.

**Comment by miniupnp** [comment]
@androm3da The CMake project files are OK, except for you windows guys.
just propose a fix via a merge request and I'll be happy to merge it

**Comment by androm3da** [comment]
@miniupnp I'm definitely not a "you windows guys" -- I was hoping you were.  😂

I'll keep digging.

**Comment by yangguanglu** [comment]
hello, I also met this problem. My development is vs2015.I solve this problem by define macro named  MINIUPNP_STATICLIB

**Comment by yangguanglu** [comment]
@Enhex I hope it works.

**Comment by carlhua** [comment]
how do you guys resolve the WINSOCK2_LIBRARY issue?


CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
WINSOCK2_LIBRARY
    linked by target "libminiupnpc-static" in directory C:/NANO/raiblocks-master1/miniupnp/miniupnpc



windows CMAKE vs2015 is my enviornment

**Comment by miniupnp** [comment]
@Enhex  could you try with the new CMakeList.txt ? 530b2723500c4a70

**Comment by Enhex** [comment]
still seems to happen.
BTW it only happens with `upnpc-shared` project.

**Comment by miniupnp** [comment]
@Enhex Could you paste the build log ?
@btolfa made the modernized CMakeList.txt

**Comment by btolfa** [comment]
I reproduced the issue with new CMakeLists.txt. I'll see what I can do.

**Comment by o-u-p** [comment]
The same issue with mingw in windows, any fix about that?
