### ISSUE TITLE
flood of: interface index not matching 0 != 7

### ISSUE THREAD

**Issue by abelbeck** [miniupnp/miniupnp#272]
Our Linux based project recently upgraded to miniupnpd-2.0.20171212, after which a fellow developer @dkerr64 reported a flood of syslog messages of the form:
```
daemon.warn miniupnpd[27970]: interface index not matching 0 != 7
```

The log messages only occur when `enable_upnp=yes` is defined.  The 50d21a38 commit adds this log.

Reading through the code, we were able to conclude that `lan_addr->index` is always zero if `listening_ip=` is a IP/NM (ex. 192.168.101.1/255.255.255.0), but if `listening_ip=` is an interface name (ex. eth1) then the `lan_addr->index` is defined a non-zero value and the 50d21a38 commit works as intended.

In our project, we worked around this change by now defining `listening_ip=` using an interface name, and as before with allow/deny configuration permission rules.

**Comment by miniupnp** [comment]
indeed it is advised to always set listening_ip= with interface name.
However I have to investigate this problem

**Comment by nyetwurk** [comment]
I see the exact same thing
