### ISSUE TITLE
Can't redirect a port

### ISSUE THREAD

**Issue by nidza07** [miniupnp/miniupnp#273]
Hello. I wanted to use mini uPNP to forward port 2500 UDP, and here is what I get: 
upnpc : miniupnpc library test client, version 1.9.
 (c) 2005-2014 Thomas Bernard.
Go to http://miniupnp.free.fr/ or http://miniupnp.tuxfamily.org/
for more information.
List of UPNP devices found on the network :
 desc: http://192.168.1.1:37215/upnpdev.xml
 st: urn:schemas-upnp-org:service:WANPPPConnection:1

UPnP device found. Is it an IGD ? : http://192.168.1.1:37215/ctrlu/WANPPPConnection_1
Trying to continue anyway
Local LAN ip address : 192.168.1.3
ExternalIPAddress = 100.69.157.250
AddPortMapping(2500, 2500, 192.168.1.3) failed with code 501 (Action Failed)
GetSpecificPortMappingEntry() failed with code 402 (Invalid Args)

My router is a HG531v1. Anybody can help me? I've also checked in the web interface and UPNP is correctly enabled.

**Comment by miniupnp** [comment]
try with another port / IP.
Also please check it is working with another UPnP client software.
You should also try with the LATEST version of miniupnpc
