### ISSUE TITLE
SSDP packet sender IP:PORT not from a LAN, ignoring

### ISSUE THREAD

**Issue by karelvanhecke** [miniupnp/miniupnp#274]
Is their any way to have miniupnp allow access to different subnets, not just the subnet from the LAN interface?

I have multiple vlans configured on a layer 3 switch and static routes to each subnet on pfSense.
Everything else works, except for uPnP, which always rejects requests because they are not in the LAN subnet's ip range.

**Comment by miniupnp** [comment]
well I guess you need to patch miniupnpd to change the check

**Comment by miniupnp** [comment]
@karelvanhecke what is your LAN addresses ?
I guess you can work around the check with forcing a mask. Like eth0/16

**Comment by miniupnp** [comment]
@karelvanhecke which version are you using ? because I believe your issue has been fixed in 50d21a38d0719682f276173efd705ccbe78aca3d
