### ISSUE TITLE
Python module documentation and example

### ISSUE THREAD

**Issue by vit1251** [miniupnp/miniupnp#276]
Can not documentation or any example of usage python module.
Could you please write small example of usage UPnP object and initialize.

**Comment by miniupnp** [comment]
Are you kidding ?
https://github.com/miniupnp/miniupnp/blob/master/miniupnpc/testupnpigd.py
https://github.com/miniupnp/miniupnp/blob/master/miniupnpc/pymoduletest.py

**Comment by vit1251** [comment]
No. Talk about small document on package page in https://pypi.python.org/pypi/miniupnpc
Your approach for source code install way but it usually uncommon.

**Comment by miniupnp** [comment]
I'm not managing anything on pypi.python.org, please ask the pypi package manager
