### ISSUE TITLE
allow (mis?)reporting IGDv1 to fool broken igd clients

### ISSUE THREAD

**Issue by yangfl** [miniupnp/miniupnp#277]
Forwarded from https://bugs.debian.org/885960

Many IGD clients (most notably MS BITS) look for IGD v1 and do not recognize v2 as a valid igd service

Since v2 is backwards compatible with v1, perhaps there should be a way to force miniupnpd to report v1

**Comment by miniupnp** [comment]
this is a know issue. see #167 
Default has been reverted to UDA 1.1 for 2 years now : 58b130116ba7f1a3669cd822811822b4967c5ac7

Please use latest code.

**Comment by nyetwurk** [comment]
I am still seeing urn:schemas-upnp-org:device:InternetGatewayDevice:2 on 2.0

**Comment by miniupnp** [comment]
@nyetwurk  what is in your config.h file ?

**Comment by nyetwurk** [comment]
```
/* UPnP version reported in XML descriptions
 * 1.0 / 1.1 / 2.0 depending on which UDA (UPnP Device Architecture) Version */
#define UPNP_VERSION_MAJOR      1
#define UPNP_VERSION_MINOR      1
#define UPNP_VERSION_MAJOR_STR  XSTR(UPNP_VERSION_MAJOR)
#define UPNP_VERSION_MINOR_STR  XSTR(UPNP_VERSION_MINOR)
```

**Comment by nyetwurk** [comment]
```
/* Enable the support of IGD v2 specification.
 * This is not fully tested yet and can cause incompatibilities with some
 * control points, so enable with care. */
#define IGD_V2

#ifdef IGD_V2
/* Enable DeviceProtection service (IGDv2) */
#define ENABLE_DP_SERVICE
/*#define ENABLE_HTTPS*/
/*#define HTTPS_CERTFILE "/path/to/certificate.pem"*/
/*#define HTTPS_KEYFILE "/path/to/private.key"*/

/* Enable WANIPv6FirewallControl service (IGDv2). needs IPv6 */
#ifdef ENABLE_IPV6
#define ENABLE_6FC_SERVICE
#endif /* ENABLE_IPV6 */
#endif /* IGD_V2 */
```

**Comment by miniupnp** [comment]
So you have configured UPNP version 1.1 (UDA 1.1)
but enabled IGD 2 (if it is disabled it will be IGD 1)

**Comment by miniupnp** [comment]
if `SSDP_RESPOND_SAME_VERSION` is defined in config.h, miniupnpd should respond to M-SEARCH SSDP request with the version that was requested.
So any client requesting for V1 will still be answered V1.

**Comment by miniupnp** [comment]
@nyetwurk  are you using minissdpd ?

**Comment by nyetwurk** [comment]
No, I am not using minissdpd, just checking the config.h when building the miniupnpd deb package from apt-get source on debian.

**Comment by nyetwurk** [comment]
To be explicit, the deb maintainer just closed (incorrectly, IMO) the downstream bug:
https://bugs.debian.org/885960

I believe it should be re-opened but before doing so I want to make sure it isn't me doing something stupid.

**Comment by nyetwurk** [comment]
In particular, I believe the option of v1 vs v2 should be a **runtime** option for the purposes of binary only based distributions (that is to say, the vast majority of them these days :)

**Comment by miniupnp** [comment]
It is not currently a runtime option.
Anyway a client sending a M-SEARCH request for IGDv1 will be replied with urn:schemas-upnp-org:device:InternetGatewayDevice:2 in the response.
So can you be more specific about it ? Which client are you testing with ?

**Comment by nyetwurk** [comment]
It is a third party developed piece of software which I do not have the source for. It appears to look for GatewayDevice:1 and will not function with miniupnpd at all (it doesn't even detect it as an IGD device) I do not know what M-SEARCH request it is sending; I confess I am not very familiar with the details of SSDP

I am also using http://www.meshcommander.com/upnptools, and it also results in GatewayDevice:2

As above, I do not know what sort of M-SEARCH query it sends. I will investigate further. Apologies if I am cluttering things.

**Comment by nyetwurk** [comment]
The only NOTIFIES I am getting from miniupnpd when sniffing the network are GatewayDevice:2, not :1

I believe this is why the first piece of software I mentioned is not seeing miniupnpd at all.

**Comment by nyetwurk** [comment]
I found a third piece of software:

https://sourceforge.net/projects/upnp-portmapper/

which reports:

DEBUG Found service of wrong type urn:schemas-upnp-org:device:InternetGatewayDevice:2, expected urn:schemas-upnp-org:device:InternetGatewayDevice:1.

**Comment by nyetwurk** [comment]
Here is another:

http://www.xldevelopment.net/upnpwiz.php

**Comment by miniupnp** [comment]
SSDP is using UDP on port 1900. use wireshark/tcpdump to see what's going on.
NOTIFY are periodicly broadcasted (multicasted in fact) on the network by UPnP Devices.

But clients can search for specific devices using a M-SEARCH request (multicasted)
the device must answer by an unicast packet.

I'm going to have a look at https://sourceforge.net/projects/upnp-portmapper/

**Comment by nyetwurk** [comment]
I am increasingly of the opinion that all of these clients are broken. See https://github.com/kaklakariada/portmapper/issues/29#issuecomment-362930556

**Comment by nyetwurk** [comment]
They are depending on the multicast NOTIFY to locate an IGD, and if the version is wrong (e.g. they see IGD:2), they do not find it. They do not get as far as to send a unicast M-SEARCH for IGD:1

**Comment by nyetwurk** [comment]
xldevelopment sent me this in response:

> Thanks for contacting us.  Our tool uses the native UPnP functionality that is built into Windows which is compatible with most routers and configurations but not all.  Unfortunately at this time we do not plan to enhance UPnP Wizard to offer more than what is already provided by Windows.

Not a good sign, since it is likely most developers will do the same.

**Comment by miniupnp** [comment]
microsoft created UPnP IGD, and they killed it...

**Comment by miniupnp** [comment]
If Microsoft is clearly not following the specification it contributed to, I don't know what to do.
From :
http://www.upnp.org/specs/arch/UPnP-arch-DeviceArchitecture-v1.0-20081015.pdf
1.1.2 page 14

> Updated UPnP device and service types are required to be fully backward compatible with previous versions of the same type. 
> Devices **must** advertise the **highest supported version** of each supported type. For example, if a device supports version 2 of the “Audio” service, it would advertise only version 2, even though it also supports version 1. Control points that support a given version of a device or service are able to also interact with higher versions because of this backward compatibility requirement, but only using the functionality that was defined in the lower version.
> For example, if a control point supports only version “1” of the “Audio” service, and a device advertises that it supports version “2” of the “Audio” service, the control point should recognize and be able to use the device. 

So if you compile miniupnpd with IGD v2 support, it **must** advertise version 2 to comply to the spec.
And whatever client (called control point in UPnP nomenclature) must recognize it.

**Comment by miniupnp** [comment]
version 1.1 (http://www.upnp.org/specs/arch/UPnP-arch-DeviceArchitecture-v1.1.pdf) is even more specific : 
1.2.2 page 20-21

> Updated UPnP device and service types are **REQUIRED** to be fully backward compatible with previous versions of the same type.
> Devices **MUST** advertise the highest supported version of each supported type. For example, if a device supports version 2 of the “Audio” service, it would advertise only version 2, even though it also supports version 1. It **MUST NOT** advertise additional supported versions.
> Control points that support a given version of a device or service are able to also interact with higher versions because of this backward compatibility requirement, but only using the functionality that was defined in the lower version.
> For example, if a control point supports only version “1” of the “Audio” service, and a device advertises that it supports version “2” of the “Audio” service, the control point **MUST** recognize the device and be able to use it.

**Comment by yangfl** [comment]
As M$ shit still take up a large part of the world, I think some countermeasures should be taken to promote miniupnp. An option should be OK.
@nyetwurk I would suggest you to come up with an PR.

**Comment by miniupnp** [comment]
My solution is to default to IGD v1.
So only aware users can recompile to get IGDv2.

Note : even compiled with IGDv1 option, new methods introduced in IGDv2 are supported. It is just that they are not advertised/not put into description, so the devices complies 100% with IGD v1.

**Comment by nyetwurk** [comment]
This is typical MS behavior BTW. Make (or adopt) a standard, do a poor job of implementation, and from then on, anyone trying to use it must adjust to MS's behavior. They have done it with more than a few "standards" (IMAP, DHCP, DNS, CIFS, Kerberos, LDAP). The list is endless.

I think the best way would be to make a run time option to allow overriding the NOTIFY.

**Comment by nyetwurk** [comment]
Changing the NOTIFY to :1 does nothing for any of the above except for upnp-portmapper.

**Comment by miniupnp** [comment]
so the solution are : 

1. compile with default option which is advertising IGD v1. This it the **DEFAULT** option, and will work for 99% of users which just need the UPnP IGD functionality to open some IPv4 port mappings. The v2 added methods are still there, but not advertised, in order to retain 100% compatibility with broken clients which don't conform to the UPnP standard which states clearly they **MUST** recognize and use device of upper versions.
1. For the very few user which need fully compliant IGD v2, enable it at compile time and make sure the clients they are using are not broken.

If your bug is "my distro miniupnpd package is compiled with --igd2 option enabled", don't report it here.

**Comment by nyetwurk** [comment]
Thank you!
