### ISSUE TITLE
provide a pkg-config file

### ISSUE THREAD

**Issue by yangfl** [miniupnp/miniupnp#281]
Forwarded from https://bugs.debian.org/664240

Please consider adding a pkg-config file, so other packages can more easily get the correct build flags.

PS: I personally doubt the usefulness of such file. Should CMake file alse be included?

**Comment by miniupnp** [comment]
you mean just Cflags: -I/usr/include/miniupnpc
and Libs: -lminiupnpc   ?

**Comment by yangfl** [comment]
Probably yes, and maybe with this one https://github.com/monero-project/kovri/blob/master/cmake/FindMiniUPnPc.cmake
