### ISSUE TITLE
from the tar.gz for miniupnpd -Makefile:36: *** missing separator.  Stop.

### ISSUE THREAD

**Issue by tofutim** [miniupnp/miniupnp#283]
I think it is a space/tab issue. I am attempting to cross-compile on Linux for ARM but this applies also to directly making from Linux.

**Comment by miniupnp** [comment]
make -f Makefile.linux

**Comment by tofutim** [comment]
Thanks, that was silly of me to miss.

My new error is:
```
netfilter/iptcrdr.c:52:22: error: unknown type name 'iptc_handle_t'
 #define IPTC_HANDLE  iptc_handle_t
etc.
```

**Comment by tofutim** [comment]
maybe it should be iptc_handle and not iptc_handle_t, i'm working off 20180203

**Comment by miniupnp** [comment]
check your ip tables version
You may need to set  -DIPTABLES_143
In some case you need to 
`$ IPTABLESPATH=/path/to/iptables-1.4.1 make -f Makefile.linux`

**Comment by miniupnp** [comment]
please read the INSTALL. linking against libiptc is not always easy...

**Comment by tofutim** [comment]
Thanks Thomas, you were right on.
```
make -f Makefile.linux VERBOSE=1 CC="arm-linux-gnueabihf-gcc" AR="arm-linux-gnueabihf-ar r" RANLIB="arm-linux-gnueabihf-ranlib" DESTDIR="/home/tim/raspi/usr" CFLAGS="-I/home/tim/raspi/usr/include" LDFLAGS="-L/home/tim/raspi/usr/lib" PKG_CONFIG_LIBDIR=/home/tim/raspi/usr/lib/pkgconfig IPTABLESPATH=../iptables-1.6.1 STRIP=arm-linux-gnueabihf-strip
```
worked for me, though ../iptables-1.6.1 was the source code (after make) for iptables. I did run `make install` for iptables, which installed into /home/tim/raspi/usr. Strangely, when I set IPTABLESPATH=/home/tim/raspi/usr it doesn't work.
