### ISSUE TITLE
minissdpd: SSDP_LISTEN_ON_SPECIFIC_ADDR unusable

### ISSUE THREAD

**Issue by yangfl** [miniupnp/miniupnp#285]
By enabling `SSDP_LISTEN_ON_SPECIFIC_ADDR` in config.h, I got

```
openssdpsocket.c:164:26: warning: implicit declaration of function ‘GetIfAddrIPv4’ [-Wimplicit-function-declaration]
    sa->sin_addr.s_addr = GetIfAddrIPv4(listen_addr[0]);
                          ^~~~~~~~~~~~~
openssdpsocket.c:164:40: error: ‘listen_addr’ undeclared (first use in this function); did you mean ‘n_listen_addr’?
    sa->sin_addr.s_addr = GetIfAddrIPv4(listen_addr[0]);
                                        ^~~~~~~~~~~
                                        n_listen_addr
```

Clearly something is broken.

**Comment by miniupnp** [comment]
GetIfAddrIPv4() was removed from commit 63179a1f7f8ad5986f0973a0a99e261f738574ea
anyway, why are you enabling `SSDP_LISTEN_ON_SPECIFIC_ADDR`  ?

**Comment by yangfl** [comment]
From https://bugs.debian.org/746586

**Comment by yangfl** [comment]
Hi,
Much thanks for your fix. However you might forget the below lines https://github.com/miniupnp/miniupnp/blob/master/minissdpd/openssdpsocket.c#L185

**Comment by miniupnp** [comment]
@yangfl : make sure enabling  `SSDP_LISTEN_ON_SPECIFIC_ADDR` doesn't prevent multicast packets from being received. That was the case 4 years ago, it is probably still the case

**Comment by yangfl** [comment]
multicast?

https://github.com/miniupnp/miniupnp/blob/master/minissdpd/config.h#L29 says only "broadcast"

**Comment by yangfl** [comment]
I suggest listening on 239.255.255.250 only.

**Comment by miniupnp** [comment]
yes. multicast packets are in fact broadcasted on the LAN and delivered by the TCP/IP stack to the socket which have "subscribed" to the group.
I should have said multicast

**Comment by miniupnp** [comment]
also take into account that in some case SSDP packets are "unicasted"

**Comment by miniupnp** [comment]
for reference : https://stackoverflow.com/questions/10692956/what-does-it-mean-to-bind-a-multicast-udp-socket/10739443#10739443

**Comment by miniupnp** [comment]
Le 23.02.2018 à 14:13, yangfl a écrit :
>
> I suggest listening on 239.255.255.250 only.
>
in anycase, listening on 239.255.255.250 only doesn't restrict the
socket to one network interface !
