### ISSUE TITLE
Annoying syslog spam

### ISSUE THREAD

**Issue by PaulGWebster** [miniupnp/miniupnp#287]
Hey all miniupnpd works perfectly well but in my messages I keep keeping spammed with: 

Mar  4 13:16:31 gateway miniupnpd[1755]: try_sendto(sock=8, len=487, dest=239.255.255.250:1900): sendto: No buffer space available
Mar  4 13:16:31 gateway miniupnpd[1755]: try_sendto(sock=8, len=469, dest=239.255.255.250:1900): sendto: No buffer space available
Mar  4 13:16:31 gateway miniupnpd[1755]: try_sendto(sock=8, len=416, dest=239.255.255.250:1900): sendto: No buffer space available
Mar  4 13:16:31 gateway miniupnpd[1755]: try_sendto(sock=8, len=455, dest=239.255.255.250:1900): sendto: No buffer space available
Mar  4 13:16:31 gateway miniupnpd[1755]: try_sendto(sock=8, len=416, dest=239.255.255.250:1900): sendto: No buffer space available
Mar  4 13:16:31 gateway miniupnpd[1755]: try_sendto(sock=8, len=475, dest=239.255.255.250:1900): sendto: No buffer space available
Mar  4 13:16:31 gateway miniupnpd[1755]: try_sendto(sock=8, len=416, dest=239.255.255.250:1900): sendto: No buffer space available
Mar  4 13:16:31 gateway miniupnpd[1755]: try_sendto(sock=8, len=479, dest=239.255.255.250:1900): sendto: No buffer space available
Mar  4 13:16:31 gateway miniupnpd[1755]: try_sendto(sock=8, len=407, dest=239.255.255.250:1900): sendto: No buffer space available
Mar  4 13:16:31 gateway miniupnpd[1755]: try_sendto failed to send 11 packets
Mar  4 13:17:31 gateway miniupnpd[1755]: sendto(udp_notify=8, 172.30.1.1): No buffer space available

miniupnpd is listening on igb0 and igb1, igb1 = 
igb1: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=6403bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,VLAN_HWTSO,RXCSUM_IPV6,TXCSUM_IPV6>
        ether 6c:b3:11:1b:10:d5
        hwaddr 6c:b3:11:1b:10:d5
        inet 172.30.1.1 netmask 0xffffff00 broadcast 172.30.1.255
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
        media: Ethernet autoselect
        status: no carrier

**Comment by miniupnp** [comment]
try to run with "-d" option to get more verbose output.

It looks like NOTIFY packets are not sent : That won't prevent most of the clients to work properly, because they discover the router using a M-SEARCH SSDP request

**Comment by miniupnp** [comment]
@PaulGWebster have you been able to know why SSDP Notify packets are not sent ?
What's your OS ?
