### ISSUE TITLE
Do't build getroute.c IFF IPv6 is disabled.

### ISSUE THREAD

**Issue by nihilus** [miniupnp/miniupnp#290]
As the title say it should not try to build getroute.c if IPv6-support is turned off, the toolchain might not have all the headers necessary to compile it.

**Comment by miniupnp** [comment]
linux ? BSD ?
which header causes the problem ?

**Comment by nihilus** [comment]
I dont recall it now, but it was some ipv6 header on uclibc and Linux.

**Comment by nihilus** [comment]
@miniupnp it might be that libnfnetlink is missing, however since IPv6 is disabled it doesnt make sense to build it.

**Comment by nihilus** [comment]
Ah, this has been fixed for miniupnpd but not for minissdpd, that is why it doesnt work for minissdpd

**Comment by miniupnp** [comment]
could you post you build log ?
thought you were talking about miniupnpd. is it minissdpd ?

**Comment by nihilus** [comment]
yes it is minissdpd, didnt realized there was a getroute.c in miniupnpd, however my setup is not available at the moment.
