### ISSUE TITLE
Connection Issues

### ISSUE THREAD

**Issue by jshand2015** [miniupnp/miniupnp#291]
I got this error:

miniupnpd[322]: [truncated] m.  i have no idea what this or the cause

**Comment by miniupnp** [comment]
I have no idea neither.
If you want that somebody is able to help you, you should give the full context of the error.
Also try to launch miniupnpd with -d flag, it will be more verbose and you'll be able to find more easily when the error happens.

**Comment by miniupnp** [comment]
closing for now. Reopen if you are able to give more details about the issue.
