### ISSUE TITLE
make: *** [miniupnpcstrings.h] Error 127

### ISSUE THREAD

**Issue by worxcoin** [miniupnp/miniupnp#293]
HI,

I recieve an error if I try to compile it with debian by using this command `make -f Makefile.mingw DLLWRAP=i586-mingw32msvc-dllwrap CC=i586-mingw32msvc-gcc AR=i586-mingw32msvc-ar`

The console gives me 
`debian@debian:~/miniupnpc-1.9$ make -f Makefile.mingw DLLWRAP=i586-mingw32msvc-dllwrap CC=i586-mingw32msvc-gcc AR=i586-mingw32msvc-ar
wingenminiupnpcstrings miniupnpcstrings.h.in miniupnpcstrings.h
make: wingenminiupnpcstrings: Command not found
Makefile.mingw:72: recipe for target 'miniupnpcstrings.h' failed
make: *** [miniupnpcstrings.h] Error 127`

My gitian recipe tell me I should run these two sed command first 

`sed 's/dllwrap -k --driver-name gcc/$(DLLWRAP) -k --driver-name $(CC)/' -i Makefile.mingw
  sed 's|wingenminiupnpcstrings $< $@|./wingenminiupnpcstrings $< $@|' -i Makefile.mingw`

Doing this I receive the following error

`debian@debian:~/miniupnpc-1.9$ make -f Makefile.mingw DLLWRAP=i586-mingw32msvc-dllwrap CC=i586-mingw32msvc-gcc AR=i586-mingw32msvc-ar    ./wingenminiupnpcstrings miniupnpcstrings.h.in miniupnpcstrings.h
./wingenminiupnpcstrings: 1: ./wingenminiupnpcstrings: MZ▒▒▒▒@▒▒▒: not found
./wingenminiupnpcstrings: 2: ./wingenminiupnpcstrings: Syntax error: word unexpected (expecting ")")
Makefile.mingw:72: recipe for target 'miniupnpcstrings.h' failed
make: *** [miniupnpcstrings.h] Error 2`

Anyone who can help me?

**Comment by miniupnp** [comment]
well the Makefile.mingw assumes it is not CROSS compiling.
I'm going to have a look
