### ISSUE TITLE
Neufbox (sfr)  very strange behaviour.

### ISSUE THREAD

**Issue by pparent76** [miniupnp/miniupnp#294]
When I try to use miniupnpc with a neufbox (sfrbox), at first I can add rules and then after 1 or 2 operations, everything stops working and starts doing strange things for no apparent reason. The only way to recover is reboot the box. 

```
upnpc -l
upnpc : miniupnpc library test client, version 2.0.
 (c) 2005-2018 Thomas Bernard.
Go to http://miniupnp.free.fr/ or https://miniupnp.tuxfamily.org/
for more information.
List of UPNP devices found on the network :
 desc: http://[2a02:8420:4ce8:5c01::1]:49152/rootDesc.xml
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

 desc: http://192.168.1.1:49152/rootDesc.xml
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

Found valid IGD : http://[2a02:8420:4ce8:5c01::1]:49152/ctl/IPConn
Local LAN ip address : 192.168.1.177
Connection Type : IP_Routed
Status : Connected, uptime=6206s, LastConnectionError : ERROR_NONE
  Time started : Thu Apr 26 11:39:48 2018
MaxBitRateDown : 10255360 bps (10.2 Mbps)   MaxBitRateUp 1045504 bps (1.0 Mbps)
ExternalIPAddress = 86.71.154.243
 i protocol exPort->inAddr:inPort description remoteHost leaseTime
GetGenericPortMappingEntry() returned 713 (SpecifiedArrayIndexInvalid)
```

```
upnpc -a 192.168.1.117 1194 443 tcp
upnpc : miniupnpc library test client. (c) 2005-2013 Thomas Bernard
Go to http://miniupnp.free.fr/ or http://miniupnp.tuxfamily.org/
for more information.
List of UPNP devices found on the network :
 desc: http://[2a02:8420:4ce8:5c01::1]:49152/rootDesc.xml
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

 desc: http://192.168.1.1:49152/rootDesc.xml
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

Found valid IGD : http://[2a02:8420:4ce8:5c01::1]:49152/
Local LAN ip address : 192.168.1.177
ExternalIPAddress = 86.71.154.243
AddPortMapping(993, 1194, 192.168.1.177) failed with code 718 (ConflictInMappingEntry)
GetSpecificPortMappingEntry() failed with code 714 (NoSuchEntryInArray)
```

The description file shows that the neufbox uses miniupnpd
`<root><specVersion><major>1</major><minor>0</minor></specVersion><device><deviceType>urn:schemas-upnp-org:device:InternetGatewayDevice:1</deviceType><friendlyName>neufbox router</friendlyName><manufacturer>neufbox</manufacturer><manufacturerURL>http://efixo.com</manufacturerURL><modelDescription>neufbox router</modelDescription><modelName>neufbox router</modelName><modelNumber>1</modelNumber><modelURL>http://efixo.com</modelURL><serialNumber>00000000</serialNumber><UDN>uuid:eaee12ee-61e4-4979-8f55-e806d70ed3e6</UDN><serviceList><service><serviceType>urn:schemas-upnp-org:service:Layer3Forwarding:1</serviceType><serviceId>urn:upnp-org:serviceId:Layer3Forwarding1</serviceId><controlURL>/ctl/L3F</controlURL><eventSubURL>/evt/L3F</eventSubURL><SCPDURL>/L3F.xml</SCPDURL></service></serviceList><deviceList><device><deviceType>urn:schemas-upnp-org:device:WANDevice:1</deviceType><friendlyName>WANDevice</friendlyName><manufacturer>MiniUPnP</manufacturer><manufacturerURL>http://miniupnp.free.fr/</manufacturerURL><modelDescription>WAN Device</modelDescription><modelName>WAN Device</modelName><modelNumber>20170814</modelNumber><modelURL>http://miniupnp.free.fr/</modelURL><serialNumber>00000000</serialNumber><UDN>uuid:eaee12ee-61e4-4979-8f55-e806d70ed3e7</UDN><UPC>000000000000</UPC><serviceList><service><serviceType>urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1</serviceType><serviceId>urn:upnp-org:serviceId:WANCommonIFC1</serviceId><controlURL>/ctl/CmnIfCfg</controlURL><eventSubURL>/evt/CmnIfCfg</eventSubURL><SCPDURL>/WANCfg.xml</SCPDURL></service></serviceList><deviceList><device><deviceType>urn:schemas-upnp-org:device:WANConnectionDevice:1</deviceType><friendlyName>WANConnectionDevice</friendlyName><manufacturer>MiniUPnP</manufacturer><manufacturerURL>http://miniupnp.free.fr/</manufacturerURL><modelDescription>MiniUPnP daemon</modelDescription><modelName>MiniUPnPd</modelName><modelNumber>20170814</modelNumber><modelURL>http://miniupnp.free.fr/</modelURL><serialNumber>00000000</serialNumber><UDN>uuid:eaee12ee-61e4-4979-8f55-e806d70ed3e8</UDN><UPC>000000000000</UPC><serviceList><service><serviceType>urn:schemas-upnp-org:service:WANIPConnection:1</serviceType><serviceId>urn:upnp-org:serviceId:WANIPConn1</serviceId><controlURL>/ctl/IPConn</controlURL><eventSubURL>/evt/IPConn</eventSubURL><SCPDURL>/WANIPCn.xml</SCPDURL></service></serviceList></device></deviceList></device><device><deviceType>urn:schemas-upnp-org:device:EventDevice:1</deviceType><friendlyName>NeufboxEventDevice</friendlyName><manufacturer>efixo</manufacturer><manufacturerURL>http://www.efixo.com/</manufacturerURL><modelDescription>software Event Device</modelDescription><modelName>Neufbox Event Device</modelName><modelNumber>20170814</modelNumber><modelURL>http://www.efixo.com/</modelURL><serialNumber>00000000</serialNumber><UDN>uuid:eaee12ee-61e4-4979-8f55-e806d70ed3e9</UDN><UPC>000000000000</UPC><serviceList><service><serviceType>urn:neufbox-org:service:NeufBoxEvent:1</serviceType><serviceId>urn:neufbox-org:serviceId:NeufBoxEvent1</serviceId><controlURL>/ctl/NBX</controlURL><eventSubURL>/evt/NBX</eventSubURL><SCPDURL>/NBX.xml</SCPDURL></service></serviceList></device></deviceList><presentationURL>http://192.168.1.1/</presentationURL></device></root>`

**Comment by miniupnp** [comment]
what do you mean by " everything stops working and starts doing strange things for no apparent reason." ?

**Comment by miniupnp** [comment]
I would be interested in getting  http://192.168.1.1:49152/NBX.xml

**Comment by pparent76** [comment]
>everything stops working and starts doing strange things for no apparent reason
As you can see in the message whenever I try to add a new rule (whatever it is, whichever is the computer asking for it), it replies ConflictInMappingEntry + NoSuchEntryInArray (even though the new rule is not conflicting anything). And when simply trying to list existing rules I get SpecifiedArrayIndexInvalid.

**Comment by pparent76** [comment]
>I would be interested in getting http://192.168.1.1:49152/NBX.xml

`<scpd><specVersion><major>1</major><minor>1</minor></specVersion><actionList/><serviceStateTable><stateVariable sendEvents="yes"><name>NeufBoxEvent</name><dataType>string</dataType></stateVariable></serviceStateTable></scpd>`

**Comment by miniupnp** [comment]
`upnpc -a 192.168.1.117 1194 443 tcp`
You're trying to redirect port 443. This one is very likely already used or forbidden.
Try ports > 1024 such as 12345 or 54321

**Comment by pparent76** [comment]
```
You're trying to redirect port 443. This one is very likely already used or forbidden.
Try ports > 1024 such as 12345 or 54321
```

I tried exactly the same result, when it does not work as above it does not work for all ports. And when UpnP from the box has not crashed, asking for 443 works fine.

**Comment by pparent76** [comment]
```
upnpc -a 192.168.1.117 1194 34500 tcp
upnpc : miniupnpc library test client. (c) 2005-2013 Thomas Bernard
Go to http://miniupnp.free.fr/ or http://miniupnp.tuxfamily.org/
for more information.
List of UPNP devices found on the network :
 desc: http://192.168.1.1:49152/rootDesc.xml
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

 desc: http://[2a02:8420:4ce8:5c01::1]:49152/rootDesc.xml
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

Found valid IGD : http://192.168.1.1:49152/ctl/IPConn
Local LAN ip address : 2a02:8420:4ce8:5c01:e695:6eff:fe44:520b
ExternalIPAddress = 86.71.154.183
AddPortMapping(34500, 1194, 192.168.1.117) failed with code 718 (ConflictInMappingEntry)
GetSpecificPortMappingEntry() failed with code 714 (NoSuchEntryInArray)
```

**Comment by miniupnp** [comment]
Well if there is a bug in the neufbox (SFRbox) please see directly  with them : http://efixo-dev.pfd.sfr.net/

**Comment by pparent76** [comment]
Ok Thank's I was not sure whether to post it here or not.

**Comment by miniupnp** [comment]
they also use github : https://github.com/sfr-cpe/openwrt/wiki
