### ISSUE TITLE
timestamp stored in lease_file unusable with switch to monotonic clock

### ISSUE THREAD

**Issue by RMerl** [miniupnp/miniupnp#295]
Since the switch to a monotonic clock, the timestamp stored in lease_file is relative to an arbitrary, unknown point in time.

At the very least, it prevents external applications from parsing the file and reporting how much time is left on the lease (this is a problem for router firmware reporting the remaining time on a lease).  It's  possible that it also prevents miniupnpd itself from properly reloading that lease file on a restart - I haven't checked.

If that's the case, I would suggest possibly storing a reference point in the lease file, or changing the timestamp field to something that can be processed by an external process or a new miniupnpd instance.

**Comment by miniupnp** [comment]
I think I should change so unix timestamp are still used in the lease_file

**Comment by RMerl** [comment]
When I discussed the issue with @themiron, he suggested taking a look at how dnsmasq had implemented it as a reference, since dnsmasq also uses a monotonic clock, and stores lease time into a file for external usage/daemon restart reuse.

**Comment by miniupnp** [comment]
it looks like dnsmasq uses time(NULL) : 
http://thekelleys.org.uk/gitweb/?p=dnsmasq.git;a=blob;f=src/util.c;h=532bc16d96ee4a47bdc018c98860b017b4b6a23a;hb=HEAD#l358

**Comment by RMerl** [comment]
Except on embedded devices with no RTC (such as routers), where it seems to define its own clock by using  times().

**Comment by miniupnp** [comment]
@RMerl can you test 00abd9e ?

**Comment by themiron** [comment]
@miniupnp after 00abd9e6c86fbd46954db918777fced50c177abb some leases will expire too early in case of ntp time shift after file write & before file read (miniupnpd restart)
what if to write out the remaining lease time (timeout -= upnp_time) and add current unpn_time() if no rtc support was configured?
with this approach the leases will be prolongued by non-run time as acceptable side effect, from my point of view.

**Comment by miniupnp** [comment]
I prefer leases to expire too early than too late. Anyway, the expiration time in lease_file have to be stored in an absolute time value, and this can only work if there is a working RTC.

There is absolutely no way to check if a lease loaded from the file is expired if there is no RTC.
Just don't reload the lease_file if running on such a system.

**Comment by themiron** [comment]
Yes, talking about configured support I mean exactly compile time option, beacuse RTC suport state is likely known for target system.
As for too early expiration, this behavior on non-RTC systems will be almost the same as original (without monotonic time support), what actually was the original issue for implementing monotonic time.

**Comment by miniupnp** [comment]
@themiron is 17773f0 OK ? just define LEASEFILE_USE_REMAINING_TIME in build and lease_file times are remaining lease time

**Comment by themiron** [comment]
looks good, thank you.
limited leaseduration for particular lease will not break any renew logic, right? (can't see the code at the moment, sorry). if yes, maybe default configured duration can be applied, not sure here

**Comment by RMerl** [comment]
Thanks for the changes.  I'll update my repo and do some tests, will provide feedback after that.

**Comment by RMerl** [comment]
Doing tests with LEAEFILE_REMAINING_TIME.

First issue I notice: when I restart miniupnpd, the remaining time shown in the lease_file didn't get updated.  Test case:

1. Setup a port forward with a lease time of 3600 seconds
2. Check lease file: it will contain 3600 seconds.
3. Wait a minute, then restart miniupnpd
4. Check lease_file :  it will still contain 3600, instead of whatever time was left when miniupnpd was shut down.

Could it be because the lease file didn't get refreshed before shutting down?  Since the value is now a countdown rather than a timestamp, lease_file probably needs to be written to disk at exit time, with the latest remaining time.

Also, a method to force updating the lease_file will be required for it to be of use to external applications, otherwise we don't know how up-to-date the remaining time field is.  Something triggered by a signal would work.


Other issue I haven't been able to fully track down yet: qbittorrent is giving me a remaining lease time of a few years instead of hours like it should be.  I suspect the issue occurred because lease time was initially set before the clock got set.

Current content of my generated lease_file:

```
admin@Stargate88:/tmp/home/root# more /tmp/upnp.leases 
TCP:12345:192.168.10.106:12345:3600:libminiupnpc
TCP:46537:192.168.10.100:46537:4294966703:qBittorrent/4.0.4 at 192.168.10.100:46537
UDP:46537:192.168.10.100:46537:4294966703:qBittorrent/4.0.4 at 192.168.10.100:46537
```

**Comment by RMerl** [comment]
Further info regarding qbittorrent: exiting and restarting qbittorrent still generates the large bogus remaining time:

```
TCP:18549:192.168.10.100:18549:4294965854:qBittorrent/4.0.4 at 192.168.10.100:18549
UDP:18549:192.168.10.100:18549:4294965854:qBittorrent/4.0.4 at 192.168.10.100:18549
```
So it's unrelated to the time shift.  Could be an instance where miniupnpd is still using a timestamp instead of remaining time?  qBitTorrent uses NAT-PMP.

**Comment by john9527** [comment]
Just to provide a second data point....I also see the large incorrect remaining time testing on my merlin-fork

`TCP:17174:192.168.1.101:32400:4294965256:Plex Media Server`

**Comment by RMerl** [comment]
qBittorrent seems to use both.  When you start it, you get the lease with the description.  A few hours later, it gets replaced with this one:

```
admin@Stargate88:/tmp/home/root# cat /tmp/upnp.leases 
TCP:46922:192.168.10.100:46922:3600:NAT-PMP 46922 tcp
UDP:46922:192.168.10.100:46922:3600:NAT-PMP 46922 udp
```
I'll test the f6ac854f0f9a3c6f10d42b4269cbd679d3535685 change later today.

**Comment by miniupnp** [comment]
@RMerl please test the last commits on my branch [issue_295](https://github.com/miniupnp/miniupnp/tree/issue_295)
I added lease_file_rewrite() which is called before exiting, and when SIGUSR2 is received

**Comment by RMerl** [comment]
I merged up to a92138345b609214095f2ed8b12301989aa50e47.

qBittorrent: lease value now correctly set at 0 in upnp_lease.

SIGUSR2: seems to work properly:

```
admin@Stargate88:/tmp/home/root# cat /tmp/upnp.leases 
TCP:25880:192.168.10.100:25880:0:qBittorrent/4.0.4 at 192.168.10.100:25880
UDP:25880:192.168.10.100:25880:0:qBittorrent/4.0.4 at 192.168.10.100:25880
TCP:12345:192.168.10.106:12345:3600:libminiupnpc

admin@Stargate88:/tmp/home/root# killall -USR2 miniupnpd

admin@Stargate88:/tmp/home/root# cat /tmp/upnp.leases 
TCP:25880:192.168.10.100:25880:0:qBittorrent/4.0.4 at 192.168.10.100:25880
UDP:25880:192.168.10.100:25880:0:qBittorrent/4.0.4 at 192.168.10.100:25880
TCP:12345:192.168.10.106:12345:3581:libminiupnpc
```
Saving and reloading on exit: seems to work correctly:

```
admin@Stargate88:/tmp/home/root# cat /tmp/upnp.leases 
TCP:25880:192.168.10.100:25880:0:qBittorrent/4.0.4 at 192.168.10.100:25880
UDP:25880:192.168.10.100:25880:0:qBittorrent/4.0.4 at 192.168.10.100:25880
TCP:12345:192.168.10.106:12345:3581:libminiupnpc
admin@Stargate88:/tmp/home/root# service restart_upnp

Done.
admin@Stargate88:/tmp/home/root# cat /tmp/upnp.leases 
TCP:12345:192.168.10.106:12345:3530:libminiupnpc
TCP:25880:192.168.10.100:25880:0:qBittorrent/4.0.4 at 192.168.10.100:25880
UDP:25880:192.168.10.100:25880:0:qBittorrent/4.0.4 at 192.168.10.100:25880
```

I'd say things are looking good at this point.

**Comment by miniupnp** [comment]
@RMerl thank you for your tests

**Comment by john9527** [comment]
Typo in line 265,
'lease_duration' should be 'leaseduration'
