### ISSUE TITLE
miniupnpcstrings.h not found

### ISSUE THREAD

**Issue by jenokizm** [miniupnp/miniupnp#297]
Hi, im clone this repo, open **miniupnpc_vs2015.sln** in vs2015 or vs2017 and and got a compilation error:

> Error C1083 Can not open file inclusion: miniupnpcstrings.h: No such file or directory 

file is really not in any folders. why and where to get it?

**Comment by miniupnp** [comment]
just create it : 
```
#define OS_STRING "Windows"
#define MINIUPNPC_VERSION_STRING "2.0"
#define UPNP_VERSION_STRING "UPnP/1.1
```

**Comment by jenokizm** [comment]
Thank You! Now everything is compiled.

**Comment by jenokizm** [comment]
By the way about header files is still a question. I do not understand why on Appveyor builds you do not put the header file in the archive with the library. Because if it were, it would be possible to use Implicate linking, and without it only Explicit linking which is inconvenient.
about linking vs read more here https://msdn.microsoft.com/en-us/library/9yd93633.aspx

**Comment by miniupnp** [comment]
the miniupnpcstrings.h file is generated. It is implemented in the various Makefiles, but not in the MS VS project. I could do it
