### ISSUE TITLE
Allow to change iptables chain

### ISSUE THREAD

**Issue by pali** [miniupnp/miniupnp#300]
Currently iptables chain names are hardcoded in miniupnpd source code
https://github.com/miniupnp/miniupnp/blob/bd836936f7ed7e697f36dff709d00a907644172a/miniupnpd/upnpglobalvars.c#L102-L112
and cannot be configured at runtime. Please add some ability to change iptables chain names via some configuration option, like linux-igd project have it.

**Comment by miniupnp** [comment]
you are entirely wrong.
Please use the following options in miniupnpd.conf : 
```
upnp_forward_chain=
upnp_nat_chain=
upnp_nat_postrouting_chain=
```
https://github.com/miniupnp/miniupnp/blob/2b6fa0839f705b7c144ea4df0310307f76d2ad45/miniupnpd/miniupnpd.conf#L46

**Comment by pali** [comment]
Ops, sorry for that. That is my fault!
