### ISSUE TITLE
Git signing

### ISSUE THREAD

**Issue by anonimal** [miniupnp/miniupnp#301]
Hi Thomas,

Have you considered GPG signing commits/tags/releases? If not, will you please consider?

- https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work
- https://softwareengineering.stackexchange.com/questions/212192/what-are-the-advantages-and-disadvantages-of-cryptographically-signing-commits-a
- https://github.com/jayphelps/git-blame-someone-else
- https://github.com/weidai11/cryptopp/issues/290

**Comment by miniupnp** [comment]
indeed, maybe should I

**Comment by miniupnp** [comment]
@anonimal is that OK ?
https://github.com/miniupnp/miniupnp/commit/582375b64f347d6ef1a4dc3478ff3678ea923f80
https://github.com/miniupnp/miniupnp/releases/tag/miniupnpd_2_1

**Comment by anonimal** [comment]
Thanks, Thomas.
