### ISSUE TITLE
Website and release security

### ISSUE THREAD

**Issue by anonimal** [miniupnp/miniupnp#302]
Hi Thomas,

There are several glaring MiTM issues regarding the website and releases:

1. http://miniupnp.free.fr/files/ does not implement TLS via https
2. The release packages are not GPG signed with detached signatures

Point 1 is easily resolved with [Let's Encrypt](https://letsencrypt.org/). Point 2 can be trivially resolved once #301 is resolved.

Will these points be resolved in the near future? Point 1 *could* be avoided if point 2 is completed (though, ideally, both points should be resolved).

**Comment by miniupnp** [comment]
1) miniupnp.free.fr does not support HTTPS. Use the mirror https://miniupnp.tuxfamily.org/files/
2) Indeed I should GPG sign release packages.

**Comment by miniupnp** [comment]
@anonimal is that ok ? https://miniupnp.tuxfamily.org/files/

**Comment by Chocobo1** [comment]
@miniupnp 
You should also make your PGP public key more visible so others/users may easily verify its owner.
Here is an example: https://www.qbittorrent.org/download.php

**Comment by anthraxx** [comment]
awesome :heart:

**Comment by anonimal** [comment]
Why did you close this issue? It has not been resolved.

**Comment by miniupnp** [comment]
1. miniupnp.free.fr doesn't not support HTTP (until the hoster enable it) but miniupnp.tuxfamily.org does.  So please use miniupnp.tuxfamily.org if you need HTTPS.
2. releases packages are now provided with GPG detached signatures.

**Comment by anonimal** [comment]
>releases packages are now provided with GPG detached signatures.

You have many releases on http://miniupnp.free.fr/files/ and only the 2.1 series is signed. Not all distros pull from the 2.1 series. Either remove the deprecated files or sign them all. The site is a mess and brings me back to 1995.
