### ISSUE TITLE
[feature request] add 'iptable_extra_option=' in miniupnpd.conf

### ISSUE THREAD

**Issue by enihcam** [miniupnp/miniupnp#305]
The background is that in some network boxes, there could be multiple services/scripts triggering iptables. There is an option '-w' in iptables for adding read/write lock of the tables. I wanted to add this option into miniupnpd scripts and avoid from override by package update.

**Comment by miniupnp** [comment]
I think you misunderstand the way miniupnpd works. It doesn't call the iptables binary but call libiptc functions.
see https://github.com/miniupnp/miniupnp/blob/master/miniupnpd/netfilter/iptcrdr.c

So it is not possible to pass additional options to iptables...

However, it is possible to wait the "xtables lock" just as iptables -w is doing.
Do you know how does it work ?

**Comment by miniupnp** [comment]
@enihcam could you explain me more in details the issue you are facing ?

**Comment by enihcam** [comment]
@miniupnp 
Last year I requested to add a lock to iptables operations. https://github.com/miniupnp/miniupnp/issues/232

But now looks like the lock is not added. Could you double confirm?

**Comment by miniupnp** [comment]
In fact, I think it is not necessary to add netfilter access locking to miniupnpd, because miniupnpd only accesses its own tables
Also you are wrong, -w is **not** for adding read/write lock of the tables : it let iptables waits for the lock to be released (by calling sleep(1) ...)

**Comment by enihcam** [comment]
@miniupnp sounds reasonable. :)
