### ISSUE TITLE
Python Documentation

### ISSUE THREAD

**Issue by Javier-AN** [miniupnp/miniupnp#308]
First of all, thank you for all your work, I truly appreciate it and I don't mean to criticize, if that is what it seems.

My question: is there any explanation of classes, methods, etc of the Python Module?
I think it's hard to understand the examples and to code your own scrpits without knowing what does each method exactly do.
The only thing I'm trying right now is to forward a single port from the router to another one in my Raspberry. If you help me doing this, I'll don't need any Documentation, but I think that a library without accesible and easy to understand documentation can be pretty useless.
If there is a Documention, please simply tell me where can I find it, I've been searching for it for a while now (maybe I'm just stupid and don't know how to find it).
Again, thank you.

**Comment by miniupnp** [comment]
you can have a look at the samples : 
https://github.com/miniupnp/miniupnp/blob/master/miniupnpc/pymoduletest.py

The method descriptions are inside the python module : https://github.com/miniupnp/miniupnp/blob/master/miniupnpc/miniupnpcmodule.c#L545
I'm no python expert, but I think you can
```
>>> import miniupnpc
>>> dir(miniupnpc)

```

**Comment by Javier-AN** [comment]
Thank you! I think I'll can work with that!
