### ISSUE TITLE
MiniUPnP for android 

### ISSUE THREAD

**Issue by knkrth** [miniupnp/miniupnp#309]
Hi, Can anyone know how to compile MiniUPnP for android?

**Comment by miniupnp** [comment]
I don't see any reason for miniupnpc not to compile for Android.
Which android SDK are you targeting ?

**Comment by knkrth** [comment]
@miniupnp Android SDK Tools 24.0.2, Android SDK Platform-tools 21, Android SDK Build-tools 21.1.2

**Comment by miniupnp** [comment]
@knkrth so what's wrong ?  Have you tried
`> CC=aarch64-linux-android-gcc make`

**Comment by knkrth** [comment]
Thank you.
