### ISSUE TITLE
Support HTTPS on the MiniUPnP Website

### ISSUE THREAD

**Issue by oboukli** [miniupnp/miniupnp#310]
It would be great to add support for and enforce the HTTPS scheme on the MiniUPnP website (miniupnp.free.fr). A certificate can be obtained from a certificate authority such as [Let's Encrypt](https://letsencrypt.org/).

Also, now [GitHub Pages with custom domains support HTTPS](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/).

Does the MiniUPnP website need HTTPS?
Yes. See https://doesmysiteneedhttps.com/

**Comment by anonimal** [comment]
Referencing #302. And yes, this is trivial to accomplish and should be done.

**Comment by miniupnp** [comment]
this is a duplicate of #302 and https://miniupnp.tuxfamily.org/ does support HTTPS.
I'm still waiting for the hoster of miniupnp.free.fr to support HTTPS. if you find it so trivial, feel free to ask them : http://portail.free.fr/

**Comment by anonimal** [comment]
>if you find it so trivial, feel free to ask them directly 

It's not my project.
