### ISSUE TITLE
Run Coverity Scan

### ISSUE THREAD

**Issue by anonimal** [miniupnp/miniupnp#313]
For example, you can use Coverity through Travis CI https://scan.coverity.com/travis_ci

Coverity currently reports 17 defects in the current codebase. Mostly insecure data handling but there are also resource leaks and memory corruptions as well (with potential for false-positives).

**Comment by anonimal** [comment]
Note: that's only for miniupnpc. I haven't scanned the other paths.

**Comment by miniupnp** [comment]
I've tried to do something but failed : 
https://github.com/miniupnp/miniupnp/tree/coverity_scan
https://travis-ci.org/miniupnp/miniupnp/builds/400792575

**Comment by anonimal** [comment]
I currently run automated builds for https://github.com/monero-project/monero and https://gitlab.com/kovri-project/kovri. I could easily add miniupnp to the list of my builds after I add miniupnp to my coverity dashboard. You would get notification emails after every build (after I send you an invite).

Another option is for you to create an account on https://scan.coverity.com and add miniupnp, add me as maintainer, and then give me the token to upload the builds. I'm fine either way.

Would you want either of these options? I don't have many good things to say about Travis-CI but I mentioned it only as a potential option. I'm rarely on github now (moved to gitlab) so I would be best reached by email if you're interested https://pgp.mit.edu/pks/lookup?search=anonimal%40getmonero.org&op=index

**Comment by anonimal** [comment]
Note: the automated builds would be against the master branch every N days (around 2 to 3 days).

**Comment by paul-chambers** [comment]
I'd recommend resolving #152 (split into separate repos per project) before setting up Coverity in Travis. Else you'd end up redoing it.

**Comment by miniupnp** [comment]
I'm not planning to split into separate repos soon ;)

**Comment by paul-chambers** [comment]
Would you complain if someone were to help you do it? ;)

**Comment by miniupnp** [comment]
note : travis-ci is dead ;)
