### ISSUE TITLE
Incorrect target Windows version constants

### ISSUE THREAD

**Issue by irwir** [miniupnp/miniupnp#317]
[Commit c55d27](https://github.com/miniupnp/miniupnp/commit/c55d27f46ef9649feada028583c4d3354e7909f0) got two comments, and absense of any reaction suggests  there might be no email notifications created.

The request is to fix two version checks.

**Comment by miniupnp** [comment]
I'm currently away... Pull request ?

**Comment by miniupnp** [comment]
fixed with a7626af053994fd81c792cccb3f88b0224169c19
