### ISSUE TITLE
iptables_init.sh[379]: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?

### ISSUE THREAD

**Issue by enihcam** [miniupnp/miniupnp#321]
`iptables_init.sh[379]: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?`

The conflict issue happens again. Why wouldn't we just simply add '-w' for iptables_init.sh?

**Comment by miniupnp** [comment]
because it is already done : https://github.com/miniupnp/miniupnp/commit/72005ce86a05fd3a185e78dee8d20e2c646ad6e8
