### ISSUE TITLE
Custom connection time out in selectigd

### ISSUE THREAD

**Issue by MatthewScholefield** [miniupnp/miniupnp#323]
I'm using the Python API via the following code:

```python
upnp = miniupnpc.UPnP()
upnp.discoverdelay = 10
upnp.discover()
upnp.selectigd()
```

`upnp.discover()` finds 21 devices pretty quickly. The problem is that `selectigd` seems to query each device, each one timing out and taking more than a minute to time out. It would be nice to have a time out for whatever creates these messages:
```
connect: Connection timed out
connect: Connection timed out
connect: Connection timed out
connect: Connection refused
connect: Connection timed out
connect: Connection timed out
connect: Connection timed out
connect: Connection timed out
connect: Connection timed out
```

**Comment by miniupnp** [comment]
you should compile with the option MINIUPNPC_SET_SOCKET_TIMEOUT
it sets a 3 seconds timeout for connect() : 
https://github.com/miniupnp/miniupnp/blob/master/miniupnpc/connecthostport.c#L90

**Comment by MatthewScholefield** [comment]
@miniupnp Thanks, but may I ask, why is it only configurable as a C define? I'd like to not tell developers of my software that they have to recompile a C program just to get a Python app to work.

**Comment by miniupnp** [comment]
you may notice it is enabled by default... a 3 seconds timeout looks reasonable for everyone.
It is up to you to code a runtime configuration of the feature if you want to.

**Comment by MatthewScholefield** [comment]
@miniupnp I totally agree. The reason I'm confused is because it takes more than a minute for each timeout message to be produced.

**Comment by MatthewScholefield** [comment]
@miniupnp I totally agree. The reason I'm confused is because it takes more than a minute for each timeout message to be produced, even after explicitly compiling it with that flag.

**Comment by RomulusC** [comment]
> 
> 
> @miniupnp I totally agree. The reason I'm confused is because it takes more than a minute for each timeout message to be produced, even after explicitly compiling it with that flag.

Did anyone ever find out how to prevent the timeout taking so long? I've compiled with the MINIUPNPC_SET_SOCKET_TIMEOUT define and it takes me >300s to query 3 unresponsive devices. It does step through the code and appropriately calls setsockopt, but no changes observed. 
(Ive removed these devices from the network but still wondering how one might fix this)

**Comment by miniupnp** [comment]
@RomulusC which OS do you use ?

**Comment by RomulusC** [comment]
Unfortunately, PS4's OS, FreeBSD.

**Comment by MatthewScholefield** [comment]
I'm running on Linux, specifically Solus, and I had the same problem.

**Comment by miniupnp** [comment]
well if you have any suggestion regarding the `setsockopt(s, SOL_SOCKET, SO_RCVTIMEO, &timeout, sizeof(struct timeval)` and `setsockopt(s, SOL_SOCKET, SO_SNDTIMEO, &timeout, sizeof(struct timeval)` code

**Comment by miniupnp** [comment]
from linux man page : 

> SO_RCVTIMEO and SO_SNDTIMEO
>     Specify the receiving or sending timeouts until reporting an error. The argument is a struct timeval. If an input or output function blocks for this period of time, and data has been sent or received, the return value of that function will be the amount of data transferred; if no data has been transferred and the timeout has been reached then -1 is returned with errno set to EAGAIN or EWOULDBLOCK, or EINPROGRESS (for connect(2)) just as if the socket was specified to be nonblocking. If the timeout is set to zero (the default) then the operation will never timeout. Timeouts only have effect for system calls that perform socket I/O (e.g., read(2), recvmsg(2), send(2), sendmsg(2)); timeouts have no effect for select(2), poll(2), epoll_wait(2), and so on.
