### ISSUE TITLE
Support for indirectly connected Internal networks

### ISSUE THREAD

**Issue by whiskeyalpharomeo** [miniupnp/miniupnp#330]
I'm running the miniupnp package on PFSense 2.4.4.  None of my upnp devices (game systems, etc) are on a directly connected segment from my firewall.  There're all a subnet away, seperated by an internal router which is multicast enabled.

The SSDP multicast group (239.255.255.250) is present on both the transit network (between the firewall and the router), and the inner network (where my client devices live):

`SWILFN001#sh ip igmp groups`
`IGMP Connected Group Membership`
`Group Address    Interface                Uptime    Expires   Last Reporter`
`. . .`
`239.255.255.250  ClientVlan                    02:19:34  00:02:56  xx.x.100.x`
`239.255.255.250  TransitVlan                   00:02:18  00:02:04  xx.x.50.x`

I get the following messages in the logs:

> Sep 27 00:19:41 | miniupnpd | 22643 | HTTP peer xx.x.xxx.8:55580 is not from a LAN, closing the connection

Is there a way to specify additional non-local LAN networks such that internal clients a couple of hops away can register?  If not, is there a way this capability can be added?

**Comment by miniupnp** [comment]
what happens if you add the LAN addresses to the .conf file ?
[code]listening_ip=192.168.0.1/24[/code]

**Comment by miniupnp** [comment]
Depending on your network namings, you can easily work around the limitation.
Let imagine the following setup : 
`internet <=> miniupnpd router <=> 192.168.1.x LAN <=> router <=> 192.168.2.x LAN`
Instead of `listening_ip=192.168.1.1/24` one can use `listening_ip=192.168.1.1/16`

**Comment by whiskeyalpharomeo** [comment]
Last night I fooled around with the config file.  Initially, I had the following line:

`listening_ip=vtnet1`

I tried a couple of different ways - modifications to the existing line, and adding additional lines:

`listening_ip=vtnet1`

`listening_ip=10.0.0.0/8`

`listening_ip=10.0.50.1` <-My inside IP on the transit network to the internal router
`listening_ip=10.0.0.0/8`

I got the same result with all of the various options.  It simply rejects any incoming connection that doesn't originate from within the 10.0.50/24 space, saying that it's "not from a LAN."

**Comment by whiskeyalpharomeo** [comment]
I did not try pairing the actual interface IP address with a broad mask, as you suggested above:

`listening_ip=10.0.50.1\16`

I'll give that a shot later this evening.

I also tried adding a sprecific ACL last night:

`allow 1024-65535 10.0.0.0/8 1024-65535`

This didn't help either.

**Comment by miniupnp** [comment]
`listening_ip=10.0.50.1/16` should work
it will find vtnet1 from 10.0.50.1 and force the network mask used to check if the IP is "from" this interface to 255.255.0.0

**Comment by whiskeyalpharomeo** [comment]
Very well.  I'll try that this evening, and let you know if it worked.  Thanks for the replies.

**Comment by whiskeyalpharomeo** [comment]
Ok, so I tried what we discussed, but it still didn't work.

1)
`listening_ip=10.0.50.1/16`
Resulted in the service failing to start.

2)
`listening_ip=vtnet1`
`listening_ip=10.0.50.1/16`
Allows the service to start, but I still get the "is not from a LAN, closing the connection" messages.  None are successful.

**Comment by miniupnp** [comment]
What is the log output when it is failing to start ? (you can use the -d option to enable DEBUG messages)

**Comment by whiskeyalpharomeo** [comment]
miniupnpd.conf 
`ext_ifname=vtnet0`
`port=2189`
`listening_ip=10.0.50.1/16`
`secure_mode=yes`
`presentation_url=https://10.0.50.1/`
`uuid=c91f4a44-a3ec-a077-eda1-afe2de9ef22`
`serial=C91F4A44`
`model_number=2.4.4-RELEASE`
`enable_upnp=yes`
`enable_natpmp=yes`

Yields these results:

`# miniupnpd -d -f /var/etc/miniupnpd.conf`
`Error: please specify LAN network interface by name instead of IPv4 address : 10.0.50.1/16`
`can't parse "10.0.50.1/16" as a valid interface name`
`Usage:`
`	miniupnpd [-f config_file] [-i ext_ifname] [-o ext_ip]`
`		[-a listening_ip] [-p port] [-d] [-L] [-U] [-S] [-N]`
`		[-u uuid] [-s serial] [-m model_number] `
`		[-t notify_interval] [-P pid_filename] `
`		[-B down up] [-w url] [-r clean_ruleset_interval]`
`		[-q queue] [-T tag]`
`		[-A "permission rule"] [-b BOOTID]`
``
`Notes:`
`	There can be one or several listening_ips.`
`	Notify interval is in seconds. Default is 30 seconds.
`	Default pid file is '/var/run/miniupnpd.pid'.``
`	Default config file is '/etc/miniupnpd.conf'.`
`	With -d miniupnpd will run as a standard program.`
`	-L sets packet log in pf and ipf on.`
`	-S sets "secure" mode : clients can only add mappings to their own ip`
`	-U causes miniupnpd to report system uptime instead of daemon uptime.`
`	-N enables NAT-PMP functionality.`
`	-B sets bitrates reported by daemon in bits per second.`
`	-w sets the presentation url. Default is http address on port 80`
`	-q sets the ALTQ queue in pf.`
`	-T sets the tag name in pf.`
`	-A use following syntax for permission rules :`
`	  (allow|deny) (external port range) ip/mask (internal port range)`
`	examples :`
`	  "allow 1024-65535 192.168.1.0/24 1024-65535"`
`	  "deny 0-65535 0.0.0.0/0 0-65535"`
`	-b sets the value of BOOTID.UPNP.ORG SSDP header`
`	-h prints this help and quits.`

**Comment by miniupnp** [comment]
OK, i'm sorry, interfaces names are mandatory with IPV6

**Comment by whiskeyalpharomeo** [comment]
I have no need nor desire for IPv6...  Is there a flag to disable that?

**Comment by miniupnp** [comment]
to work around the problem you can disable the check
https://github.com/miniupnp/miniupnp/blob/master/miniupnpd/miniupnpd.c#L468

**Comment by miniupnp** [comment]
IPV6 is a build time option. It is not enabled by default.
check config.h

**Comment by whiskeyalpharomeo** [comment]
So I have lied to pfsense a little bit, and now have _partial success_...

I made sure I had a static route for the innermost subnet pointed to the internal router, and then I changed the mask on the firewall's physical interface to a /16.  This allowed me to use `vtnet1` as the listen address, as the config seems to demand.

I now see registration attempts coming in from the remote sources, rather than dropping them as non-LAN.  Example, from my Plex host:

`miniupnpd[35043]: SSDP M-SEARCH from 10.0.100.8:14876 ST: upnp:rootdevice`
`miniupnpd[35043]: Single search found`
`miniupnpd[35043]: SendSSDPResponse(): 0 bytes to 10.0.100.8:14876 ST: HTTP/1.1 200 OK`
`CACHE-CONTROL: max-age=120`
`ST: upnp:rootdevice`
`USN: uuid:c91f4a44-a3ec-a077-eda1-afe2de9ef22::upnp:rootdevice`
`EXT:`
`SERVER: FreeBSD/11.2-RELEASE-p2 UPnP/1.1 MiniUPnPd/2.0`
`LOCATION: http://10.0.50.1:2189/rootDesc.xml`
`OPT: "http://schemas.upnp.org/upnp/1/0/"; ns=01`
`01-NLS: 1538172710`
`BOOTID.UPNP.ORG: 1538172710`
`CONFIGID.UPNP.ORG: 1337`

I say partial success, because in the past, UPnP was adequate to enable remote access to Plex without having to set up manual port forwarding.  Currently, that doesn't seem to be the case - the Plex UI shows that the attempt to enable remote access fails, and the pfsense UI shows no dynamically learned UPnP rules.

While Plex is no biggie, as I can do the manual port forwarding, I'm concerned the game consoles, and other multiplayer games will not be able to make the appropriate port forwarding requests.  Are there other multicast groups that need to be enabled?  Currently, I'm just doing 239.255.255.250.

**Comment by miniupnp** [comment]
The SSDP multicast group (239.255.255.250) is the only one used by UPNP

**Comment by miniupnp** [comment]
I forgot that the trick
`listening_ip=vtnet1/8`
is present in the INSTALL file :
https://github.com/miniupnp/miniupnp/blob/master/miniupnpd/INSTALL#L133

**Comment by miniupnp** [comment]
So you should reset the mask to the proper value on the network interface, and only cheat in the miniupnpd.conf file ;)

**Comment by miniupnp** [comment]
Please tell me if that works, I will update the INSTALL file to make it clearer.
