### ISSUE TITLE
[miniupnpd] [nat-pmp] iptables_init does not create postrouting table

### ISSUE THREAD

**Issue by 5paceToast** [miniupnp/miniupnp#334]
`NPDIRTY` is not even mentioned in `iptables_init.sh`, nor is the string "postrouting".
The result is a flood of syslog messages, such as:
```
[date] [hostname] daemon.err miniupnpd[pid] Failed to add NAT-PMP [port] tcp->[ip:port] 'NAT-PMP [port] tcp'
[date] [hostname] daemon.notice miniupnpd[pid] add_redirect_rule2(): addmasqueraderule returned -1
```

The only action required (as far as I can tell) is adding an NPDIRTY-related section to `iptables_init.sh`

**Comment by miniupnp** [comment]
`addmasqueraderule()` add the rule to the `MINIUPNPD-POSTROUTING` chain by default.
it looks the init for it was lost in commit 82ec7bc3df0eab362163545f5e61eb97a84652cd @yangfl ?

**Comment by miniupnp** [comment]
from #286

**Comment by miniupnp** [comment]
@5paceToast could you test the commit 1453df5 ?
I've no linux box setup for this test currently :-(

**Comment by 5paceToast** [comment]
@miniupnp I get the following error:
```
iptables v1.6.2: Can't use -i with POSTROUTING

Try `iptables -h' or 'iptables --help' for more information.
```

**Comment by miniupnp** [comment]
@5paceToast I'm sorry. I fixed that. Could you test commit c3f752db4a8286be00ad1d8b2a9fab37dc8d116d ?

**Comment by 5paceToast** [comment]
I don't seem to get any more errors with c3f752d, but as-is it won't do anything (it'll only quieten the logs).
Se comment on the commit for more details.

**Comment by miniupnp** [comment]
The order in which rules are added to iptables are another issue. The iptables_init.sh script has always used -A.

We cannot switch to -I without offering a way to configure that.
