### ISSUE TITLE
Compilation of minissdpc.c fails in debug configuration

### ISSUE THREAD

**Issue by irwir** [miniupnp/miniupnp#336]
After the commit https://github.com/miniupnp/miniupnp/commit/a31c86b8db76b8c491343c0c664aaa046d5488c5 `miniupnpc` fails to compile in debug configuration.

In the current code the offending lines are: 586, 595, 604 and 612.
I did not test it properly, but possibly these lines should be:

> IN_ADDR IPAddr = ((PSOCKADDR_IN)pUnicast->Address.lpSockaddr)->sin_addr;
> 
> IN_ADDR IPAddr = ((PSOCKADDR_IN)pAnycast->Address.lpSockaddr)->sin_addr;
> 
> IN_ADDR IPAddr = ((PSOCKADDR_IN)pMulticast->Address.lpSockaddr)->sin_addr;
> 
> PSOCKADDR_IN ipv4 = (PSOCKADDR_IN)pUnicast->Address.lpSockaddr;

**Comment by miniupnp** [comment]
fixed by 3e32ea04c8e7914689ad739e8430326870046f7e
