### ISSUE TITLE
Specify an upnp device

### ISSUE THREAD

**Issue by ccokee** [miniupnp/miniupnp#339]
My router has upnp enabled, but I'm connected to a wireless repeater so, when I run upnpc I get this:

```
upnpc : miniupnpc library test client. (c) 2005-2014 Thomas Bernard
Go to http://miniupnp.free.fr/ or http://miniupnp.tuxfamily.org/
for more information.
List of UPNP devices found on the network :
 desc: http://192.168.1.254:49152/wps_device.xml
 st: uuid:00000000-0000-1000-0000-f8d11199952f

 desc: http://192.168.1.254:49152/wps_device.xml
 st: upnp:rootdevice

UPnP device found. Is it an IGD ? : http://192.168.1.254:49152/
Trying to continue anyway
Local LAN ip address : 192.168.1.48
GetExternalIPAddress failed.
AddPortMapping(60130, 60130, 192.168.1.48) failed with code 401 (Invalid Action)
GetSpecificPortMappingEntry() failed with code 401 (Invalid Action)
```

And I cant do nothing about it, I would be nice to have an option to specify the Upnp device address. Thanks!

**Comment by miniupnp** [comment]
For some reason your router is not responding. We can do nothing about it...
Is your router on the same 192.168.1.x network ?

by the way, there is an option to _upnpc_ to specify the UPnP device address : _-u_

**Comment by ccokee** [comment]
I've been looking for the discovery mechanism of upnp, the thing would not be to use the url, but force the httpu message instead of broadcasting it. My router is in the same network, and other devices are using upnp, for some reason my repeater block those broadcast packets.
