### ISSUE TITLE
No IGD UPnP Device found

### ISSUE THREAD

**Issue by benni2108** [miniupnp/miniupnp#340]
When I try „upnpc -l“ on my RPi 2 it works fine.
When I try it on my RPi Zero W with the same sd-card I get an error
„No IGD Device found on the network!“.
The connection to the network is definitely working because I am able to ping to the router.
Any ideas what the problem could be?

**Comment by miniupnp** [comment]
Does your TCP/IP stack support multicast ?

**Comment by miniupnp** [comment]
use tcpdump/wireshark to see if your RPi Zero does receive the multicast packets. (SSDP)
