### ISSUE TITLE
log_daemon_msg: command not found

### ISSUE THREAD

**Issue by elisayys** [miniupnp/miniupnp#342]
when i do  
/etc/init.d/miniupnpd restart
/etc/init.d/miniupnpd: line 42: log_daemon_msg: command not found       anyone can help me ? thks very much!        operating  system is centos7.2

**Comment by miniupnp** [comment]
check your `/lib/lsb/init-functions` file. the script expect it to define _log_daemon_msg_

**Comment by elisayys** [comment]
cat /lib/lsb/init-functions
#!/bin/sh

# LSB initscript functions, as defined in the LSB Spec 1.1.0
#
# Lawrence Lim <llim@redhat.com> - Tue, 26 June 2007
# Updated to the latest LSB 3.1 spec
# http://refspecs.freestandards.org/LSB_3.1.0/LSB-Core-generic/LSB-Core-generic_lines.txt

start_daemon () {
        /etc/redhat-lsb/lsb_start_daemon "$@"
}

killproc () {
        /etc/redhat-lsb/lsb_killproc "$@"
}

pidofproc () {
        /etc/redhat-lsb/lsb_pidofproc "$@"
}

log_success_msg () {
        /etc/redhat-lsb/lsb_log_message success "$@"
}

log_failure_msg () {
        /etc/redhat-lsb/lsb_log_message failure "$@"
}

log_warning_msg () {
        /etc/redhat-lsb/lsb_log_message warning "$@"
}

log_daemon_msg () {
    # Dummy function to be replaced by LSB library.
 
    echo $@
}
log_progress_msg() {
    echo $@
}
log_end_msg () {
    # Dummy function to be replaced by LSB library.
 
    if test "$1" != "0"; then
      echo "Error with $DESCRIPTION: $NAME"
    fi
    return $1
}

i add    log_daemon_msg   functions  now it is ok  ,   but  new problem comes!

/etc/init.d/miniupnpd start
Starting miniupnpd miniupnpd
/etc/init.d/miniupnpd: line 32: start-stop-daemon: command not found  !
