### ISSUE TITLE
netfilter_nft/nftnlrdr.c:29:27: fatal error: libmnl/libmnl.h: No such file or directory

### ISSUE THREAD

**Issue by elisayys** [miniupnp/miniupnp#343]
when i excute , the problem comes !  
 make -f Makefile.linux_nft
cc -O -g  -fno-strict-aliasing -fno-common -Wall -Wextra -Wstrict-prototypes -Wdeclaration-after-statement -D_GNU_SOURCE  -c -o netfilter_nft/nftnlrdr.o netfilter_nft/nftnlrdr.c
netfilter_nft/nftnlrdr.c:29:27: fatal error: libmnl/libmnl.h: No such file or directory
 #include <libmnl/libmnl.h>
                           ^
compilation terminated.
make: *** [netfilter_nft/nftnlrdr.o] Error 1

there are too much problems  when i installing this , i'm going to give up !

**Comment by miniupnp** [comment]
The error is explicit : you are missing libmnl.

**Comment by FateEvent** [comment]
https://lore.kernel.org/all/727feddb9fdcbf6e74f68d783986a1bc83a50f54.1646195012.git.geliang.tang@suse.com/T/
