### ISSUE TITLE
Failed to start LSB: MiniUPnPd port-forwarding daemon

### ISSUE THREAD

**Issue by elisayys** [miniupnp/miniupnp#344]
when i excute , it fails 
/etc/init.d/miniupnpd restart
[....] Restarting miniupnpd (via systemctl): miniupnpd.serviceJob for miniupnpd.service failed. See 'systemctl status miniupnpd.service' and 'journalctl -xn' for details.
 failed!
root@CDS-SH-Debian001:~/miniupnp/miniupnpd# journalctl -xn
-- Logs begin at Wed 2019-01-09 14:40:38 CST, end at Wed 2019-01-09 15:39:51 CST. --
Jan 09 15:39:51 CDS-SH-Debian001 miniupnpd[28855]: -w sets the presentation url. Default is http address on port 80
Jan 09 15:39:51 CDS-SH-Debian001 miniupnpd[28855]: -A use following syntax for permission rules :
Jan 09 15:39:51 CDS-SH-Debian001 miniupnpd[28855]: (allow|deny) (external port range) ip/mask (internal port range)
Jan 09 15:39:51 CDS-SH-Debian001 miniupnpd[28855]: examples :
Jan 09 15:39:51 CDS-SH-Debian001 miniupnpd[28855]: "allow 1024-65535 192.168.1.0/24 1024-65535"
Jan 09 15:39:51 CDS-SH-Debian001 miniupnpd[28855]: "deny 0-65535 0.0.0.0/0 0-65535"
Jan 09 15:39:51 CDS-SH-Debian001 miniupnpd[28855]: -h prints this help and quits.
Jan 09 15:39:51 CDS-SH-Debian001 systemd[1]: miniupnpd.service: control process exited, code=exited status=1
Jan 09 15:39:51 CDS-SH-Debian001 systemd[1]: Failed to start LSB: MiniUPnPd port-forwarding daemon.
-- Subject: Unit miniupnpd.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit miniupnpd.service has failed.
-- 
-- The result is failed.
Jan 09 15:39:51 CDS-SH-Debian001 systemd[1]: Unit miniupnpd.service entered failed state.

**Comment by miniupnp** [comment]
you installed the debian package, right ?

**Comment by miniupnp** [comment]
debian package repository : https://salsa.debian.org/miniupnp-team/miniupnpd
please contact the debian package maintainer for such problem

**Comment by elisayys** [comment]
yes ，i use debian system , i start  it manually like this   
miniupnpd -f /etc/miniupnpd/miniupnpd.conf -i eth0 -d 
but it seems not stable !       
is this code for centos?  i install it in centos7 yesterday, there are to much problem , so i change to install it debian , and there are less problems , but still have fews, like this.   another is `
make -f Makefile.linux_nft
cc -O -g  -fno-strict-aliasing -fno-common -Wall -Wextra -Wstrict-prototypes -Wdeclaration-after-statement -D_GNU_SOURCE  -c -o netfilter_nft/nftnlrdr.o netfilter_nft/nftnlrdr.c
netfilter_nft/nftnlrdr.c:29:27: fatal error: libmnl/libmnl.h: No such file or directory
 #include <libmnl/libmnl.h>
                           ^
compilation terminated.
<builtin>: recipe for target 'netfilter_nft/nftnlrdr.o' failed
make: *** [netfilter_nft/nftnlrdr.o] Error 1`

**Comment by miniupnp** [comment]
you haven't answered the question.
You should use packages from your distribution.
