### ISSUE TITLE
miniupnpd incompatible with kernel 5.0

### ISSUE THREAD

**Issue by mooninite** [miniupnp/miniupnp#346]
Starting with kernel 5.0 the NFC defines that you are using have been removed.

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/include/uapi/linux/netfilter_ipv4.h?id=c3e9305983597a61083482581e83f0bd77ba306a

I am unable to build miniupnpd for Fedora Rawhide (Fedora 30), which now uses kernel 5.0.

Build logs:
https://kojipkgs.fedoraproject.org//work/tasks/8508/32438508/build.log
(beware, this log will be deleted after about 30 days)

**Comment by miniupnp** [comment]
Does it build with nftables ? `$ make -f Makefile.linux_nft`

**Comment by mooninite** [comment]
No it does not build with nftables. The nftables library has dropped some of the defines you're using there.

Your 6106111 commit does not fix this. NFC_UNKNOWN was also removed and the build fails:

`error: 'NFC_UNKNOWN' undeclared`

This error was already present in the original build log link I suppiled in my OP.

**Comment by miniupnp** [comment]
You're right, I'm sorry I focused on the kernel patch.
Do you know when NFC_UNKNOWN. It is still defined in the current iptables sources git://git.netfilter.org/iptables

**Comment by miniupnp** [comment]
https://git.netfilter.org/iptables/tree/include/linux/netfilter.h#n37

**Comment by miniupnp** [comment]
ok found : 
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/include/uapi/linux/netfilter.h?id=c3e9305983597a61083482581e83f0bd77ba306a

**Comment by mooninite** [comment]
Thanks for the quick fixes. We're compiling again. :)
