### ISSUE TITLE
TotalBytesReceived and TotalBytesSent do not rollover when reaching max

### ISSUE THREAD

**Issue by cbrherms** [miniupnp/miniupnp#349]
**Version:** 2.1

**Issue:**

TotalBytesReceived and TotalBytesSent are not rolling over to 0 when they reach 4294967295. Stays at 4294967295 and no longer updates.

Both packets functions are working correctly.

Noticed in freshtomato-arm using git snapshot of miniupnpd from 20181218 and also in tomato-shibby using version 2.0 of miniupnpd

**Comment by miniupnp** [comment]
are they supposed to roll over ?
I'm going to check the standard

**Comment by miniupnp** [comment]
Indeed they should roll over : http://upnp.org/specs/gw/UPnP-gw-WANCommonInterfaceConfig-v1-Service.pdf 2.2.9 2.2.10  2.2.11 2.2.12

> This variable represents the cumulativecounter for total number of bytes sent upstream across all connection service instances on WANDevice. The count rolls over to 0 after it reaching the maximum value (2^32) –1

**Comment by miniupnp** [comment]
@cbrherms however the rollover is already implemented, but only enabled when building in "strict" mode.
https://github.com/miniupnp/miniupnp/blob/master/miniupnpd/upnpsoap.c#L126

add option ` --strict`  to genconfig.sh or ` CONFIG_OPTIONS="--strict" make -f Makefile.linux`

**Comment by miniupnp** [comment]
The linux version uses `strtoul()` to read the value from ` /proc/net/dev`. `strtoul()` returns ULONG_MAX when the value would overflow...

https://github.com/miniupnp/miniupnp/blob/master/miniupnpd/linux/getifstats.c#L83

@cbrherms  could you tell me : 
- if your linux system is 32 or 64bits
- paste a dump of ` /proc/net/dev`
