### ISSUE TITLE
socklen_t type in MSC

### ISSUE THREAD

**Issue by irwir** [miniupnp/miniupnp#350]
MSC uses `socklen_t` type instead of `size_t` for the second parameter of `getnameinfo` call (`ai_addrlen` structure member).
The suggestion is ~to change definition of `MSC_CAST_INT` and~ to add the missing type cast into the line https://github.com/miniupnp/miniupnp/blob/3e32ea04c8e7914689ad739e8430326870046f7e/miniupnpc/minissdpc.c#L826

**Comment by miniupnp** [comment]
What is the error/warning message you get ? which version of MSC do you use ?
I have just tried with MS VC++ 2010. No warning.

Here what's in ws2def.h :
```
//
//  Structure used in getaddrinfo() call
//

typedef struct addrinfo
{
    int                 ai_flags;       // AI_PASSIVE, AI_CANONNAME, AI_NUMERICHOST
    int                 ai_family;      // PF_xxx
    int                 ai_socktype;    // SOCK_xxx
    int                 ai_protocol;    // 0 or IPPROTO_xxx for IPv4 and IPv6
    size_t              ai_addrlen;     // Length of ai_addr
    char *              ai_canonname;   // Canonical name for nodename
    __field_bcount(ai_addrlen) struct sockaddr *   ai_addr;        // Binary address
    struct addrinfo *   ai_next;        // Next structure in linked list
}
ADDRINFOA, *PADDRINFOA;
```

**Comment by irwir** [comment]
That was an incorrect statement in the first message, and it was changed.

Currently I am using VS 2017, but the warning probably came from static analysis.
According to [this topic's](https://www.linuxquestions.org/questions/programming-9/invalid-conversion-from-`int*'-to-`socklen_t*'-145992/) dates, `socklen_t` is an old invention.

And, speaking of static analysis: the line 644 should be `goto error;` to avoid resource leak.

**Comment by irwir** [comment]
Changing lines 742-743 would cut some bytes from the code size.
