### ISSUE TITLE
[feature request] clean up mapping of IPs no longer in ARP table.

### ISSUE THREAD

**Issue by enihcam** [miniupnp/miniupnp#355]
After 2 days of one of my devices disconnected from LAN, the upnp mapping still exists in iptables.
It would be great if miniupnpd could have a background job for cleaning up the mappings of IPs no longer in ARP table. Thanks.

**Comment by miniupnp** [comment]
it has. But it is triggerred only when the number of mapping is above a limit.
see https://github.com/miniupnp/miniupnp/blob/master/miniupnpd/miniupnpd.conf#L117
