### ISSUE TITLE
Import error on Windows

### ISSUE THREAD

**Issue by antoinepikcio** [miniupnp/miniupnp#356]
Hello!

After installing the build of the latest version on AppVeyor (2.1.456), I got an error when I try to import the miniupnpc Python library.

Here is the error:
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
ImportError: DLL load failed: The specified module could not be found.
```

I tried to place the miniupnc.dll file in the Python 2.7 DLLs folder and also in the current directory.

**Comment by miniupnp** [comment]
you should use a tool to find which are the DLL dependencies of the python module.

**Comment by NathanRichard** [comment]
I have successfully used the software [dependencies](https://github.com/lucasg/Dependencies) on the Upnpc python module.
You first need to open the egg file (with 7z for instance) and open the .pyd file using dependencies.
![Dependances_Egg_Py27](https://user-images.githubusercontent.com/1778774/56797718-9b436d00-6815-11e9-9d48-8ce4915252a0.png)

**Comment by miniupnp** [comment]
@antoinepikcio can you check the dependencies ?

**Comment by chwba** [comment]
How did you achieve to install this?

**Comment by mrx23dot** [comment]
These are the deps on win10 x64
![2021-10-05 11_21_29-Dependencies](https://user-images.githubusercontent.com/4163396/136005517-0c854651-4bf5-40de-b1bd-d43f2ad5c73f.jpg)

I think **miniupnpc.dll** is not part of the pre-built installation.

Should be built by:
```
miniupnpc/Makefile
ifeq ($(JARSUFFIX), win32)
  SHAREDLIBRARY = $(BUILD)/miniupnpc.dll
```
