### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by XmiliaH** [miniupnp/miniupnp#357]
If you send a packet with multiple NewPortListing Tags then, at least in miniupnpd, only the last one will be freed. The problem is in [NameValueParserGetData](https://github.com/miniupnp/miniupnp/blob/master/miniupnpd/upnpreplyparse.c#L81)
```C
static void
NameValueParserGetData(void * d, const char * datas, int l)
{
    struct NameValueParserData * data = (struct NameValueParserData *)d;
	if(strcmp(data->curelt, "NewPortListing") == 0)
	{
		/* specific case for NewPortListing which is a XML Document */
		data->portListing = malloc(l + 1);  // XXX will override the old value without releasing it.
		if(!data->portListing)
		{
```

**Comment by miniupnp** [comment]
thank you for the report !

**Comment by XmiliaH** [comment]
No problem. Don't forget to fix it in miniupnpc too, looks like it's the same there:
https://github.com/miniupnp/miniupnp/blob/master/miniupnpc/upnpreplyparse.c#L81
