### ISSUE TITLE
Add redirect for other LAN IP gives "AddPortMapping(5556, 5556, 192.168.1.1) failed with code 718 (ConflictInMappingEntry)"

### ISSUE THREAD

**Issue by sanderjo** [miniupnp/miniupnp#359]
Redirecting a port to another host gives

```
AddPortMapping(5556, 5556, 192.168.1.1) failed with code 718 (ConflictInMappingEntry)
```
It works OK if I redirect to the host from which I'm running upnpc. So the `ConflictInMappingEntry` is not true

So, hypothesis: the router (a Genexis Platinum fiber device) is **refusing** the call because it's from another device? In other words: only port redirects for 'yourself' / to yourself are accepted by the router?

If so: 
1) is the router doing something valid (refusing the request)?
2) can/should the error message by UPnP be a bit different?

FWIW: https://tools.ietf.org/html/rfc6970#section-4.3 says 

>    2 NOT_AUTHORIZED:  IGD:1 718 "ConflictInMappingEntry" / IGD:2 606
>       "Action not authorized"

I get the "718 ConflictInMappingEntry", but the "606 Action not authorized" sounds more logical to me.
I'll try to find the actual answer from the router using wireshark.

Trying port forwarderd for another host gives an error:
```
$ ./upnpc-static -a 192.168.1.1 5556 5556  tcp
upnpc : miniupnpc library test client, version 2.1.
 (c) 2005-2018 Thomas Bernard.
Go to http://miniupnp.free.fr/ or https://miniupnp.tuxfamily.org/
for more information.
List of UPNP devices found on the network :
 desc: http://192.168.1.217:80/description.xml
 st: urn:schemas-upnp-org:device:basic:1

 desc: http://192.168.1.217:80/description.xml
 st: uuid:2f402f80-da50-11e1-9b23-001788721f4f

 desc: http://192.168.1.217:80/description.xml
 st: upnp:rootdevice

 desc: http://192.168.1.254:5000/rootDesc.xml
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

Found valid IGD : http://192.168.1.254:5000/ctl/IPConn
Local LAN ip address : 192.168.1.3
ExternalIPAddress = 163.158.9.2
AddPortMapping(5556, 5556, 192.168.1.1) failed with code 718 (ConflictInMappingEntry)

```

For the system itself (on which upnpc is running) goes OK:

```
$ ./upnpc-static -a 192.168.1.3 5556 5556  tcp
upnpc : miniupnpc library test client, version 2.1.
 (c) 2005-2018 Thomas Bernard.
Go to http://miniupnp.free.fr/ or https://miniupnp.tuxfamily.org/
for more information.
List of UPNP devices found on the network :
 desc: http://192.168.1.217:80/description.xml
 st: urn:schemas-upnp-org:device:basic:1

 desc: http://192.168.1.217:80/description.xml
 st: uuid:2f402f80-da50-11e1-9b23-001788721f4f

 desc: http://192.168.1.217:80/description.xml
 st: upnp:rootdevice

 desc: http://192.168.1.254:5000/rootDesc.xml
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

Found valid IGD : http://192.168.1.254:5000/ctl/IPConn
Local LAN ip address : 192.168.1.3
ExternalIPAddress = 163.158.9.2
InternalIP:Port = 192.168.1.3:5556
external 163.158.9.2:5556 TCP is redirected to internal 192.168.1.3:5556 (duration=0)


```

**Comment by miniupnp** [comment]
I guess you enabled the so called "secure mode" on the router.
https://github.com/miniupnp/miniupnp/blob/master/miniupnpd/miniupnpd.conf#L100

Indeed the error returned is 718
https://github.com/miniupnp/miniupnp/blob/master/miniupnpd/upnpsoap.c#L541
with `AddAnyPortMapping` it is 606
https://github.com/miniupnp/miniupnp/blob/master/miniupnpd/upnpsoap.c#L675

I'm not sure why `AddPortMapping` doesn't return 606.This error code may have been introduced in IGDv2

**Comment by miniupnp** [comment]
error code 606 was indeed added in IGDv2. Compare http://upnp.org/specs/gw/UPnP-gw-WANIPConnection-v1-Service.pdf and http://upnp.org/specs/gw/UPnP-gw-WANIPConnection-v2-Service.pdf
@sanderjo as your IGD version is 1, this is OK

**Comment by sanderjo** [comment]
> I guess you enabled the so called "secure mode" on the router.

If it's enabled, it's done so by the manufacturer Genexis; I even can't find such an option in the Genexis' UI.

I still have to fire up wireshark to see the exact response.

Thanks for your reply.

**Comment by sanderjo** [comment]
Wireshark analysis confirms that the GENEXIS is indeed saying "718", so upnpc is reporting it correctly, and the 'problem' is in the GENEXIS (being strict ... which I can't change in the GENEXIS).

(Fun fact: The GENXIS is also running MiniUPnPd)


Method used in Wireshark:
First apply display filter in Wireshark: tcp and frame contains "718"
Then on the found frame: Follow -> TCP Stream


My ubuntu system talking to Genexis
```
POST /ctl/IPConn HTTP/1.1
Host: 192.168.1.254:5000
User-Agent: Ubuntu/17.10, UPnP/1.1, MiniUPnPc/2.0
Content-Length: 595
Content-Type: text/xml
SOAPAction: "urn:schemas-upnp-org:service:WANIPConnection:1#AddPortMapping"
Connection: Close
Cache-Control: no-cache
Pragma: no-cache

<?xml version="1.0"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
<s:Body><u:AddPortMapping xmlns:u="urn:schemas-upnp-org:service:WANIPConnection:1">
<NewRemoteHost></NewRemoteHost>
<NewExternalPort>5556</NewExternalPort><NewProtocol>TCP</NewProtocol>
<NewInternalPort>5556</NewInternalPort><NewInternalClient>192.168.1.120</NewInternalClient>
<NewEnabled>1</NewEnabled>
<NewPortMappingDescription>libminiupnpc</NewPortMappingDescription>
<NewLeaseDuration>0</NewLeaseDuration></u:AddPortMapping></s:Body></s:Envelope>
```


Response from GENEXIS:
```
HTTP/1.1 500 Internal Server Error
Content-Type: text/xml; charset="utf-8"
Connection: close
Content-Length: 406
Server: OpenWRT/OpenWrt UPnP/1.1 MiniUPnPd/2.0
Ext:

<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
<s:Body><s:Fault><faultcode>s:Client</faultcode>
<faultstring>UPnPError</faultstring><detail>
<UPnPError xmlns="urn:schemas-upnp-org:control-1-0">
<errorCode>718</errorCode><errorDescription>ConflictInMappingEntry</errorDescription>
</UPnPError></detail></s:Fault></s:Body></s:Envelope>
```

**Comment by miniupnp** [comment]
It confirms that everything works fine.
