### ISSUE TITLE
Problem while installing miniupnpd

### ISSUE THREAD

**Issue by bishneet** [miniupnp/miniupnp#36]
When I am trying command, make -f Makefile.linux, I am getting this error:

linux/getroute.c:19:39: fatal error: libnfnetlink/libnfnetlink.h: No such file or directory
compilation terminated.
make: **\* [linux/getroute.o] Error 1

Also, I am not able to find any folder named libfnetlink. Can you help?

**Comment by elisayys** [comment]
[root@CDS-SH-Boluo-test miniupnpd]# make -f Makefile.linux
please install uuid-dev package / libuuid
cc -Os -fno-strict-aliasing -fno-common -Wall -Wextra -Wstrict-prototypes -Wdeclaration-after-statement -D_GNU_SOURCE  -c -o netfilter/iptcrdr.o netfilter/iptcrdr.c
netfilter/iptcrdr.c:17:21: fatal error: xtables.h: No such file or directory
 #include <xtables.h>
                     ^
compilation terminated.
make: *** [netfilter/iptcrdr.o] Error 1

i am facing this problem ,  anyone can help me ? thks!

**Comment by miniupnp** [comment]
https://github.com/miniupnp/miniupnp/blob/master/miniupnpd/INSTALL#L70

**Comment by elisayys** [comment]
i just according this to install ,  
- Build the daemon
  > make -f Makefile.linux   when i do this  the problem comes !

**Comment by miniupnp** [comment]
@elisayys RTFM
