### ISSUE TITLE
upnpc-static port mapping success,but the ExternalIPAddress error

### ISSUE THREAD

**Issue by zhengchengbin610** [miniupnp/miniupnp#360]
I  use the miniupnpc lib, and test use the upnpc-static program, I use follow command:
 ./upnpc-static -a 192.168.0.155 8080 20000 TCP
the result is  the attachment file
![IE7NYAUEO 2_ZW 7N`R~%ET](https://user-images.githubusercontent.com/26518131/55702122-2a741680-5a08-11e9-871d-eb561e5898ab.png)

I  find the ExternalIpAddress always error ,Why?  whether my command is incorrect? please help me ,thanks.

**Comment by miniupnp** [comment]
everything seems to work fine according to your screenshot.

**Comment by zhengchengbin610** [comment]
@miniupnp but the ExtennalIPAddress is error ,the IP is not the  internet ip , and  I  access the router wanip to the extend port are timeout

**Comment by miniupnp** [comment]
> @miniupnp <https://github.com/miniupnp> but the ExtennalIPAddress is
> error ,the IP is not the internet ip , and I access the router wanip
> to the extend port are timeout
>
That's bug from your router, not from miniupnpc

Please contact your router manufacturer

**Comment by zhengchengbin610** [comment]
Thanks , I  will check this with the router manufacturer
