### ISSUE TITLE
miniupnpd on pfsense ... possible bug?

### ISSUE THREAD

**Issue by wangel** [miniupnp/miniupnp#365]
Running PFSense version 2.4.4-Release-P2. I've posted on pfsense's subreddit, but haven't gotten much help/feedback.

I'm sitting miniupnp up for my consoles, a ps4 and xbox one. I'm 99% sure I have it configured it correctly. Below is my current config file:

Code:
`ext_ifname=em0`
`port=2189`
`listening_ip=em1`
`ext_ip=111.111.111.111`
`system_uptime=yes`
`secure_mode=yes`
`presentation_url=https://192.168.1.1/`
`uuid=c83b93ee-af03-59ef-10a2-51d68ba3272`
`serial=C83B93EE`
`model_number=1.1`
`allow 1024-65535 192.168.1.25/32 1024-65535`
`allow 1024-65535 192.168.1.27/32 1024-65535`
`allow 1024-65535 192.168.1.28/32 1024-65535`
`allow 1024-65535 192.168.1.31/32 1024-65535`
`deny 0-65535 0.0.0.0/0 0-65535`
`enable_upnp=yes`
`enable_natpmp=yes`

Please note that 111.111.111.111 is not my public ip, however I do have my REAL public ip in the config file. I've also tried it without the ext_ip setting.

I can stop the service, restart it ... and it then test the consoles, and they work fine, however after a bit of time, I start seeing this in my log file:

Code:	

`Apr 16 03:31:10    miniupnpd    48827    SendNATPMPPublicAddressChangeNotification: sendto(s_udp=10, port=5351): No route to host`
`Apr 16 03:31:10    miniupnpd    48827    PCPSendUnsolicitedAnnounce() sendto(): No route to host`
`Apr 16 03:31:10    miniupnpd    48827    PCPSendUnsolicitedAnnounce() IPv6 sendto(): Bad file descriptor`
`Apr 16 03:31:10    miniupnpd    48827    SendNATPMPPublicAddressChangeNotification: sendto(s_udp=10, port=5351): No route to host`
`Apr 16 03:31:10    miniupnpd    48827    PCPSendUnsolicitedAnnounce() sendto(): No route to host`
`Apr 16 03:31:10    miniupnpd    48827    PCPSendUnsolicitedAnnounce() IPv6 sendto(): Bad file descriptor`
`Apr 16 03:31:10    miniupnpd    48827    SendNATPMPPublicAddressChangeNotification: sendto(s_udp=10, port=5351): No route to host`
`Apr 16 03:31:10    miniupnpd    48827    PCPSendUnsolicitedAnnounce() sendto(): No route to host`
`Apr 16 03:31:10    miniupnpd    48827    PCPSendUnsolicitedAnnounce() IPv6 sendto(): Bad file descriptor`
`Apr 16 03:31:10    miniupnpd    48827    SendNATPMPPublicAddressChangeNotification: sendto(s_udp=10, port=5351): No route to host`
`Apr 16 03:31:10    miniupnpd    48827    PCPSendUnsolicitedAnnounce() sendto(): No route to host`
`Apr 16 03:31:10    miniupnpd    48827    PCPSendUnsolicitedAnnounce() IPv6 sendto(): Bad file descriptor`

This repeats about every 6 seconds ... When this is happening, upnp doesn't work at all .... if I clear the map table and test the consoles, they do not open ports as expected etc.

I suspect this is because my cable modem drops for a few seconds, just enough to weird miniupnp out and it gets stuck in a loop? I'm not sure.

I have ipv6 turned off in pfsense. My isp doesn't give me an ipv6, so I have the sitting to block ipv6 in pfsense turned ON.... Maybe this is the issue?

"Allow IPV6" All IPv6 traffic will be blocked by the firewall unless this box is checked NOTE: This does not disable any IPv6 features on the firewall, it only blocks traffic.

The box is NOT CHECKED

Any help would be greatly appreciated.

Thank you!

~wangel

**Comment by miniupnp** [comment]
the NAT-PMP public address changes notifications are sent to 224.0.0.1 on all the "LAN" network interfaces (em1 for you)
are you sure the multicast traffic is not blocked by something ?

**Comment by wangel** [comment]
Not to my knowledge --- It's a default pfsense install.  I don't have a lan rule blocking multicast.  Hmmmm

**Comment by azdps** [comment]
wangel try removing the following line from your config file:

ext_ip=111.111.111.111

Please report back to see if you are still seeing the errors in your log file.

**Comment by wangel** [comment]
I've tried it both ways azdps ... I originally put the ext_ip setting in my config file to try and stop it from notifying of an address change.

Still broken =(

**Comment by azdps** [comment]
Not sure then but I think the following information might be helpful.

- What version of miniupnpd are you using?
- Is your miniupnpd.conf file automatically generated from the pfsense webui upnp settings or did you manually configure it from the shell?
- Did you put an anchor in your pf.conf file?
- Are you using outbound static ports for your console IP addresses?

**Comment by wangel** [comment]
Unsure of what version.  miniupnpd -v or --version doesn't do anything.  -h just prints the help, no version information.   I am running the latest version of pfsense (2.4.4-RELEASE-p2 (amd64)) so I assume it has a newer or newest miniupnpd ... I will have to dig into it deeper.

Yes, it is automatically generated by the gui.
There is no anchor in my pf.conf file.
Yes, I am using outbound static ports for my console ips.  They are assigned static ips via dhcp.

I will try adding the below suggestions and let you.

Thank you!

**Comment by azdps** [comment]
This is obviously a NAT-PMP related issue but probably not a bug. Couple of other things I would like to add.

You probably won't see the miniupnp anchor in your firewall rules or nat page in the pfsense webui. You need to check your pf rules and nat from the command line. More than likely when you installed the miniupnp package pfsense automatically added the anchors. To check if you have the 2 required anchors using the command "pfctl -s rules" and "pfctl -s nat" from the shell. You should see an miniupnp anchor for both pf rules and nat.

Here's a quote from the freebsd miniupnp package reference the above anchors:

> For this daemon to work, you must modify your pf rules to add an anchor
> in both the NAT and rules section.  Both must be called 'miniupnpd'.
> Example:
> 
> # NAT section
> # UPnPd rdr anchor
> rdr-anchor "miniupnpd"
> 
> # Rules section
> # uPnPd rule anchor
> anchor "miniupnpd"

Check the pfsense [UPnP & NAT-PMP doc](https://docs.netgate.com/pfsense/en/latest/book/services/upnp-and-nat-pmp.html). At the very bottom there is a troubleshooting section which mentions multicast traffic. This could possibly be the issue.

Also do you need to use NAT-PMP which will allow apple devices to punch holes through your pfsense firewall? If you are using miniupnp for gaming (Xbox & PS4) NAT-PMP is not necessary and I would disable it.

**Comment by wangel** [comment]
Here's the result of the 2 pfctl commands;

`[2.4.4-RELEASE][admin@fw.areality.local]/root: pfctl -s rules | grep anchor
anchor "relayd/*" all
anchor "openvpn/*" all
anchor "ipsec/*" all
anchor "userrules/*" all
anchor "tftp-proxy/*" all
anchor "miniupnpd" all
[2.4.4-RELEASE][admin@fw.areality.local]/root: pfctl -s nat | grep anchor
nat-anchor "natearly/*" all
nat-anchor "natrules/*" all
rdr-anchor "relayd/*" all
rdr-anchor "tftp-proxy/*" all
rdr-anchor "miniupnpd" all
`
I've read the troubleshooting ... but my question is, this is LAN multicast traffic, it should never be blocked by the firewall.  As far as I can tell, it's not.  The only thing showing blocked for UDP on 1900 is ipv6 traffic.

How can I tell what version of miniupnpd I have?  pfsense installs it by default, you don't have to install it as a package. 

Thanks for all the help... I really appreciate it.

**Comment by azdps** [comment]
I'm not aware of a miniupnpd command that you can determine which version you are using. I looked at the pfsense source code but couldn't determine which version they were using because they reference a 2017 version in one of their files but they also have freebsd ports which is in sync with the official freebsd ports. That version is dated Feb 2nd 2019. Try this command from the root directory:

find . | grep miniupnp

The above command produced the following output for me from the shell in OPNsense which shows which version OPNsense is using - miniupnpd-2.0.20180503.

```
root@OPNsense:/ # find . | grep miniupnp
./usr/local/man/man8/miniupnpd.8.gz
./usr/local/etc/miniupnpd.conf.sample
./usr/local/etc/rc.d/miniupnpd
./usr/local/etc/inc/plugins.inc.d/miniupnpd.inc
./usr/local/share/licenses/miniupnpd-2.0.20180503,1
./usr/local/share/licenses/miniupnpd-2.0.20180503,1/LICENSE
./usr/local/share/licenses/miniupnpd-2.0.20180503,1/catalog.mk
./usr/local/share/licenses/miniupnpd-2.0.20180503,1/BSD3CLAUSE
./usr/local/sbin/miniupnpd
./var/etc/miniupnpd.conf
./var/run/miniupnpd.pid
./var/cache/pkg/miniupnpd-2.0.20180503,1-4296df6fdf.txz
./var/cache/pkg/miniupnpd-2.0.20180503,1.txz
```

**Comment by miniupnp** [comment]
`# strings $(miniupnpd) | grep SERVER`
can give you a hint on which version of miniupnpd is installed.

**Comment by azdps** [comment]
[miniupnp](https://github.com/miniupnp) I had to change the command for it to work on FreeBSD (OPNsense). The command provided the following information.

```
root@OPNsense:/usr/local/sbin # strings miniupnpd | grep SERVER
SERVER: FreeBSD/11.2--HBSD UPnP/1.1 MiniUPnPd/2.0
SERVER: FreeBSD/11.2--HBSD UPnP/1.1 MiniUPnPd/2.0
```
For me, using the find command provided a little more details about the specific build.
```
root@OPNsense:/ # find . | grep miniupnp
./usr/local/man/man8/miniupnpd.8.gz
./usr/local/etc/miniupnpd.conf.sample
./usr/local/etc/rc.d/miniupnpd
./usr/local/etc/inc/plugins.inc.d/miniupnpd.inc
./usr/local/share/licenses/miniupnpd-2.0.20180503,1
./usr/local/share/licenses/miniupnpd-2.0.20180503,1/LICENSE
./usr/local/share/licenses/miniupnpd-2.0.20180503,1/catalog.mk
./usr/local/share/licenses/miniupnpd-2.0.20180503,1/BSD3CLAUSE
./usr/local/sbin/miniupnpd
./var/etc/miniupnpd.conf
./var/run/miniupnpd.pid
./var/cache/pkg/miniupnpd-2.0.20180503,1-4296df6fdf.txz
./var/cache/pkg/miniupnpd-2.0.20180503,1.txz
```
[wangel](wangel) can you try adding a default pass all rule for all LAN traffic under Firewall -> Rules -> LAN. Maybe that might help.

**Comment by CV8R** [comment]
Hi, I've been trying to track this down for a long time. See many posts at pfsense and opnsense. All point back to the same problem. No real workaround exists that I've found.

See comment #3 @ pfsense issue list here:

https://redmine.pfsense.org/issues/7727#change-41170

**Comment by azdps** [comment]
Apparently this issue is related to playing the same game at the same time on your gaming consoles. I have yet to test this scenario. I'm wondering if running miniupnpd in debug mode might provide more insight into the issue. I use the following command in opnsense to run miniupnpd in debug mode:

/usr/local/sbin/miniupnpd -f /var/etc/miniupnpd.conf -d -P /var/run/miniupnpd.pid

CV8R are you also seeing "PCPSendUnsolicitedAnnounce" in your log file similar to what wangel posted above?

**Comment by FingerlessGlov3s** [comment]
> Apparently this issue is related to playing the same game at the same time on your gaming consoles. I have yet to test this scenario. I'm wondering if running miniupnpd in debug mode might provide more insight into the issue. I use the following command in opnsense to run miniupnpd in debug mode:
> 
> `/usr/local/sbin/miniupnpd -f /var/etc/miniupnpd.conf -d -P /var/run/miniupnpd.pid`
> 
> CV8R are you also seeing "PCPSendUnsolicitedAnnounce" in your log file similar to what wangel posted above?

What issues are you getting in OPNsense? Any PC game I try are unable to open UPNP port.

My friends with routers from their ISP's get not issue, so its definitively something with OPNsense or MINIUPNPD config.

**Comment by ngpb** [comment]
Hello,

For any suspected bug in pfSense, I recommend testing on the latest stable version. There is always the possibility it has been fixed if you are not testing on the latest.

Currently 2.4.4-p3 is the latest stable, if you are able to verify and replicate the issue on that version, please submit a detailed bug report directly at:
https://redmine.pfsense.org/projects/pfsense

Thank you

**Comment by Firetop** [comment]
> Hello,
> 
> For any suspected bug in pfSense, I recommend testing on the latest stable version. There is always the possibility it has been fixed if you are not testing on the latest.
> 
> Currently 2.4.4-p3 is the latest stable, if you are able to verify and replicate the issue on that version, please submit a detailed bug report directly at:
> https://redmine.pfsense.org/projects/pfsense
> 
> Thank you

Hello,

The bug was reported 3 years ago in Pfsense as found here: https://redmine.pfsense.org/issues/7727, we are trying to get a miniupnpd port of the latest commits found here: https://github.com/miniupnp/miniupnp/commit/e49d44f700355552c45a95c1e067e4a815479557
