### ISSUE TITLE
Add command to check version number

### ISSUE THREAD

**Issue by azdps** [miniupnp/miniupnp#370]
I would be great if miniupnpd had a command such as mininupnpd -v or -version  so that users can determine the exact version that is installed on their system. I've seen posts on numerous forums over the years asking what version is installed on a firewall, wireless router, etc. Would this be possible to implement?

**Comment by miniupnp** [comment]
@azdps the version is written to syslog when starting.

**Comment by miniupnp** [comment]
I think the version should be more precise.
ie _2.1.20190502_ instead of just _2.1_

**Comment by azdps** [comment]
I would like to see a a versioning system similar or exactly like Apache uses:

http://commons.apache.org/releases/versioning.html

I don't think version should ever just be just 2.1. So for example when 2.2 first comes out the version would be something like 2.2.0. Again see Apache link for an in dept explanation.
