### ISSUE TITLE
Nftables in miniupnpd (new problem)

### ISSUE THREAD

**Issue by rtorrentuser** [miniupnp/miniupnp#383]
The binary, that I compiled when @svenauhagen finally fixed issue #380 (see the discussion), is still working perfectly adding and removing the rules as expected. But today I recompiled the binary from git (after pull request #381 was merged) and now the rules are not added at all. The debug output says 'mnl_cb_run: No such file or directory.  Returning UPnPError 501: ActionFailed'. Very strange...
[debug output-2.txt](https://github.com/miniupnp/miniupnp/files/3343126/debug.output-2.txt)

**Comment by svenauhagen** [comment]
Hi,

that error means there is a problem with either the chains or the rule that is being generated. 
How does your rule set look like?
Are you using the script from git to setup the chains?

**Comment by svenauhagen** [comment]
Ah I see where I made a mistake. Sorry I will need to make another fix here

**Comment by rtorrentuser** [comment]
> Are you using the script from git to setup the chains?
Hi, @svenauhagen!
Yes, I'm using your scripts. What surprised me most is that the old binary that I compiled from your sources when you finally found the solution for #380 is still working fine, and the new one gives this error. The script are the same in both cases.

**Comment by svenauhagen** [comment]
Alright I set the wrong chain when committing the fix.
This branch should fix it:

https://github.com/svenauhagen/miniupnp/tree/fixes/nftables

Can you try it again?
Thank you for testing!

**Comment by rtorrentuser** [comment]
> Can you try it again?

Error fixed!

> Thank you for testing!

Thanks for your efforts and prompt replies!

**Comment by svenauhagen** [comment]
@rtorrentuser 
great, thank you for reporting this.
I just added the PR to fix this in the branch.
