### ISSUE TITLE
how two device use same internal port?

### ISSUE THREAD

**Issue by PHCSJC** [miniupnp/miniupnp#385]
HI,I have two same devices,and they request use same internal port to miniupnpd.
But,miniupnpd use iptables add two same external port for them.
in result,one device can't success use external port,only another device can success.
what can I config? in order to two device use same internal same,and miniupnpd give them different external port.
thanks!

**Comment by miniupnp** [comment]
please show the two AddPortMapping() requests in the logs.
start miniupnpd in debug mode if you need more logs

**Comment by miniupnp** [comment]
no feedback. closing
