### ISSUE TITLE
where is README.openwrt file

### ISSUE THREAD

**Issue by Cathgao** [miniupnp/miniupnp#387]

**Comment by miniupnp** [comment]
nowhere !
Why this question ?

**Comment by Cathgao** [comment]
I want to compile for OpenWRT, in https://miniupnp.tuxfamily.org/files/ it says:

> To compile for OpenWRT please read the README.openwrt file.

 But I can't find it anywhere

**Comment by miniupnp** [comment]
Well this is outdated information.
I have to update the website.

just use the official OpenWrt package :
https://github.com/openwrt/packages/tree/master/net/miniupnpd
