### ISSUE TITLE
Port forwarding fails with error 606 from router

### ISSUE THREAD

**Issue by adolfintel** [miniupnp/miniupnp#392]
I recently downloaded Warzone 2100, which uses miniupnpc, and I noticed that it couldn't open port 2100 on my FritzBox 3470 despite UPnP being enabled.

I know for sure that UPnP works fine on my router because I developed a [UPnP library ](https://github.com/adolfintel/WaifUPnP) for Java and it works fine. I don't know why miniupnp does not.

I investigated the problem a bit and this is what happens when the game tries to open the port:
![image](https://user-images.githubusercontent.com/16307689/63451017-94370f00-c443-11e9-9e37-da91d36b16b5.png)

Link to the original issue: https://github.com/Warzone2100/warzone2100/issues/476

**Comment by miniupnp** [comment]
606 is the error code for "Action Unauthorized"
Are you sure le port 2100 is free ? and that 192.168.1.199 is the IP of the machine.

What's the list of the current portmappings ?

**Comment by adolfintel** [comment]
These are the current port mappings:
![image](https://user-images.githubusercontent.com/16307689/63491307-25939900-c4b7-11e9-834a-a0838a6e7e24.png)

As far as I can tell, nothing is using port 2100. I really don't know why it can't open it.

**Comment by miniupnp** [comment]
can you open a port mapping on port 2100 with another UPnP IGD client ?

**Comment by miniupnp** [comment]
if that work, you could then compare the 2 SOAP requests.

**Comment by adolfintel** [comment]
It seems that this 606 error pops up on a bunch of random ports, not just 2100. I'll ask the router manufacturer, maybe it's a bug introduced in the update that came out a few days ago.
