### ISSUE TITLE
miss a ip6tc_free in ip6tc_init_verify_append

### ISSUE THREAD

**Issue by poyu** [miniupnp/miniupnp#393]
if(!ip6tc_commit(h)) {
		syslog(LOG_ERR, "ip6tc_commit() error : %s", ip6tc_strerror(errno));
		goto error;
	}
	return 0;	/* ok */

dosen't it require an ip6tc_free before return?
it seems to become file descriptor leakage.

**Comment by miniupnp** [comment]
indeed.
