### ISSUE TITLE
`-4` switch for using only IPv4

### ISSUE THREAD

**Issue by abbradar** [miniupnp/miniupnp#396]
Cross-post from [the forum](https://miniupnp.tuxfamily.org/forum/viewtopic.php?t=2387), sorry - I didn't notice there is Github page too.

I have dual-stack network and want to redirect TCP port to my IPv4 address, but I cannot do this currently: 

```
$ upnpc -r 7778 tcp   
upnpc : miniupnpc library test client, version 2.1.
 (c) 2005-2019 Thomas Bernard.
Go to http://miniupnp.free.fr/ or https://miniupnp.tuxfamily.org/
for more information.
List of UPNP devices found on the network :
 desc: http://192.168.72.1:5000/rootDesc.xml
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

 desc: http://<my_router_ipv6>:5000/rootDesc.xml
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

Found valid IGD : http://192.168.72.1:5000/ctl/IPConn
Local LAN ip address : <my_ipv6>
ExternalIPAddress = <my_external_ipv4>
AddPortMapping(7778, 7778, <my_ipv6>) failed with code 402 (Invalid Args)
```

 It'd be nice to have -4 switch to force using my local IPv4 address instead. Or maybe I'm missing something?

**Comment by miniupnp** [comment]
Well I think the -4 option is not needed, because -r is for adding a mapping, so it is IPv4 only...

**Comment by abbradar** [comment]
True. I guess instead we should make `-r`, `-N`, `-n` etc use ipv4 by default.

**Comment by miniupnp** [comment]
@abbradar could you update to commit 5f85321 and perform the following test please ?
```
$ make clean
$ CFLAGS=-DDEBUG gmake testminiwget
$ ./testminiwget http://192.168.72.1:5000/rootDesc.xml /dev/null
```
Also what is the OS you are running ?

**Comment by miniupnp** [comment]
@abbradar never mind, I think I understood the problem. It was a bug in `UPNP_GetValidIGD()`.
Could you confirm that commit c281839 fixes the problem ?

**Comment by abbradar** [comment]
Sure! At the end of the week though, at a vacation now without IPv6 connectivity.

**Comment by miniupnp** [comment]
@abbradar are you back ? ;)

**Comment by abbradar** [comment]
Sorry, I had my passport stolen so I'm at involuntary vacation extension till 28th :D

**Comment by miniupnp** [comment]
that's bad luck. Enjoy your prolonged bread !

**Comment by abbradar** [comment]
Tested, confirm it works!
