### ISSUE TITLE
Lease duration isn't set properly

### ISSUE THREAD

**Issue by psibi** [miniupnp/miniupnp#398]
My co-worker has the following router: https://www.technicolor.com/node/7357

When trying to do port mapping and then checking it's status this is the output:

``` shellsession
$ upnpc -a 10.0.0.2 1234 1234 TCP
Found valid IGD : http://10.0.0.1:49152/upnp/control/WANIPConnection0
Local LAN ip address : 10.0.0.200
ExternalIPAddress = 184.64.35.96
InternalIP:Port = 10.0.0.2:1234
external 184.64.35.96:1234 TCP is redirected to internal 10.0.0.2:1234 (duration=86400)
```

You can see in the above output how the duration is set to `86400` instead of `0`.

Also, whatever lease time it is initialised with (eg: 1000, 1000000) it always starts from "86400".

Any idea on what exactly is happening there and how this can be debugged ?

**Comment by miniupnp** [comment]
use TCP dump to see the SOAP requests/responses and check the duration values in them.

The most probable is that the router is using the default value of 86400 instead of the one supplied by the control point.

**Comment by azdps** [comment]
There's a possibility that the min_lifetime value in the miniupnpd.conf file for the router is using a value of 86400. Telnet or SSH into the router and find the miniupnpd.conf file (could be named something else) and look at the conf file to see what the settings show. Report back with your findings.

**Comment by miniupnp** [comment]
@azdps I don't think this router is using miniupnpd

**Comment by miniupnp** [comment]
at least it is not listed in https://www.technicolor.com/sites/default/files/2018-08/CGM4140COM%20%28XB6%29%20v1.0%20OSS%20Publication.pdf

**Comment by psibi** [comment]
Yeah, it's not using miniupnpd. Anyway, I'm closing this issue as this isn't related to the softwares. Thanks Thomas!
