### ISSUE TITLE
upnp.c - 32bit int value too small for bytesreceived

### ISSUE THREAD

**Issue by azdps** [miniupnp/miniupnp#401]
For example the following line in upnp.c is using unsigned int:

`unsigned int bytessent, bytesreceived, packetsreceived, packetssent;`

When checking Get Connection Status bytesreceived is too small and easily showed the maximum unsigned int value of 4,294,967,295. Maybe you can change the unsigned int to unsigned long long int. I didn't look at the code thoroughly to see if changing it will impact any other code.

With how fast the internet is these days a 32bit int for bytesreceived is easily surpassed. Just a suggestion.

**Comment by miniupnp** [comment]
UPNP standard uses 32 bits unsigned integers.

**Comment by miniupnp** [comment]
> > UPNP standard uses 32 bits unsigned integers.
> 
> It's true, maybe the UPnP standard protocol need upgrade.

You should see that with the Open Connectivity foundation : https://openconnectivity.org/
