### ISSUE TITLE
Using two listening_ip=extX spams "Interface Index not matching" 

### ISSUE THREAD

**Issue by WhiteRC** [miniupnp/miniupnp#408]
Howdy. I saw this was fixed (for one interface) by using e.g. listening_ip=eth0, but when you have two internal networks on different adapters you get the spam.

So:
listening_ip=int0
listening_ip=int1

will result in all packets for one interface failing to match the test.

I took a quick glance at the code and you might want to pass the messages from upnpd to ssdpd via explicit use of the loopback (lo) interface instead of one of the more public interfaces. That will let you avoid an oddities like firewall rules, bridging overhead, and this sort of explicit problem.

**Comment by miniupnp** [comment]
can you give the full debug log ? and your network config ?
I don't understand why having 2 interface will make all packets fail the test.
The packet is received on either one of the interfaces, that should match.

Also I don't understand what you are talking about with message from upnpd to ssdpd. can you point out specifically at the code that causes problems to you ?

**Comment by WhiteRC** [comment]
Sorry for the delay, got caught up in a wac-a-mole situation.

So my basic config is that my main router does everything through bridges. I have five kinds of active adapters renamed as such:

extN :: External adapters, usually an ethN; in device group 1; has public (ISP) addresses etc.

intN :: Fully trusted points of entry, has private ; all bridges (ip link add dev intN type bridge; etc); in device group 2; has internal IP addresses and IPv6 delegated prefix addresses (comcast will issue a ;;/60 range of nets on request). 

locN :: renamed native adapters, e.g. ethN, on local segments; in device group 3; has no ip address of its own as it's always a slave to a bridge (ip link set dev locN master intN)

vpnN :: like locN but controlled by openvpn etc.

wstaN :: endpoints created by hostapd and added to an intN bridge by same. effectively another locN type of deal.

So my ssdpd/upnpd config is pretty simple. 
ext_ifname=ext0
listening_ip=int0
listening_ip=int1

The problem seems to be that the actual arrival interface is e.g. loc0 and the addressed interface is e.g. int0 and so I get a number of interesting messages.
They very depending on the ordering of the listening_ip stanzas. When int1 is first I get 

Oct 24 01:57:35 lightning miniupnpd[5191]: interface index not matching 10 != 12

This seems to be generated when miniupnpd logic generates and sends ssdpd frames to minissdpd logic (at least if my dry reading of the code is correct). interface 10 is int0 and interface 12 is int1, so when the daemons talk to each other they do using whichever listening_ip device is configured first. That was why I suggested that the two daemons should always talk through the loopback device eliminate this conflict/test.

I tried adding listening_ip=lo before the other two, hoping that transport would clean up, but then it complained that the packets were not comming from a lan. So that didn't work.

When I put int0 first -- most of my potential requests would be coming from int0 anyway -- I still get lots of errors but not it's all related to IPv6 addresses etc. which I think is also an issue of sending things out via bridges instead of low-level ethernet devices and/or having both an IPv6 Native Address on the ext0 device and IPv6 Prefix Delegations on the internal segments.

Nov  6 16:51:57 lightning miniupnpd[4905]: Failed to convert hostname '2601:601:1401:6073:ad4b:bf16:1891:11dc' to ip address

Oct 25 17:47:27 lightning miniupnpd[12538]: try_sendto(sock=12, len=448, dest=[ff02::c]:1900): sendto: Network is unreachable

Oct 25 17:47:27 lightning miniupnpd[12538]: sendto(udp_notify=12, [2601:601:1401:6073::1]): Network is unreachable

The best way to test a similar setup is to create a couple bridges and populate them with some dummy adapters, give them IP addresses and then move your real ethN devices into the various bridges to see the way the behaviors change.

**Comment by miniupnp** [comment]
minissdpd and miniupnpd communicates through a unix socket !
Please do first all your testing of miniupnpd without minissdpd running.

`Nov 6 16:51:57 lightning miniupnpd[4905]: Failed to convert hostname '2601:601:1401:6073:ad4b:bf16:1891:11dc' to ip address
`
=> that messages is outputed when a IGD IP v4 portmapping  method is called with an IPv6 address.  What is the UPnP client which does the requests ?

`Oct 25 17:47:27 lightning miniupnpd[12538]: sendto(udp_notify=12, [2601:601:1401:6073::1]): Network is unreachable`
Please check what is the output of 
`$ ./testgetroute 2601:601:1401:6073::1`

**Comment by WhiteRC** [comment]
Comcast has conveniently reassigned my IPv6 delegation, but at the time XXXX73::1 was assigned to the int0 bridge device, and XXXX74::1 was assigned to the int1 bridge device. So the route was in the local master rule and route tables.

Yeah, for reasons I don't understand Windows 10 preferentially (exclusively?) sends UPNP via IPv6 when there is a valid global IPv6 address configured on the outgoing interface. It seems to be consistent regardless of what client is making the request. (At least several games and the miniupnpc library tools do this.)

    C:\Bin>.\upnpc-shared.exe -L
    upnpc : miniupnpc library test client, version 1.9.
    (c) 2005-2014 Thomas Bernard.
    Go to http://miniupnp.free.fr/ or http://miniupnp.tuxfamily.org/
    for more information.
    List of UPNP devices found on the network : 
    desc: http://192.168.10.1:8081/rootDesc.xml
    st: urn:schemas-upnp-org:device:InternetGatewayDevice:1
    
    desc: http://[2601:601:1400:7283::1]:8081/rootDesc.xml
    st: urn:schemas-upnp-org:device:InternetGatewayDevice:1
    
    Found valid IGD : http://192.168.10.1:8081/ctl/IPConn
    LAN ip address : 2601:601:1400:7283:f07e:f3eb:83a0:918a
     i protocol exPort->inAddr:inPort description remoteHost leaseTime
     0 UDP  9308->192.168.10.16:9308  '192.168.10.16:9308 to 9308 (UDP)' '' 0

Note that the 192.168.10.16 client (my PS4) is working just fine, it's my windows 10 box -- 192.168.10.109 -- on the same connection that fails (probably due to the IPv6 stuff).

**Comment by miniupnp** [comment]
@WhiteRC see if 7800de9 is of any help for you

**Comment by lnpz** [comment]
> `Nov 6 16:51:57 lightning miniupnpd[4905]: Failed to convert hostname '2601:601:1401:6073:ad4b:bf16:1891:11dc' to ip address `
> => that messages is outputed when a IGD IP v4 portmapping method is called with an IPv6 address. What is the UPnP client which does the requests ?

I also get this error message on OpenWrt, my error contains an IPv6 ULA address. The UPnP client is an Android smart TV, it's on a dual stack network, it has both RFC1918 IPv4 address and globally routable IPv6 address (as well as ULA and link-local IPv6).

**Comment by miniupnp** [comment]
> > `Nov 6 16:51:57 lightning miniupnpd[4905]: Failed to convert hostname '2601:601:1401:6073:ad4b:bf16:1891:11dc' to ip address `
> > => that messages is outputed when a IGD IP v4 portmapping method is called with an IPv6 address. What is the UPnP client which does the requests ?
> 
> I also get this error message on OpenWrt, my error contains an IPv6 ULA address. The UPnP client is an Android smart TV, it's on a dual stack network, it has both RFC1918 IPv4 address and globally routable IPv6 address (as well as ULA and link-local IPv6).

well it is calling `AddPortMapping()` with an ip v6 address, so this android smart TV has a bug that should be reported to the manufacturer.

**Comment by WhiteRC** [comment]
I am still ending up with an IPv6 address (in string form) arriving in AddPortMapping whenever the target app (Elite Dangerous on Windows 10)  or the test application (upnpc-whared.exe) whenever a port mapping is requested (e.g. "upnpc-shared -r 5960 tcp").

The problem seems pathological. I can't see any way that miniupnpd can deduce the IPv4 address from the received IPv6 packet.

Doing an administrative add ("upnpc-shared -a ..." instead of "upnpc-shared -r") works fine because the command line includes an explicit IP address that need not be related to the issuing machine (aside from strict mode rule enforcements on the server side).

There doesn't seem to be a way to make windows prefer the IPv4 address in the UPNP  dll-or-whatever when there is a valid IPv6 address.

**Comment by miniupnp** [comment]
Do you really use IPv6 ?
try to run _miniupnpd_ with the `-4` command line flag.

**Comment by miniupnp** [comment]
also, have you tried with a less outdated miniupnpc client ?

**Comment by miniupnp** [comment]
@WhiteRC also please confirm if 7800de9429fd43b7fcf59c9ad511e1cb27d4222a#diff-2d7e0fb079957c4f42278f7e94fb3137 fixes the initial issue

**Comment by lnpz1** [comment]
> Do you really use IPv6 ?
> try to run _miniupnpd_ with the `-4` command line flag.

How do I disable IPv6 on an OpenWrt router? I tried adding `ipv6_disable=yes` to `miniupnpd.conf` , but it didn't stop miniupnpd using IPv6. I don't want to disable IPv6 network as I do need to use it.

There could be quite a few clients with this bug (not handling dual stack properly), I tried the tool https://github.com/kaklakariada/portmapper with `weupnp` library, the "Internal address" would change between IPv4 and IPv6 when clicking Connect/Disconnect many times.

**Comment by miniupnp** [comment]
@lnpz1 the ipv6 disabling feature is quite new : https://github.com/miniupnp/miniupnp/commit/a774830fe0f621b6ae7c9a6249dc8afd7826305a
does your version of miniupnpd includes it ?

**Comment by lnpz1** [comment]
@miniupnp I have miniupnpd - 2.1.20191006-4 which is the latest version in OpenWrt stable release repository, the version number looks like a timestamp which predates the change you mentioned, so I'll just have to wait unless I compile it myself.
