### ISSUE TITLE
 WanDevice service in CPE with Wan status check

### ISSUE THREAD

**Issue by dqnu** [miniupnp/miniupnp#411]
in Customer Premise Equipment，
when using WanDevice service(like AddPortMapping method)，should I check the status of Wan？
in many implements，when wan is down，AddPortMapping may not works, I don't think it is
neccessary

**Comment by miniupnp** [comment]
Just check with the standard : http://upnp.org/specs/gw/UPnP-gw-WANIPConnection-v2-Service.pdf

I don't think it the AddPortMapping method should fail if the IGD is not connected to the WAN.
