### ISSUE TITLE
miniupnpd is not available

### ISSUE THREAD

**Issue by liyiranlab** [miniupnp/miniupnp#412]
Sat Nov 30 12:24:45 2019 daemon.err [6063]: upnp_event_recv: recv(): Connection reset by peer
Sat Nov 30 12:24:45 2019 daemon.err miniupnpd[6063]: upnpevents_processfds: 0x428660, remove subscriber uuid:70802982-dac0-4e34-a053-bcd56b996e9a after an ERROR cb: http://192.168.12.167:2869/upnp/eventing/kyhoeeycla
Sat Nov 30 12:26:09 2019 daemon.notice miniupnpd[6063]: shutting down MiniUPnPd
Sat Nov 30 12:26:10 2019 daemon.err miniupnpd[6137]: could not open lease file: /var/run/miniupnpd.leases
Sat Nov 30 12:26:10 2019 daemon.notice miniupnpd[6137]: HTTP listening on port 5000
Sat Nov 30 12:26:10 2019 daemon.notice miniupnpd[6137]: HTTP IPv6 address given to control points : [fd45:6cb:e067::1]
Sat Nov 30 12:26:10 2019 daemon.notice miniupnpd[6137]: Listening for NAT-PMP/PCP traffic on port 5351
Sat Nov 30 12:36:31 2019 daemon.notice miniupnpd[6137]: shutting down MiniUPnPd
Sat Nov 30 12:36:31 2019 daemon.err miniupnpd[10550]: could not open lease file: /var/run/miniupnpd.leases
Sat Nov 30 12:36:31 2019 daemon.notice miniupnpd[10550]: HTTP listening on port 5000
Sat Nov 30 12:36:31 2019 daemon.notice miniupnpd[10550]: HTTP IPv6 address given to control points : [fd45:6cb:e067::1]
Sat Nov 30 12:36:31 2019 daemon.notice miniupnpd[10550]: Listening for NAT-PMP/PCP traffic on port 5351

**Comment by miniupnp** [comment]
@liyiranlab what is the issue ?
Please translate to english

**Comment by liyiranlab** [comment]
miniupnpd is not available
