### ISSUE TITLE
Unable to map multiple ports at a time

### ISSUE THREAD

**Issue by Aaranaw** [miniupnp/miniupnp#415]
Hi, I am trying to add a range of ports as the same time, my understanding of the possible switches would be
`
upnpc -ar 192.168.1.9 22 55551 TCP 23 55552 TCP`

This would redirect 55551 to port 22 on 192.168.1.9, 55552 to port 23 on the same ip, however it seems this is incorrect as it throws an error 

> 
> AddPortMapping (5551, 22, 192.168.1.9) failed with code 725 (OnlyPermanentLeasesSupported)  
> GetSpecificPortMappingEntry () failed with code 714 (NoSuchEntryInArray)  

Some advice with this would be appreciated.
Thanks

**Comment by miniupnp** [comment]
can you test with the latest version ?

**Comment by Aaranaw** [comment]
Sure, with the latest version and same command I get

> 
AddPortMapping(55551, 22, 192.168.1.9) failed with code 725 (OnlyPermanentLeasesSupported)

**Comment by miniupnp** [comment]
it should be
```
$ upnpc -r 22 55551 TCP 23 55552 TCP
upnpc : miniupnpc library test client, version 2.1.
 (c) 2005-2018 Thomas Bernard.
Go to http://miniupnp.free.fr/ or https://miniupnp.tuxfamily.org/
for more information.
List of UPNP devices found on the network :
 desc: http://192.168.10.254:5678/desc/root
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

Found valid IGD : http://192.168.10.254:5678/control/wan_ip_connection
Local LAN ip address : 192.168.10.70
ExternalIPAddress = xx.xx.xx.xx
InternalIP:Port = 192.168.10.70:22
external xx.xx.xx.xx:55551 TCP is redirected to internal 192.168.10.70:22 (duration=0)
ExternalIPAddress = 78.192.170.37
InternalIP:Port = 192.168.10.70:23
external xx.xx.xx.xx:55552 TCP is redirected to internal 192.168.10.70:23 (duration=0)
```
The error are reported by your router. What router is it ?

**Comment by Aaranaw** [comment]
Perfect this now works, thank you.
