### ISSUE TITLE
Help with unusual mapping problem

### ISSUE THREAD

**Issue by PaulGWebster** [miniupnp/miniupnp#417]
Ok I have a small problem and cannot seem to see what the issue is, I used upnpc to do this test from a windows machine (10.200.200.104), all ips and ports seem correct, 

The gateway has the following ips:
bridge100 192.168.254.1 (This is what inbound ports should be mapped on)
re0: 10.200.200.1 (This is what the lan is connected to)
igb0/igb1 (Ignore these they do not have a real ip and are part of bridge100)

Miniupnpd is: 
  miniupnpd-2.1.20190210,1
  [x] CHECK_PORTINUSE  Check if ports are in use
  [ ] IPV6             IPv6 protocol support                    
  [x] LEASEFILE        Enable lease file                        
  [x] PF_FILTER_RULES  Enable pf generation of filter rules     
  [ ] UPNP_IGDV2       Build an IGDv2 instead of an IGDv1       
  [ ] UPNP_STRICT      More strict UPnP specification compliance

Here is what the test client says:

C:\Users\paulg\Downloads\upnpc-exe-win32-20150918>upnpc-shared.exe -a 10.200.200.104 5656 5656 tcp 60
upnpc : miniupnpc library test client, version 1.9.
 (c) 2005-2014 Thomas Bernard.
Go to http://miniupnp.free.fr/ or http://miniupnp.tuxfamily.org/
for more information.
List of UPNP devices found on the network :
 desc: http://10.200.200.1:41978/rootDesc.xml
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

Found a (not connected?) IGD : http://10.200.200.1:41978/ctl/IPConn
Trying to continue anyway
Local LAN ip address : 10.200.200.104
GetExternalIPAddress failed.
AddPortMapping(5656, 5656, 10.200.200.104) failed with code 501 (Action Failed)
GetSpecificPortMappingEntry() failed with code 714 (NoSuchEntryInArray)
`

And this is what miniupnpd has to say on it:

`
miniupnpd 2049 - - 168 rt_msg : msglen=168 version=5 type=7
miniupnpd 2049 - - unprocessed RTM message type=7
miniupnpd 2049 - - level=0 type=20
miniupnpd 2049 - - sdl_index = 3  re0:70.71.bc.b9.6a.5a
miniupnpd 2049 - - ST: urn:schemas-upnp-org:device:InternetGatewayDevice:1 (ver=1)
miniupnpd 2049 - - SSDP M-SEARCH from 10.200.200.104:65482 ST: urn:schemas-upnp-org:device:InternetGatewayDevice:1
miniupnpd 2049 - - Single search found
miniupnpd 2049 - - SendSSDPResponse(): 0 bytes to 10.200.200.104:65482 ST: HTTP/1.1 200 OK
CACHE-CONTROL: max-age=120
ST: urn:schemas-upnp-org:device:InternetGatewayDevice:1
USN: uuid:ed6f7cdb-de83-11e7-88ce-0025906584c4::urn:schemas-upnp-org:device:InternetGatewayDevice:1
EXT:
SERVER: FreeBSD/12.1-STABLE UPnP/1.1 MiniUPnPd/2.1
LOCATION: http://10.200.200.1:41978/rootDesc.xml
OPT: "http://schemas.upnp.org/upnp/1/0/"; ns=01
01-NLS: 1579907214
BOOTID.UPNP.ORG: 1579907214
CONFIGID.UPNP.ORG: 1337

miniupnpd 2049 - - HTTP REQUEST from 10.200.200.104:25160 : GET /rootDesc.xml (HTTP/1.1)
miniupnpd 2049 - - Host: 10.200.200.1:41978
miniupnpd 2049 - - HTTP REQUEST from 10.200.200.104:25161 : POST /ctl/IPConn (HTTP/1.1)
miniupnpd 2049 - - Host: 10.200.200.1:41978
miniupnpd 2049 - - SOAPAction: urn:schemas-upnp-org:service:WANIPConnection:1#GetStatusInfo
miniupnpd 2049 - - HTTP REQUEST from 10.200.200.104:25162 : POST /ctl/IPConn (HTTP/1.1)
miniupnpd 2049 - - Host: 10.200.200.1:41978
miniupnpd 2049 - - SOAPAction: urn:schemas-upnp-org:service:WANIPConnection:1#GetExternalIPAddress
miniupnpd 2049 - - Returning UPnPError 501: Action Failed
miniupnpd 2049 - - HTTP REQUEST from 10.200.200.104:25163 : POST /ctl/IPConn (HTTP/1.1)
miniupnpd 2049 - - Host: 10.200.200.1:41978
miniupnpd 2049 - - SOAPAction: urn:schemas-upnp-org:service:WANIPConnection:1#GetExternalIPAddress
miniupnpd 2049 - - Returning UPnPError 501: Action Failed
miniupnpd 2049 - - HTTP REQUEST from 10.200.200.104:25164 : POST /ctl/IPConn (HTTP/1.1)
miniupnpd 2049 - - Host: 10.200.200.1:41978
miniupnpd 2049 - - SOAPAction: urn:schemas-upnp-org:service:WANIPConnection:1#AddPortMapping
miniupnpd 2049 - - AddPortMapping: ext port 5656 to 10.200.200.104:5656 protocol TCP for: libminiupnpc leaseduration=60 rhost=
miniupnpd 2049 - - UPnP permission rule 0 matched : port mapping accepted
miniupnpd 2049 - - Check protocol tcp for port 5656 on ext_if bridge100 192.168.254.1, 01FEA8C0
miniupnpd 2049 - - 01c8c80a:41978 68c8c80a:25164 <=> 5656 01fea8c0:5656
miniupnpd 2049 - - 01c8c80a:41978 68c8c80a:25163 <=> 5656 01fea8c0:5656
miniupnpd 2049 - - 01c8c80a:41978 68c8c80a:25162 <=> 5656 01fea8c0:5656
miniupnpd 2049 - - 01c8c80a:41978 68c8c80a:25161 <=> 5656 01fea8c0:5656
miniupnpd 2049 - - 01c8c80a:41978 68c8c80a:25160 <=> 5656 01fea8c0:5656
miniupnpd 2049 - - 01fea8c0:35787 fefea8c0:80 <=> 5656 01fea8c0:5656
miniupnpd 2049 - - 01c8c80a:8080 68c8c80a:25114 <=> 5656 01fea8c0:5656
miniupnpd 2049 - - 01fea8c0:29893 fdfea8c0:80 <=> 5656 01fea8c0:5656
miniupnpd 2049 - - 01c8c80a:8080 68c8c80a:25113 <=> 5656 01fea8c0:5656
miniupnpd 2049 - - 01c8c80a:8080 68c8c80a:25072 <=> 5656 01fea8c0:5656
miniupnpd 2049 - - 01c8c80a:8080 68c8c80a:25071 <=> 5656 01fea8c0:5656
miniupnpd 2049 - - 00000000:41978 00000000:0 <=> 5656 01fea8c0:5656
miniupnpd 2049 - - 01c8c80a:8080 00000000:0 <=> 5656 01fea8c0:5656
miniupnpd 2049 - - 01c8c80a:22 68c8c80a:17447 <=> 5656 01fea8c0:5656
miniupnpd 2049 - - 00000000:22 00000000:0 <=> 5656 01fea8c0:5656
miniupnpd 2049 - - 00000000:53 00000000:0 <=> 5656 01fea8c0:5656
miniupnpd 2049 - - redirecting port 5656 to 10.200.200.104:5656 protocol TCP for: libminiupnpc
miniupnpd 2049 - - Returning UPnPError 501: ActionFailed
miniupnpd 2049 - - HTTP REQUEST from 10.200.200.104:25165 : POST /ctl/IPConn (HTTP/1.1)
miniupnpd 2049 - - Host: 10.200.200.1:41978
miniupnpd 2049 - - SOAPAction: urn:schemas-upnp-org:service:WANIPConnection:1#GetSpecificPortMappingEntry
miniupnpd 2049 - - Returning UPnPError 714: NoSuchEntryInArray
`

**Comment by miniupnp** [comment]
what is the configuration of miniupnpd ? (either miniupnpd.conf or command line options)

**Comment by miniupnp** [comment]
it looks like you are in a "NAT behind NAT" setup... You need a lot of patching and tweaking to make it work properly in this kind of setup. have you tried to set ext_ip conf value to the real public IP adress ?

That may help games to work better.

**Comment by PaulGWebster** [comment]
The weird thing here is that there are two public ip's the freebsd system behind it is actually using fibs (3 routing tables) and doing split routing out. what I really need miniupnpd to do is just open a port on bridge100 and redirect inbound to whatever ip asked it to

**Comment by miniupnp** [comment]
UPnP IGD is designed to work with 1 public IP. Just choose one so `GetExternalIPAddress` could work !
also I made a few patches lately that could help you : 
https://github.com/miniupnp/miniupnp/commit/3f04f7992c4e8f11c2a2f66e678d9e63c8103dea and https://github.com/miniupnp/miniupnp/commit/7800de9429fd43b7fcf59c9ad511e1cb27d4222a

**Comment by miniupnp** [comment]
may be related to #433

**Comment by PaulGWebster** [comment]
Hey there I updated my network slightly!

Basically the way it is now, igb0 (my WAN interface) has the address 192.168.1.1 above this is a dedicated edgerouter that basically load balances multiple PPPoE lines, these are all DMZ to 192.168.1.1 (for all protocols)

So now the situation is, that I have multiple public ips though FreeBSD is unaware of them, as far as it is concerned 192.168.1.1 is basically a fully public address.

So now the problems :) if I tell miniupnpd I want igb0 to be my WAN if there is a note saying it has to know the actual 'external ip', but I have multiple.

What is the correct way to configure in this situation?

**Comment by miniupnp** [comment]
Well UPnP IGD is not designed to work with several "external" IP addresses. Just pick one and see how it works...

**Comment by PaulGWebster** [comment]
The issue is both PPPoE lines are dynamic, so I decided to try use the STUN detection, the problem is it does find one of the external ip addresses, but then any mappings fail.

What I would really like to do is have it simply open up a port on 0.0.0.0 when it is requested to do so, the reason for this is the only mappable ports allowed are >1024 and there is no services on anything in the non-privileged range. 

So even though 0.0.0.0 would open them up to both pppoe lines and the lan, that is perfectly acceptable.

Is there anyway I can force this type of behaviour?

**Comment by miniupnp** [comment]
dynamic IP address OK, but it is a fixed network interface, right ?
So `ext_ifname=ppp0` or so...

**Comment by PaulGWebster** [comment]
The FreeBSD gateway has igb0 connected to a ubique edgemax, the edgemax does load balancing for two PPPoE connections, the IP of igb0 is 192.168.1.2 the edgemax is 192.168.1.1, so yes the interface has a staticip but the upstream to that has two dynamic connections.

So what I need to happen is have miniupnp say ... Ok I got a request to map something I will just listen on igb0 and do nothing else (especially add things like dst_ip=PUBLIC_IP) I just want it to listen on the igb0 for anything on the correct port

**Comment by miniupnp** [comment]
So miniupnpd has no way to know the external IP address.
So you should either configure 
```
ext_ifname=igb0
ext_ip=xx.xx.xx.xx
```

or use STUN

**Comment by PaulGWebster** [comment]
STUN appears to fail, could I set the external ip to 0.0.0.0 and not have it flip out?

**Comment by PaulGWebster** [comment]
And works! or seems to

**Comment by PaulGWebster** [comment]
using: 
```
ext_ifname=igb0
ext_ip=192.168.1.2
#ext_perform_stun=no
#ext_stun_host=stun.stunprotocol.org
#ext_stun_port=3478
listening_ip=10.200.200.1/24
``` Seems to have worked utorrent and other apps are reporting port map success

**Comment by miniupnp** [comment]
utorrent and other apps may communicate the "ExternalIPAddress" to other hosts that will then be unable to connect if it is incorrect.

**Comment by PaulGWebster** [comment]
Would it be posible to have miniupnpd report multiple external ip addresses or alternatively give it a pool to offer? so I could specify 2 and it would hand them back in a round-robin type fasion?

**Comment by miniupnp** [comment]
no. That's no use anyway. utorrent will pick the one at startup

**Comment by PaulGWebster** [comment]
Yes but the point of the multiple connections is load balancing, so even if utorrent selected just one, then another application may get another, I do not want the situation where all apps load onto one single connection

**Comment by miniupnp** [comment]
As stated before, UPnP IGD is really not well suited for such setup. Just use another protocol...

**Comment by PaulGWebster** [comment]
Is there any alternatives :P

**Comment by miniupnp** [comment]
just configure your router by hand.
