### ISSUE TITLE
Error when building program with VS2019

### ISSUE THREAD

**Issue by Ty-Chen** [miniupnp/miniupnp#421]
Hello, I download the source code and using the .sln file in msvc to open the project, and when I try to build it, it shows : 
Error C1083 Cannot open include file: 'miniupnpcstrings.h': No such file or directory	miniupnpc	D:\miniupnpc-2.1.20191224\miniupnpc-2.1.20191224\minisoap.c	23	

I also try to use mingw32-make or mingw32make.bat, there are some errors.

process_begin: CreateProcess(NULL, cc -dumpmachine, ...) failed.
mingw32-make: Makefile:16: pipe: No error
process_begin: CreateProcess(NULL, cc -dumpmachine, ...) failed.
mingw32-make: Makefile:20: pipe: No error
process_begin: CreateProcess(NULL, cc -dumpmachine, ...) failed.
mingw32-make: Makefile:23: pipe: No error
process_begin: CreateProcess(NULL, cc -dumpmachine, ...) failed.
mingw32-make: Makefile:23: pipe: No error
process_begin: CreateProcess(NULL, cc -dumpmachine, ...) failed.
mingw32-make: Makefile:23: pipe: No error
process_begin: CreateProcess(NULL, cc -dumpmachine, ...) failed.
mingw32-make: Makefile:41: pipe: No error
process_begin: CreateProcess(NULL, cc -dumpmachine, ...) failed.
mingw32-make: Makefile:44: pipe: No error
process_begin: CreateProcess(NULL, cc -dumpmachine, ...) failed.
mingw32-make: Makefile:44: pipe: No error
process_begin: CreateProcess(NULL, cc -dumpmachine, ...) failed.
mingw32-make: Makefile:65: pipe: No error
process_begin: CreateProcess(NULL, cc -dumpmachine, ...) failed.
mingw32-make: Makefile:87: pipe: No error
process_begin: CreateProcess(NULL, cc -dumpmachine, ...) failed.
mingw32-make: Makefile:88: pipe: No error
process_begin: CreateProcess(NULL, cc -dumpmachine, ...) failed.
mingw32-make: Makefile:88: pipe: No error
process_begin: CreateProcess(NULL, cc -dumpmachine, ...) failed.
mingw32-make: Makefile:88: pipe: No error
process_begin: CreateProcess(NULL, cc -dumpmachine, ...) failed.
mingw32-make: Makefile:105: pipe: No error
process_begin: CreateProcess(NULL, cc -dumpmachine, ...) failed.
mingw32-make: Makefile:136: pipe: No error
process_begin: CreateProcess(NULL, cc -dumpmachine, ...) failed.
mingw32-make: Makefile:156: pipe: No error
process_begin: CreateProcess(NULL, cc -dumpmachine, ...) failed.
mingw32-make: Makefile:239: pipe: No error
process_begin: CreateProcess(NULL, cc -dumpmachine, ...) failed.
mingw32-make: Makefile:246: pipe: No error
process_begin: CreateProcess(NULL, cc -dumpmachine, ...) failed.
mingw32-make: Makefile:252: pipe: No error
process_begin: CreateProcess(NULL, cc -dumpmachine, ...) failed.
mingw32-make: Makefile:255: pipe: No error
process_begin: CreateProcess(NULL, cc -dumpmachine, ...) failed.
mingw32-make: Makefile:290: pipe: No error
process_begin: CreateProcess(NULL, cc -dumpmachine, ...) failed.
mingw32-make: Makefile:297: pipe: No error
/bin/sh updateminiupnpcstrings.sh
process_begin: CreateProcess(NULL, cc -dumpmachine, ...) failed.
mingw32-make: Makefile:13: pipe: No such file or directory
process_begin: CreateProcess(NULL, sh.exe -c "/bin/sh updateminiupnpcstrings.sh", ...) failed.
make (e=2): 系统找不到指定的文件。
mingw32-make: *** [Makefile:325: miniupnpcstrings.h] Error 2

D:\little try\miniupnpc-2.1.20191224\miniupnpc-2.1.20191224>mingw32make.bat
cc -Wall -Os -DNDEBUG -D_WIN32_WINNT=0X501 -DMINIUPNP_STATICLIB -c -o wingenminiupnpcstrings.o wingenminiupnpcstrings.c
process_begin: CreateProcess(NULL, cc -Wall -Os -DNDEBUG -D_WIN32_WINNT=0X501 -DMINIUPNP_STATICLIB -c -o wingenminiupnpcstrings.o wingenminiupnpcstrings.c, ...) failed.
make (e=2): 系统找不到指定的文件。
mingw32-make: *** [Makefile.mingw:68: wingenminiupnpcstrings.o] Error 2

**Comment by miniupnp** [comment]
* MS Visual studio
There is a `genminiupnpcstrings.vbs` that should be launched to generate the `miniupnpcstrings.h` file. but maybe it is missing from one of the .vcxproj file. Which .sln are you using ?
* Mingw32 : the errors shows that "cc" is not a correct command.  you should set the CC environment variable to the compiler (gcc or minwgw32-gcc or whatever)

**Comment by Ty-Chen** [comment]
Thanks for your help! I solve the problem by launching miniupnpcstrings.vbs. I use the miniunpnc.sln, it include the head file.

 And I wonder why don't you put test projects in miniunpnc.sln too, it will be much easier for testing in Windows OS.

**Comment by miniupnp** [comment]
_miniupnpc.sln_ is for Visual Studio 2008.

All *.sln files does include the "test" project _upnpc-static_
