### ISSUE TITLE
make: wingenminiupnpcstrings: Command not found

### ISSUE THREAD

**Issue by GalaxyML** [miniupnp/miniupnp#428]
Hi
I am trying to use this command in windows 10(msys shell)
`$ make -f Makefile.mingw`
but I give this error:
```
mkdir dll
echo init > init
cc -Wall -Os -DNDEBUG -D_WIN32_WINNT=0X501 -DMINIUPNP_STATICLIB -c -o wingenminiupnpcstrings.o wingenminiupnpcstrings.c
cc -Wall -Os -DNDEBUG -D_WIN32_WINNT=0X501 -DMINIUPNP_EXPORTS -c -o dll/wingenminiupnpcstrings.o wingenminiupnpcstrings.c
cc   wingenminiupnpcstrings.o  -lws2_32 -liphlpapi -o wingenminiupnpcstrings
wingenminiupnpcstrings miniupnpcstrings.h.in miniupnpcstrings.h
make: wingenminiupnpcstrings: Command not found
make: *** [Makefile.mingw:92: miniupnpcstrings.h] Error 127
```
I also try this and give the same error: 
`$ make -f Makefile.mingw DLLWRAP=mingw32-dllwrap CC=mingw32-gcc AR=mingw32-ar`
Can you help me, Please

**Comment by pali** [comment]
Try to apply following patch and build again:
```diff
diff --git a/miniupnpc/Makefile.mingw b/miniupnpc/Makefile.mingw
index 27cdbaf..31ff35c 100644
--- a/miniupnpc/Makefile.mingw
+++ b/miniupnpc/Makefile.mingw
@@ -82,16 +82,14 @@ upnpc-shared:	dll/upnpc.o miniupnpc.lib
 listdevices: listdevices.o libminiupnpc.a
 	$(CC) -o $@ $^ $(LDLIBS)
 
-wingenminiupnpcstrings:	wingenminiupnpcstrings.o
-
-wingenminiupnpcstrings.o:	wingenminiupnpcstrings.c
-
 # To make miniupnpcstrings.h from miniupnpcstrings.h.in we either
 # use a custom executable (if running make under windows) or use
 # sed (if cross compiling from another platform).
 ifeq ($(OS),Windows_NT)
-miniupnpcstrings.h: miniupnpcstrings.h.in wingenminiupnpcstrings
-	wingenminiupnpcstrings $< $@
+wingenminiupnpcstrings.exe:	wingenminiupnpcstrings.o
+wingenminiupnpcstrings.o:	wingenminiupnpcstrings.c
+miniupnpcstrings.h: miniupnpcstrings.h.in wingenminiupnpcstrings.exe
+	wingenminiupnpcstrings.exe $< $@
 else
 miniupnpcstrings.h:	miniupnpcstrings.h.in VERSION
 	sed 's|OS_STRING ".*"|OS_STRING "Windows/Mingw32"|' $< | \
```

**Comment by miniupnp** [comment]
@pali could you make a pull Request of your patch ?

**Comment by pali** [comment]
I do not know if it works... so I'm waiting if somebody can reproduce this problem and check if my patch fixes it. I do not want to create untested PR which I even do not know if works...

**Comment by miniupnp** [comment]
https://ci.appveyor.com will test it for you

**Comment by pali** [comment]
Can you point me to the appveyor build where appveyor detected this @GalaxyML's problem?

**Comment by miniupnp** [comment]
@GalaxyML problem doesn't appears in appveyor build. But any change has to still build in appveyor environment.

Anyway @GalaxyML are you able to test the proposed fix ?

**Comment by pali** [comment]
Now I looked at this problem and the reason why it works on AppVeyor and some other Windows machines, but does not work on @GalaxyML machine and all unix cross compiled gcc versions is the fact about automatic .exe extension.

Some gcc versions (mainly those used on Windows) automatically adds .exe extension for output files when linking. So `gcc test.c -o test` would create file `test.exe`. This is also what happen on AppVeyor

On unix systems and also on some gcc Windows versions there is no automatic extension and therefore `gcc test.c -o test` would create file `test`. This is what happen on Linux and also on @GalaxyML machine.

My proposed patch just ensure that `.exe` extension is always added despite if gcc automatically adds it or not. As it is just for Windows builds there should be no problems.

**Comment by pali** [comment]
I created pull request with fix there: https://github.com/miniupnp/miniupnp/pull/434
