### ISSUE TITLE
Bug: FreeBSD firewall type detection doesn't work, defaulting to PF always

### ISSUE THREAD

**Issue by ke6jjj** [miniupnp/miniupnp#431]
# Summary

Both `genconfig.sh` and the project `Makefile` make good attempts to determine the local firewall type at build time. Unfortunately, the detection code for FreeBSD systems is broken because of a typo. As a result, the system always builds for the `pf` firewall, independent of the firewall in use.

# Expected behavior

`miniupnpd` appears to be written so that it can control three different firewall types: `pf`, `ipf ` aka `IPFILTER`, and `ipfw`, the choice of which is made at build time. When configuring and building for a FreeBSD system the appropriate firewall to use can be discerned from the system setup in `/etc/rc.conf` with the help of Bourne shell functions in `/etc/rc.subr`.

* `pf` is controlled by the variable `pf_enable`
* `ipf` is controlled by the variable `ipfilter_enable`
* `ipfw` is controlled by the variable `firewall_enable`

# Actual behavior

The `genconfig.sh` and `Makefile` fragments will only make these checks if the files `/etc/rc.subr` and `/etc/default/rc.conf` exist, and if both exist, the code fragments then read in the entirety of `/etc/default/rc.conf`. This logic is incorrect, which leads the system to give up on auto detection and instead choose to build for the `pf` firewall.

1. There is never an `/etc/default` directory on modern FreeBSD systems; it is instead named `/etc/defaults` (plural). The file to check should instead be `/etc/defaults/rc.conf`.
2. Checking `/etc/defaults/rc.conf` only picks up the operating system _defaults_. It does not check the settings actually in effect because those settings live in `/etc/rc.conf`.

# Proposed fix

Once the local system is determined to be FreeBSD, the code in both `genconfig.sh` and `Makefile` should:

1. Check that `/etc/rc.subr` exists, and then
2. Check that `/etc/defaults/rc.conf` exists, and then
3. Check that `/etc/rc.conf` exists, and then
4. Evaluate `/etc/rc.subr`, and then
5. Evaluate `/etc/defaults/rc.conf`, and then
6. Evaluate `/etc/rc.conf`, and then, finally
7. Make the `checkyesno` checks that currently exist.

**Comment by ke6jjj** [comment]
Thanks for the quick response!

**Comment by ke6jjj** [comment]
We may have to reopen this issue. The commit above does fix `genconfig.sh` but `Makefile` is still using the old logic.

**Comment by ke6jjj** [comment]
```
# better way to find if we are using ipf or pf
.if $(OSNAME) == "FreeBSD"
.if exists(/etc/rc.subr) && exists(/etc/default/rc.conf)
FWNAME != . /etc/rc.subr; . /etc/default/rc.conf; \
          if checkyesno ipfilter_enable; then \
          echo "ipf"; elif checkyesno pf_enable; then \
          echo "pf"; elif checkyesno firewall_enable; then \
          echo "ipfw"; else echo "pf"; fi
.else
FWNAME = pf
.endif
.endif
```

**Comment by AMDmi3** [comment]
I'd like to note that this is not a correct way to detect firewall type at all. This cannot be done at build time, as packages may be and usually are built in different environment than a host where they are run. The correct way would be to support all firewalls and chose one at runtime or require/allow an explicit selection of firewall at build time (e.g. via an environment variable).

**Comment by ke6jjj** [comment]
@AMDmi3, they have closed this issue, so it may not be noticed. We should open a separate issue and provide some more concrete suggestions. Perhaps even a fork/commit/PR would be even better.

**Comment by bsd-source** [comment]
AMDmi3,

I'm sure miniupnp would accept a PR. He doesn't seem to use BSD based distro's, and when he does make changes, he needs testers and many times he doesn't get them. Anyways, you seem like you're right person to help with changes to miniupnpd for better FreeBSD implementation.

A very needed change to miniupnpd related to FreeBSD (pfSense):
[Issue tracker](https://redmine.pfsense.org/issues/7727)
[UPnP fix for multiple consoles or computers playing the same game](url) (forum post)

**Comment by miniupnp** [comment]
> I'd like to note that this is not a correct way to detect firewall type at all. This cannot be done at build time, as packages may be and usually are built in different environment than a host where they are run. The correct way would be to support all firewalls and chose one at runtime or require/allow an explicit selection of firewall at build time (e.g. via an environment variable).

or you can build all three versions and choose the right one to run on your system.

**Comment by AMDmi3** [comment]
> Anyways, you seem like you're right person to help with changes to miniupnpd for better FreeBSD implementation.

Please don't make such assumptions. What I'm doing is sorting out FreeBSD issue backlog which contains half a thousand issues, and unfortunately I cannot afford spending enough time to come with a pull request for each/many of these. Which is worse, I don't use muniupnp and don't in fact even know what it does, so I myself need a tester.
