### ISSUE TITLE
Can Anyone Help With Error Codes? 

### ISSUE THREAD

**Issue by shedcreations** [miniupnp/miniupnp#432]
I have a problem with ports not opening using miniupnp? I have tried to post on the forum but can't see where to ad a new post?
I'm running the software on a raspberry pi running the Archlinux OS. It was working but seems to have stopped working.

The Router is a Hitronhub.Home supplied by Virgin Media UK

I am running the commands via a Cron job every 6 hours to keep the port alive.

/usr/bin/upnpc -d 4569 UDP
/usr/bin/upnpc -d 5198 UDP
/usr/bin/upnpc -d 5199 UDP
/usr/bin/upnpc -d 222 TCP
/usr/bin/upnpc -d 50941 TCP
/usr/bin/upnpc -a $(ip route get 8.8.8.8 | head -1 | awk '{ print $NF }') 4569 4569 UDP > /dev/null 2>&1 &
/usr/bin/upnpc -a $(ip route get 8.8.8.8 | head -1 | awk '{ print $NF }') 5198 5198  UDP  > /dev/null 2>&1
/usr/bin/upnpc -a $(ip route get 8.8.8.8 | head -1 | awk '{ print $NF }') 5199 5199  UDP  > /dev/null 2>&1
/usr/bin/upnpc -a $(ip route get 8.8.8.8 | head -1 | awk '{ print $NF }') 222 222  TCP  > /dev/null 2>&1
/usr/bin/upnpc -a $(ip route get 8.8.8.8 | head -1 | awk '{ print $NF }') 50941 50941  TCP  > /dev/null 2>&1 

When I run the /usr/bin/upnpc -d 5198 UDP command manually I get the following errors and output.

upnpc : miniupnpc library test client, version 2.1.
 (c) 2005-2019 Thomas Bernard.
Go to http://miniupnp.free.fr/ or https://miniupnp.tuxfamily.org/
for more information.
List of UPNP devices found on the network :
 desc: http://[ip Address]/rootDesc.xml
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

Found valid IGD : http://[ip Address]2/ctl/IPConn
Local LAN ip address : [ip address]
UPNP_DeletePortMapping() failed with code : 714  

Can you tell me what the error  UPNP_DeletePortMapping() failed with code : 714    means please.

When I run the /usr/bin/upnpc -a $(ip route get 8.8.8.8 | head -1 | awk '{ print $NF }') 5198 5198  UDP Manually I get the following output.

upnpc : miniupnpc library test client, version 2.1.
 (c) 2005-2019 Thomas Bernard.
Go to http://miniupnp.free.fr/ or https://miniupnp.tuxfamily.org/
for more information.
List of UPNP devices found on the network :
 desc: http://[ip Address]/rootDesc.xml
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

Found valid IGD : http://[ip address]:34922/ctl/IPConn
Local LAN ip address : [ip address]
ExternalIPAddress = [ip address]
GetSpecificPortMappingEntry() failed with code 714 (NoSuchEntryInArray)  

Can you tell me what the GetSpecificPortMappingEntry() failed with code 714 (NoSuchEntryInArray) error is please.

I fear this is a router issue and I am unable to access the router to reboot it.

Hope to hear from you soon.

Jon

**Comment by miniupnp** [comment]
> 714 NoSuchEntryInArray - The specified value does not exist in the array.

http://upnp.org/specs/gw/UPnP-gw-WANIPConnection-v2-Service.pdf
