### ISSUE TITLE
Why --leasefile option is not provided by default in makefile?

### ISSUE THREAD

**Issue by Dean151** [miniupnp/miniupnp#435]
I there!
Thanks for this awesome project!

I faced persistency issues with my rules, and turns out that the makefile does not enable --leasefile by default. I rebuilded the lib using it and it seems to work perfectly now.

My question is : 
Why does the leasefile option is not included yet as default when building? Is it beta, or not well supported? 
Isn't persistency accross reboot of upnp and nat-pmp rules something we want and expect from miniupnpd?

Awesome job anyway, works like a charm on my home network :)

**Comment by miniupnp** [comment]
I think most people would expect a "fresh" configuration of their home router when they reboot it.

Unless you have a particular use case, why would you reboot your router and keep the upnp and nat-pmp rules ? That's why it is an optional feature

**Comment by miniupnp** [comment]
To be clear, nat-pmp and UPNP IGD are for transient port mappings.

If you need a persistent port mapping (for your web server or ssh) there are other way to configure them on your router.
