### ISSUE TITLE
Miniupnpd shall add firewall input rules for STUN testing

### ISSUE THREAD

**Issue by Menion2k** [miniupnp/miniupnp#437]
Hi all

Following the openwrt discussion here https://forum.openwrt.org/t/miniupnpd-in-trunk-stun-setup/18688 there is a problem with STUN public IP discovery.

Miniupnpd seems to open 4 input port for testing the STUN inbound but if they are not opened on firewall the test will never pass even if ISP router is in DMZ

**Comment by pali** [comment]
Hello! This problem should be already fixed. miniupnpd already adds those four ports to firewall for unblocking them prior sending any packets. See relevant code in file [upnpstun.c](https://github.com/miniupnp/miniupnp/blob/master/miniupnpd/upnpstun.c#L331-L333).

**Comment by miniupnp** [comment]
the stun code may lack a bit of logging, but the 4 port are open on the firewall (and closed afterward)

**Comment by Menion2k** [comment]
Hi

OK I see the code but in practice it does not work, at least on Openwrt. I do not see anything special with the openwrt system and I saw problems also with pfsense

**Comment by pali** [comment]
Can you test it with miniupnpd netfilter/iptables version with empty iptables rules and initialized iptables chains from supplied script https://github.com/miniupnp/miniupnp/tree/master/miniupnpd/netfilter ?
