### ISSUE TITLE
upnpc-exe-win32-20150918.zip

### ISSUE THREAD

**Issue by stdedos** [miniupnp/miniupnp#440]
I came here from https://answers.microsoft.com/en-us/windows/forum/all/how-to-check-if-my-router-upnp-is-working/0428fd2a-2c51-4dbd-9433-c5f9b744199a, and I barely understand what is UPnP. (Also, my router is _shaken_)

I see that the rest of the files are very recent, in a modern & active repository - except this one.

I was wondering if you could enlighten me why is this file so old.
It's still working, so I am definitely not complaining! 😃

**Comment by miniupnp** [comment]
because I don't build on windows anymore.

you can get fresh builds from appveyor : https://ci.appveyor.com/project/miniupnp/miniupnp/build/job/fjwsaptb91chjgp4/artifacts

**Comment by stdedos** [comment]
And ... what's the difference between the `upnpc` and the `miniupnpc`?

Is it just a naming difference?

**Comment by miniupnp** [comment]
upnpc is a command line tool. miniupnpc is the name of the software library
