### ISSUE TITLE
Compatibility problems with fedora 32

### ISSUE THREAD

**Issue by Mint-M** [miniupnp/miniupnp#445]
Problem1: unable to build with nft
I downloaded the package source file and source code from urls below

https://src.fedoraproject.org/rpms/miniupnpd/blob/master/f/miniupnpd.spec
http://miniupnp.free.fr/files/download.php?file=miniupnpd-2.1.20200329.tar.gz

The spec file was modified to switch to Makefile.linux_nft and remove some unnecessary patches.
[miniupnpd.txt](https://github.com/miniupnp/miniupnp/files/4597584/miniupnpd.txt)

The critical error message seemed to be 'erelocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE' ,however, adding -fPIE to CFLAGS or LDFLAGS didn't help.
[buildoutput.txt](https://github.com/miniupnp/miniupnp/files/4597590/buildoutput.txt)

As long as Makefile.linux_nft is replaced by Makefile.linux ,build process will complete successfully and the rpm package can be installed correctly.

Problem2: miniupnpd was not compatible with fedora 32 since fedora 32 replace iptables-legacy with iptables-nft
Both the official package of miniupnpd and the one built as mentioned above didn't work with the default version of iptables.

The error shows 'addnatrule() : chain MINIUPNPD not found' and 'chain MINIUPNPD not found'.

Temporary workaround:
Install iptables（the legacy version）
Set IPTABLES=iptables-legacy and IPTABLES=ip6tables-legacy in miniupnpd_functions.sh

OS information:
fedora 32 minimal installation
kernel  5.6.8-300.fc32.x86_64

**Comment by miniupnp** [comment]
I'm currently reworking the build system.
Please test with latest master from github.

You need now to use ./configure

**Comment by miniupnp** [comment]
I just released a new tgz : [miniupnpd-2.1.20200510.tar.gz](https://miniupnp.tuxfamily.org/files/download.php?file=miniupnpd-2.1.20200510.tar.gz)

**Comment by gasinvein** [comment]
Latest master seems to work fine on Fedora 32.

**Comment by miniupnp** [comment]
thanks.

**Comment by Mint-M** [comment]
The modified spec file compatible with fedora 32 is uploaded below in case there is anyone who need it.
miniupnpd-2.1.20200510.tar.gz and the folder inside should be renamed as miniupnpd-2.1.
The RPM package can built without error but the functions haven't been tested yet.(according to Gasinvein,it should work.)
[miniupnpd-nft.spec.txt](https://github.com/miniupnp/miniupnp/files/4625766/miniupnpd-nft.spec.txt)
