### ISSUE TITLE
anyone can help me out?

### ISSUE THREAD

**Issue by norikohxb** [miniupnp/miniupnp#447]
![QQ截图20200430231635](https://user-images.githubusercontent.com/12111990/81529789-32805180-9392-11ea-8451-3fd80e559ebb.jpg)
my lede ip is 192.168.16.248  its gateway is a ROS  192.168.16.252
there exsit another LAN ip range 192.168.8.0/24  they are used by Broadlink devices
my LEDE keep on get those message in system log
my LEDE's IP are set 192.168.16.248  255.255.255.0 
it should has no relationship with 192.168.8.x
why it keeps on getting error message ?

Mon May 11 14:15:08 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.168:33094 is not from a LAN, closing the connection
Mon May 11 14:15:08 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.168:33096 is not from a LAN, closing the connection
Mon May 11 14:15:08 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.175:37352 is not from a LAN, closing the connection
Mon May 11 14:15:08 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.175:37354 is not from a LAN, closing the connection
Mon May 11 14:15:08 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.174:46362 is not from a LAN, closing the connection
Mon May 11 14:15:08 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.173:33904 is not from a LAN, closing the connection
Mon May 11 14:15:08 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.173:33906 is not from a LAN, closing the connection
Mon May 11 14:15:08 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.173:33908 is not from a LAN, closing the connection
Mon May 11 14:15:08 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.174:46366 is not from a LAN, closing the connection
Mon May 11 14:15:08 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.174:46364 is not from a LAN, closing the connection
Mon May 11 14:15:08 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.178:45576 is not from a LAN, closing the connection
Mon May 11 14:15:08 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.178:45578 is not from a LAN, closing the connection
Mon May 11 14:15:08 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.172:53844 is not from a LAN, closing the connection
Mon May 11 14:15:08 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.172:53846 is not from a LAN, closing the connection
Mon May 11 14:15:08 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.172:53848 is not from a LAN, closing the connection
Mon May 11 14:15:08 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.178:45580 is not from a LAN, closing the connection
Mon May 11 14:15:38 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.176:43262 is not from a LAN, closing the connection
Mon May 11 14:15:38 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.176:43264 is not from a LAN, closing the connection
Mon May 11 14:15:38 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.175:37392 is not from a LAN, closing the connection
Mon May 11 14:15:38 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.168:33154 is not from a LAN, closing the connection
Mon May 11 14:15:38 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.162:50784 is not from a LAN, closing the connection
Mon May 11 14:15:38 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.175:37396 is not from a LAN, closing the connection
Mon May 11 14:15:38 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.175:37394 is not from a LAN, closing the connection
Mon May 11 14:15:38 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.178:45582 is not from a LAN, closing the connection
Mon May 11 14:15:38 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.178:45584 is not from a LAN, closing the connection
Mon May 11 14:15:38 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.162:50786 is not from a LAN, closing the connection
Mon May 11 14:15:38 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.178:45586 is not from a LAN, closing the connection
Mon May 11 14:15:38 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.179:47516 is not from a LAN, closing the connection
Mon May 11 14:15:38 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.179:47520 is not from a LAN, closing the connection
Mon May 11 14:15:38 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.179:47518 is not from a LAN, closing the connection
Mon May 11 14:15:38 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.176:43266 is not from a LAN, closing the connection
Mon May 11 14:15:38 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.176:43268 is not from a LAN, closing the connection
Mon May 11 14:15:38 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.176:43270 is not from a LAN, closing the connection
Mon May 11 14:15:38 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.168:33158 is not from a LAN, closing the connection
Mon May 11 14:15:38 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.168:33156 is not from a LAN, closing the connection
Mon May 11 14:15:38 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.162:50788 is not from a LAN, closing the connection
Mon May 11 14:15:38 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.168:33160 is not from a LAN, closing the connection
Mon May 11 14:15:38 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.167:42290 is not from a LAN, closing the connection
Mon May 11 14:15:38 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.175:37398 is not from a LAN, closing the connection
Mon May 11 14:15:38 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.167:42294 is not from a LAN, closing the connection
Mon May 11 14:15:38 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.167:42292 is not from a LAN, closing the connection
Mon May 11 14:15:38 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.178:45588 is not from a LAN, closing the connection
Mon May 11 14:15:38 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.178:45590 is not from a LAN, closing the connection
Mon May 11 14:15:38 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.178:45592 is not from a LAN, closing the connection
Mon May 11 14:15:38 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.168:33162 is not from a LAN, closing the connection
Mon May 11 14:15:38 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.168:33164 is not from a LAN, closing the connection
Mon May 11 14:15:38 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.168:33166 is not from a LAN, closing the connection
Mon May 11 14:15:38 2020 daemon.warn miniupnpd[29850]: HTTP peer 192.168.8.174:46372 is not from a LAN, closing the connection

**Comment by miniupnp** [comment]
well you receive HTTP connections from 192.168.8.* LAN, they are rejected by miniupnpd

**Comment by miniupnp** [comment]
I guess there is a problem in the network setup, but I can't tell more without details about the configuration
