### ISSUE TITLE
Sanitizing Callback URLs (UPnP 2.0)

### ISSUE THREAD

**Issue by paul-chambers** [miniupnp/miniupnp#454]
The Open Connectivity Forum released v2.0 of the UPnP spec in April, and this caught my eye;

> This latest revision adds the following text to section 4.1.1:
> 
> The subscription request containing a delivery URL not on the same network segment as the fully qualified event subscription URL shall not be accepted. For private networks this means that the delivery URL provided will adhere to the following IP ranges:
> 
> 10.0.0.0 - 10.255.255.255 (10/8 prefix)
> 172.16.0.0 - 172.31.255.255 (172.16/12 prefix)
> 192.168.0.0 - 192.168.255.255 (192.168/16 prefix)

- Paul

**Comment by paul-chambers** [comment]
I'm assuming that the same IP subnet identified for the 'secure mode' should now also be used to validate that callback URLs fall within that IP subnet?

**Comment by miniupnp** [comment]
miniupnpd does a more strict check. The callback URL is rejected if it is not on the same host that initiated the SUBSCRIBE request.

https://github.com/miniupnp/miniupnp/blob/master/miniupnpd/upnphttp.c#L541
