### ISSUE TITLE
minissdpd log at service startup:  "ssdpDiscover: sendto: Operation not permitted"

### ISSUE THREAD

**Issue by hobbieman** [miniupnp/miniupnp#457]
On Debian buster when starting the minissdpd service I see the following:

May 28 10:02:00 unixbox systemd[1]: Starting keep memory of all UPnP devices that announced themselves...
May 28 10:02:00 unixbox minissdpd[24816]: ssdpDiscover: sendto: Operation not permitted
May 28 10:02:00 unixbox systemd[1]: Started keep memory of all UPnP devices that announced themselves.

Not sure what the "operation not permitted" log means, but it looks like the daemon is otherwise working as it discovered 8 devices on the network...

**Comment by miniupnp** [comment]
well there must be a permission or capabilities issue.
_minissdpd_ does send a few SSDP M-SEARCH packets at startup, and then just listen to the traffic.
if the system forbids _minissdpd_ to send thoses packets, it will still discover devices thanks to their periodical announcements.

Do you reproduce the same problem when launching minissdpd on the same machine from the command line ? `./minissdpd -d -i eth0`

**Comment by hobbieman** [comment]
Yes, you are right.  The "sendto: Operation not permitted" is being caused by a rule in my firewall.  So, I can remove the rule and that warning goes away, but I still think there is an issue either in the way I am configuring the daemon or in the daemon itself.

This machine has two network interfaces: one to the WAN (ens3) and the other to the LAN (enp1s0). The firewall rule is only being applied to block multicast to the WAN interface, and the command I am issuing (even when I run it manually on the shell) is telling the daemon to use the LAN interface.

Command:

# /usr/sbin/minissdpd -d -i enp1s0

When I run it, Wireshark capture does not show any packets on enp1s0, but it does show the following packet on the ens3 interface:

M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
ST: ssdp:all
MAN: "ssdp:discover"
MX: 3

I would expect that if "-i enp1s0" is provided, that the multicast packet would go out on enp1s0. Is that incorrect understanding on how this is supposed to work?

**Comment by miniupnp** [comment]
yes. That's possible there is a bug there

**Comment by miniupnp** [comment]
it looks like `setsockopt(sudp, IPPROTO_IP, IP_MULTICAST_IF, ...)` is missing
