### ISSUE TITLE
minissdpd:  not binding to the specific interface provided by "-i" cli option

### ISSUE THREAD

**Issue by hobbieman** [miniupnp/miniupnp#458]
Although minissdpd checks that the interface provided in the -i option actually exists, it does not end up binding to it.  Instead, it binds to all the interfaces.

For example, on my debian buster install, I have the following in /etc/default/minissdpd:
MiniSSDPd_INTERFACE_ADDRESS="10.10.10.1"

When I start the minissdpd service, I see this:

# systemctl  status minissdpd.service
● minissdpd.service - keep memory of all UPnP devices that announced themselves
   Loaded: loaded (/lib/systemd/system/minissdpd.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2020-05-28 10:02:00 CDT; 6s ago
     Docs: man:minissdpd(1)
  Process: 24815 ExecStart=/usr/lib/minissdpd/minissdpd-systemd-wrapper ${MiniSSDPd_INTERFACE_ADDRESS} $MiniSSDPd_OTHER_OPTIONS (code=exited, status=0/SUCCESS)
 Main PID: 24816 (minissdpd)
    Tasks: 1 (limit: 4915)
   Memory: 1.1M
   CGroup: /system.slice/minissdpd.service
           └─24816 /usr/sbin/minissdpd -i 10.10.10.1

Then, when I inspect the ports in use with netstat, I see minissdpd bound to what I understand is all interfaces:

#netstat -lptu | grep ssdp
udp        0      0 0.0.0.0:1900            0.0.0.0:*                           24816/minissdpd     

Same happens if I set the variable to:
MiniSSDPd_INTERFACE_ADDRESS="enp1s0"

**Comment by miniupnp** [comment]
well, that's not a bug, that's how multicast works.

You bind to * but then subscribe for multicast membership on the specific interface(s).

please have a look at : 
https://github.com/miniupnp/miniupnp/blob/master/minissdpd/config.h#L24

**Comment by hobbieman** [comment]
@miniupnp : I read the comment in the header file and I can't debate whether this a bug or not. You are the expert in this, but please just allow me to provide the below information.

I have the attached python script, which sends the multicast packet on the interface of my choosing in a machine with two interfaces (I hardcoded the IP address of the chosen interface inside the script).  The python script binds only to the specified interface, sends the multicast packet on that interface, and receives the 200 OK responses from the clients on the WAN.

$ netstat -na | grep 1900
udp        0      0 10.10.10.1:1900    0.0.0.0:*

I have attached the python script and the output of the script (some info was anonymized).

Perhaps I completely misunderstood the purpose of "-i", but it seems to me that minissdpd should behave (ie. bind) the same as the python script does when "-i 10.10.10.1" is provided to the daemon.

[find_ssdp_devices.python2_script.txt](https://github.com/miniupnp/miniupnp/files/4705039/find_ssdp_devices.python2_script.txt)

[output.txt](https://github.com/miniupnp/miniupnp/files/4705040/output.txt)

**Comment by miniupnp** [comment]
Just enable SSDP_LISTEN_ON_SPECIFIC_ADDR if you like, default is having it disabled.
