### ISSUE TITLE
duration in /var/log/upnp.leases seems ignored by miniupnpd

### ISSUE THREAD

**Issue by emojifreak** [miniupnp/miniupnp#463]
miniupnpd is the latest version from the git. `config.h` has the following lines:

```
/* Uncomment the following line to enable lease file support */
#define ENABLE_LEASEFILE
/* Uncomment the following line to store remaining time in lease file */
#define LEASEFILE_USE_REMAINING_TIME
```

```
root@router1:~# cat /var/log/upnp.leases 
TCP:65229:192.168.1.75:65229:600:libminiupnpc
TCP:65228:192.168.1.75:65228:600:libminiupnpc
root@router1:~# ls -l /var/log/upnp.leases 
-rw-r--r-- 1 root root 92 May 30 15:34 /var/log/upnp.leases
```

The lease file was last modified 30 minutes ago, but it has redirection entries of 10-minute lifetime (Note added: the above commands were run around 16:00). The NAT table still has the expired redirections as below:

```
root@router1:~# nft list ruleset | grep 6522
		iif "ip6tnl1" th dport 65229 @nh,128,32 3232235851 @nh,72,8 6 accept
		iif "ip6tnl1" th dport 65228 @nh,128,32 3232235851 @nh,72,8 6 accept
		iif "ip6tnl1" tcp dport 65229 dnat to 192.168.1.75:65229
		iif "ip6tnl1" tcp dport 65228 dnat to 192.168.1.75:65228
```

**Comment by miniupnp** [comment]
Well I think it is quite contradictory to use a lease file to have lease persisting reboots, with the idea of limited lease duration.

In almost all IGD1 implementations, port mappings where not time limited (duration = 0) so in this context it was relevant to implement a lease file, as control points/clients were expecting their portmappings to live forever.

But the spirit of IGD2 is to force a limited duration for port mappings, control points are expected to renew them when needed.

In that context, I advise to disable lease file completely.

**Comment by miniupnp** [comment]
also, `LEASEFILE_USE_REMAINING_TIME` was designed for device without clocks persisting after reboot.
By using this, you assumes that there are no time between reboots...

it should definitely be disabled if the machine has time correctly set when miniupnpd is launched.

**Comment by emojifreak** [comment]
#466 will handle the issue that duration is sometime ignored, and use of a lease file is discouraged, maybe this issue should be closed. Please reopen it if necessary. I believe that I finished all of your homework. If there is a remaining one or a new one, please give a mention. I will do it Sunday morning (in Japanese time). Good day! (Maybe I should not say good night :-)
