### ISSUE TITLE
miniupnpc should prefer IPv4 devices for IPv4 related functions

### ISSUE THREAD

**Issue by miniupnp** [miniupnp/miniupnp#467]
see #461 

I think there should be a protocol preference given to `UPNP_GetValidIGD()`

**Comment by miniupnp** [comment]
@emojifreak
 The issue may be also  miniupnpd answering to ipv4 M-SEARCH with ipv6 devices...

**Comment by miniupnp** [comment]
@emojifreak what is the output of `/sbin/sysctl -n net.ipv6.bindv6only` on your system ?
and ` grep V6SOCKETS_ARE_V6ONLY config.h `

**Comment by emojifreak** [comment]
As you probably expected... 

> what is the output of `/sbin/sysctl -n net.ipv6.bindv6only` on your system ?

```
# /sbin/sysctl -n net.ipv6.bindv6only
0
```
> and `grep V6SOCKETS_ARE_V6ONLY config.h`

```
# grep V6SOCKETS_ARE_V6ONLY config.h
/* Define V6SOCKETS_ARE_V6ONLY if AF_INET6 sockets are restricted
/*#define V6SOCKETS_ARE_V6ONLY*/
```

**Comment by miniupnp** [comment]
thanks. Thats ok
