### ISSUE TITLE
Could you consider to add systemd-friendly startup option for miniupnpd and minissdpd?

### ISSUE THREAD

**Issue by emojifreak** [miniupnp/miniupnp#468]
This is a feature request.

The debian package of miniupnpd uses `-d` to start `miniupnpd`. Their reason of that decision is explained as

>  * debian/miniupnpd.service: Pass -d to miniupnpd and set Type to simple.
>    That way systemd will detect whether the process is exiting with a
>    non-zero code or not and properly track the it.

at https://metadata.ftp-master.debian.org/changelogs//main/m/miniupnpd/miniupnpd_2.1-6.1_changelog

In my view, the `Type` should be exec, because https://github.com/systemd/systemd/blob/d904afc730268d50502f764dfd55b8cf4906c46f/man/systemd.service.xml#L175-L183

The defaut `Type=` is in `systemd` is `simple`. With `Type=simple` or `Type=exec`, the stdout and the stderr are sent to `systemd-journald` as https://github.com/systemd/systemd/blob/d904afc730268d50502f764dfd55b8cf4906c46f/man/systemd.exec.xml#L2186-L2189 and https://github.com/systemd/systemd/blob/d904afc730268d50502f764dfd55b8cf4906c46f/man/systemd.exec.xml#L2201-L2204

`-d` option of `miniupnpd` and `minissdpd` is suitable for the above default of `systemd` as

1. `-d` keeps `miniupnpd` and `minissdpd` foreground, and
2. `-d` lets  `miniupnpd` and `minissdpd` send their messages to stdout or stderr instead of `syslog`.

A minor problem is that `-d` make messages by `miniupnpd` and `minissdpd` too much for ordinary logging. So could you consider to add an option to let `miniupnpd` and `minissdpd` to do 1 and 2 above without much logging in `-d`? I note that if a program is started by `systemd` with `Type=simple` or `Type=exec` then pid file is not used as `systemd` can track the PID of started process directly, as https://github.com/systemd/systemd/blob/d904afc730268d50502f764dfd55b8cf4906c46f/man/systemd.service.xml#L279-L285

Independent of the above feature request,
https://github.com/miniupnp/miniupnp/blob/3b20182c860788b84be7fd5eab65e40a87920608/miniupnpd/linux/miniupnpd.service#L3
should also added `Aftre=minissdpd.service` so that `miniupnpd` starts after `minissdpd`.

Debian Linux's current `miniupnpd.service` is shown below:

```
[Unit]
Description=UPnP Internet Gateway Device Daemon
Documentation=man:miniupnpd(8)
After=network-online.target

[Service]
Type=simple
EnvironmentFile=-/etc/default/miniupnpd
EnvironmentFile=/etc/miniupnpd/miniupnpd.conf
ExecStartPre=/etc/miniupnpd/iptables_init.sh -i $ext_ifname
ExecStartPre=/bin/sh -c "[ \"$MiniUPnPd_ip6tables_enable\" != 1 ] || /etc/miniupnpd/ip6tables_init.sh -i $ext_ifname"
ExecStart=/usr/sbin/miniupnpd -d -f /etc/miniupnpd/miniupnpd.conf $MiniUPnPd_OTHER_OPTIONS
ExecStopPost=/etc/miniupnpd/iptables_removeall.sh -i $ext_ifname
ExecStopPost=/bin/sh -c "[ \"$MiniUPnPd_ip6tables_enable\" != 1 ] || /etc/miniupnpd/ip6tables_removeall.sh -i $ext_ifname"
PrivateTmp=yes
PIDFile=/run/miniupnpd.pid

[Install]
WantedBy=multi-user.target
```

**Comment by emojifreak** [comment]
I am unsure if it is acceptable to use  systemd-specific functions to harden the security of `miniupnpd`. `miniupnpd` can access files in the filesystems, and runs in UID 0. Those accesses and capabilities are mostly unnecessary to `miniupnpd`. In particular, [Linux Capabilities possessed by UID 0](https://www.man7.org/linux/man-pages/man7/capabilities.7.html) should be removed from `miniupnpd` process. I tested the following systemd service file and ran `upnpc -a`, `upnpc -n`, `upnpc -l`, `upnpc -L`, `upnpc -d`, and found that `miniupnpd` ran fine and did not say `Operation not permitted`, which is observed when too many capabilities are dropped. Most useful trick seems `CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BROADCAST CAP_NET_RAW CAP_SYSLOG` below, which seems to drop most of UID 0 powers.

```
[Unit]
Description=UPnP Internet Gateway Device Daemon
Documentation=man:miniupnpd(8)
After=network-online.target minissdpd.service

[Service]
# /etc/miniupnpd/nft_removeall.sh needs some child processes
TasksMax=4
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BROADCAST CAP_NET_RAW CAP_SYSLOG
MountAPIVFS=yes
NoNewPrivileges=yes
#miniupnpd does not need a device access
PrivateDevices=yes
# files in /tmp should not be shared with other programs.
PrivateTmp=yes
MemoryDenyWriteExecute=yes
ProtectSystem=full
ProtectHome=yes
ProtectHostname=yes
ProtectClock=yes
ProtectKernelTunables=yes
ProtectKernelModules=yes
ProtectKernelLogs=yes
ProtectControlGroups=yes
LockPersonality=yes
RestrictRealtime=yes
RestrictNamespaces=yes
RestrictSUIDSGID=yes


Type=exec
Environment="LANG=C.UTF-8" "ASAN_OPTIONS=detect_leaks=1:detect_stack_use_after_return=1:check_initialization_order=1:strict_string_checks=1:detect_invalid_pointer_pairs=2:abort_on_error=0:halt_on_error=0" "UBSAN_OPTIONS=print_stacktrace=1:halt_on_error=0"
ExecStartPre=/etc/miniupnpd/nft_init.sh -i ip6tnl1
ExecStart=/usr/sbin/miniupnpd -d -f /etc/miniupnpd/miniupnpd.conf
ExecStopPost=/etc/miniupnpd/nft_removeall.sh -i ip6tnl1

[Install]
WantedBy=multi-user.target
```

On the other hand, I tried to run `minissdpd` in `User=nobody` and `Group=nobody`, but failed by the following error message:

```
May 31 08:44:21 router1 systemd[7448]: minissdpd.service: Failed to determine group credentials: No such process
May 31 08:44:21 router1 systemd[7448]: minissdpd.service: Failed at step GROUP spawning /home/ryutaroh/minissdpd: No such process
```

**Comment by emojifreak** [comment]
The following stricter systemd service file works for `minissdpd`:

```
[Unit]
Description=keep memory of all UPnP devices that announced themselves
Documentation=man:minissdpd(1)
After=network-online.target
Before=miniupnpd.service

[Service]
# It does not need a child process at all!
TasksMax=1
CapabilityBoundingSet=CAP_NET_BROADCAST CAP_SYSLOG
MountAPIVFS=yes
NoNewPrivileges=yes
# minissdpd does not need a device access
PrivateDevices=yes
# files in /tmp should not be shared with other programs.
PrivateTmp=yes
# minissdpd does not mount
PrivateMounts=yes
MemoryDenyWriteExecute=yes
ProtectSystem=full
ProtectHome=yes
ProtectHostname=yes
ProtectClock=yes
ProtectKernelTunables=yes
ProtectKernelModules=yes
ProtectKernelLogs=yes
ProtectControlGroups=yes
LockPersonality=yes
RestrictRealtime=yes
RestrictNamespaces=yes
RestrictSUIDSGID=yes
LimitNOFILE=20

#PrivateUsers=yes cannot be used

Type=exec
Environment="LANG=C.UTF-8" "ASAN_OPTIONS=detect_leaks=1:detect_stack_use_after_return=1:check_initialization_order=1:strict_string_checks=1:detect_invalid_pointer_pairs=2:abort_on_error=0:halt_on_error=0" "UBSAN_OPTIONS=print_stacktrace=1:halt_on_error=0"
ExecStart=/usr/sbin/minissdpd -d -6 -i enp0s25

[Install]
WantedBy=multi-user.target
```

**Comment by miniupnp** [comment]
Isn't it a way to redirect syslog() to the systemd logging system ?

**Comment by miniupnp** [comment]
Note : miniupnpd is already able to drop privilege thanks to libcap or libcap-ng : https://github.com/miniupnp/miniupnp/blob/master/miniupnpd/miniupnpd.c#L2334

**Comment by emojifreak** [comment]
> Isn't it a way to redirect syslog() to the systemd logging system ?

Of course, yes, any output to syslog() is logged.
My point was that, according to Debian changelog cited, when miniupnpd goes background (the default behavior), systemd does not track it well. My impression is that systemd can handle daemons running in foreground better than those in background (by forking).
Output of -d is too much for normal operation, but it is acceptable to me, and this feature request is *weak*.

**Comment by miniupnp** [comment]
I can easily add a build time option so _miniupnpd_ never goes to the background.

I think I can also add a build time option to not create the pid file

**Comment by emojifreak** [comment]
> I can easily add a build time option so _miniupnpd_ never goes to the background.

I believe this will help packaging of miniupnpd for distros with systemd being PID 1.

> I think I can also add a build time option to not create the pid file

As far as I understand, existence of a pid file harms nothing, while a pid file is necessary for systemd to track a daemon when the daemon goes background.

**Comment by miniupnp** [comment]
@emojifreak you may have a look at miniupnpd-2.2.0-RC1.tar.gz from https://miniupnp.tuxfamily.org/files/

**Comment by emojifreak** [comment]
Thank you. I started using RC1, and if I find an issue I will report it.

**Comment by emojifreak** [comment]
When I shut down I saw the following message. The binary was compiled without SAN checkers. The message seems related to the LSAN error previously discussed.

```
Jun 07 08:19:55 router1 systemd[1]: Stopping UPnP Internet Gateway Device Daemon...
Jun 07 08:19:55 router1 miniupnpd[614]: shutting down MiniUPnPd
Jun 07 08:19:55 router1 miniupnpd[614]: mnl_cb_run() FAILED: No such file or directory
Jun 07 08:19:55 router1 miniupnpd[614]: mnl_cb_run() FAILED: No such file or directory
```
