### ISSUE TITLE
Cannot assign requested address by minissdpd and miniupnpd on MACVLAN interface

### ISSUE THREAD

**Issue by emojifreak** [miniupnp/miniupnp#470]
When minissdpd and miniupnpd use a MACVLAN interface as their LAN interface, at their start-up they give

```
Jun 03 06:22:17 router1 minissdpd[1545]: minissdpd[1545]: ssdpDiscover: sendto: Cannot assign requested address
Jun 03 06:22:17 router1 minissdpd[1545]: ssdpDiscover: sendto: Cannot assign requested address
Jun 03 06:24:29 router1 miniupnpd[1602]: miniupnpd[1602]: PCPSendUnsolicitedAnnounce() IPv6 sendto(): Cannot assign requested addre>
Jun 03 06:24:29 router1 miniupnpd[1602]: PCPSendUnsolicitedAnnounce() IPv6 sendto(): Cannot assign requested address
```

But their operations does not seem to have any problem. The configurations of interfaces of the machine is as follows:

```
# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s25: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:1b:d3:88:9b:8f brd ff:ff:ff:ff:ff:ff
3: wls3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 00:24:d6:59:c6:68 brd ff:ff:ff:ff:ff:ff
    altname wlp10s0
4: myve1@enp0s25: <BROADCAST,MULTICAST,ALLMULTI,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 2e:84:b3:cc:ae:44 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.2/24 brd 192.168.1.255 scope global myve1
       valid_lft forever preferred_lft forever
    inet6 2400:4050:2ba1:ac00:2c84:b3ff:fecc:ae44/64 scope global dynamic mngtmpaddr noprefixroute 
       valid_lft 13439sec preferred_lft 11639sec
    inet6 2400:4050:2ba1:ac00:99:f0ae:8600:2c00/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::2c84:b3ff:fecc:ae44/64 scope link 
       valid_lft forever preferred_lft forever
5: ip6tnl0@NONE: <NOARP> mtu 1452 qdisc noop state DOWN group default qlen 1000
    link/tunnel6 :: brd :: permaddr a220:eaa1:40c3::
6: ip6tnl1@myve1: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1460 qdisc noqueue state UNKNOWN group default qlen 1000
    link/tunnel6 2400:4050:2ba1:ac00:99:f0ae:8600:2c00 peer 2001:380:a120::9 permaddr a3e:4471:2a04::
    inet 153.240.174.134/32 scope global ip6tnl1
       valid_lft forever preferred_lft forever
```

**Comment by miniupnp** [comment]
whare are the configurations of miniupnpd and minissdpd ?

**Comment by emojifreak** [comment]
> whare are the configurations of miniupnpd and minissdpd ?

minissdpd was started as `minissdpd -d -6 -i myve1`. Only `-i` option was changed from `enp0s25` to `myve1`.
miniupnpd was started as `miniupnpd -d -f /etc/miniupnpd/miniupnpd.conf`, which was unchanged. Config was changed as 
```
listening_ip=myve1
ext_ifname=ip6tnl1
ext_ip=153.240.174.134
```
Only `listening_ip` was changed from `enp0s25` to `myve1`.

By the way, use of macvlan is a common technique to allow host Linux to communicate with a VM using macvtap network, as https://access.redhat.com/documentation/en_us/red_hat_enterprise_linux/7/html/virtualization_deployment_and_administration_guide/sect-troubleshooting-common_libvirt_errors_and_troubleshooting#sect-Guest_can_reach_outside_network_but_cannot_reach_host_when_using_macvtap_interface

**Comment by emojifreak** [comment]
This issue stops if `minissdpd` is started WITHOUT `-6` and miniupnpd is compiled WITHOUT `--ipv6`.

**Comment by miniupnp** [comment]
are you sure the interface driver properly implements IPv6 multicast ?

**Comment by emojifreak** [comment]
> are you sure the interface driver properly implements IPv6 multicast ?

Unsure. But MACVLAN has been used for 10 years in the standard Linux kernels, so I suppose it does ...

https://forums.docker.com/t/is-multicast-possible-with-macvlan/55496
https://superuser.com/questions/944678/how-to-configure-macvtap-to-let-it-pass-multicast-packet-correctly
https://patchwork.ozlabs.org/project/netdev/patch/1408122299-29632-1-git-send-email-vyasevic@redhat.com/

The above links also suggest it does... On the other hand, my configuration could have errors. `/sbin/ip` shows below:

```
# ip l show dev myve1
5: myve1@enp0s25: <BROADCAST,MULTICAST,ALLMULTI,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 2e:84:b3:cc:ae:44 brd ff:ff:ff:ff:ff:ff
# ip a show dev myve1
5: myve1@enp0s25: <BROADCAST,MULTICAST,ALLMULTI,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 2e:84:b3:cc:ae:44 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.2/24 brd 192.168.1.255 scope global myve1
       valid_lft forever preferred_lft forever
    inet6 2400:4050:2ba1:ac00:2c84:b3ff:fecc:ae44/64 scope global dynamic mngtmpaddr noprefixroute 
       valid_lft 13793sec preferred_lft 11993sec
    inet6 2400:4050:2ba1:ac00:99:f0ae:8600:2c00/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::2c84:b3ff:fecc:ae44/64 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by miniupnp** [comment]
I do think it is a problem of macvlan multicast support with ipv6.
- https://discuss.linuxcontainers.org/t/macvlan-and-multicast-between-host-and-guest/16158/4
- https://lore.kernel.org/netdev/CAGnHSEmu2iYnRzFfKA9iT585M1GnCHCxY3Riztu+oDZyb0whUA@mail.gmail.com/T/
