### ISSUE TITLE
Granularity of logging levels

### ISSUE THREAD

**Issue by xcasxcursex** [miniupnp/miniupnp#477]
Having configured a new router to use miniupnpd, but being mindful of security, I checked the logs to confirm that queries to the server, and failed attempts of clients to map to illegal addresses, were being logged. Sadly, they were not. These events are logged at info level, and as such were filtered out. 

In order to monitor potentially threatening activity of the service, I needed to use the -d option, which did provide the desired insight into the service's activity, but also included overly-detailed information down to individual HTTP requests. It seems that my only choices are 'too little' or 'too much'.

I hope you would consider a small alteration of the logging levels, such that the service can be monitored for a summary of activity, without showing excessive detail. The extra detail could be left behind the -d flag filter. Whether this is done by moving some messages up a level or down, and/or moving the level of the filter applied by -d, I would leave in your capable hands.

In simple terms: It would be good to monitor what the service is doing on a superficial level, without having to view every action it takes.

For example:

Now:
No -d option:
`
`

With -d option:
```
Jun  8 08:41:02 ubnt miniupnpd[6471]: SSDP M-SEARCH from 192.168.1.2:61297 ST: urn:schemas-upnp-org:device:InternetGatewayDevice:1
Jun  8 08:41:04 ubnt miniupnpd[6471]: HTTP REQUEST from 192.168.1.2:57192 : GET /rootDesc.xml (HTTP/1.1)
Jun  8 08:41:04 ubnt miniupnpd[6471]: HTTP REQUEST from 192.168.1.2:57193 : POST /ctl/IPConn (HTTP/1.1)
Jun  8 08:41:04 ubnt miniupnpd[6471]: SOAPAction: urn:schemas-upnp-org:service:WANIPConnection:1#GetStatusInfo
Jun  8 08:41:04 ubnt miniupnpd[6471]: HTTP REQUEST from 192.168.1.2:57194 : POST /ctl/IPConn (HTTP/1.1)
Jun  8 08:41:04 ubnt miniupnpd[6471]: SOAPAction: urn:schemas-upnp-org:service:WANIPConnection:1#GetExternalIPAddress
Jun  8 08:41:04 ubnt miniupnpd[6471]: HTTP REQUEST from 192.168.1.2:57195 : POST /ctl/IPConn (HTTP/1.1)
Jun  8 08:41:04 ubnt miniupnpd[6471]: SOAPAction: urn:schemas-upnp-org:service:WANIPConnection:1#GetExternalIPAddress
Jun  8 08:41:04 ubnt miniupnpd[6471]: HTTP REQUEST from 192.168.1.2:57196 : POST /ctl/IPConn (HTTP/1.1)
Jun  8 08:41:04 ubnt miniupnpd[6471]: SOAPAction: urn:schemas-upnp-org:service:WANIPConnection:1#AddPortMapping
Jun  8 08:41:04 ubnt miniupnpd[6471]: Client 192.168.1.2 tried to redirect port to 192.168.1.6
Jun  8 08:41:04 ubnt miniupnpd[6471]: Returning UPnPError 718: ConflictInMappingEntry
```

Future:
No -d option:
```
Jun  8 08:41:02 ubnt miniupnpd[6471]: SSDP M-SEARCH from 192.168.1.2:61297 ST: urn:schemas-upnp-org:device:InternetGatewayDevice:1
Jun  8 08:41:04 ubnt miniupnpd[6471]: Client 192.168.1.2 tried to redirect port to 192.168.1.6
Jun  8 08:41:04 ubnt miniupnpd[6471]: Returning UPnPError 718: ConflictInMappingEntry
```

With -d option:
```
Jun  8 08:41:02 ubnt miniupnpd[6471]: SSDP M-SEARCH from 192.168.1.2:61297 ST: urn:schemas-upnp-org:device:InternetGatewayDevice:1
Jun  8 08:41:04 ubnt miniupnpd[6471]: HTTP REQUEST from 192.168.1.2:57192 : GET /rootDesc.xml (HTTP/1.1)
Jun  8 08:41:04 ubnt miniupnpd[6471]: HTTP REQUEST from 192.168.1.2:57193 : POST /ctl/IPConn (HTTP/1.1)
Jun  8 08:41:04 ubnt miniupnpd[6471]: SOAPAction: urn:schemas-upnp-org:service:WANIPConnection:1#GetStatusInfo
Jun  8 08:41:04 ubnt miniupnpd[6471]: HTTP REQUEST from 192.168.1.2:57194 : POST /ctl/IPConn (HTTP/1.1)
Jun  8 08:41:04 ubnt miniupnpd[6471]: SOAPAction: urn:schemas-upnp-org:service:WANIPConnection:1#GetExternalIPAddress
Jun  8 08:41:04 ubnt miniupnpd[6471]: HTTP REQUEST from 192.168.1.2:57195 : POST /ctl/IPConn (HTTP/1.1)
Jun  8 08:41:04 ubnt miniupnpd[6471]: SOAPAction: urn:schemas-upnp-org:service:WANIPConnection:1#GetExternalIPAddress
Jun  8 08:41:04 ubnt miniupnpd[6471]: HTTP REQUEST from 192.168.1.2:57196 : POST /ctl/IPConn (HTTP/1.1)
Jun  8 08:41:04 ubnt miniupnpd[6471]: SOAPAction: urn:schemas-upnp-org:service:WANIPConnection:1#AddPortMapping
Jun  8 08:41:04 ubnt miniupnpd[6471]: Client 192.168.1.2 tried to redirect port to 192.168.1.6
Jun  8 08:41:04 ubnt miniupnpd[6471]: Returning UPnPError 718: ConflictInMappingEntry

```

Thanks :)

**Comment by miniupnp** [comment]
@xcasxcursex you can patch the call to `setlogmask` in _miniupnpd.c_

**Comment by xcasxcursex** [comment]
Thanks for the advice. Unfortunately I'm using a router for which sources are unavailable, so I'm stuck with what I have. I just thought I should make the feature request for others to enjoy in the future. 

Hopefully it would just be a few simple changes to log some messages as warning or notice, rather than info.

**Comment by miniupnp** [comment]
@xcasxcursex future versions will support -v / -vv command line flags

**Comment by xcasxcursex** [comment]
That's fantastic, thanks!

**Comment by miniupnp** [comment]
@nyetwurk what's your configuration ?  what command line flags ?
These look like debug messages, that are NOT outputted by default. You can also configure at the syslog.conf level.

**Comment by nyetwurk** [comment]
It looks like `-d` is passed as part of debian's systemd unit:
```
$ apt-cache policy miniupnpd
miniupnpd:
  Installed: 2.2.1-1
  Candidate: 2.2.1-1
  Version table:
 *** 2.2.1-1 500
        500 http://http.us.debian.org/debian unstable/main amd64 Packages
        500 http://http.us.debian.org/debian unstable/main i386 Packages
        100 /var/lib/dpkg/status
$ grep ExecStart= /lib/systemd/system/miniupnpd.service
ExecStart=/usr/sbin/miniupnpd -d -f /etc/miniupnpd/miniupnpd.conf $MiniUPnPd_OTHER_OPTIONS
```
It seems there is no way to run in foreground without `-d`?

**Comment by nyetwurk** [comment]
Does `start_daemon: false` in the config file foreground it w/o the verbose logging?

**Comment by miniupnp** [comment]
> Does `start_daemon=false` in the config file foreground it w/o the verbose logging?

I'm not aware of such `start_daemon` option.

there is a `--disable-fork` `configure` option :
https://github.com/miniupnp/miniupnp/blob/master/miniupnpd/Changelog.txt#L29
just rebuild using this option if you need to.
