### ISSUE TITLE
[BitComet] Failed: UPnP device not found

### ISSUE THREAD

**Issue by msoayu56** [miniupnp/miniupnp#480]
Version: latest (2.1.20191006-6)

**Comment by msoayu56** [comment]
If you need more information, please tell me. :-)

**Comment by miniupnp** [comment]
> If you need more information, please tell me. :-)

Well as you give no information, please give at least some information about the problem

**Comment by msoayu56** [comment]
> > If you need more information, please tell me. :-)
> 
> Well as you give no information, please give at least some information about the problem

![image](https://user-images.githubusercontent.com/38905616/85962145-b396b500-b9e1-11ea-80d8-17d488ae1e7e.png)
/etc/config
![image](https://user-images.githubusercontent.com/38905616/85962166-d1fcb080-b9e1-11ea-85cf-3f8a11c11167.png)
web miniupnp settings

**Comment by msoayu56** [comment]
![image](https://user-images.githubusercontent.com/38905616/85962525-cad6a200-b9e3-11ea-9720-653e33dc0ecf.png)
interfaces

![image](https://user-images.githubusercontent.com/38905616/85962384-015fed00-b9e3-11ea-9e6d-70667d3354e0.png)
'Presentation URL' is 192.168.1.1, but the router IP is 192.168.2.1, should I change it to http://192.168.2.1 ?

**Comment by miniupnp** [comment]
no OS, no log, no issue.
I'm closing.
I will reopen if there is a proper bug report
