### ISSUE TITLE
miniupnpcstrings.h does not exist

### ISSUE THREAD

**Issue by TrianglesPCT** [miniupnp/miniupnp#482]
I am new to this project and was trying to compile miniupnpc using the provided MSVC solution.  
It does not compile because it tries to

#include "miniupnpcstrings.h"

There is no such file, but there is one called "miniupnpcstrings.h.in"

Switching the include to this other file fixed compile problem.

**Comment by miniupnp** [comment]
miniupnpcstrings.h is generated during the build.

Are you using the MS Visual studio projects ?
`genminiupnpcstrings.vbs ` is generating the file
https://github.com/miniupnp/miniupnp/tree/master/miniupnpc/msvc
