### ISSUE TITLE
Does this library work correctly on Windows?

### ISSUE THREAD

**Issue by TrianglesPCT** [miniupnp/miniupnp#483]
After dealing with the various build issues getting miniupnp(client) building on Windows and now attempting to use it, the results seem very buggy..

I tried creating mapping using UPNP_AddPortMapping, but it only works once, the first time the computer is turned on after being off for a long time.

Also it has wrong settings as returned by UPNP_GetGenericPortMappingEntry, the request was for UDP, but the resulting mapping is using TCP, and the ports are different than was requested.

After this one "successful" run,  UPNP_AddPortMapping will always return -3 (UPNPCOMMAND_HTTP_ERROR).  

I've tried testing to see if any port mappings are present and interfering, but all the functions such as UPNP_GetGenericPortMappingEntry/UPNP_GetPortMappingNumberOfEntries/UPNP_GetListOfPortMappings state
that there are no port mappings.  I also tried deleting the previously created port mapping but that did nothing.

Windows seems to have its own COM library for dealing with UPNP but this library doesn't seem to use it, which makes me wonder if it isn't doing something slightly off.

**Comment by miniupnp** [comment]
why don't you use the windows UPNP COM library ?

I can't help you without a more precise bug report.
