### ISSUE TITLE
After updating the rules using the AddPortMaping method, the rules in the filter are missing ACCEPT.

### ISSUE THREAD

**Issue by zyp2015** [miniupnp/miniupnp#487]
step 1
AddPortMaping ：10000  tcp  10000 192.168.3.168
-A PRE_UPNP_WAN -p tcp -m tcp --dport 10000 -j DNAT --to-destination 192.168.3.168:10000
-A FWD_UPNP_WAN -d 192.168.3.168/32 -p tcp -m tcp --dport 10000 -j ACCEPT

step 2
AddPortMaping ：10000  tcp  10001 192.168.3.168
-A PRE_UPNP_WAN -p tcp -m tcp --dport 10000 -j DNAT --to-destination 192.168.3.168:10001
-A FWD_UPNP_WAN -d 192.168.3.168/32 -p tcp -m tcp --dport 10001

As above, accept is lost after the update.

**Comment by zyp2015** [comment]
After debugging：
iptcrdr.c  1885 line,
After the rule is converted by the kernel, the ACCEPT string is replaced. The target obtained from the kernel does not have a corresponding string, so when the rule is updated, the target is empty. Re-assign the string ACCEPT here.

**Comment by miniupnp** [comment]
@zyp2015 which is your versions of kernel / netfilter / iptables ?

I don't have currently a linux box to test. could you add log messages around 
https://github.com/miniupnp/miniupnp/blob/master/miniupnpd/netfilter/iptcrdr.c#L1857 :
`syslog(LOG_DEBUG, "%s %s", target->u.user.name, iptc_get_target(e, h));`

**Comment by miniupnp** [comment]
https://github.com/miniupnp/miniupnp/commit/b44e5e7a83db6df37a75dc66514dd5677e83c1fc was supposed to fix the issue. Are you sure your build includes it ?

**Comment by miniupnp** [comment]
@zyp2015  ?
