### ISSUE TITLE
Missing testaddr_is_reserved.c in official miniupnpc tarball

### ISSUE THREAD

**Issue by ffontaine** [miniupnp/miniupnp#493]
testaddr_is_reserved.c is not in miniupnpc official tarball (i.e. http://miniupnp.free.fr/files/download.php?file=miniupnpc-2.1.20200928.tar.gz) resulting in the following build failure:

```
CMake Error at CMakeLists.txt:195 (add_executable):
  Cannot find source file:

    testaddr_is_reserved.c
```

**Comment by miniupnp** [comment]
it is now fixed with : https://miniupnp.tuxfamily.org/files/download.php?file=miniupnpc-2.1.20201016.tar.gz
