### ISSUE TITLE
Fix a couple of BSD build issues

### ISSUE THREAD

**Issue by bsd-source** [miniupnp/miniupnp#495]
Commit 1baa952 was suppose to fix the BSD man page but there was a small error in the pull request. The pull request inadvertently changed the original pfSense patch that is currently in their repo. Below will fix the issue. 

This doesn't work and will cause the build to fail:
$(INSTALL) -m miniupnpd.8 $(DESTDIR)$(INSTALLMANDIR)/man8/miniupnpd.8

Is should be:
$(INSTALL) miniupnpd.8 $(DESTDIR)$(INSTALLMANDIR)/man8/miniupnpd.8

Also the FreeBSD /usr/ports/net/miniupnpd would not require any patches if below is changed in the miniupnpd Makefile.bsd file. CFLAGS is needed for the FreeBSD ports Makefile.
 
This code:
miniupnpd: $(ALLOBJS)
        $(CC) $(LDFLAGS) -o $@ $(ALLOBJS) $(LIBS)

To this code:
miniupnpd: $(ALLOBJS)
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $(ALLOBJS) $(LIBS)

Thank you!

**Comment by miniupnp** [comment]
@bsd-source shouldn't it be `$(INSTALL) -m 644 miniupnpd.8 $(DESTDIR)$(INSTALLMANDIR)/man8/miniupnpd.8` ?

**Comment by bsd-source** [comment]
> @bsd-source shouldn't it be `$(INSTALL) -m 644 miniupnpd.8 $(DESTDIR)$(INSTALLMANDIR)/man8/miniupnpd.8` ?

Yes this would be more appropriate. Thanks.
