### ISSUE TITLE
portinuse.c build error with OpenBSD 6.8

### ISSUE THREAD

**Issue by bsd-source** [miniupnp/miniupnp#496]
I uncommented /*#define CHECK_PORTINUSE*/ in the miniupnpd configure file and nothing else and attempted to build miniupnpd-2.2.0-RC2 from source code using OpenBSD 6.8. I used only the make command and the build process produced the following errors:

> cc  -I. -O2 -pipe  -Wall -W -Wstrict-prototypes -fno-common -c -o miniupnpd.o ./miniupnpd.c
cc  -I. -O2 -pipe  -Wall -W -Wstrict-prototypes -fno-common -c -o upnphttp.o ./upnphttp.c
cc  -I. -O2 -pipe  -Wall -W -Wstrict-prototypes -fno-common -c -o upnpdescgen.o ./upnpdescgen.c
cc  -I. -O2 -pipe  -Wall -W -Wstrict-prototypes -fno-common -c -o upnpsoap.o ./upnpsoap.c
cc  -I. -O2 -pipe  -Wall -W -Wstrict-prototypes -fno-common -c -o upnpredirect.o ./upnpredirect.c
cc  -I. -O2 -pipe  -Wall -W -Wstrict-prototypes -fno-common -c -o getifaddr.o ./getifaddr.c
cc  -I. -O2 -pipe  -Wall -W -Wstrict-prototypes -fno-common -c -o daemonize.o ./daemonize.c
cc  -I. -O2 -pipe  -Wall -W -Wstrict-prototypes -fno-common -c -o upnpglobalvars.o ./upnpglobalvars.c
cc  -I. -O2 -pipe  -Wall -W -Wstrict-prototypes -fno-common -c -o options.o ./options.c
cc  -I. -O2 -pipe  -Wall -W -Wstrict-prototypes -fno-common -c -o upnppermissions.o ./upnppermissions.c
cc  -I. -O2 -pipe  -Wall -W -Wstrict-prototypes -fno-common -c -o minissdp.o ./minissdp.c
cc  -I. -O2 -pipe  -Wall -W -Wstrict-prototypes -fno-common -c -o natpmp.o ./natpmp.c
cc  -I. -O2 -pipe  -Wall -W -Wstrict-prototypes -fno-common -c -o pcpserver.o ./pcpserver.c
cc  -I. -O2 -pipe  -Wall -W -Wstrict-prototypes -fno-common -c -o upnpevents.o ./upnpevents.c
cc  -I. -O2 -pipe  -Wall -W -Wstrict-prototypes -fno-common -c -o upnputils.o ./upnputils.c
cc  -I. -O2 -pipe  -Wall -W -Wstrict-prototypes -fno-common -c -o getconnstatus.o ./getconnstatus.c
cc  -I. -O2 -pipe  -Wall -W -Wstrict-prototypes -fno-common -c -o upnpstun.o ./upnpstun.c
./upnpstun.c:255:86: warning: format specifies type 'long' but the argument has type 'time_t' (aka 'long long') [-Wformat]
                syslog(LOG_DEBUG, "%s: waiting %ld secs and %ld usecs", "wait_for_stun_responses", timeout.tv_sec, timeout.tv_usec);
                                               ~~~                                                 ^~~~~~~~~~~~~~
                                               %lld
1 warning generated.
cc  -I. -O2 -pipe  -Wall -W -Wstrict-prototypes -fno-common -c -o upnppinhole.o ./upnppinhole.c
cc  -I. -O2 -pipe  -Wall -W -Wstrict-prototypes -fno-common -c -o asyncsendto.o ./asyncsendto.c
cc  -I. -O2 -pipe  -Wall -W -Wstrict-prototypes -fno-common -c -o portinuse.o ./portinuse.c
./portinuse.c:166:9: warning: implicit declaration of function 'CIRCLEQ_FIRST' is invalid in C99 [-Wimplicit-function-declaration]
        next = CIRCLEQ_FIRST(&table.inpt_queue); /*TAILQ_FIRST(&table.inpt_queue);*/
               ^
./portinuse.c:166:7: warning: incompatible integer to pointer conversion assigning to 'struct inpcb *' from 'int' [-Wint-conversion]
        next = CIRCLEQ_FIRST(&table.inpt_queue); /*TAILQ_FIRST(&table.inpt_queue);*/
             ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./portinuse.c:174:10: warning: implicit declaration of function 'CIRCLEQ_NEXT' is invalid in C99 [-Wimplicit-function-declaration]
                next = CIRCLEQ_NEXT(&inpcb, inp_queue); /*TAILQ_NEXT(&inpcb, inp_queue);*/
                       ^
./portinuse.c:174:31: error: use of undeclared identifier 'inp_queue'
                next = CIRCLEQ_NEXT(&inpcb, inp_queue); /*TAILQ_NEXT(&inpcb, inp_queue);*/
                                            ^
3 warnings and 1 error generated.
*** Error 1 in /usr/ports/pobj/miniupnpd-2.2.0-RC2/miniupnpd-2.2.0-RC2 (Makefile:260 'portinuse.o')



Had to use quote insert quote instead of insert code because the code did not format properly for this build issue I'm submitting.

**Edit:** I'll get back to you on this. I removed kvm from the OpenBSD miniupnpd Makefile a couple of days ago and is probably the issue. Why checking if a port is in use for OpenBSD is dependent on kvm is beyond me. Seems to be a lack of coding logic for when kvm is not in use.

**Comment by bsd-source** [comment]
Put kvm back into the OpenBSD miniupnpd ports Makefile and it built without any errors.

**Comment by bsd-source** [comment]
I was wrong about this. I think something is wrong here.

**Comment by miniupnp** [comment]
https://man.openbsd.org/OpenBSD-6.8/queue.3

CIRCLEQ_* functions has been removed. The code should be rewritten

**Comment by bsd-source** [comment]
Since OpenBSD 5.5 release "All CIRCLEQ uses replaced with TAILQ". I'm not sure why I wasn't able to find that doing a google search earlier. Anyways, just for a test I replaced both CIRCLEQ_FIRST WITH TAILQ_FIRST and the portinuse.c did not produce and error although changing CIRCLEQ_NEXT TO TAILQ_NEXT produced an error. See my build below using miniupnpd master source code dated October 28th, 2020.

> cc  -I. -O2 -pipe  -Wall -W -Wstrict-prototypes -fno-common -c -o miniupnpd.o ./miniupnpd.c
cc  -I. -O2 -pipe  -Wall -W -Wstrict-prototypes -fno-common -c -o upnphttp.o ./upnphttp.c
cc  -I. -O2 -pipe  -Wall -W -Wstrict-prototypes -fno-common -c -o upnpdescgen.o ./upnpdescgen.c
cc  -I. -O2 -pipe  -Wall -W -Wstrict-prototypes -fno-common -c -o upnpsoap.o ./upnpsoap.c
cc  -I. -O2 -pipe  -Wall -W -Wstrict-prototypes -fno-common -c -o upnpredirect.o ./upnpredirect.c
cc  -I. -O2 -pipe  -Wall -W -Wstrict-prototypes -fno-common -c -o getifaddr.o ./getifaddr.c
cc  -I. -O2 -pipe  -Wall -W -Wstrict-prototypes -fno-common -c -o daemonize.o ./daemonize.c
cc  -I. -O2 -pipe  -Wall -W -Wstrict-prototypes -fno-common -c -o upnpglobalvars.o ./upnpglobalvars.c
cc  -I. -O2 -pipe  -Wall -W -Wstrict-prototypes -fno-common -c -o options.o ./options.c
cc  -I. -O2 -pipe  -Wall -W -Wstrict-prototypes -fno-common -c -o upnppermissions.o ./upnppermissions.c
cc  -I. -O2 -pipe  -Wall -W -Wstrict-prototypes -fno-common -c -o minissdp.o ./minissdp.c
cc  -I. -O2 -pipe  -Wall -W -Wstrict-prototypes -fno-common -c -o natpmp.o ./natpmp.c
cc  -I. -O2 -pipe  -Wall -W -Wstrict-prototypes -fno-common -c -o pcpserver.o ./pcpserver.c
cc  -I. -O2 -pipe  -Wall -W -Wstrict-prototypes -fno-common -c -o upnpevents.o ./upnpevents.c
cc  -I. -O2 -pipe  -Wall -W -Wstrict-prototypes -fno-common -c -o upnputils.o ./upnputils.c
cc  -I. -O2 -pipe  -Wall -W -Wstrict-prototypes -fno-common -c -o getconnstatus.o ./getconnstatus.c
cc  -I. -O2 -pipe  -Wall -W -Wstrict-prototypes -fno-common -c -o upnpstun.o ./upnpstun.c
./upnpstun.c:255:86: warning: format specifies type 'long' but the argument has type 'time_t' (aka 'long long') [-Wformat]
                syslog(LOG_DEBUG, "%s: waiting %ld secs and %ld usecs", "wait_for_stun_responses", timeout.tv_sec, timeout.tv_usec);
                                               ~~~                                                 ^~~~~~~~~~~~~~
                                               %lld
1 warning generated.
cc  -I. -O2 -pipe  -Wall -W -Wstrict-prototypes -fno-common -c -o upnppinhole.o ./upnppinhole.c
cc  -I. -O2 -pipe  -Wall -W -Wstrict-prototypes -fno-common -c -o asyncsendto.o ./asyncsendto.c
cc  -I. -O2 -pipe  -Wall -W -Wstrict-prototypes -fno-common -c -o portinuse.o ./portinuse.c
./portinuse.c:175:8: error: called object type 'struct inpcb *' is not a function or function pointer
                next TAILQ_NEXT(&inpcb, inp_queue);     /*TAILQ_NEXT(&inpcb, inp_queue);*/
                ~~~~ ^
/usr/include/sys/queue.h:430:33: note: expanded from macro 'TAILQ_NEXT'
#define TAILQ_NEXT(elm, field)          ((elm)->field.tqe_next)
                                        ^
1 error generated.
*** Error 1 in /usr/ports/pobj/miniupnpd-5/miniupnpd-miniupnpd-5 (Makefile:260 'portinuse.o')


Thanks for looking into this!

**Comment by miniupnp** [comment]
@bsd-source could you check if my patch fixes it for you ?

**Comment by bsd-source** [comment]
I just tested the patch and it builds portinuse.c without any problems. Thanks for fixing this!
