### ISSUE TITLE
Releases section is not good

### ISSUE THREAD

**Issue by Neustradamus** [miniupnp/miniupnp#515]
Currently we see only miniupnpc 2.1.0 (7 May 2018):
- https://github.com/miniupnp/miniupnp/releases/tag/miniupnpc_2_1

Can you add changelog for 2.2.0 releases?
- https://github.com/miniupnp/miniupnp/releases

It is possible to have only one tag for miniupnpc_2_2_0 and miniupnpd_2_2_0?

It is easy to do one tag and have all builds in one section like other softwares/librairies?

Thanks in advance.

PS: In the same time, the organization is not done.

**Comment by bsd-source** [comment]
I've come to the conclusion that Neustradamus works for github.com. See other repository issues on github that Neustradamus has opened which seem to be very annoying and persistent github policing.

**Comment by Neustradamus** [comment]
@bsd-source: You have done a mistake but for a perfect project, it is important to have good releases.

Some examples: 
- https://github.com/nextcloud/server/releases
- https://github.com/brave/brave-browser/releases
- https://github.com/microsoft/PowerToys/releases
- https://github.com/atom/atom/releases

Thanks.

**Comment by miniupnp** [comment]
Indeed I do not use github "release".
Source packages are available at https://miniupnp.tuxfamily.org/files/
