### ISSUE TITLE
stun server timout adjustment

### ISSUE THREAD

**Issue by professor-jonny** [miniupnp/miniupnp#519]
Is it possible to adjust the timeout for a response to a stun request ?

I find that 3 seconds is not enough to traverse my current CGN but works with an external stun server if i set the timout to 10 seconds.

**Comment by pali** [comment]
Could you explain your CGN setup a little bit more? I have not caught when is 3 seconds not enough.

**Comment by professor-jonny** [comment]
My openwrt router is behind a providers router that I cant replace that is behind a carrier grade network on the providers side.
Im currently playing with a connection via satellite and it takes some time to traverse  22000km up to the satellite and another 22000km to traverse back and the routing at the providers base station satellite routing etc....

I'm wondering if we could adjust the time out value for the stun server via a parsing a config parameter.

below is my log output with miniupnpd in openwrt.

`
daemon.info miniupnpd[4405]: system uptime is 44 seconds
daemon.info miniupnpd[4405]: Reloading rules from lease file
daemon.info miniupnpd[4405]: version 2.2.1 starting NAT-PMP/PCP UPnP-IGD ext if eth1 BOOTID=1610128827
daemon.info miniupnpd[4405]: specific IPv6 ext if
daemon.info miniupnpd[4405]: STUN: Performing with host=stun.2talk.co.nz and port=3478 ...
daemon.debug miniupnpd[4405]: resolve_stun_host: stun.2talk.co.nz:3478 => 27.111.14.93:3478
daemon.info miniupnpd[4405]: perform_stun: local ports 49578 54904 56039 46784
daemon.debug miniupnpd[4405]: wait_for_stun_responses: waiting 3 secs and 0 usecs
daemon.debug miniupnpd[4405]: wait_for_stun_responses: select(): no more responses
daemon.debug miniupnpd[4405]: wait_for_stun_responses: waiting 3 secs and 0 usecs
daemon.debug miniupnpd[4405]: wait_for_stun_responses: select(): no more responses
daemon.debug miniupnpd[4405]: wait_for_stun_responses: waiting 3 secs and 0 usecs
daemon.debug miniupnpd[4405]: wait_for_stun_responses: select(): no more responses
`

**Comment by pali** [comment]
Currently stun timeout is 9s (there are 3 attempts and every one is waiting for 3s). I have tried this your stun server stun.2talk.co.nz 3478 and it does not work even for me. I tried to put this stun server into other applications and they were not able to contact it too.

So are you sure that this your stun server stun.2talk.co.nz is working? Can you try to use different stun server? For example stun.stunprotocol.org or stun.sipgate.net.

**Comment by professor-jonny** [comment]
My stun server is no acessable unless you are with our provider I get the same results with the servers above.
if I use a 4g connection connection as opposed to satellite I get the below response:

`
daemon.info miniupnpd[4427]: STUN: Performing with host=stun.stunprotocol.org and port=3478 ...
daemon.debug miniupnpd[4427]: resolve_stun_host: stun.stunprotocol.org:3478 => 18.191.223.12:3478
daemon.info miniupnpd[4427]: perform_stun: local ports 34574 54385 41687 55862
daemon.debug miniupnpd[4427]: wait_for_stun_responses: waiting 3 secs and 0 usecs
daemon.debug miniupnpd[4427]: wait_for_stun_responses: received responses: 1
daemon.debug miniupnpd[4427]: wait_for_stun_responses: waiting 3 secs and 0 usecs
daemon.debug miniupnpd[4427]: wait_for_stun_responses: select(): no more responses
daemon.debug miniupnpd[4427]: wait_for_stun_responses: waiting 3 secs and 0 usecs
daemon.debug miniupnpd[4427]: wait_for_stun_responses: select(): no more responses
daemon.debug miniupnpd[4427]: wait_for_stun_responses: waiting 3 secs and 0 usecs
daemon.debug miniupnpd[4427]: wait_for_stun_responses: select(): no more responses
daemon.debug miniupnpd[4427]: parse_stun_response: Type 0x0101, Length 48, Magic Cookie 2112a442
Sun Jan 10 09:48:21 2021 daemon.debug miniupnpd[4427]: parse_stun_response: MAPPED-ADDRESS 115.189.81.247:46664
Sun Jan 10 09:48:21 2021 daemon.debug miniupnpd[4427]: parse_stun_response: RESPONSE-ORIGIN 18.191.223.12:3478
daemon.debug miniupnpd[4427]: parse_stun_response: OTHER-ADDRESS 18.219.110.18:3479
daemon.debug miniupnpd[4427]: parse_stun_response: XOR-MAPPED-ADDRESS 115.189.81.247:46664
daemon.notice miniupnpd[4427]: perform_stun: 1 response out of 4 received
daemon.notice miniupnpd[4427]: perform_stun: #0 external address or port changed
daemon.warn miniupnpd[4427]: STUN: ext interface eth1 with IP address 192.168.1.100 is now behind restrictive NAT with public IP address 115.189.81.247: Port forwarding is now impossible
daemon.notice miniupnpd[4427]: HTTP listening on port 5000
daemon.warn miniupnpd[4427]: no HTTP IPv6 address, disabling IPv6
daemon.notice miniupnpd[4427]: Listening for NAT-PMP/PCP traffic on port 5351


`

**Comment by pali** [comment]
Thank you for explanation, now it makes sense!

What is the ping latence over the satellite connection to that your stun server?

Can you try to increase attempts at this line
https://github.com/miniupnp/miniupnp/blob/7fc8d3268d79787a5dcb01e95a2a9357a443b06a/miniupnpd/upnpstun.c#L449
from `j < 3` to e.g. `j < 6` (or 10)? If it helps?

**Comment by professor-jonny** [comment]
Thanks i will look for the reference in the miniupnpd in the feed source and modify.

The ping on satellite it is about 600ms on a good day.

**Comment by professor-jonny** [comment]
Stun is now working and getting a response by compling wiht a lagger time value but sadly upnp does not seem to create redirects it seems to be a common theme with openwrt 19.x on the openwrt forums.

i just get the  below log over and over and it just fills up the system log with this upnp request:
`
<e:propertyset xmlns:e="urn:schemas-upnp-org:event-1-0"><e:property><DefaultConnectionService>uuid:78775f9e-c20d-4a56-943c-6126cbf626db:WANConnectionDevice:2,urn:upnp-org:serviceId:WANIPConn1</DefaultConnectionService></e:property></e:propertyset>
Sun Jan 17 15:25:40 2021 daemon.debug miniupnpd[8916]: upnpevents_selectfds: 0x41a30 4 10
Sun Jan 17 15:25:40 2021 daemon.debug miniupnpd[8916]: upnpevents_processfds: 0x41a30 4 10 1 0
Sun Jan 17 15:25:40 2021 daemon.debug miniupnpd[8916]: upnp_event_recv: (125bytes) HTTP/1.1 200 OK
 Server: Microsoft-HTTPAPI/2.0
 Date: Sun, 17 Jan 2021 02:25:40 GMT
 Connection: close
 Content-Length: 0
Sun Jan 17 15:25:41 2021 daemon.info miniupnpd[8916]: HTTP REQUEST from [::ffff:192.168.2.189]:49492 : GET /DP.xml (HTTP/1.1)
Sun Jan 17 15:25:41 2021 daemon.debug miniupnpd[8916]: Host: 192.168.2.1:5000
Sun Jan 17 15:25:41 2021 daemon.info miniupnpd[8916]: HTTP REQUEST from [::ffff:192.168.2.189]:50054 : SUBSCRIBE /evt/DP (HTTP/1.1)
Sun Jan 17 15:25:41 2021 daemon.debug miniupnpd[8916]: Host: 192.168.2.1:5000
Sun Jan 17 15:25:41 2021 daemon.debug miniupnpd[8916]: ProcessHTTPSubscribe /evt/DP
Sun Jan 17 15:25:41 2021 daemon.debug miniupnpd[8916]: Callback '<http://192.168.2.189:2869/upnp/eventing/nzxnkfeblp>' Timeout=1800
Sun Jan 17 15:25:41 2021 daemon.debug miniupnpd[8916]: SID ''
Sun Jan 17 15:25:41 2021 daemon.debug miniupnpd[8916]: addSubscriber(/evt/DP, http://192.168.2.189:2869/upnp/eventing/nzxnkfeblp, 1800)
Sun Jan 17 15:25:41 2021 daemon.debug miniupnpd[8916]: generated sid=uuid:3c822217-afe8-4b62-b634-e28355fbf19a
Sun Jan 17 15:25:41 2021 daemon.debug miniupnpd[8916]: upnpevents_selectfds: 0x41ab0 1 10
Sun Jan 17 15:25:41 2021 daemon.debug miniupnpd[8916]: upnp_event_notify_connect: '192.168.2.189' 2869 '/upnp/eventing/nzxnkfeblp'
Sun Jan 17 15:25:41 2021 daemon.debug miniupnpd[8916]: upnpevents_processfds: 0x41ab0 2 10 0 1
Sun Jan 17 15:25:41 2021 daemon.debug miniupnpd[8916]: upnp_event_send: sending event notify message to 192.168.2.189:2869
Sun Jan 17 15:25:41 2021 daemon.debug miniupnpd[8916]: upnp_event_send: msg: NOTIFY /upnp/eventing/nzxnkfeblp HTTP/1.1
 Host: 192.168.2.189:2869
 Content-Type: text/xml; charset="utf-8"
 Content-Length: 125
 NT: upnp:event
 NTS: upnp:propchange
 SID: uuid:3c822217-afe8-4b62-b634-e28355fbf19a
 SEQ: 0
 Connection: close
 Cache-Control: no-cache
 
`

**Comment by pali** [comment]
> Stun is now working and getting a response by compling wiht a lagger time value

Which value helped? Can you post stun output?

**Comment by professor-jonny** [comment]
I adjusted the value to 9 and built from source locally using ubuntu under WSL in windows 10 this was the output  that seemed to work:

`Sun Jan 17 15:25:30 2021 daemon.info miniupnpd[8916]: system uptime is 1579 seconds
Sun Jan 17 15:25:30 2021 daemon.info miniupnpd[8916]: Reloading rules from lease file
Sun Jan 17 15:25:30 2021 daemon.info miniupnpd[8916]: version 2.2.1 starting NAT-PMP/PCP UPnP-IGD ext if eth1 BOOTID=1610850330
Sun Jan 17 15:25:30 2021 daemon.info miniupnpd[8916]: specific IPv6 ext if
Sun Jan 17 15:25:30 2021 daemon.info miniupnpd[8916]: STUN: Performing with host=host=stun.2talk.co.nz and port=3478 ...
Sun Jan 17 15:25:30 2021 daemon.debug miniupnpd[8916]: resolve_stun_host: host=stun.2talk.co.nz:3478 => 18.191.223.12:3478
Sun Jan 17 15:25:30 2021 daemon.info miniupnpd[8916]: perform_stun: local ports 34574 54385 41687 55862
Sun Jan 17 15:25:30 2021 daemon.debug miniupnpd[8916]: wait_for_stun_responses: waiting 9 secs and 0 usecs
Sun Jan 17 15:25:30 2021 daemon.debug miniupnpd[8916]: wait_for_stun_responses: received responses: 1
Sun Jan 17 15:25:30 2021 daemon.debug miniupnpd[8916]: wait_for_stun_responses: waiting 9 secs and 0 usecs
Sun Jan 17 15:25:33 2021 daemon.debug miniupnpd[8916]: wait_for_stun_responses: select(): no more responses
Sun Jan 17 15:25:33 2021 daemon.debug miniupnpd[8916]: wait_for_stun_responses: waiting 9 secs and 0 usecs
Sun Jan 17 15:25:36 2021 daemon.debug miniupnpd[8916]: wait_for_stun_responses: select(): no more responses
Sun Jan 17 15:25:36 2021 daemon.debug miniupnpd[8916]: wait_for_stun_responses: waiting 9 secs and 0 usecs
Sun Jan 17 15:25:39 2021 daemon.debug miniupnpd[8916]: wait_for_stun_responses: select(): no more responses
Sun Jan 17 15:25:40 2021 daemon.debug miniupnpd[8916]: parse_stun_response: Type 0x0101, Length 48, Magic Cookie 2112a442
Sun Jan 17 15:25:40 2021 daemon.debug miniupnpd[8916]: parse_stun_response: MAPPED-ADDRESS 115.189.135.58:53259
Sun Jan 17 15:25:40 2021 daemon.debug miniupnpd[8916]: parse_stun_response: RESPONSE-ORIGIN 115.189.135.12:3478
Sun Jan 17 15:25:40 2021 daemon.debug miniupnpd[8916]: parse_stun_response: OTHER-ADDRESS 115.198.143.66:3479
Sun Jan 17 15:25:40 2021 daemon.debug miniupnpd[8916]: parse_stun_response: XOR-MAPPED-ADDRESS 115.189.135.58:53259
Sun Jan 17 15:25:40 2021 daemon.notice miniupnpd[8916]: perform_stun: 1 response out of 4 received
Sun Jan 17 15:25:40 2021 daemon.notice miniupnpd[8916]: perform_stun: #0 external address or port changed
Sun Jan 17 15:25:40 2021 daemon.warn miniupnpd[8916]: STUN: ext interface eth1 with IP address 192.168.1.130 is now behind restrictive NAT with public IP address 115.189.135.58: Port forwarding is now impossible`

**Comment by pali** [comment]
You received response immediately in the same second as you have sent request, see:
```
Sun Jan 17 15:25:30 2021 daemon.info miniupnpd[8916]: STUN: Performing with host=host=stun.2talk.co.nz and port=3478 ...                                                                                                                                                                                                                                                   
Sun Jan 17 15:25:30 2021 daemon.debug miniupnpd[8916]: resolve_stun_host: host=stun.2talk.co.nz:3478 => 18.191.223.12:3478                                                                                                                                                                                                                                                 
Sun Jan 17 15:25:30 2021 daemon.info miniupnpd[8916]: perform_stun: local ports 34574 54385 41687 55862                                                                                                                                                                                                                                                                    
Sun Jan 17 15:25:30 2021 daemon.debug miniupnpd[8916]: wait_for_stun_responses: waiting 9 secs and 0 usecs                                                                                                                                                                                                                                                                 
Sun Jan 17 15:25:30 2021 daemon.debug miniupnpd[8916]: wait_for_stun_responses: received responses: 1
```
**received responses: 1**

So I think it should work without modification of _the value_. Could you please it again with original values?

And which version you have used in your first test https://github.com/miniupnp/miniupnp/issues/519#issuecomment-757106499? Have you used the latest version or with your custom patches?

**Comment by professor-jonny** [comment]
you are right it works with reverting the value to 3 now but buggered if I know why?
It would not work before?
I'm wondering if i had something messed up and a git pull fixed something? or there is some issue with my stun server?
I have switched to the one you mentioned above and it seems to work every time but i definatly could not get it to work previously except with an alternate program with alterin

**Comment by pali** [comment]
Maybe you have used older miniupnpd version and now after changing its code you have updated to the latest version? Or you have some other local patch previously which was breaking it?

You also have mentioned that you are using OpenWRT. I know that some (probably older) OpenWRT versions have incorrect iptables rules for miniupnpd which caused that miniupnpd was not able to open any port for incomming connection (so miniupnpd did not see response for stun packets and just timed out). Also OpenWRT has custom patches which could be reason why OpenWRT's miniupnpd version behave slightly different. (See e.g. comment on OpenWRT patch https://github.com/miniupnp/miniupnp/pull/511)

**Comment by professor-jonny** [comment]
stun is working now and it is giving me a reponce saying the ip adress of my gcnat at the providers end.
I think a git pull or updating the feeds may have sorted those issues out.

I'm using bleeding edge openwrt build from myown repo so the packages would be the latest available.

I am having issues with miniupnp opening up ports in the openwrt firewall it seems and im behind a CGnat like the link you post above, nothing ever shows up in the redirects i just get the chain rules when the upnp daemon starts.

I get this from the output of STUN:
`192.168.1.130 is now behind restrictive NAT with public IP address 115.189.135.58: Port forwarding is now impossible`
is this the reason for no redirects being established ?

The thing is with the factory router it opens up those ports and I get connection as verified with a external port test.
if i direct traffic to a port it seems to open them at the provider's nat automatically and get forwarded to me, Im not too sure what happens if two people request the same port behind the cgnat.

I do know certaine ones I cant open and I just try alternative ports.

I think the stock router blindly opens up ports on the wan side reguardless of the IP address and lets the nat handle the port forwarding?

With the openwrt router nothing seems to work.

I just get the below log over and over from my xbxox and it just fills up the system log with this which I guess is a upnp request from 192.168.2.189? (im new to openwrt):

`
<e:propertyset xmlns:e="urn:schemas-upnp-org:event-1-0"><e:property>uuid:78775f9e-c20d-4a56-943c-6126cbf626db:WANConnectionDevice:2,urn:upnp-org:serviceId:WANIPConn1</e:property></e:propertyset>
Sun Jan 17 15:25:40 2021 daemon.debug miniupnpd[8916]: upnpevents_selectfds: 0x41a30 4 10
Sun Jan 17 15:25:40 2021 daemon.debug miniupnpd[8916]: upnpevents_processfds: 0x41a30 4 10 1 0
Sun Jan 17 15:25:40 2021 daemon.debug miniupnpd[8916]: upnp_event_recv: (125bytes) HTTP/1.1 200 OK
Server: Microsoft-HTTPAPI/2.0
Date: Sun, 17 Jan 2021 02:25:40 GMT
Connection: close
Content-Length: 0
Sun Jan 17 15:25:41 2021 daemon.info miniupnpd[8916]: HTTP REQUEST from [::ffff:192.168.2.189]:49492 : GET /DP.xml (HTTP/1.1)
Sun Jan 17 15:25:41 2021 daemon.debug miniupnpd[8916]: Host: 192.168.2.1:5000
Sun Jan 17 15:25:41 2021 daemon.info miniupnpd[8916]: HTTP REQUEST from [::ffff:192.168.2.189]:50054 : SUBSCRIBE /evt/DP (HTTP/1.1)
Sun Jan 17 15:25:41 2021 daemon.debug miniupnpd[8916]: Host: 192.168.2.1:5000
Sun Jan 17 15:25:41 2021 daemon.debug miniupnpd[8916]: ProcessHTTPSubscribe /evt/DP
Sun Jan 17 15:25:41 2021 daemon.debug miniupnpd[8916]: Callback 'http://192.168.2.189:2869/upnp/eventing/nzxnkfeblp' Timeout=1800
Sun Jan 17 15:25:41 2021 daemon.debug miniupnpd[8916]: SID ''
Sun Jan 17 15:25:41 2021 daemon.debug miniupnpd[8916]: addSubscriber(/evt/DP, http://192.168.2.189:2869/upnp/eventing/nzxnkfeblp, 1800)
Sun Jan 17 15:25:41 2021 daemon.debug miniupnpd[8916]: generated sid=uuid:3c822217-afe8-4b62-b634-e28355fbf19a
Sun Jan 17 15:25:41 2021 daemon.debug miniupnpd[8916]: upnpevents_selectfds: 0x41ab0 1 10
Sun Jan 17 15:25:41 2021 daemon.debug miniupnpd[8916]: upnp_event_notify_connect: '192.168.2.189' 2869 '/upnp/eventing/nzxnkfeblp'
Sun Jan 17 15:25:41 2021 daemon.debug miniupnpd[8916]: upnpevents_processfds: 0x41ab0 2 10 0 1
Sun Jan 17 15:25:41 2021 daemon.debug miniupnpd[8916]: upnp_event_send: sending event notify message to 192.168.2.189:2869
Sun Jan 17 15:25:41 2021 daemon.debug miniupnpd[8916]: upnp_event_send: msg: NOTIFY /upnp/eventing/nzxnkfeblp HTTP/1.1
Host: 192.168.2.189:2869
Content-Type: text/xml; charset="utf-8"
Content-Length: 125
NT: upnp:event
NTS: upnp:propchange
SID: uuid:3c822217-afe8-4b62-b634-e28355fbf19a
SEQ: 0
Connection: close
Cache-Control: no-cache
`

**Comment by pali** [comment]
What version of miniupnpd are you using? If from git what is the exact miniupnpd commit?

**Comment by professor-jonny** [comment]
9th of jan was when I laast  built so the last commit before that. which would be this I believe but i would have to check my source on github desktop to be 100% sure but I'm fairly confident.

https://github.com/openwrt/packages/commit/061f81ff6df703ecb3e2fcc7e5c19b2a6bf991cd

**Comment by pali** [comment]
Can you try to use latest version of miniupnpd from git master branch? Now the latest commit is 71830c711a058fb2a65de8f69c337379d7f27dde. There are some few fixes related to error messages and listening on public addresses.

**Comment by professor-jonny** [comment]
ok so if I just update the feeds and copy your master branch overtop locally and build will surfice or will i have to customise if for openwrt intergration?

**Comment by pali** [comment]
Yes, try to use Makefile.linux. Eiter by `make -f Makefile.linux` renaming it to Makefile.

**Comment by professor-jonny** [comment]
The makefile downloads the source directly from your web site as a tar.gz and builds from the makefile.linux after applying patches.

it gets the files from here:
`http://miniupnp.free.fr/files/ `
currently it downloads version 2.2.1 with hash
 `f158dc73b718ca72da69e25ef23c57c3a10a0d7e7d1b4b9b57d5690823040ec2`

It looks like I cant just locally copy in the master source from github it is a bit beyond my skilset to rework the makefiles
I guess soon you will have a new release and I can update the makefile hash and direct to the new version when available as it is not urgent just something im playing with really.

**Comment by miniupnp** [comment]
> Yes, try to use Makefile.linux. Eiter by `make -f Makefile.linux` renaming it to Makefile.

you're now supposed to use `./configure` for that.
using configure also allows you to build in another path than the one with the sources

**Comment by professor-jonny** [comment]
I got it to build with master source. my files i downloaded had wrong premissions and would not build, i managed to build in the end.

This is the output of a upnp request with lasest source:


`u Jan 21 20:34:51 2021 daemon.info miniupnpd[6386]: HTTP REQUEST from [::ffff:192.168.2.189]:57346 : GET /rootDesc.xml (HTTP/1.1)
Thu Jan 21 20:34:51 2021 daemon.debug miniupnpd[6386]: Host: 192.168.2.1:5000
Thu Jan 21 20:34:51 2021 daemon.info miniupnpd[6386]: HTTP REQUEST from [::ffff:192.168.2.189]:57347 : POST /ctl/IPConn (HTTP/1.1)
Thu Jan 21 20:34:51 2021 daemon.debug miniupnpd[6386]: Host: 192.168.2.1:5000
Thu Jan 21 20:34:51 2021 daemon.info miniupnpd[6386]: SOAPAction: urn:schemas-upnp-org:service:WANIPConnection:1#GetExternalIPAddress
Thu Jan 21 20:34:51 2021 daemon.info miniupnpd[6386]: HTTP REQUEST from [::ffff:192.168.2.189]:57348 : POST /ctl/IPConn (HTTP/1.1)
Thu Jan 21 20:34:51 2021 daemon.debug miniupnpd[6386]: Host: 192.168.2.1:5000
Thu Jan 21 20:34:51 2021 daemon.info miniupnpd[6386]: SOAPAction: urn:schemas-upnp-org:service:WANIPConnection:1#GetSpecificPortMappingEntry
Thu Jan 21 20:34:51 2021 daemon.info miniupnpd[6386]: Returning UPnPError 714: NoSuchEntryInArray
Thu Jan 21 20:34:51 2021 daemon.info miniupnpd[6386]: HTTP REQUEST from [::ffff:192.168.2.189]:57349 : POST /ctl/IPConn (HTTP/1.1)
Thu Jan 21 20:34:51 2021 daemon.debug miniupnpd[6386]: Host: 192.168.2.1:5000
Thu Jan 21 20:34:51 2021 daemon.info miniupnpd[6386]: SOAPAction: urn:schemas-upnp-org:service:WANIPConnection:1#AddPortMapping
Thu Jan 21 20:34:51 2021 daemon.info miniupnpd[6386]: AddPortMapping: ext port 3076 to 192.168.2.189:3076 protocol UDP for: DemonwarePortMapping leaseduration=604800 rhost=
Thu Jan 21 20:34:51 2021 daemon.debug miniupnpd[6386]: UPnP permission rule 0 matched : port mapping accepted
Thu Jan 21 20:34:51 2021 daemon.debug miniupnpd[6386]: Check protocol udp for port 3076 on ext_if eth1 192.168.1.130, 8201A8C0
Thu Jan 21 20:34:51 2021 daemon.info miniupnpd[6386]: redirecting port 3076 to 192.168.2.189:3076 protocol UDP for: DemonwarePortMapping
Thu Jan 21 20:34:51 2021 daemon.info miniupnpd[6386]: Returning UPnPError 501: ActionFailed`

**Comment by pali** [comment]
(hint: put three backticks followed by a newline prior and also after the multiline verbatim text)

I have not understood what from previous post/log what is the problem. Is stun working now?

**Comment by professor-jonny** [comment]
Yes stun is working but I get upnp error when trying to create rules as the above log.
This is the specific error:
`miniupnpd[6386]: Returning UPnPError 501: ActionFailed
`

**Comment by pali** [comment]
So ensure that you have latest version from git master branch (there were some updates in diagnostic messages with better hints how to resolve issues) and provide full miniupnpd log, so @miniupnp or me can look at it.

**Comment by professor-jonny** [comment]
I think i may have found the issue with IGDv2 not supporting the xbox and windows operating systems.
https://github.com/openwrt/packages/pull/14656

**Comment by miniupnp** [comment]
> I think i may have found the issue with IGDv2 not supporting the xbox and windows operating systems.
> [openwrt/packages#14656](https://github.com/openwrt/packages/pull/14656)

it is the other way around. The XBOX does not support IGDv2
https://miniupnp.tuxfamily.org/forum/viewtopic.php?t=1833
https://github.com/miniupnp/miniupnp/issues/167

**Comment by professor-jonny** [comment]
Sorry yes typo on my part, do I guess there is no hope of getting microsoft to up their game?

**Comment by miniupnp** [comment]
> Sorry yes typo on my part, do I guess there is no hope of getting microsoft to up their game?

Well, Microsoft is aware of the problem for more than 5 years now, so if the company had any will to fix the issue, it would have been done for years now.

I guess they want to kill UPnP.

**Comment by miniupnp** [comment]
I guess I can close this issue.
