### ISSUE TITLE
"sendto: Network is unreachable" is printed to console instead of throwing an exception

### ISSUE THREAD

**Issue by brsnik** [miniupnp/miniupnp#521]
I am detecting whether the external IP has changed in Python. And during my testing I've noticed that when I turn off Wi-Fi (disconnect my pc from the internet) I get an error which I cannot catch with the exception.

It appears to be printed to the console.

```
u = miniupnpc.UPnP()
u.discoverdelay = config.svc_upnp_disc_delay

try:
    discover = u.discover()
    print(discover, 'device(s) detected')

    if discover:
        u.selectigd()

        while True:
            stat_info, stat_port, stat_error = u.statusinfo()
            if stat_info == 'Connected':

                if u.lanaddr != os.environ.get(config.envr_name_int_addr):
                    os.environ[config.envr_name_int_addr] = u.lanaddr

                ext_ip = u.externalipaddress()
                if ext_ip != os.environ.get(config.envr_name_ext_addr):
                    os.environ[config.envr_name_ext_addr] = ext_ip

                print('+', end=' ', flush=True)

            else:
                print('-', end=' ', flush=True)
                if stat_info != os.environ.get(config.envr_svc_status):
                    os.environ[config.envr_svc_status] = stat_info

            time.sleep(5)


except Exception as e:
    print('Exception :', e)
```

This is the error:

```
sendto: Network is unreachable
sendto: Network is unreachable
sendto: Network is unreachable
sendto: Network is unreachable
```

Is there any way I can catch this so I can log it in a log file instead of the console?

And what is causing it in the first place...because I am not printing it?

**Comment by miniupnp** [comment]
I guess it is printed there : https://github.com/miniupnp/miniupnp/blob/474658716fea90c8b9abdb84f402e6e9d2c75fff/miniupnpc/minissdpc.c#L848

**Comment by miniupnp** [comment]
indeed the python module doesn't return the error : 
https://github.com/miniupnp/miniupnp/blob/master/miniupnpc/miniupnpcmodule.c#L122

**Comment by miniupnp** [comment]
> Is there any way I can catch this so I can log it in a log file instead of the console?

it is written to stderr.
https://stackoverflow.com/questions/1956142/how-to-redirect-stderr-in-python

**Comment by brsnik** [comment]
Thanks. Maybe raise a custom exception then?
