### ISSUE TITLE
Compile fail version v2.2.1

### ISSUE THREAD

**Issue by fabiuz7** [miniupnp/miniupnp#522]
Hi, when I try to compile miniupnpc v2.2.1 in Visual Studio 2019 (Platform toolset v142), it fails with the following error:

    Error RC2104 undefined keyword or key name: INTERNAL_NAME in file miniupnpc.rc

Do you know how to solve it? Version v2.2.0 doesn't have `miniupnpc.rc` and it compiles perfectly.

**Comment by miniupnp** [comment]
you should add the define somewhere to `"miniupnpc.dll"`

**Comment by fabiuz7** [comment]
I had found a workaround that it `#define INTERNAL_NAME "miniupnpc.dll"` at the begin of `miniupnpc.rc`.

I had tried to add this define as preprocessor define, but no luck. Do you where it should be placed in VS 2019?

**Comment by fabiuz7** [comment]
it works, thank you!
