### ISSUE TITLE
Have problem with setuptools import

### ISSUE THREAD

**Issue by Evro123** [miniupnp/miniupnp#524]
I have setuptools 51.1.0 already installed, but when I run setup.py script it says: `No module named setuptools`. Should I use a certain version of this module or is there something that I did wrong?

**Comment by miniupnp** [comment]
I'm no python expert, I don't think I installed anything special to get setuptools available with my Python 3.7.9 installation.

Which python version do you uses ?

**Comment by CRTao** [comment]
I have faced the same problem on python 2.7.18, kali 2020.4.
After installing setuptools and python-dev, everything goes well.
`sudo apt-get install python-setuptools`
`sudo apt-get install python-dev`

**Comment by miniupnp** [comment]
@CRTao thanks.
