### ISSUE TITLE
windows build: miniupnp.rc or rc_version.h lack INTERNAL_NAME definition

### ISSUE THREAD

**Issue by bialix** [miniupnp/miniupnp#527]
https://github.com/miniupnp/miniupnp/blob/master/miniupnpc/miniupnpc.rc
lines 23 and 26 are referring INTERNAL_NAME. I suppose that should be a macro definition from rc_version.h.
But the latter lacks such definition. I've generated that file with 
https://github.com/miniupnp/miniupnp/blob/master/miniupnpc/msvc/genminiupnpcstrings.vbs
which is not very obvious step (I'd suggest put generated rc_version.h under version control).

So far I've simply edited rc file and replaced INTERNAL_NAME with "miniupnpc\0".

If you have any suggestions what should be written for INTERNAL_NAME - I can create a patch.

**Comment by bialix** [comment]
Oh, it's duplicate of https://github.com/miniupnp/miniupnp/issues/522

**Comment by bialix** [comment]
Sorry for re-open. But I've checked out the latest code from github and miniupnpc_vs2010.sln still lacks this definition. Why do you need to specify it at the project/solution level? It's more convenient to put into header file.

**Comment by miniupnp** [comment]
https://github.com/miniupnp/miniupnp/commit/36cc66edda92093b24e051e38bd16a64900272e9

which version of MS VS do you use ?

**Comment by bialix** [comment]
I'm trying to build with vs2010

**Comment by bialix** [comment]
Maybe my problem in the fact I've tried to use solution named miniupnpc_vs2010

**Comment by miniupnp** [comment]
I will try to apply the same changes to the VS 2010 project files.

**Comment by pali** [comment]
Anyway, why not rather put `miniupnpc.dll` string into miniupnpc.rc file instead of using this INTERNAL_NAME macro? IIRC this macro INTERNAL_NAME is used only in miniupnpc.rc file, so it can be directly replaced by string constant, like value for "FileDescription" or "ProductName".

**Comment by miniupnp** [comment]
see https://github.com/miniupnp/miniupnp/commit/bfc5eab6be38d693d0fa8bfecc467021c0c85c1f
