### ISSUE TITLE
AddAnyPortMapping failed with code -3

### ISSUE THREAD

**Issue by Puzomor** [miniupnp/miniupnp#528]
OS: Windows 10 version 1803
Modem: Ubee EVW32C-0S

I'm getting the following output when trying to use AddAnyPortMapping, for any set of input parameters:
```
C:\Users\marko\Desktop\upnpc-exe-win32-20150918
λ upnpc-shared.exe -n 192.168.1.5 8085 8085 TCP 3600
upnpc : miniupnpc library test client, version 1.9.
 (c) 2005-2014 Thomas Bernard.
Go to http://miniupnp.free.fr/ or http://miniupnp.tuxfamily.org/
for more information.
List of UPNP devices found on the network :
 desc: http://192.168.1.1:80/RootDevice.xml
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

Found valid IGD : http://192.168.1.1:80/WANIPConnection
Local LAN ip address : 192.168.1.5
ExternalIPAddress = (redacted)
Socket error: recv, 10054
AddAnyPortMapping(8085, 8085, 192.168.1.5) failed with code -3 (UnknownError)
GetSpecificPortMappingEntry() failed with code 714 (NoSuchEntryInArray)
```
I've discovered this after trying to use miniupnpc as a library, compiling it from source and adding it to my own code where the same error occured.
Using regular AddPortMapping works and shows no errors, as do other functions (list, delete, status).
List redirections using GetListOfPortMappings doesn't work either, showing the same socket recv error.
Get Firewall status also works.

**Comment by miniupnp** [comment]
well I guess the router doesn't support `AddAnyPortMapping` nor `GetListOfPortMappings` but closes the connection abruptly instead of returning an error.

**Comment by Puzomor** [comment]
Well, nothing to be done if router is being uncooperative 🤷
