### ISSUE TITLE
OpenBSD 6.8 - wrong syntax for pf rule

### ISSUE THREAD

**Issue by bsd-source** [miniupnp/miniupnp#529]
pfSense and OpenBSD use different pf syntax.

miniupnpd 2.2.0-RC2 created the 2 following rules for my Xbox Series X console using OpenBSD 6.8:

```
pass in quick on em0 inet proto udp from any to any port = 50622 label "Teredo 10.100.100.100:50622-&gt;50622 UDP" rdr-to 10.100.100.100 port 50622
nat quick on em0 inet proto udp from 10.100.100.100 port = 50622 to any label "Teredo 10.100.100.100:50622-&gt;50622 UDP" nat-to 184.71.6.242 port 50622
```
The nat rule produced a syntax error and should be **pass out quick** instead of nat quick. I've testedt his on OpenBSD several times.

**Comment by miniupnp** [comment]
miniupnpd doesn't make any pass out rule. IGD is not designed to work with filtered outbound traffic.
The nat rule here is to allow bidirectionnal nat mapping for UCP, so if that is you local machine that initiate the "connection" from 10.100.100.100:50622 it appears to come from <wan ip>:50622 instead of a random port

**Comment by bsd-source** [comment]
The local machine is my Xbox Series X using port static port 50622. To avoid port conflict on a LAN network Microsoft allows each Xbox to have a different static port to avoid port conflict. So it's not a random port. Either way, that nat rule that is being created is not the correct syntax for OpenBSD.

I also tested the miniupnpd (miniupnpd-2.1.tar.gz | 225458 | 08/05/2018) currently in the OpenBSD ports source code tree. This particular miniupnpd version produces the following single rule and not nat rule:

`pass in quick on em0 inet proto udp from any to any port = 50622 label "Teredo 10.100.100.100:50622-&gt;50622 UDP" rdr-to 10.100.100.100 port 50622`

I was looking at OpenBSD [pf.conf](https://man.openbsd.org/pf.conf.5) man page and found the following relevent information:

> The bidirectional address translation example uses a single binat-to rule that expands to a nat-to and an rdr-to rule.
> 
> pass on $ext_if from 10.1.2.120 to any binat-to 192.0.2.17
> 
> The previous example is identical to the following set of rules:
> 
> pass out on $ext_if inet from 10.1.2.120 to any nat-to 192.0.2.17 static-port
> pass in on $ext_if inet from any to 192.0.2.17 rdr-to 10.1.2.120

Would a single binat-to rule work the same? Either way the single nat rule that miniupnpd creates is not correct for OpenBSD.

Also the only AddPortMapping requests from my Xboxs are for the single static port that is set for each Xbox in the network settings for the Xbox's. So for one Xbox I get an AddPortMapping request for port 50622 and one for my other Xbox static port 56450. No additional AddPortMapping requests made. I see this when running miniupnpd in debug mode. I'm really not sure why I don't see any other port mapping requests when I start games etc.

I guessing I'm not grasping things here. Hopefully one day someone with enough knowlege of FreeBSD and OpenBSD can sort this out.

**Comment by sthen** [comment]
This came to my attention, I'm not a miniupnp user but I can give a bit of info about what's needed for PF.

PF_RDR, PF_NAT and PF_BINAT are not valid actions for "modern" PF (post-2010 in OpenBSD, I'm not sure of the date for Solaris/MacOS) i.e. PF_NEWSTYLE in miniupnp. In those the translation address must be attached to either a PF_PASS or PF_MATCH rule (in the case of PF_MATCH I think there may need to be a PF_PASS in the same anchor matching the packet but I'm not 100% sure about that). (Maybe OpenBSD should remove the #defines as nothing using them can actually be working correctly..)

binat-to is a construct only used in the config parser in pfctl, it inserts two matching rules (exactly equivalent to a pair of rules with nat-to and rdr-to).

**Comment by timelessremix** [comment]
Same happens here on OpenBSD 7.1 the  "nat quick on ..." rule is wrong see 

https://marc.info/?l=openbsd-ports&m=165242182918937&w=2

Besr regards

**Comment by miniupnp** [comment]
> pfSense and OpenBSD use different pf syntax.
> 
> miniupnpd 2.2.0-RC2 created the 2 following rules for my Xbox Series X console using OpenBSD 6.8:
> 
> ```
> pass in quick on em0 inet proto udp from any to any port = 50622 label "Teredo 10.100.100.100:50622-&gt;50622 UDP" rdr-to 10.100.100.100 port 50622
> nat quick on em0 inet proto udp from 10.100.100.100 port = 50622 to any label "Teredo 10.100.100.100:50622-&gt;50622 UDP" nat-to 184.71.6.242 port 50622
> ```
> 
> The nat rule produced a syntax error and should be **pass out quick** instead of nat quick. I've testedt his on OpenBSD several times.

1. the "nat" rule is only added for UDP when `ENABLE_PORT_TRIGGERING` is set and was added in miniupnpd version 2.2.0.
2. What do you mean by "The nat rule produced a syntax error" ? what error is logged exactly ?

**Comment by miniupnp** [comment]
> PF_RDR, PF_NAT and PF_BINAT are not valid actions for "modern" PF (post-2010 in OpenBSD, I'm not sure of the date for Solaris/MacOS) i.e. PF_NEWSTYLE in miniupnp.

`PF_NEWSTYLE` means OpenBSD 4.7+ which has been released in May 2010.

**Comment by miniupnp** [comment]
@bsd-source sorry for the  delay, could you test the branch https://github.com/miniupnp/miniupnp/tree/529-port-triggering-openbsd and see if that fixes your issue ?

**Comment by miniupnp** [comment]
> I have a question regarding Point 1:
> 
> If i add via network places upnp gateway (TCP) i got these messages in the logs
> 
> miniupnpd[49920]: could not find redirect rule to delete eport=5432
> 
> Like you described "nat" rule is only added for UDP ..."
> 
> Is this a normal message ? because it claims to delete the redirect rule witch is not added in TCP ... ;)

no that's not a normal message, but I need more context to understand why you've got this message.
you should run miniupnpd with the -d flag to enable all debug output.
The output of ` pfctl -sr -a miniupnpd`  before and after you've got this message could help too.

**Comment by miniupnp** [comment]
> Regarding point 2: i did:
> 
> `pfctl -sr -a miniupnpd >> testpf.conf`
> 
> ```
> pass in quick on bge1 inet proto udp from any to any port = 53418 label "Teredo 192.168.1.100:53418-&gt;53418 UDP" rdr-to 192.168.1.100 port 53418
> nat quick on bge1 inet proto udp from 192.168.1.100 port = 53418 to any label "Teredo 192.168.1.100:53418-&gt;53418 UDP" nat-to XXX.XXX.XXX.XXX port 53418
> 
> pfctl -nf testpf.conf
> testpf.conf:2: syntax error
```
Thank you for your answer. So as @sthen was saying, it is possible to create "invalid" rules with the API, that ` pfctl` can't create ! ;)

**Comment by timelessremix** [comment]
> > I have a question regarding Point 1:
> > If i add via network places upnp gateway (TCP) i got these messages in the logs
> > miniupnpd[49920]: could not find redirect rule to delete eport=5432
> > Like you described "nat" rule is only added for UDP ..."
> > Is this a normal message ? because it claims to delete the redirect rule witch is not added in TCP ... ;)
> 
> no that's not a normal message, but I need more context to understand why you've got this message. you should run miniupnpd with the -d flag to enable all debug output. The output of ` pfctl -sr -a miniupnpd` before and after you've got this message could help too.

Sry for late answer
Here are the outputs of miniupnpd and the pfctl 
[minupnpd_out.txt](https://github.com/miniupnp/miniupnp/files/8728138/minupnpd_out.txt)

**Comment by miniupnp** [comment]
@timelessremix well you see in your log that it starts without any portmapping, then 
`urn:schemas-upnp-org:service:WANIPConnection:1#DeletePortMapping` is called, of course no portmapping is found, so the message `could not find redirect rule to delete eport=5432` is normal

Then  `urn:schemas-upnp-org:service:WANIPConnection:1#AddPortMapping` is called and the portmapping added.

**Comment by timelessremix** [comment]
Thx for explanation and Support! I can unser Stand c, c++ a litle Bit. But so deep i am not in thxAm 19.05.2022 21:53 schrieb Thomas BERNARD ***@***.***>:
@timelessremix well you see in your log that it starts without any portmapping, then
urn:schemas-upnp-org:service:WANIPConnection:1#DeletePortMapping is called, of course no portmapping is found, so the message could not find redirect rule to delete eport=5432 is normal
Then  urn:schemas-upnp-org:service:WANIPConnection:1#AddPortMapping is called and the portmapping added.

**Comment by timelessremix** [comment]
> @bsd-source sorry for the delay, could you test the branch https://github.com/miniupnp/miniupnp/tree/529-port-triggering-openbsd and see if that fixes your issue ?

Has sombody tested this already or shoud we wait ?

**Comment by bsd-source** [comment]
> @bsd-source sorry for the delay, could you test the branch https://github.com/miniupnp/miniupnp/tree/529-port-triggering-openbsd and see if that fixes your issue ?

Today on May 28, 2022 I was able to compile and test the miniupnpd 529-port-triggering branch. It compiled fine under OpenBSD 6.9. Also, **it works great** and now creates the appropriate pass out quick rule instead of the nat quick rule. miniupnpd created the following 2 rules for when I started my Xbox:

```
pass in quick on em0 inet proto udp from any to any port = 50622 label "Teredo 10.250.3.100:50622-&gt;50622 UDP" rdr-to 10.250.3.100 port 50622
pass out quick on em0 inet proto udp from 10.250.3.100 port = 50622 to any label "Teredo 10.250.3.100:50622-&gt;50622 UDP" nat-to 182.18.258.19 port 50622
```

I'm currently unable to test to see if it's working as well as pfSense now when it comes to using multiple gaming devices of the same type at the same time playing the same game. I've been following pfSense's progress which is a different issue.

**Comment by timelessremix** [comment]
Should the binat-to rule not include also static-port ?!

**Comment by timelessremix** [comment]
Sry i got a little bit confused with the 2nd pass out line ... 
 
I used OpenBSD with Miniupnpd  ("OpenBSD PF - Building a Router" FAQ) the match out with static-port and anchor miniupnpd i placed after block all

as i can remember more then 10 years i saw only the "pass in quick rdr-to rule"

and i never mentioned a 2nd pass out line

regarding "OpenBSD PF - Network Address Translation" FAQ and the "pass out nat-to"

where i have to place miniupnpd anchor before or after the match out line and the static-port (match out )is this obsolete right now ? 

also if it is a binat-to rule (see articles above) it should generate a static-port statement but with a "port ="  this makes no sense.

Thx for help ....

**Comment by bsd-source** [comment]
timelessremix I placed a single miniupnpd anchor before any match rule in my pf.conf file. I previously placed the miniupnpd anchor at the very end of my pf.conf but have since removed it. Also, I previously had a static-port match out rule for interface em3 which I changed to below and based on my testing should no longer be needed:

```
anchor miniupnpd
match in all scrub (no-df random-id max-mss 1440)
match out on em0 inet from em3:network to any nat-to (em0:0) port 1024:65535
```

**Comment by timelessremix** [comment]
Many Thx ! now i understand more but i is not better to but the anchor between match in and match out because of the scrub statement ...
i can understand to put the anchor first but it looks wrong for me if i read PF Book,  or pf examples i have never seen pass rules before the match rules ....

and maybe i am wrong but the match rule will catch first but if i do explicit a pas out nat-to afterwards it should be fine ( OpenBSD PF - Network Address Translation -- to read and understand not native English speaker ... Example !(made "sticky")! )

i will do a "Real" test this week as i said above and give a shout !

PS: I think i read to much and i confound some thinks ...

**Comment by miniupnp** [comment]
@bsd-source @timelessremix thank you for your tests, I will wait until you test everything in real life before merging in the master branch.

**Comment by bsd-source** [comment]
I did a lot of testing the last few days. OpenBSD 6.9 with miniupnpd 529-port-triggering branch. Tested with an XBOX One and XBOX Series X and PS4 and PS5. Works great with the following OpenBSD pf.conf settings:

The miniupnpd anchor in pf.conf needs to be placed before outbound NAT translation. No need to place an additional anchor at the end of the pf.conf file. The match out NAT rule does not require static-port. The example below results in NAT Type 2 for PS4 and PS5 and Open NAT for Call of Duty Cold War game.
```
match in all scrub (no-df random-id max-mss 1440)
anchor miniupnpd
match out on em0 inet from em3:network to any nat-to (em0:0) port 1024:65535
```
One important thing I noticed which is not a miniupnpd bug is that the PS4 and PS5 **WOULD NOT** request a different port if notified by miniupnpd that the requested addportmapping port was already taken. I only observed this behavior with port 9308 which was the port both Playstations requested on startup. This may apply to other ports as well but further testing would be required. Both Playstations **DID** appropriately respect the upnp protocol when it requested addportmapping for port 3074. This specific port was requested after starting the Call of Duty Cold War game. When port 3074 was already taken, the Playstions would request make an additional addportmapping request with a random port to map back to port 3074. Example of real miniupnpd debug output showing what happened when a port mapping is requested that is already taken:

```
miniupnpd[84189]: SOAPAction: urn:schemas-upnp-org:service:WANIPConnection:1#AddPortMapping
miniupnpd[84189]: AddPortMapping: ext port 3074 to 10.50.2.101:3074 protocol UDP for: DemonwarePortMapping leaseduration=0 rhost=
miniupnpd[84189]: UPnP permission rule 0 matched : port mapping accepted
miniupnpd[84189]: port 3074 UDP (rhost '') already redirected to 10.50.3.100:3074
miniupnpd[84189]: Returning UPnPError 718: ConflictInMappingEntry
miniupnpd[84189]: HTTP REQUEST from 10.50.2.101:62783 : POST /ctl/IPConn (HTTP/1.1)
miniupnpd[84189]: Host: 10.50.2.1:34207
miniupnpd[84189]: SOAPAction: urn:schemas-upnp-org:service:WANIPConnection:1#AddPortMapping
miniupnpd[84189]: AddPortMapping: ext port 3116 to 10.50.2.101:3074 protocol UDP for: DemonwarePortMapping leaseduration=0 rhost=
miniupnpd[84189]: UPnP permission rule 0 matched : port mapping accepted
miniupnpd[84189]: Check protocol udp for port 3116 on ext_if em0 80.171.21.72, 48DDAE46
miniupnpd[84189]: redirecting port 3116 to 10.50.2.101:3074 protocol UDP for: DemonwarePortMapping
miniupnpd[84189]: use external ip 80.171.21.72
```
Breakdown of what happened above:
1. PS5 requested port 3074
2. miniupnpd responded back to the PS5 that there was an issue with port 3074
3. PS5 then requested port 3116 which was an alternative port to port 3074
4. miniupnpd then created new port mapping using port 3116 which redirected back to port 3074

The rules below were listed using the command: pfctl -a miniupnpd -s rules
```
pass in quick on em0 inet proto udp from any to any port = 3074 label "libminiupnpc" rdr-to 10.50.3.100 port 3074
pass out quick on em0 inet proto udp from 10.50.3.100 port = 3074 to any label "libminiupnpc" nat-to 80.171.21.72 port 3074
pass in quick on em0 inet proto udp from any to any port = 3116 label "DemonwarePortMapping" rdr-to 10.50.2.101 port 3074
pass out quick on em0 inet proto udp from 10.50.2.101 port = 3074 to any label "DemonwarePortMapping" nat-to 80.171.21.72 port 3116
```
Playstations do not seem to always respect the UPNP protocol like in the instance with the issue of port 9308 further above. This may result in a second Playstation on the same network that starts up obtaining a NAT Type 3 instead of NAT Type 2 which the first Playstation ideally should already have mapped by miniupnpd on startup.
