### ISSUE TITLE
Support duration in -r and multi protocol

### ISSUE THREAD

**Issue by Anuskuss** [miniupnp/miniupnp#532]
I was using a combination of `upnpc -r` and `upnpc -d` in my systemd services to always have my ports open on boot / closed on shutdown but after using it for a bit I realized that the default duration of 7 days is too short-lived for my needs. You can't specify a duration in `-r` so as a workaround I'm using `-a` now. But I don't know my ip address beforehand and systemd unfortunately doesn't support command substitutions (`$(hostname -i)`) so I have to invoke a shell which is ugly. I see four possible solutions to this:
- Dangling duration (confusing): `upnpc [options] -r port1 [external_port1] protocol1 [...] [duration]`
- Options argument: `upnpc -d 604800 -r [external_port1] protocol1 [...]`
- Magic value representing current ip address: `upnpc -a @ port external_port protocol [duration] [remote host]`
- Configuration file with new default duration

The other request is about specifying multiple protocols instead of a single one. Many routers offer the third option `TCP/UDP` which miniupnp should definitely make use of. I have no idea if the UPnP protocol allows that though.

**Comment by Anuskuss** [comment]
Also I was just testing what would happen if I use `0` (indefinite) as duration but it defaulted to `604800`. Is that just not supported on my router? If it's missing in miniupnp, I'd like to request that as well.

**Comment by miniupnp** [comment]
indefinite duration may not be supported by the router.
also 604800 (7 days) is the maximum.

the recommended way of keeping a port-mapping open is to use a shorter duration (a few hours) and renew periodically.

**Comment by Anuskuss** [comment]
> indefinite duration may not be supported by the router.
also 604800 (7 days) is the maximum.

I'm not sure about the first point (does it really work with compatible routers?) but I can definitely set it to more than 608400.

> the recommended way of keeping a port-mapping open is to use a shorter duration (a few hours) and renew periodically.

I was considering some sort of cronjob which checks my running services and renews my UPnP ports automatically but in the end decided to just "hardcode" them in my router. They won't show up in `upnpc -l` so I guess that's just the GUI listing them beside the UPnP ports but internally it's stored in the iptables or something. But I still use UPnP with another service so I hope that the OP gets tackled someday.

**Comment by miniupnp** [comment]
> It could be just a background periodic thread. Too easy to be part of the lib.

what is too easy ? I'm waiting for your Pull Request then.

**Comment by miniupnp** [comment]
> > indefinite duration may not be supported by the router.
> > also 604800 (7 days) is the maximum.
> 
> I'm not sure about the first point (does it really work with compatible routers?) but I can definitely set it to more than 608400.

IGD WANIPConnection:2  specifies in 2.5.16.2 :
> This action has restrictions on its arguments as follows:
> • NewPortMappingLeaseDuration value can be between 1 second and 604800 seconds, however value “0” can exist for port mappings made out of band,
> • Infinite mappings cannot be made in WANIPConnection:2 and value “0” MUST be interpreted as 604800 seconds,
> • It is RECOMMENDED that a lease time of 3600 seconds would be used as a default value.

https://web.archive.org/web/20211214062613/http://upnp.org/specs/gw/UPnP-gw-WANIPConnection-v2-Service.pdf

however IGD v1 devices may not enforce such limitation and are likely to support unlimited lease times.
But for maximum compatibility with all IGD's, you should use a lease duration between 1 and 604800 seconds.

**Comment by Anuskuss** [comment]
@miniupnp Last year I was trying to make my setup as secure as possible and I was worried that there might be some potential vulnerabilities if I left the ports open while no device was listening on the other end. Since then I've realized that I'm not even turning off my server anyway, so I decided to just hardocde them in my router. But I still wanna thank you for implementing this because it might be useful to somebody else.
After reading through this issue once again, I have two questions left:
> The other request is about specifying multiple protocols instead of a single one. Many routers offer the third option TCP/UDP which miniupnp should definitely make use of. I have no idea if the UPnP protocol allows that though.

I've got a new router now, which has even more protocol options than my old one (`ESP` and `GRE`) but lacks `TCP/UDP`. So I'll presume that `TCP/UDP` is just a comfort option and doesn't actually exist on it's own but rather just creates both a `TCP` and `UDP` entry (and then combines them again depending on the UI). I would still like to request this as a "comfort option" because that's one less line you gotta type :-)

> however IGD v1 devices may not enforce such limitation and are likely to support unlimited lease times.

So that means `0` will just get forwarded as-is, right? No internal translation to `604800`? Because according to my earlier comment, `0` didn't work but a value greater than `604800` did (too lazy to retest). If I ever use UPnP again, I might go for the cron/systemd approach (if you don't beat me to it) but if miniupnp doesn't do that for you, and you can't create the job on your own, `0` might still be the best option.

**Comment by miniupnp** [comment]
> @miniupnp Last year I was trying to make my setup as secure as possible and I was worried that there might be some potential vulnerabilities if I left the ports open while no device was listening on the other end. Since then I've realized that I'm not even turning off my server anyway, so I decided to just hardocde them in my router. But I still wanna thank you for implementing this because it might be useful to somebody else. After reading through this issue once again, I have two questions left:
> 
> > The other request is about specifying multiple protocols instead of a single one. Many routers offer the third option TCP/UDP which miniupnp should definitely make use of. I have no idea if the UPnP protocol allows that though.
> 
> I've got a new router now, which has even more protocol options than my old one (`ESP` and `GRE`) but lacks `TCP/UDP`. So I'll presume that `TCP/UDP` is just a comfort option and doesn't actually exist on it's own but rather just creates both a `TCP` and `UDP` entry (and then combines them again depending on the UI). I would still like to request this as a "comfort option" because that's one less line you gotta type :-)

TCP/UDP is not a protocol. I guess it is translated by clients supporting it to 2 AddPortMapping requests.
You may request it, someone might someday spend the time to contribute such feature.
 
> > however IGD v1 devices may not enforce such limitation and are likely to support unlimited lease times.
> 
> So that means `0` will just get forwarded as-is, right? No internal translation to `604800`? Because according to my earlier comment, `0` didn't work but a value greater than `604800` did (too lazy to retest). If I ever use UPnP again, I might go for the cron/systemd approach (if you don't beat me to it) but if miniupnp doesn't do that for you, and you can't create the job on your own, `0` might still be the best option.

I think you don't understand how the miniupnpc client work, although I thought my previous answers were quite clear :
miniupnpc is just sending the commands to the UPNP IGD, it has no power on how they are interpreted. If you want to know more about your router IGD implementation, please contact the manufacturer/developer.

So I repeat again my advice : you should stick to what UPNP IGD specifies and follow the recommendations, even if some implementations do not comply with the specifications.
