### ISSUE TITLE
IPv6 NAT camouflage ports are automatically mapped

### ISSUE THREAD

**Issue by jack9603301** [miniupnp/miniupnp#536]
We know that IPv6 generally does not rely on NAT address translation and is generally only NPT address translation, but I am still exploring the potential of UPnP-IGD in IPv6

- Does the UPnP-IGD implemented by `miniupnpd` currently support dynamic NAT mapping for IPv6 NAT camouflage networks?
- If so, how should I configure `miniupnpd`
- What is the difference between IGDv1 and IGDv2, that they seem to offer the same interface and service

**Comment by miniupnp** [comment]
I think you should first study the UPNP IGD specifications : https://openconnectivity.org/developer/specifications/upnp-resources/upnp/internet-gateway-device-igd-v-2-0/

The quick answer is : I'm not aware of any support for "IPv6 NAT camouflage networks" in UPNP-IGD
