### ISSUE TITLE
VERSION file causes problems when compiled with C++20

### ISSUE THREAD

**Issue by cryptocode** [miniupnp/miniupnp#540]
In C++20, `<version>` is a header the compiler looks for. When miniupnp is used as a submodule, the submodule's `miniupnpc` directory is often set as a header location. On case insensitive file systems (macOS default for instance), this causes compilation errors since the VERSION file is incorrectly picked up as the `<version>` header.

The ideal IMO would be if miniupnpc didn't mix source and non-source files (maybe a `src` or at least an `include` directory), while renaming `VERSION` is another solution (the least breaking change). It can also be solved various ways for each user, but would be nice if it worked out of the box :) Thanks for considering.

**Comment by miniupnp** [comment]
Well if you build and install miniupnpc, the install files are put in /usr/include/miniupnpc  so there should be no problem.

Anyway it would be great for the build system to put public include files in a include subdirectory.

**Comment by cryptocode** [comment]
In this case, miniupnp is a submodule and build is initated by CMake. Maybe it can be done differently to avoid the issue, but yeah, would be great to have an include subdir at any rate 👍

**Comment by scribam** [comment]
I have the same issue with miniupnp 2.2.2 as a submodule in an android C++11 project:
```
[...]
In file included from C:/Users/scribam/AppData/Local/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1\algorithm:639:
In file included from C:/Users/scribam/AppData/Local/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1\initializer_list:46:
In file included from C:/Users/scribam/AppData/Local/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1\cstddef:37:
../../../../../../../external/miniupnp/miniupnpc\version:1:1: error: expected unqualified-id
```

```
[...]
In file included from C:/Users/scribam/AppData/Local/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1\algorithm:640:
In file included from C:/Users/scribam/AppData/Local/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1\type_traits:418:
../../../../../../../external/miniupnp/miniupnpc\version:1:1: error: expected unqualified-id
```

`cstddef` and `type_traits` both have `#include <version>`
