### ISSUE TITLE
daemon.notice miniupnpd[8116]: private/reserved address checking is ignore

### ISSUE THREAD

**Issue by DropbearNinja** [miniupnp/miniupnp#542]
I'm getting a lot of this line over and over in syslog - what exactly is triggering this error?

Thanks.

**Comment by pali** [comment]
This is custom openwrt patch, not part of miniupnp project. Please report this bug to the openwrt project.

**Comment by ptpt52** [comment]
if you are using openwrt, try to disable this option
in `/etc/config/upnpd`
```
option ext_ip_reserved_ignore '0'
```

**Comment by vpei** [comment]
> option ext_ip_reserved_ignore '0'


The problem is still not solved.

**Comment by vpei** [comment]
**option ext_ip_reserved_ignore '0'**


Thu May 20 20:35:54 2021 daemon.notice miniupnpd[16074]: private/reserved address 100.81.100.169 is not suitable for external IP
Thu May 20 20:35:54 2021 daemon.notice miniupnpd[16074]: private/reserved address 100.81.100.169 is not suitable for external IP
Thu May 20 20:35:54 2021 daemon.notice miniupnpd[16074]: private/reserved address 100.81.100.169 is not suitable for external IP
Thu May 20 20:35:54 2021 daemon.notice miniupnpd[16074]: private/reserved address 100.81.100.169 is not suitable for external IP

**Comment by ptpt52** [comment]
this is not related to `ext_ip_reserved_ignore `

**Comment by miniupnp** [comment]
@vpei `Thu May 20 20:37:30 2021 daemon.notice miniupnpd[16074]: private/reserved address 100.81.100.169 is not suitable for external IP` is not the same issue that initially reported.

100.81.100.169 is a RFC6598 IP address that is not fully routable.

**Comment by vpei** [comment]
> 
> 
> @vpei `Thu May 20 20:37:30 2021 daemon.notice miniupnpd[16074]: private/reserved address 100.81.100.169 is not suitable for external IP` is not the same issue that initially reported.
> 
> 100.81.100.169 is a RFC6598 IP address that is not fully routable.

For dial-up Internet access, the IP addresses assigned are those of the LAN, for example:100.81.100.169

**Comment by miniupnp** [comment]
> > @vpei `Thu May 20 20:37:30 2021 daemon.notice miniupnpd[16074]: private/reserved address 100.81.100.169 is not suitable for external IP` is not the same issue that initially reported.
> > 100.81.100.169 is a RFC6598 IP address that is not fully routable.
> 
> For dial-up Internet access, the IP addresses assigned are those of the LAN, for example:100.81.100.169

So UPNP IGD will not work anyway.

Please stop polluting the discussion in this issue with an unrelated problem.
