### ISSUE TITLE
Download broken

### ISSUE THREAD

**Issue by sjaeckel** [miniupnp/miniupnp#543]
Hi,

I've downloaded miniupnpd-2.1.20191006.tar.gz from the free.fr mirror and I've noticed that the signatures don't match!

It seems like the file is not packed.

When downloading the same file from the tuxfamily.org mirror it's fine...

OK:  http://miniupnp.tuxfamily.org/files/miniupnpd-2.1.20191006.tar.gz
NOK: http://miniupnp.free.fr/files/miniupnpd-2.1.20191006.tar.gz

Thanks & Cheers
Steffen

**Comment by miniupnp** [comment]
```
$ curl -O  http://miniupnp.free.fr/files/miniupnpd-2.1.20191006.tar.gz
$ curl -O  http://miniupnp.free.fr/files/miniupnpd-2.1.20191006.tar.gz.sig
$ gpg --verify miniupnpd-2.1.20191006.tar.gz.sig
gpg: les données signées sont supposées être dans « miniupnpd-2.1.20191006.tar.gz »
gpg: Signature faite le dim.  6 oct. 23:02:22 2019 CEST
gpg:                avec la clef RSA 0FF11B67A5C0863C
gpg: Bonne signature de « miniupnp (miniupnp !) <miniupnp@free.fr> » [expirée]
gpg: Remarque : cette clef a expiré.
Empreinte de clef principale : BEB7 EA42 900F F505 B790  7AE5 0FF1 1B67 A5C0 863C
$ sha256 *gz*
SHA256 (miniupnpd-2.1.20191006.tar.gz) = 218fad7af31f3c22fb4c9db28a55a2a8b5067d41f5b38f52008a057a00d2206d
SHA256 (miniupnpd-2.1.20191006.tar.gz.sig) = ba26f5515354244a252a4b32ab24b9a77709c280316fa78b0734f18ed50bb23c
```

**Comment by miniupnp** [comment]
> Did you fix something?
> 
> Because the version I downloaded when opening this issue has
> 
> ```
> $ sha256sum miniupnpd-2.1.20191006.tar.gz 
> 5459160a153eae4ff73bfc908897363c1fdc9be9c7edee2645db6bb456f79917  miniupnpd-2.1.20191006.tar.gz
> ```
> 
> and the issue was discovered because there were build jobs in our CI failing because of that.

I have modified nothing

**Comment by sjaeckel** [comment]
Did you try the link I provided above?

If I use http://miniupnp.free.fr/files/miniupnpd-2.1.20191006.tar.gz it's fine for me as well, but http://miniupnp.free.fr/files/download.php?file=miniupnpd-2.1.20191006.tar.gz produces the broken file

**Comment by miniupnp** [comment]
```
$ for f in miniupnpd-2.1.20191006.tar.gz miniupnpd-2.1.20191006.tar.gz.sig ; do curl -L -o $f "http://miniupnp.free.fr/files/download.php?file=$f" ; done ; gpg --verify miniupnpd-2.1.20191006.tar.gz.sig ; sha256 miniupnpd* ; ls -l miniupnpd*
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  237k  100  237k    0     0  5656k      0 --:--:-- --:--:-- --:--:-- 5656k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   543  100   543    0     0  28578      0 --:--:-- --:--:-- --:--:-- 28578
gpg: les données signées sont supposées être dans « miniupnpd-2.1.20191006.tar.gz »
gpg: Signature faite le dim.  6 oct. 23:02:22 2019 CEST
gpg:                avec la clef RSA 0FF11B67A5C0863C
gpg: Bonne signature de « miniupnp (miniupnp !) <miniupnp@free.fr> » [expirée]
gpg: Remarque : cette clef a expiré.
Empreinte de clef principale : BEB7 EA42 900F F505 B790  7AE5 0FF1 1B67 A5C0 863C
SHA256 (miniupnpd-2.1.20191006.tar.gz) = 218fad7af31f3c22fb4c9db28a55a2a8b5067d41f5b38f52008a057a00d2206d
SHA256 (miniupnpd-2.1.20191006.tar.gz.sig) = ba26f5515354244a252a4b32ab24b9a77709c280316fa78b0734f18ed50bb23c
-rw-r--r--  1 nanard  staff  243255 13 mai   12:07 miniupnpd-2.1.20191006.tar.gz
-rw-r--r--  1 nanard  staff     543 13 mai   12:07 miniupnpd-2.1.20191006.tar.gz.sig
```

**Comment by sjaeckel** [comment]
and now try the link with a chromisum based browser please ...

**Comment by miniupnp** [comment]
> Did you try the link I provided above?
> 
> If I use http://miniupnp.free.fr/files/miniupnpd-2.1.20191006.tar.gz it's fine for me as well, but http://miniupnp.free.fr/files/download.php?file=miniupnpd-2.1.20191006.tar.gz produces the broken file

So at first you reported the bug about  http://miniupnp.free.fr/files/miniupnpd-2.1.20191006.tar.gz  and then you changed your mind and that URL is fine...

Just don't unzip the file after downloading it.

```
$ gunzip miniupnpd-2.1.20191006.tar.gz
$ sha256 miniupnpd-2.1.20191006.tar
SHA256 (miniupnpd-2.1.20191006.tar) = 5459160a153eae4ff73bfc908897363c1fdc9be9c7edee2645db6bb456f79917
```

**Comment by miniupnp** [comment]
> and now try the link with a chromium based browser please ...

Why would I waste my time ? Just download the file with a tool that doesn't unzip it.

**Comment by sjaeckel** [comment]
Yes, I realized this only later, that the initial bug report was wrong.

I only found out now that this only happens with a chromium based browser or the downloader from yocto ... and only sometimes ...

> Why would I waste my time ? Just download the file with a tool that doesn't unzip it.

nvm

**Comment by miniupnp** [comment]
there may be an issue with `miniupnp.free.fr` setting the HTTP header `Content-Encoding: x-gzip` although it should not. I can't do anything about it, so please use `miniupnp.tuxfamily.org` if that causes issues with your HTTP Client.

**Comment by sjaeckel** [comment]
thanks for acknowledging that there's an issue with the free.fr mirror ... :)
