### ISSUE TITLE
Small questions about miniupnpc

### ISSUE THREAD

**Issue by irwir** [miniupnp/miniupnp#544]
Three tiny issues.
1. Indent is inconsistent https://github.com/miniupnp/miniupnp/blob/3a87be33e797ba947b2b2a5f8d087f6c3ff4d93e/miniupnpc/minissdpc.c#L642
2. https://github.com/miniupnp/miniupnp/blob/3a87be33e797ba947b2b2a5f8d087f6c3ff4d93e/miniupnpc/minissdpc.c#L708 Condition `if (multecastif && multicastif != '\0')` would be convenient sometimes. For one, when the string is a C++ object; it could be empty, but not a NULL.
3. The latest version in Releases on Github is 2.1. Is this intentional?

**Comment by miniupnp** [comment]
1) yes indent is inconsistent.
I try to normalize it when there are new changes, but I think changing everything at once is not worth it.

2) indeed.

3) I think there is a github "release" only because I uploaded a file.
Just use the official distribution packages from the website.
