### ISSUE TITLE
daemon.err miniupnpd[5602]

### ISSUE THREAD

**Issue by vpei** [miniupnp/miniupnp#550]
Wed May 26 20:26:56 2021 daemon.err miniupnpd[5602]: try_sendto(sock=8, len=473, dest=[ff02::c]:1900): sendto: Permission denied
Wed May 26 20:26:56 2021 daemon.err miniupnpd[5602]: try_sendto(sock=8, len=461, dest=[ff02::c]:1900): sendto: Permission denied
Wed May 26 20:26:56 2021 daemon.err miniupnpd[5602]: try_sendto(sock=8, len=459, dest=[ff02::c]:1900): sendto: Permission denied
Wed May 26 20:26:56 2021 daemon.err miniupnpd[5602]: try_sendto(sock=8, len=406, dest=[ff02::c]:1900): sendto: Permission denied
Wed May 26 20:26:56 2021 daemon.err miniupnpd[5602]: try_sendto(sock=8, len=445, dest=[ff02::c]:1900): sendto: Permission denied
Wed May 26 20:26:56 2021 daemon.err miniupnpd[5602]: try_sendto(sock=8, len=406, dest=[ff02::c]:1900): sendto: Permission denied
Wed May 26 20:26:56 2021 daemon.err miniupnpd[5602]: try_sendto(sock=8, len=465, dest=[ff02::c]:1900): sendto: Permission denied
Wed May 26 20:26:56 2021 daemon.err miniupnpd[5602]: try_sendto(sock=8, len=406, dest=[ff02::c]:1900): sendto: Permission denied
Wed May 26 20:26:56 2021 daemon.err miniupnpd[5602]: try_sendto(sock=8, len=469, dest=[ff02::c]:1900): sendto: Permission denied
Wed May 26 20:26:56 2021 daemon.err miniupnpd[5602]: try_sendto(sock=8, len=397, dest=[ff02::c]:1900): sendto: Permission denied
Wed May 26 20:26:56 2021 daemon.err miniupnpd[5602]: try_sendto(sock=7, len=467, dest=239.255.255.250:1900): sendto: No such device
Wed May 26 20:26:56 2021 daemon.err miniupnpd[5602]: try_sendto(sock=7, len=467, dest=239.255.255.250:1900): sendto: No such device
Wed May 26 20:26:56 2021 daemon.err miniupnpd[5602]: try_sendto(sock=7, len=483, dest=239.255.255.250:1900): sendto: No such device
Wed May 26 20:26:56 2021 daemon.err miniupnpd[5602]: try_sendto(sock=7, len=479, dest=239.255.255.250:1900): sendto: No such device
Wed May 26 20:26:56 2021 daemon.err miniupnpd[5602]: try_sendto(sock=7, len=467, dest=239.255.255.250:1900): sendto: No such device
Wed May 26 20:26:56 2021 daemon.err miniupnpd[5602]: try_sendto(sock=7, len=465, dest=239.255.255.250:1900): sendto: No such device

**Comment by miniupnp** [comment]
It looks like the network interface on which the SSDP packers are to be sent is not working or does not support multicast.

It is impossible to tell much more without any detail.

**Comment by vpei** [comment]
> 
> 
> It looks like the network interface on which the SSDP packers are to be sent is not working or does not support multicast.
> 
> It is impossible to tell much more without any detail.

Previously there was no such problem, it is the upgrade to the latest version of this problem.

**Comment by miniupnp** [comment]
Sorry I can't help you without any detail : 
- OS
- network configuration
- miniupnpd version
- etc.
