### ISSUE TITLE
read_permission_line allows incomplete (or missing) IP address in allow/deny rules

### ISSUE THREAD

**Issue by mvadu** [miniupnp/miniupnp#551]
I recently had an issue where due to a bug in script generating the config, IP address part of the `allow` was missing, yet the miniupnpd daemon started, and it did not complain about the config being incomplete. Only symptom was any attempt to port forward was making `match_permission` to fail for any ports. 

https://github.com/miniupnp/miniupnp/blob/2254e8928e658e7f65418bec1efcaa055946f123/miniupnpd/upnppermissions.c#L25

example bad config
```
ext_ifname=ppp0
listening_ip=br0
port=0
enable_upnp=yes
enable_natpmp=yes
secure_mode=yes
upnp_nat_postrouting_chain=PUPNP
upnp_forward_chain=FUPNP
upnp_nat_chain=VUPNP
notify_interval=60
system_uptime=yes
friendly_name=RT-AC86U
model_name=RT-AC86U
model_description=ASUS Wireless Router
model_number=386.2
serial=0c:99:99:99:c6:b0
uuid=3ddcd1d3-2380-45f5-b069-dc6b00c9d922
lease_file=/tmp/upnp.leases
clean_ruleset_interval=600
clean_ruleset_threshold=20
presentation_url=http://192.168.1.1:80/
allow 22-6000 /255.255.255.255 22-6000
min_lifetime=120
max_lifetime=86400

deny 0-65535 0.0.0.0/0 0-65535
```

**Comment by ColinTaylorUK** [comment]
If you had started miniupnpd from the command line you should have seen a warning message. Starting it via the router's services does not send the warning in the syslog however.

```
# miniupnpd -f /etc/upnp/config
parsing error file /etc/upnp/config line 26 : allow 22
```

**Comment by mvadu** [comment]
@ColinTaylorUK correct, so two things there. I believe an incomplete config which will never let the server to handle port forwards, should make it stop the startup sequence. That is the method used in nginx, samba etc. 

Second, the error is currently thrown with a [fprintf(stderror](https://github.com/miniupnp/miniupnp/blob/2254e8928e658e7f65418bec1efcaa055946f123/miniupnpd/options.c#L180) which should be updated to `syslog(LOG_ERROR` so normal syslog parsers can show the error.

**Comment by miniupnp** [comment]
for some reasons, openlog() is called after parsing of configuration file and command line options. it should be changed too.

**Comment by mvadu** [comment]
thank you @miniupnp for considering this bug and fixing it.
