### ISSUE TITLE
pypi missing binary for windows

### ISSUE THREAD

**Issue by mrx23dot** [miniupnp/miniupnp#570]
Please add pre-compiled binary for windows x64/x32 to pypi.
Compiling on every client PC is impractical by pip installation.

**Comment by miniupnp** [comment]
@mrx23dot aren't packages available on https://ci.appveyor.com/project/miniupnp/miniupnp OK ?
if not, why ?

**Comment by miniupnp** [comment]
I'm neither a python developer, nor a Windows developer, so I'm not able to help you.

I'm accepting any Pull Request, but there have been a lot of people complaining the lack of precompiled python packages, and only a few offering help to build one.

**Comment by mrx23dot** [comment]
Only you have access to the appveyor, to take the built binaries from there to pypi you need to add this extra step:

```
deploy_script:
  - ps: |
      if($env:APPVEYOR_REPO_TAG -eq 'true') {
        Write-Output ("Deploying " + $env:APPVEYOR_REPO_TAG_NAME + " to PyPI...")
        &"${Env:PYTHON}/python.exe" -m pip install twine
        &"${Env:PYTHON}/python.exe" -m twine upload -u ${Env:USER} -p ${Env:PASS} --skip-existing dist/\*.whl
      } else {
        Write-Output "No tag for deployment"
      }

```
details https://www.dynamsoft.com/codepool/appveyor-build-deploy-python-wheels.html
it uses this lib to upload it: https://pypi.org/project/twine/

**Comment by miniupnp** [comment]
> Only you have access to the appveyor

???
you mean the appveyor script ? https://github.com/miniupnp/miniupnp/blob/master/appveyor.yml

**Comment by mrx23dot** [comment]
I added windows binaries and instruction in my release:
https://github.com/mrx23dot/miniupnp/releases/tag/miniupnpd_2_2_3
appveyor only retains binaries for 1month.

Only you have permission to publish into your repo 
https://pypi.org/project/miniupnpc/
"The user 'me' isn't allowed to upload to project 'miniupnpc'."

You can try it manually: 
python -m twine upload -u username -p pwd --skip-existing *.whl *.zip

I tried to rename the project to try it out, but wheel need comes from folder structure.

**Comment by miniupnp** [comment]
> Only you have permission to publish into your repo
> https://pypi.org/project/miniupnpc/
> "The user 'me' isn't allowed to upload to project 'miniupnpc'."

That is not my repo. I have no account on pypi.org. You should contact the listed maintainers.

**Comment by mrx23dot** [comment]
@niamster could you please join in?

**Comment by niamster** [comment]
> @niamster could you please join in?

Hello, I'm not a maintainer of that package either, by chance I got permissions to manage granted by https://pypi.org/user/chenhouwu/ to be able to push one update. Did you reach him?

**Comment by mrx23dot** [comment]
Could you grant me and miniupnp maintainer permission?

**Comment by niamster** [comment]
For some reason I can't do that
![Screenshot](https://user-images.githubusercontent.com/211000/136526758-78ad6e80-23d9-4ef2-805e-f487646efab0.png)
@laishulu I think that were you who gave me some permissions initially

**Comment by niamster** [comment]
@mrx23dot what's your `pypi` account? @laishulu granted me a maintainer permissions.
