### ISSUE TITLE
Using gateway address

### ISSUE THREAD

**Issue by mrx23dot** [miniupnp/miniupnp#571]
miniupnp works great with my Virgin Media Hub 3.0 (192.168.0.1) router when I directly connect to it.
But when I use a wifi repeater (which has it's own IP subnet 192.168.10.1) it cannot register the port.

upnp.discover() ok
upnp.selectigd() ok 
upnp.addportmapping() fails 

Not sure if it finds the repeater or the router.
Windows already knows what gateway to use (192.168.0.1).
Would it be possible to use the gateway IP to guide upnp?

**Comment by miniupnp** [comment]
first of all, could you precisely describe your environment ? OS version, miniupnpc library version etc.
It looks like you are using the python module, is that right ? Which python version.

It is easier to help people when we are 100% sure we are talking about the same thing.

**Comment by miniupnp** [comment]
you have to disable the NAT or Routing feature of you repeater that's all.

**Comment by miniupnp** [comment]
@mrx23dot the new version will allow to specify the root desc url like this : 
`upnp.selectigd('http://192.168.0.1/rootDesc.xml')`
