### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by mrx23dot** [miniupnp/miniupnp#572]
Could we add a short documentation for each API function to website or readme?
I couldn't find it on website.

like how to use these:
```
externalipaddress()  -> how does this work?
deleteportmapping()
deleteportmappingrange()
upnpDiscover() 
upnpDiscoverAll() 
upnpDiscoverDevice()
```

**Comment by miniupnp** [comment]
https://github.com/miniupnp/miniupnp/blob/master/miniupnpc/include/upnpcommands.h#L65
https://github.com/miniupnp/miniupnp/blob/master/miniupnpc/include/miniupnpc.h#L44
etc.

Also https://github.com/miniupnp/miniupnp/blob/master/miniupnpc/man3/miniupnpc.3

also for the python module : 
https://github.com/miniupnp/miniupnp/blob/master/miniupnpc/src/miniupnpcmodule.c#L561
