### ISSUE TITLE
UPnP Daemon Unable to start, "Failed to open socket for HTTP on port 2189" , "bind(http): Address already in use" - Looking at Sockets shows that it is not in use

### ISSUE THREAD

**Issue by Spacey67** [miniupnp/miniupnp#583]
Nov 27 12:33:35 miniupnpd 12971 Failed to open socket for HTTP on port 2189 (IPv4). EXITING
Nov 27 12:33:35 miniupnpd 12971 bind(http): Address already in use
Nov 27 12:33:35 miniupnpd 12971 HTTP listening on port 2189
Nov 27 12:33:20 miniupnpd 5317 Failed to open socket for HTTP on port 2189 (IPv4). EXITING
Nov 27 12:33:20 miniupnpd 5317 bind(http): Address already in use
Nov 27 12:33:20 miniupnpd 5317 HTTP listening on port 2189
Nov 27 12:32:48 miniupnpd 64038 Failed to open socket for HTTP on port 2189 (IPv4). EXITING
Nov 27 12:32:48 miniupnpd 64038 bind(http): Address already in use
Nov 27 12:32:48 miniupnpd 64038 HTTP listening on port 2189

Looking under Diagnostics > Sockets there is no entry for port 2189 for any IP that would indicate it's in use

I've disabled the suspected services that typically cause issues, Avahi, pfblockerng, ntopng

Still nothing would get it to start even after multiple reboots,

This started when I was going through and hardening system tunables the last few that I did were:
System\Advanced\System Tunables Add: security.bsd.see_other_gids=0 # Disallow users to see gids
System\Advanced\System Tunables Add: security.bsd.unprivileged_read_msgbuf=0 # Disallow jails to read system buffer
System\Advanced\System Tunables Add: security.bsd.unprivileged_proc_debug=0 # Disallow users to use ptrace(2)
System\Advanced\System Tunables Add: security.bsd.stack_guard_page=1 # Additional stack protection
System\Advanced\System Tunables Add: net.inet6.ip6.v6only=0 # Wildcard ipv6 bindings also bind to ipv4
System\Advanced\System Tunables Add: net.inet.tcp.msl=15000 # Max time (ms) to wait for ACK
System\Advanced\System Tunables Add: net.inet.icmp.icmplim=200 # Limit icmp requests per second
System\Advanced\System Tunables Add: kern.ipc.somaxconn=32768 # Max parallel sockets
System\Advanced\System Tunables Add:net.inet.tcp.maxtcptw=40960 # Max compressed TCP TIME_WAIT
System\Advanced\System Tunables Add:net.inet.tcp.nolocaltimewait=1 # No compressed TCP TIME_WAIT for local conns
System\Advanced\System Tunables Add:net.inet.ip.portrange.first=1024 # First port for outbound
System\Advanced\System Tunables Add:net.inet.ip.portrange.last=65535 # Last port for outbound
System\Advanced\System Tunables Add:net.inet.ip.portrange.randomized=0 # Enable random port allocation
System\Advanced\System Tunables Add:net.inet.tcp.finwait2_timeout=15000 # Finwait2 timeout
System\Advanced\System Tunables Add:net.inet.tcp.fast_finwait2_recycle=1 # Recycle closed FIN_WAIT_2 connections faster
System\Advanced\System Tunables Add:net.inet.ip.fw.dyn_buckets=4096 # Max dyn buckets (ipfw)
System\Advanced\System Tunables Add:net.inet.ip.fw.dyn_max=65536 # Max number of dyn rules
System\Advanced\System Tunables Add:net.inet.ip.fw.dyn_keepalive=1 # Enable keepalive for ipfw
System\Advanced\System Tunables Add:net.inet.ip.forwarding=0 # Disable ip forwarding
System\Advanced\System Tunables Add:net.inet.icmp.drop_redirect=1 # Ignore ICMP redirects
System\Advanced\System Tunables Add:net.inet.ip.redirect=0 # Disable sending IP redirects
System\Advanced\System Tunables Add:net.inet.icmp.log_redirect=0 # No prints of icmp redirects in console
System\Advanced\System Tunables Add:net.inet.ip.intr_queue_maxlen=512 # Maximum size of the IP input queue
System\Advanced\System Tunables Add:net.inet.ip.random_id=1 # Random id's for IP packets
System\Advanced\System Tunables Add:net.inet.tcp.drop_synfin=1 # Drop TCP packets with SYN+FIN

So I THEN, went back and deleted the ones that I added and restarted and it still will not start, so I'm completely lost now.

I believe it actually started when I added : System\Advanced\System Tunables Add:net.inet.ip.fw.dyn_max=65536 # Max number of dyn rules -this morning

Here is a screenshot of my UPnP Settings:

https://imgur.com/a/qHyothX

Here is my NAT port forward mappings:

https://imgur.com/a/U0jmgVX

Worth noting looking at the system logs from earlier on this morning these were present as well when it was working:

Nov 27 11:45:03 miniupnpd 40142 interface index not matching 10 != 3
Nov 27 11:45:03 miniupnpd 40142 interface index not matching 10 != 3
Nov 27 11:45:03 miniupnpd 40142 interface index not matching 10 != 3
Nov 27 11:45:03 miniupnpd 40142 interface index not matching 10 != 3
Nov 27 11:45:03 miniupnpd 40142 interface index not matching 10 != 3
Nov 27 11:45:03 miniupnpd 40142 interface index not matching 10 != 3
Nov 27 11:45:03 miniupnpd 40142 interface index not matching 10 != 3

Any help would be appreciated since I pissed away the whole day trying to figure this out : , )

**Comment by miniupnp** [comment]
```
Nov 27 12:33:20 miniupnpd 5317 Failed to open socket for HTTP on port 2189 (IPv4). EXITING
Nov 27 12:33:20 miniupnpd 5317 bind(http): Address already in use
```
well it means there is already something listening on port 2189...

**Comment by Spacey67** [comment]
It would be nice if it told you what process is using that port
