### ISSUE TITLE
unresolved external symbol from dll

### ISSUE THREAD

**Issue by andreffrosa** [miniupnp/miniupnp#585]
when linking to the .dll provided in the released .zip file I get the following error in Windows 10:

Error	LNK2019	unresolved external symbol __imp_upnpDiscoverAll referenced in function "bool __cdecl open_port(unsigned short,unsigned short,char const *,char const *)" (?open_port@@YA_NGGPEBD0@Z)	D:\Users\X\Documents\Visual Studio 2019\source\repos\PortOpener\out\build\x64-Debug\PortOpener	D:\Users\X\Documents\Visual Studio 2019\source\repos\PortOpener\out\build\x64-Debug\PortOpener.cpp.obj	1

**Comment by pali** [comment]
Could you please try to check if this issue is still prevent in the git master branch? I was fixing issue with upnpDiscoverAll in commit 2e3e6990db97a7ed614ceb0d5514e2a675ef8fef which is more than year old.

**Comment by andreffrosa** [comment]
I can't build the binaries in my machine (I don't have all the tools required) so I'm unable to check that. That is why I resorted to the released binaries in the .zip file and tried to link them to my projected.

**Comment by miniupnp** [comment]
@andreffrosa which .zip file ?
please provide exact reference.

you can download freshly built archives from https://ci.appveyor.com/project/miniupnp/miniupnp

**Comment by andreffrosa** [comment]
> @andreffrosa which .zip file ? please provide exact reference.
> 
> you can download freshly built archives from https://ci.appveyor.com/project/miniupnp/miniupnp

I was using the .zip file provided in the releases of this repository (https://github.com/miniupnp/miniupnp/releases). When I changed to the one from appveyor it started working. Thnak you. Is there any plans for providing the binaries for arm architecture so that we can use it in a raspberry pi?

**Comment by miniupnp** [comment]
you should build binaries from sources.
