### ISSUE TITLE
[Feature request] Add inbound ipv6 traffic rules to firewall

### ISSUE THREAD

**Issue by tenwx** [miniupnp/miniupnp#601]
Platform: OpenWRT
Version:2.3.0

Most routers currently add a rule to the firewall that disables all inbound ipv6 traffic. As a result, p2p applications that support dual-stack networking cannot pass inbound traffic for ipv6 through miniupnpd.
An example of adding a separate ipv6 inbound pass traffic rule in router is as follows:
`
ip6tables -A FORWARD -d {client ipv6 address} -p tcp -m state --state NEW -m tcp --dport {port} -j ACCEPT
`
I hope miniupnpd can support this feature.

**Comment by miniupnp** [comment]
I'm sorry, but doesn't the whole "iptpinhole.c" handles this ?
What is wrong with that is currently done in `add_pinhole` https://github.com/miniupnp/miniupnp/blob/master/miniupnpd/netfilter/iptpinhole.c#L207 ?
