### ISSUE TITLE
miniupnpd-2.0.20170421.tar.gz file size conflict

### ISSUE THREAD

**Issue by geniusjoe** [miniupnp/miniupnp#605]
I'm an openwrt user(aka lede). I often download `miniupnpd-2.0.20170421.tar.gz` source code from the [download site](https://miniupnp.tuxfamily.org/files/index_fr.php) when I compile openwrt. This is my download curl command below, and it will freeze with a 100% download process bar.
```
curl -f --connect-timeout 20 --retry 5 --location --insecure http://miniupnp.free.fr/files/miniupnpd-2.0.20170421.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1010k    0 1010k    0     0    207      0 --:--:--  1:23:13 --:--:-- 
```
I download the file by chrome web downloader, and I find that the download file size (about 1010KB) is larger than the site described (abount 200KB). Besides, when I try to unzip the file, 7-zip FileManager tells me it is a tar file instead of a tar.gz file.

![image](https://user-images.githubusercontent.com/37236056/161426304-f8ccbd88-bc37-4870-aee9-b4328accadcf.png)

I think it might be a small mistake by a resource uploader 😂.

**Comment by miniupnp** [comment]
1. you should not download outdated miniupnpd source code.
2. I think there is an issue with the way the webserver advertise .tar.gz files. Please download from https://miniupnp.tuxfamily.org/

```
$ curl -I http://miniupnp.free.fr/files/miniupnpd-2.0.20170421.tar.gz
HTTP/1.1 200 OK
Date: Sun, 01 May 2022 23:40:23 GMT
Server: Apache/ProXad [Jan 23 2019 20:05:46]
Last-Modified: Fri, 21 Apr 2017 12:02:04 GMT
ETag: "2d9e074-35837-58f9f4bc"
Connection: close
Accept-Ranges: bytes
Content-Length: 219191
Content-Type: application/x-gzip
Content-Encoding: x-gzip

$ curl -I http://miniupnp.tuxfamily.org/files/miniupnpd-2.0.20170421.tar.gz
HTTP/1.1 200 OK
Server: nginx/1.6.2
Date: Sun, 01 May 2022 23:41:16 GMT
Content-Type: application/x-gzip
Content-Length: 219191
Connection: keep-alive
Last-Modified: Fri, 21 Apr 2017 12:02:06 GMT
ETag: "35837-54dac06bf5ef4"
Accept-Ranges: bytes

```
Presences of the `Content-Encoding` header makes curl unzip the file.

**Comment by geniusjoe** [comment]
I switched to download from the new mirror repo. Till now it works just fine.
Thank you very much. 😁
