### ISSUE TITLE
OpenBSD 7.1 - nat rule in anchor ...

### ISSUE THREAD

**Issue by timelessremix** [miniupnp/miniupnp#609]
Hi !

like in the case OpenBSD 6.8 wrong Syntax

pass in quick on XXX inet proto udp from any to any port = XXXX label "XXXX" rdr-to X.X.X.X port XXXX
nat quick on XXX inet proto udp from X.X.X.X port = XXXX to any label "XXXX" nat-to  X.X.X.X port XXXX

the first rule is correct 

but 

the 2nd line the nat rule must be wrong, or i am not right ?
(this line cannot be "processed", because this syntax is not in the man page only (also describe in the other ticket nat-to with pass out ....)
i have never seen this nat line, it is the first time and i use openbsd with miniupnpd for a long time  

sry for broken English

many thx for help

**Comment by sthen** [comment]
This is a duplicate of https://github.com/miniupnp/miniupnp/issues/529

**Comment by timelessremix** [comment]
Thx ! Will close
