### ISSUE TITLE
Fritzbox 7490: Found a (not connected?) IGD

### ISSUE THREAD

**Issue by frederictobiasc** [miniupnp/miniupnp#610]
Hi,
I tried adding a pinhole with upnpc, but it failes with the following error (regardless if -6 is used or not):

Code:
```
130 user@nb-user ~ % upnpc -6 -m wlp3s0 -A 0 5900 2001:<..>:88dd 5901 TCP 300
upnpc : miniupnpc library test client, version 2.2.3.
 (c) 2005-2021 Thomas Bernard.
Go to miniupnp.free.fr/ or miniupnp.tuxfamily.org/
for more information.
List of UPNP devices found on the network :
 desc: [fe80::a96:d7ff:fe77:6a14]:49000/igddesc.xml
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

Found a (not connected?) IGD : [fe80::a96:d7ff:fe77:6a14%25wlp3s0]:49000/igdupnp/control/WANIPConn1
No valid UPNP Internet Gateway Device found.
```
Do you know if Fritzbox is supported? I enabled both UPnP forwarding for my device and UPnP in general.
How can I debug this? On my other home network (OpenWRT-Router), it works as expected: 

```
user@nb-user ~ % upnpc -6 -m wlp3s0 -A 0 5900 2a02:<..>:3861 5901 TCP 300
upnpc : miniupnpc library test client, version 2.2.3.
 (c) 2005-2021 Thomas Bernard.
...
for more information.
List of UPNP devices found on the network :
 desc: [2a02:<..>::1]:5000/rootDesc.xml
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

Found valid IGD : [2a02:<..>::1]:5000/ctl/IPConn
Local LAN ip address : 2a02:<..>:3861
AddPinhole: ([0]:5900 -> [2a02:<..>:3861]:5901) / Pinhole ID = 1 
```

Also posted [here](https://miniupnp.tuxfamily.org/forum/viewtopic.php?t=2477) but no answer yet.

**Comment by VictorVolpe** [comment]
Same problem here with FreeBSD box and AsKey Router (Ubuntu Router). If I set -i flag it works, but applications that rely on miniupnpc library like transmission-daemon dont work at all! It's this library is broken by design?

**Comment by frederictobiasc** [comment]
Thanks for the hint with `-i`. Seems to me that the Fritzbox probably doesn't reply correctly and thereby disturbing the execution of `upnpc`. @VictorVolpe what do you meand with Ubuntu Router? On their website, I only see this embedded plastic boxes, and I'm betting they run some kind of OpenWRT.

**Comment by VictorVolpe** [comment]
> what do you meand with Ubuntu Router?

Don't know. My ISP router branded AsKey is reporting UPnP service as Ubuntu Router. Weird!

**Comment by frederictobiasc** [comment]
Would you mind telling me the exact model of your AsKey router?
Btw: Short investigation led to the [function in question](https://github.com/miniupnp/miniupnp/blob/2df8120326ed4246e049a7a6de707539604cd514/miniupnpc/src/miniupnpc.c#L546)
returning `2 = A valid IGD has been found but it reported as not connected` I'll have a look into it.

**Comment by miniupnp** [comment]
It is difficult to know if it is the Fritzbox or miniupnpc which worngly implements the standard.

Is there a UPnP client that works properly with the FritzBox ?

**Comment by frederictobiasc** [comment]
Can you recommend one to test? I tried the M$-Tool you recommended in the [forum](https://miniupnp.tuxfamily.org/forum/viewtopic.php?t=867), but it doesn't run on wine.

**Comment by miniupnp** [comment]
> Hi Thomas! Thanks for your nice upnp implementation. Can you recommend one to test? I tried the M$-Tool you recommended in the [forum](https://miniupnp.tuxfamily.org/forum/viewtopic.php?t=867), but it doesn't run on wine.

I don't know any other UPNP IGD Pinhole implementation. there must be some, I'm curious to know :)

**Comment by frederictobiasc** [comment]
Do you have a recommendation how to debug this? I would like to start by sending the corresponding soap document manually and have a look at the response. Is there any comfortable way to debug this? Please excuse the question, but I haven't interacted with these endpoints yet. RESTful APIs are a lot more straightforward IMHO.

**Comment by VictorVolpe** [comment]
> Would you mind telling me the exact model of your AsKey router?

Askey RTF8115VW REV5 GPON Router

**Comment by VictorVolpe** [comment]
> It is difficult to know if it is the Fritzbox or miniupnpc which worngly implements the standard.
> 
> Is there a UPnP client that works properly with the FritzBox ?

In my case both qBittorrent Windows and Synolgy NAS DSM work as expected with "wrongly" implemented miniupnp service on Askey router.

**Comment by miniupnp** [comment]
you may use wireshark or a similar tool to capture both the Discovery packets (SSDP) and the SOAP exchanges between your router and the client.
In the SSDP you're looking for the IP used and the LOCATION of the M-SEARCH response :   
![image](https://user-images.githubusercontent.com/1070377/169103018-ba89a259-21f0-4c9f-aefd-6256e4ef0764.png)

in the SOAP request you should look for the IP used 
![image](https://user-images.githubusercontent.com/1070377/169103461-171849a4-a6c1-432b-924c-15144dcf0c09.png)

**Comment by miniupnp** [comment]
@VictorVolpe have you been able to capture the SSDP and HTTP (SOAP) communications between miniupnpc and the _Askey RTF8115VW REV5 GPON Router_ ?
