### ISSUE TITLE
No UPnP device discovered

### ISSUE THREAD

**Issue by hhp-the-maestro** [miniupnp/miniupnp#612]
I have implemented different approach on port forwarding but none works . someone pls help me i have been suffering around this for almost a month.

**Comment by miniupnp** [comment]
can you explain what is your network setup. It is impossible to help you without any detail about your problem.

**Comment by hhp-the-maestro** [comment]
I am on my ubuntu machine connected to a 5g or 4g router and i am not able to discover my upnp device using miniupnp or any of the methods which i implemented, but today when  i ran a msearch script and it gave me some outs, and rapidly i used the  upnp-port-forward library in a small script which gave me further note that a upnp device was found  "jio-setup" along with a nat error,  i was pretty happy i did not realize how it worked but after some time when i ran the similar scripts which gave me None. how can i figure out this one. Is there any other means by which my server can be contacted from outside the network.

**Comment by miniupnp** [comment]
If you don't understand what it does means to give the network setup, I definitely can't help you.
regards
