### ISSUE TITLE
code 402 (Invalid Args) code 714 (NoSuchEntryInArray)

### ISSUE THREAD

**Issue by grifs250** [miniupnp/miniupnp#625]
when i write this C:\Users\mikel>C:\Users\mikel\OneDrive\Documents\upnpc.exe -a [my public ip] [port] [port] TCP
i get an error: failed with code 402 (Invalid Args)
GetSpecificPortMappingEntry() failed with code 714 (NoSuchEntryInArray)
I tried to use my pc ip and everiting was working but of course i could not go in the port from the out side.
Please help me?

**Comment by miniupnp** [comment]
@grifs250 what are you trying to do ?
If the port mapping is not working, you'd better see that with you router vendor.
