### ISSUE TITLE
Request: add [duration] option for -r command

### ISSUE THREAD

**Issue by ryny24** [miniupnp/miniupnp#626]
I love miniupnpc! Thank you so much, this has been so helpful.     It's easiest to use the -r command, as you don't need to determine your local IP, and you can combine multiple ports.  However, if you shutdown the server and reinstall the OS, then I need to reboot my router and disrupt my family because it defaults the duration to 0 (perm).  The delete (-d) does not work for me when my router thinks it's from another machine.

I would love to be able to set -r to 60 minutes. Is this possible?

Thank you!

**Comment by miniupnp** [comment]
well you can use the -a command for setting duration.

however the upnpc command line tool is just a sample program, you are free to modify it to your needs.

**Comment by ryny24** [comment]
The -a requires the local IP, which means I'd need to expand my script to determine that first and put it in a varaible. I'm trying to keep it to 1 simple command.   The -r works, just annoying with that never ending duration. Thank you!

**Comment by miniupnp** [comment]
A few month ago I added the possibility to use @ for ip with -a option :  
https://github.com/miniupnp/miniupnp/commit/51f185fd13bca5f10b9b80ebd4ad4eac5e22fd11
see #532
