### ISSUE TITLE
failed with code -3 (Miniupnpc HTTP error)

### ISSUE THREAD

**Issue by Slavfucious** [miniupnp/miniupnp#627]
so i am trying to port forward aaand idk what is happening:

Found valid IGD : http://192.168.1.1:52869/upnp/control/WANIPConnection
Local LAN ip address : 192.168.1.11
ExternalIPAddress = 
AddPortMapping(10204, 4450, 192.168.1.11) failed with code -3 (Miniupnpc HTTP error)

<root>
<specVersion>
</specVersion>
<device>
<deviceType>
</deviceType>
<friendlyName>netis-WF2411E</friendlyName>
<manufacturer>netis</manufacturer>
<manufacturerURL>http://www.netis-systems.com/</manufacturerURL>
<modelDescription>WLAN Access Point</modelDescription>
<modelName>netis-WF2411E</modelName>
<modelNumber>1.00</modelNumber>
<modelURL>http://www.netis-systems.com/</modelURL>
<UDN>uuid:12342409-1234-1234-5678-ee1234cc5678</UDN>
<serviceList>
<service>
<serviceType>urn:schemas-dummy-com:service:Dummy:1</serviceType>
<serviceId>urn:dummy-com:serviceId:dummy1</serviceId>
<controlURL>/dummy</controlURL>
<eventSubURL>/dummy</eventSubURL>
<SCPDURL>/dummy.xml</SCPDURL>
</service>
</serviceList>
<deviceList>
<device>
<deviceType>urn:schemas-upnp-org:device:WANDevice:1</deviceType>
<friendlyName>netis-WF2411E</friendlyName>
<manufacturer>netis</manufacturer>
<manufacturerURL>http://192.168.1.1</manufacturerURL>
<modelDescription>WANCommonInterfaceConfig</modelDescription>
<modelName>netis-WF2411E</modelName>
<modelNumber>1</modelNumber>
<modelURL>http://www.netis-systems.com/</modelURL>
<serialNumber>00000000</serialNumber>
<UDN>uuid:12342409-1234-1234-5678-ee1234cc5678</UDN>
<UPC>MINIUPNPD</UPC>
<serviceList>
<service>
<serviceType>
urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1
</serviceType>
<serviceId>urn:upnp-org:serviceId:WANCommonIFC1</serviceId>
<controlURL>/upnp/control/WANCommonInterfaceConfig</controlURL>
<eventSubURL>/upnp/event/WANCommonInterfaceConfig</eventSubURL>
<SCPDURL>/wancfg.xml</SCPDURL>
</service>
</serviceList>
<deviceList>
<device>
<deviceType>urn:schemas-upnp-org:device:WANConnectionDevice:1</deviceType>
<friendlyName>netis-WF2411E</friendlyName>
<manufacturer>netis</manufacturer>
<manufacturerURL>http://www.netis-systems.com/</manufacturerURL>
<modelDescription>WANConnectionDevice</modelDescription>
<modelName>netis-WF2411E</modelName>
<modelNumber>1</modelNumber>
<modelURL>http://www.netis-systems.com/</modelURL>
<serialNumber>00000000</serialNumber>
<UDN>uuid:12342409-1234-1234-5678-ee1234cc5679</UDN>
<UPC>MINIUPNPD</UPC>
<serviceList>
<service>
<serviceType>urn:schemas-upnp-org:service:WANIPConnection:1</serviceType>
<serviceId>urn:upnp-org:serviceId:WANIPConn1</serviceId>
<controlURL>/upnp/control/WANIPConnection</controlURL>
<eventSubURL>/upnp/event/WANIPConnection</eventSubURL>
<SCPDURL>/wanipcn.xml</SCPDURL>
</service>
</serviceList>
</device>
</deviceList>
</device>
</deviceList>
<presentationURL>http://192.168.1.1/</presentationURL>
</device>
</root>

**Comment by miniupnp** [comment]
miniupnp is failing to send the AddPortMapping command correctly to your router.  Does it work well with others UPNP clients ?
you could try to use wireshark or another network analyzer to see why the HTTP request is failing.

**Comment by Slavfucious** [comment]
mm, im kinda noobie on that stuff, can you show me the wireshark methood? or some instructions idk

**Comment by miniupnp** [comment]
please do a capture of the HTTP stream between miniupnpc and the router.

**Comment by niko301** [comment]
![image](https://user-images.githubusercontent.com/63957391/192378036-a986643a-82aa-4fbc-bba9-be4fdca2ab88.png)

**Comment by niko301** [comment]
how to do the capture ?

**Comment by niko301** [comment]
im Slavfucious btw , but from alt acc

**Comment by Slavfucious** [comment]
ye i agree

**Comment by miniupnp** [comment]
> how to do the capture ?

use wireshark or another network analyzer tool.

**Comment by miniupnp** [comment]
@Slavfucious by the way, what is your setup ? Router ? OS ? miniupnpc version ?
