### ISSUE TITLE
Warning in upnpc.c line 153

### ISSUE THREAD

**Issue by vonj** [miniupnp/miniupnp#631]
```
upnpc.c:153:23: warning: ‘%d’ directive output may be truncated writing
between 1 and 10 bytes into a region of size 6 [-Wformat-truncation=]
  153 |   snprintf(index, 6, "%d", i);

```

In runtime, this will never be a problem because the while() condition checks for values larger than 65535. However, a fix would silence this warning, and it could also be argued that it's safer defence in depth to fix this warning.

I see two easy fixes: either change the type of the variable `i` to uint16_6 so it can never be more than 5 digits long. This would also require to change the while condition to `i <= 65535` instead of `i < 65536`.

Or the `index` string can be changed to 10 bytes long instead of 6 bytes long. ( `char index[10];` )

Will you accept a pull request for either of these?

**Comment by miniupnp** [comment]
well, as you said, this is a false positive. There is no reason to fix a working code :)

however, changing the line to `snprintf(index, 6, "%hu", (uint16_t)i);` could do the trick ;)
Or changing i to be a uint16_t
