### ISSUE TITLE
cmake does not install upnpc+external-ip binaries and miniupnpc manpage

### ISSUE THREAD

**Issue by prusnak** [miniupnp/miniupnp#637]
When I build and install miniupnpc with make install I see upnpc+external-ip binaries and manpage for miniupnpc are installed.

However, when I build and install via cmake, neither of this is installed. I would expect the cmake install does the same.

**Comment by miniupnp** [comment]
indeed, I see that the the cmake install installs : 
* .h files
* libraries
* pkgconfig (miniupnpc.pc)

Missing : 
* man pages
* binaries

**Comment by miniupnp** [comment]
@prusnak can you test the branch https://github.com/miniupnp/miniupnp/tree/637-cmake-install and tell me if that's ok ?

**Comment by prusnak** [comment]
I confirm that 014c9df8ee7a36e5bf85aa619062a2d4b95ec8f6 fixes the issue.
