### ISSUE TITLE
Problem running

### ISSUE THREAD

**Issue by SaladOwO** [miniupnp/miniupnp#639]
When running upnpc shared or static nothing happens. List devices shows up but closes shortly after. This used to work for me, what's different?

**Comment by miniupnp** [comment]
Nobody can help you if you provide so little information.

Only you can know "what's different" :laughing:

**Comment by SaladOwO** [comment]
Doesn't matter anymore, didn't need upnp. I told you what happened, the exes don't do anything for me. Like I said though, doesn't matter now.

**Comment by SaladOwO** [comment]
Appreciate the lackluster help, though.
