### ISSUE TITLE
Don't assert default policy in nftables scripts?

### ISSUE THREAD

**Issue by HarukaMa** [miniupnp/miniupnp#649]
Currently the nftables init script asserts several default policies:

https://github.com/miniupnp/miniupnp/blob/e439318cf782e30066d430f27a1365e013a5ab94/miniupnpd/netfilter_nft/scripts/nft_init.sh#L21-L23
https://github.com/miniupnp/miniupnp/blob/e439318cf782e30066d430f27a1365e013a5ab94/miniupnpd/netfilter_nft/scripts/nft_init.sh#L47-L49
https://github.com/miniupnp/miniupnp/blob/e439318cf782e30066d430f27a1365e013a5ab94/miniupnpd/netfilter_nft/scripts/nft_init.sh#L57-L59

While those are sensible defaults, setting it as a default action might be disruptive depending on the running system's configuration. (Broke my router, actually. Fortunately it's on a local network.)

Removing the policies should not affect how miniupnpd works. Maybe considering removing them?

**Comment by HarukaMa** [comment]
I'll leave this issue open to let you decide if you still want to change the server's network configuration in a potentially disruptive way by default. You can close this issue if you decide that it's fine.

**Comment by miniupnp** [comment]
as explained by @svenauhagen in #650 you don't have to use the default `nft_init.sh`  and can build your own tables/chains.

`nft_init.sh` is designed to fit the most cases and it is reasonable to drop by default incoming traffic from the internet.

What's the most disruptive, is to install miniupnpd and run its provided init scripts without customizing them and the  whole configuration to your needs first.
