### ISSUE TITLE
miniupnpd: Enable secure mode by default

### ISSUE THREAD

**Issue by MoonlightWave-12** [miniupnp/miniupnp#657]
Currently, in [miniupnpd.conf](https://github.com/miniupnp/miniupnp/blob/214deacb11aa9176f00eaac65450c8c9a5a6026c/miniupnpd/miniupnpd.conf#L117), Secure Mode is disabled by default.
It should probably be enabled by default.

The most common use-cases for UPnP-port-forwarding seem to be:
videogames, messenger-apps, torrent-apps, and other software using peer-to-peer-connections.
Such apps/videogames generally only need to set up port-forwarding for the device they are used/played on.
I currently don't know of any exceptions to this.

**Comment by miniupnp** [comment]
changed in f91a32ff02769701baa1f46c5751c0eb1b8f2f8d
Will be included in the next release
