### ISSUE TITLE
Upnpc isn't opening the port?

### ISSUE THREAD

**Issue by Jamari2k2k2k** [miniupnp/miniupnp#660]
upnpc : miniupnpc library test client, version 1.9.
 (c) 2005-2014 Thomas Bernard.
Go to http://miniupnp.free.fr/ or http://miniupnp.tuxfamily.org/
for more information.
List of UPNP devices found on the network :
 desc: http://192.168.1.1:40408/rootDesc.xml
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

Found valid IGD : http://192.168.1.1:40408/ctl/IPConn
Local LAN ip address : 192.168.1.205
ExternalIPAddress = 47.132.180.85
InternalIP:Port = 47.132.180.85:25565
external 47.132.180.85:25565 TCP is redirected to internal 47.132.180.85:25565 (duration=604800)

(I also see that the internal and external is the same)

**Comment by miniupnp** [comment]
`upnpc : miniupnpc library test client, version 1.9.` => it is an outdated version.

have you test with other clients ?

**Comment by miniupnp** [comment]
no answer, bye bye !
