### ISSUE TITLE
miniupnpd debug log shows sometime my ip address is wrong

### ISSUE THREAD

**Issue by kpas8288** [miniupnp/miniupnp#670]
miniupnpd 2.3.3 master-dc67a14f98 Aug 21 2023
run on my asus router AX86U

don't known what happened
from the debug log i found lots of this messages
`miniupnpd[11846]: Check protocol udp for port 56562 on ext_if ppp0 [, 00000021`
"123.xxx.xxx.177" is corrrect
and "[" is obviously wrong

![image](https://github.com/miniupnp/miniupnp/assets/42954645/1d931c53-e459-4977-a712-5fb4bc3fcb23)

**Comment by miniupnp** [comment]
it looks like ` getifaddr`  fails. 
have you built miniupnpd yourself ?  in that case, could you tell me if USE_GETIFADDRS is defined in config.h ?

**Comment by miniupnp** [comment]
It looks like if there is no AF_INET address set for the network interface, the return values are not set correctly.

**Comment by kpas8288** [comment]
> it looks like ` getifaddr` fails. have you built miniupnpd yourself ? in that case, could you tell me if USE_GETIFADDRS is defined in config.h ?

no, i use the binary program from asus merlin's firmware

**Comment by miniupnp** [comment]
what  the output of ` ifconfig ppp0`  ?

**Comment by kpas8288** [comment]
> what the output of ` ifconfig ppp0` ?
![image](https://github.com/miniupnp/miniupnp/assets/42954645/1f0c2f5a-0d7e-4841-9536-7679115fdd80)

and i found some error in syslog too
i think it is same error
![image](https://github.com/miniupnp/miniupnp/assets/42954645/68154c8e-6415-47f8-ae62-e5562abd0843)

**Comment by miniupnp** [comment]
from your previous logs, it looks like it sometimes has an address, sometime not....

**Comment by miniupnp** [comment]
096478dce19731ffe6fbba61dfad2fea4b57b37e should fix things. I should release a new version soon

**Comment by miniupnp** [comment]
fixed in version 2.3.4 : 
https://miniupnp.tuxfamily.org/files/miniupnpd-2.3.4.tar.gz

**Comment by kpas8288** [comment]
it works
![image](https://github.com/miniupnp/miniupnp/assets/42954645/2cded8d4-6f65-479e-8184-84c7263a3559)
