### ISSUE TITLE
miniupnpd: Enable PCP/NAT-PMP protocols by default

### ISSUE THREAD

**Issue by Self-Hosting-Group** [miniupnp/miniupnp#684]
like OpenWRT and X-Wrt. PCP and NAT-PMP are also simpler and newer than UPnP IGD.
https://github.com/openwrt/packages/blob/master/net/miniupnpd/files/upnpd.config#L3
https://github.com/x-wrt/packages/blob/master/net/miniupnpd/files/upnpd.config#L3
https://datatracker.ietf.org/doc/html/rfc6887
https://datatracker.ietf.org/doc/html/rfc6886
https://en.wikipedia.org/wiki/Port_Control_Protocol

**Comment by miniupnp** [comment]
@Self-Hosting-Group that's more a packaging issue, isn't it ?

NATPMP and PCP support are enabled in the build by default, so it is only a configuration to choose to enable or disable it at runtime.

**Comment by miniupnp** [comment]
I think you haven't understood my point : miniupnpd is almost always installed via a package system. It is up to the package maintainer to choose default options in the package.

For example, [OpenWRT miniupnpd package](https://openwrt.org/docs/guide-user/firewall/upnp/miniupnpd) maintainers have decided to enable NAT-PMP and PCP by default.

If you are dissatisfied with a package default, please contact its maintainer.
