### ISSUE TITLE
miniupnpd: Cannot open ports <1024 with IPv6 and IGD unlike IPv4 or PCP

### ISSUE THREAD

**Issue by Self-Hosting-Group** [miniupnp/miniupnp#692]

**Comment by miniupnp** [comment]
I think that is allowed in the standard. Let me look for the information

**Comment by miniupnp** [comment]
As the writers of the UPnP IGD standards recommend, you should probably not use UPnP IGD if you need to open port 80 and 443.

Permanent IPv6 pinholes for such service should be configured on the firewall by another mean than UPnP IGD.
