### ISSUE TITLE
miniupnpd: Does not send byebye before alive on startup (IGDv2 compliance)

### ISSUE THREAD

**Issue by Self-Hosting-Group** [miniupnp/miniupnp#697]
Upon startup, UPnP IGD DCP MUST broadcast an ssdp:byebye before sending the initial
ssdp:alive onto the local network. Sending an ssdp:byebye as part of the normal start up process
for a UPnP device ensures that UPnP control points with information about the previous device
http://upnp.org/specs/gw/UPnP-gw-WANIPConnection-v2-Service.pdf

**Comment by miniupnp** [comment]
OK, that's a change between IGDv1 and IGDv2

**Comment by miniupnp** [comment]
> @miniupnp Can this also be activated if UPNP_STRICT is not set?

Why ?

**Comment by miniupnp** [comment]
So you have not understood... In the case you are describing it is almost useless to broadcast byebye after the restart because the old port is not known (because of the restart).

That part of the specification makes little sense. All that kind of feature are enabled only when miniupnpd is built with UPNP_STRICT.

**Comment by miniupnp** [comment]
You are free to build miniupnpd with UPNP_STRICT enabled in order to enable all the features which makes it comply more closely with the standards.

but most are theses features are useless for most people.

**Comment by miniupnp** [comment]
thank you for your explanation.

But you have not understood what I have just explained to you : 
In you case, as the router is unexpectedly disconnected from the power supply, the old port is not known after the restart. So the router is enable to broadcast the byebye message about the old port.

Have you understood now ?

Also as there should be only one IGD on the network, the clients will very probably use the freshest one, so advertising the new one is sufficient in real life conditions.

**Comment by miniupnp** [comment]
@Self-Hosting-Group Let me be clear : I thank you for opening this issue and helping me improve the IGDv2 standard compliance.

But this feature is useless in real-life condition, which explains why nobody never bothered about it.

**Comment by miniupnp** [comment]
Other UPNP IGD also multicast advertisement every 2 or 3 minutes.

**Comment by miniupnp** [comment]
> > Have you understood now ?
> 
> In SSDP, the deavertising with byebye does NOT contain a location header (including the port), only the UUID, and invalidates all advertisements of that UUID.

either the "old" generated UUID are not known upon reboot
or the UUID is fixed and there is no need to broadcast byebye message as the new advertisement messages will use it and inform the control points of the new location and state of the rebooted IGD.

**Comment by miniupnp** [comment]
> > Other UPNP IGD also multicast advertisement every 2 or 3 minutes.
> 
> Often implementations have copied/adopted many code/defaults from miniupnp because the project is already old and because the UDA/IGD standards in particular are not easy to read/interpret.

that's kind to think that miniupnpd was the inspiration from most implementation, but miniupnpd mimicked already existing implementations using the intel UPNP SDK (now libupnp ?).
I think one of the first home router vendor which implemented UPNP IGD was linksys and they opensourced their firmware.
