### ISSUE TITLE
miniupnpd: SSDP search response cache-control header, no UPnP UDA 1.0 compliance

### ISSUE THREAD

**Issue by Self-Hosting-Group** [miniupnp/miniupnp#698]
The cache-control max-age is set based on notify_interval for SSDP notifications, but is hardcoded for SSDP M-SEARCH responses.

Field value MUST have the max-age directive ("max-age=") followed by an integer that specifies the number of
seconds the advertisement is valid. After this duration, control points SHOULD assume the device (or service) is no longer
available; as long as a control point has received at least one advertisement that is still valid from a root device, any of its
embedded devices or any of its services, then the control point can assume that all are available. The number of seconds
SHOULD be greater than or equal to 1800 seconds (30 minutes), although exceptions are defined in the text above. Specified
by UPnP vendor. Other directives MUST NOT be sent and MUST be ignored when received.
https://upnp.org/specs/arch/UPnP-arch-DeviceArchitecture-v1.1.pdf

Then the default notification interval should probably also be changed to >=900 seconds, so that the effective cache-control header has a max-age of 1800 and is compliant. It might be better to set the max-age to notify_interval * 2 plus 20 seconds and a default notify_interval of >=890.

From the specification:
In addition, the device MUST re-send its advertisements periodically prior to expiration of the duration specified in
the CACHE-CONTROL header field; it is RECOMMENDED that such refreshing of advertisements be done at a randomly-distributed
interval of less than one-half of the advertisement expiration time, so as to provide the opportunity for recovery from lost
advertisements before the advertisement expires, and to distribute over time the advertisement refreshment of multiple devices
on the network in order to avoid spikes in network traffic.

**Comment by miniupnp** [comment]
I have to search the differences between UPnP UDA versions.

[UDA 1.0](http://upnp.org/specs/arch/UPnP-arch-DeviceArchitecture-v1.0.pdf) 1.2.3 Discovery: Search: Response (p21) : 
CACHE-CONTROL
Required. Must have max-age directive that specifies number of seconds the advertisement is valid. After this duration,
control points should assume the device (or service) is no longer available. Should be greater than or equal to 1800
seconds (30 minutes), although exceptions are defined in the text above. Specified by UPnP vendor. Integer.

[UDA 1.1](http://upnp.org/specs/arch/UPnP-arch-DeviceArchitecture-v1.1.pdf) 1.3.3 Search response (p34) : 
CACHE-CONTROL
REQUIRED. Field value MUST have the max-age directive (“max-age=”) followed by an integer that specifies the number of
seconds the advertisement is valid. After this duration, control points SHOULD assume the device (or service) is no longer
available; as long as a control point has received at least one advertisement that is still valid from a root device, any of its
embedded devices or any of its services, then the control point can assume that all are available. The number of seconds
SHOULD be greater than or equal to 1800 seconds (30 minutes), although exceptions are defined in the text above. Specified by UPnP vendor. Other directives MUST NOT be sent and MUST be ignored when received.

[UDA 2.0](https://openconnectivity.org/upnp-specs/UPnP-arch-DeviceArchitecture-v2.0-20200417.pdf) 1.3.3 Search response (p40) : 
CACHE-CONTROL
Required. Field value shall have the max-age directive (“max-age=”) followed by an integer that specifies the
number of seconds the advertisement is valid. After this duration, control points should assume the device (or
service) is no longer available; as long as a control point has received at least one advertisement that is still
valid from a root device, any of its embedded devices or any of its services, then the control point can assume
that all are available. The number of seconds should be greater than or equal to 1800 seconds (30 minutes),
although exceptions are defined in the text above. Specified by UPnP vendor. Other directives shall notbe sent
and shall be ignored when received.

**Comment by miniupnp** [comment]
that is possible I mimicked the Linksys 802.11b which used 120 seconds...

**Comment by miniupnp** [comment]
I should make the notify interval match...

**Comment by miniupnp** [comment]
why are you complicating things with +20 sec ? it is totally useless.

**Comment by miniupnp** [comment]
but the interval should be a bit random. Like 900sec is between 850 and 900

**Comment by miniupnp** [comment]
> > but the interval should be a bit random. Like 900sec is between 850 and 900
> 
> Because I have read the proposed UDA standards.
> 
> **Cited from the UDA specifications:** ... it is Recommended that suchrefreshing of advertisements be done at a randomly-distributed interval of less than one-half of the advertisement expiration time, so as to provide the opportunity for recovery from lost advertisements before the advertisement expires ...
> 
> Have you considered this?

what  don't you understand when I say a random interval between 850 and 900 ?
My english is sometimes bad.

**Comment by miniupnp** [comment]
> > what don't you understand when I say a random interval between 850 and 900 ?
> 
> Before the maximum, a few seconds for processing, so never exactly 900. 890+20 gives the 1800 a simple number without random, so much easier, but random is better. But how does it work if the user wants the maximum recommended interval of 43190 (little <12 hours), what is the code then? I don't think we should make notify_interval unchangeable, should we?

So you don't understand what I am saying :(
sorry

**Comment by miniupnp** [comment]
NOTIFY "announcement" and M-SEARCH search/response are two different things.

**Comment by miniupnp** [comment]
https://openconnectivity.org/upnp-specs/UPnP-arch-DeviceArchitecture-v2.0-20200417.pdf

There are two modes of "Discovery" : 
1.2 Advertisement (using NOTIFY)
1.3 Search (using M-SEARCH)
