### ISSUE TITLE
miniupnpd: clean_ruleset_threshold/interval option not clearly described

### ISSUE THREAD

**Issue by Self-Hosting-Group** [miniupnp/miniupnp#699]
By default, the clean_ruleset_interval configuration option is set to 0 (disabled). The provided example configuration file changes this to 600 seconds, but if no configuration file or the -r command line option is given, the function is disabled.

Is this correct?

**Comment by miniupnp** [comment]
why would it be incorrect ?
Why is that "probably insecure default configuration" ?

**Comment by miniupnp** [comment]
The documentation is probably not clear enough, but there is no security issue : No expired port mapping is kept open.

Most IGDv1 implementation only supported infinite lease duration, so it is possible to enable the automatic removal of _unused_ port mappings in miniupnpd.

If you had more carefully looked at the code, you would have seen that, in its main loop, just after cleaning "unused rules", miniupnpd remove expired port mappings.

**Comment by miniupnp** [comment]
> How about the following description/sample configuration file?
> 
> ```
> # Unused rules cleaning
> # Clean ruleset threshold of number of rules cleaned once (default 20)
> #clean_ruleset_threshold=20
> # Clean ruleset (delay) interval in seconds (default 0, no delay)
> #clean_ruleset_interval=0
> ```

What is your question ?
Indeed that description should be clarified, as I stated above.

**Comment by systemcrash** [comment]
Hi gents - I admit the language here can be a bit ambiguous. Although the code comment seems clear - the intra-cleanse interval; the time interval between successive cleanse runs.

**Comment by systemcrash** [comment]
This one 

https://github.com/miniupnp/miniupnp/blob/1a49233fe76f869f8c2cef6c27e18375ea2cf6fd/miniupnpd/miniupnpd.c#L902

**Comment by miniupnp** [comment]
0 is to disable the cleaning. That is the one thing that is clear in the current miniupnpd.conf comment : 
```
# Clean process work interval in seconds. default to 0 (disabled).
```

**Comment by miniupnp** [comment]
@Self-Hosting-Group you are adding confusion where there wasn't :
Does the word "unused" has the same meaning as the word "expired" ?
No.
As explained [above](https://github.com/miniupnp/miniupnp/issues/699#issuecomment-1911193717) most IGDv1 implementation don't support port mappings expiration, so miniupnpd includes a feature to clean the ruleset (remove some of the port mappings) periodically by removing **unused** ones.

How many explanations do you need to understand ?

**Comment by miniupnp** [comment]
@Self-Hosting-Group I have received 10 notification email about this issue between 31/01/2024 07:53 and 31/01/2024 10:31.
I would probably ban the person responsible for this spam if it happens again.
