### ISSUE TITLE
miniupnpd: Add date header by default even without ./configure --strict

### ISSUE THREAD

**Issue by Self-Hosting-Group** [miniupnp/miniupnp#702]
This is for compliance, the date header has been specified since UPnP UDA 1.0.

FreeBSD ports packages seem to be built with the date header (strict mode) by default, see:
﻿https://github.com/freebsd/freebsd-ports/blob/main/net/miniupnpd/Makefile#L41﻿

RECOMMENDED. Field value contains date when response was generated. "rfc1123-date" as defined in RFC 2616
﻿https://openconnectivity.org/upnp-specs/UPnP-arch-DeviceArchitecture-v1.1.pdf﻿

**Comment by miniupnp** [comment]
Date header is recommended but not mandatory. So there is no compliance problem with not including it by default.
No issue was ever reported about it in almost 18 years, so I'm pretty confident that IGD Control point implementations don't rely on this header.

If for your usage you need that Date header, just do as the FreeBSD port maintainer : just enable STRICT mode.
