### ISSUE TITLE
Main mirror appears to be down

### ISSUE THREAD

**Issue by nevack** [miniupnp/miniupnp#722]
Main mirror, located at https://miniupnp.tuxfamily.org/, appears to be down as of right now.

Is this some planned retirement, or it will be revived?

**Comment by Coeur** [comment]
All the subdomains of tuxfamily are down:
- https://projects.tuxfamily.org (HTTP 502) → http://00teslek.tuxfamily.org/ , http://0.tuxfamily.org/ , http://0x109.tuxfamily.org/ , http://0xcode.tuxfamily.org/ , ...
- https://webmail.tuxfamily.org (HTTP 502)
- https://staff.tuxfamily.org (invalid certificate)
- https://forum.tuxfamily.org (no response)
- https://faq.tuxfamily.org (no response)
- https://irc.tuxfamily.org (no response)

**Comment by miniupnp** [comment]
https://www.tuxfamily.org/ works.
Please fund them to help the site stay online.
