### ISSUE TITLE
Build Error: function 'main' appears twice? 

### ISSUE THREAD

**Issue by dirt2022** [miniupnp/miniupnp#724]
I am compiling monero wallet.
But when I run:make,the submodule throws an error:
```
In file:libminiupnp.o:
Multiple definition of function `main'
submod/src/miniupnp/upnp.c
’int main(int argc,char ** argv)’
submod/src/miniupnp/listdevices.c
'int main(int argc,char **argv)'

/use/bin/ld returned with error code 1
Build failed.
```

**Comment by dirt2022** [comment]
Comment file : miniupnpc/CMakeLists.txt line 72.
```
set (MINIUPNPC_SOURCES
  igd_desc_parse.c
  miniupnpc.c
  minixml.c
  minisoap.c
  minissdpc.c
  miniwget.c
  upnpcommands.c
  upnpdev.c
  upnpreplyparse.c
  upnperrors.c
  connecthostport.c
  portlistingparse.c
  receivedata.c
#  listdevices.c
        addr_is_reserved.c
  connecthostport.h
```
And Debian (testing) version doesn't contain function:
`strdup' in the compiler package.
Add these following lines: to listdevices.c:
```C
#ifndef strdup
        char * strdup(const char * str){
                if (str == NULL){
                        return NULL;
                }
                char * res=(char *)malloc((strlen(str)+1) * sizeof(char));
                if (res == NULL){
                        return NULL;
                }
                memcpy(res,str,sizeof(char) * (strlen(str)+1));
                return res;
        }
#endif
```

**Comment by miniupnp** [comment]
how is that possible that Debian (testing) has no strdup ?

**Comment by miniupnp** [comment]
@dirt2022 which sources are you building ?
[CMakeLists.txt](https://github.com/miniupnp/miniupnp/blob/master/miniupnpc/CMakeLists.txt#L80) does not references `listdevices.c`

**Comment by dirt2022** [comment]
From the submodule in monero wallet source code.
Thomas BERNARD ***@***.***>于 2024年4月8日 07:38写道：
@dirt2022 which sources are you building ?
CMakeLists.txt does not references listdevices.c

**Comment by dirt2022** [comment]
Sorry,maybe I am using the broken package.
But I find the listdevices.c in the repo.

https://github.com/miniupnp/miniupnp/tree/master/miniupnpc/src/listdevices.c


Thomas BERNARD ***@***.***>于 2024年4月8日 07:34写道：

**Comment by dirt2022** [comment]
The code has been out of date.So I met the error message.Sorry.
And I am using the cloudflare dns to speed up visiting github.(just set the dns server to 1.1.1.1)
And from 8.8.8.8 , I got the A record : github.com 20.x.x.x
from 1.1.1.1 I got the record 140.82.x.x
Maybe the main site and the mirror site has time latency?(In some places,we cannot connect to the github main site.) :(

**Comment by miniupnp** [comment]
@dirt2022 latest code is available on https://github.com/miniupnp/miniupnp

"Official" GPG signed sources releases from 
- https://miniupnp.tuxfamily.org/files/
- http://miniupnp.free.fr/files/
