### ISSUE TITLE
With IGDv2 + pinhole support, qbittorrent generates "miniupnpd: Failed to parse INET6 address "(null)"" errors

### ISSUE THREAD

**Issue by RMerl** [miniupnp/miniupnp#725]
Based on one of my users who is testing the pinhole support I'm adding to Asuswrt-Merlin, it seems that when his qbittorrent client tries to open IPv6 pinholes, it provides an empty remote IP, generating the following errors in syslog:

```
miniupnpd[20735]: Failed to parse INET6 address "(null)"
```

I don't have the user's miniupnpd log, but based on the screenshots he posted, it seems that the (null) value is from the remote IP.

Is this a bug with qbittorrent, or with miniupnpd?  An empty remote IP should most likely be handled as meaning "Any remote IP" in the pihole rule.  Maybe miniupnpd should handle these as such?

Tests were done with miniupnpd 2.3.6.

**Comment by miniupnp** [comment]
https://upnp.org/specs/gw/UPnP-gw-WANIPv6FirewallControl-v1-Service.pdf
2.6.3.2 p17 : 
> RemoteHost is string type variable that describes source address for the pinhole. This can be wildcarded

**Comment by miniupnp** [comment]
an empty `RemoteHost` is accepted and treated as a wildcard (as the value `*` )

It looks like the value `(null)` is  used here.
Please check what is in the SOAP Request

**Comment by RMerl** [comment]
I just installed qbitorrent myself to attempt to reproduce the reported error.

> Please check what is in the SOAP Request

No idea how to do that.  Running miniupnpd in debug mode only shows this when qbittorrent is started (omitting the three other pinholes it also creates, as well as the rest of the chatter):

```
miniupnpd[18881]: PCP request received from 192.168.10.71:55858 60bytes
miniupnpd[18881]: UPnP permission rule 3 matched : port mapping accepted
miniupnpd[18881]: Check protocol tcp for port 29642 on ext_if ppp0 198.100.100.100, 41E010C6
miniupnpd[18881]: PCP MAP: added mapping TCP 29642->192.168.10.71:29642 'PCP MAP 79a327979a404297d06bf78a'
miniupnpd[18881]: ReceiveNATPMPOrPCPPacket: packet destination: fe80::642:1aff:fecd:54b0 scope_id=30
miniupnpd[18881]: PCP request received from [2600:1000:1000:1000:8c74:5f6e:28d5:e975]:55859 60bytes
miniupnpd[18881]: get_src_for_route_to ([2600:1000:1000:1000:8c74:5f6e:28d5:e975]:55859)
miniupnpd[18881]: get_lan_for_peer() looking for LAN interface index=30
miniupnpd[18881]: ifname=br0 index=30 str=192.168.10.1 addr=c0a80a01 mask=ffffff00
miniupnpd[18881]: PCP MAP: added mapping TCP 29642->2600:1000:1000:1000:8c74:5f6e:28d5:e975:29642 'PCP MAP 3626b54d941ec7c2dfb6fc37'
miniupnpd[18881]: Expire: parsing lease file line 'TCP;2600:1000:1000:1000:8c74:5f6e:28d5:e975;29642;(null);0;1;1713327304;PCP MAP 3626b54d941ec7c2dfb6fc37
'
miniupnpd[18881]: Expire: timestamp is '1713327304'
miniupnpd[18881]: Expire: current timestamp is '1713323704'
```

(Public IP addresses were obfuscated here)

The (null) string gets written to the lease file, I suspect that's what is triggering the aditionnal syslog error when it loads it back since the syslog errors don't show up on initial pinhole setup, only later on.

You can easily reproduce the issue just by installing qbittorrent and starting it (with its default settings).  It will try to use PCP out of the box without needing to change any of its settings, and attempt to create four pinholes.

**Comment by miniupnp** [comment]
OK so it is using PCP. You had not given this information...

**Comment by miniupnp** [comment]
@RMerl could you check if #726 fixes the issue ?

**Comment by RMerl** [comment]
> OK so it is using PCP. You had not given this information...

Sorry about that, I didn't know either until I reproduced the problem myself last night and got the debug log..  The initial reporter didn't mention anything beside the name of the program triggering it.

> @RMerl could you check if #726 fixes the issue ?

I'll give it a try later tonight and I'll get back to you.

**Comment by RMerl** [comment]
Looking good now.  The lease file shows an empty field, and there are no more errors when restarting miniupnpd and having it reparse the existing lease file.  ip6tables properly shows the pinholes, and they also get properly removed when existing qbittorrent.  Thank you!
