### ISSUE TITLE
Check nonce when renewing IPv6 pinhole

### ISSUE THREAD

**Issue by Sjors** [miniupnp/miniupnp#748]
When renewing an IPv6 pinhole via PCP the nonce is not checked.

A similar nonce check as in `DeletePCPMap` could be used...

https://github.com/miniupnp/miniupnp/blob/52357a7d1c7defff2ecf223ca8f4074305c7b206/miniupnpd/pcpserver.c#L1121-L1129

... in CreatePCPMap_FW, right after the `if(uid >= 0)` check:

https://github.com/miniupnp/miniupnp/blob/52357a7d1c7defff2ecf223ca8f4074305c7b206/miniupnpd/pcpserver.c#L1011-L1024

[rfc6887 section 11.2.1](https://datatracker.ietf.org/doc/html/rfc6887#section-11.2.1).  "Renewing a Mapping" doesn't mention that the nonce should be checked, but imo it follows from 11.2:

> The Mapping Nonce value [...] is used as part of the validation of PCP   responses (see below) by the PCP client **and validation for mapping refreshes** by the PCP server.

I don't think this is dangerous. If program A opens a port then program B can keep that port open. But probably better to fix.

**Comment by miniupnp** [comment]
@Sjors could you test the branch [issue-748](https://github.com/miniupnp/miniupnp/tree/issue-748) and tell me if that fixes the problem ?

**Comment by Sjors** [comment]
The code in ffe88f7e8fbc0afe3f62a8a6e58ea85e1a6abccf looks reasonable to me.

I'll see if I can reproduce the issue and verify the fix by patching (breaking) https://github.com/bitcoin/bitcoin/pull/30043

**Comment by Sjors** [comment]
I tested that when using a new nonce (https://github.com/Sjors/bitcoin/commit/99b2e2e893cfdffd71057e46f8209bd82b5f6406) the pinhole lease is not extended. The router returns `NOT_AUTHORIZED` when the renewal is attempted.

When I do use the correct nonce it fails with `NO_RESOURCES`, as expected due to #747.
