### ISSUE TITLE
miniupnpd: Do not SSDP notify using global-scope (ff0e::c) IPv6 multicast

### ISSUE THREAD

**Issue by Self-Hosting-Group** [miniupnp/miniupnp#757]
The global-scope multicast address is only defined in UDA 1.1 and not in UDA 1.0 Annex A - IPv6 and the UDA 2.0 specifications state that it **shall not** be used. UDA 1.1 defines that **either** global-scope (ff0e::c) or site-local scope (ff05::c) can be used, but global is preferred in complex topologies. As the site-local scope is defined in all versions of UDA, the daemon should probably only use it.

Currently the daemon already behaves in this way, but only if `UPNP_STRICT` is defined. See this:

https://github.com/miniupnp/miniupnp/blob/c735d2b39a7931de0c9ec1b59a3ffa0de4366536/miniupnpd/minissdp.c#L748-L752

**Comment by miniupnp** [comment]
I don't understand the problem here.

what do you mean by `IPv6` GH label ?

**Comment by miniupnp** [comment]
ah ok

**Comment by miniupnp** [comment]
So what's the issue here ?
