### ISSUE TITLE
miniupnpc: Please do not break API compatibility without documentation

### ISSUE THREAD

**Issue by Self-Hosting-Group** [miniupnp/miniupnp#758]
in a patch version update and without a "breaking changes" note in the changelog. API compatibility was last broken in the 2.2.8 version update, and was discovered by https://github.com/transmission/transmission/pull/6907#issuecomment-2158664001. The issue was https://github.com/miniupnp/miniupnp/issues/732 and the breaking change is https://github.com/miniupnp/miniupnp/commit/c0a50ce33e3b99ce8a96fd43049bb5b53ffac62f.

Such changes are better implemented in the planned minor miniupnpc version update 2.3.0, https://github.com/miniupnp/miniupnp/milestone/7.

*About documenting breaking changes*

- https://keepachangelog.com/
- https://www.conventionalcommits.org/
- https://semver.org/

**Comment by miniupnp** [comment]
that was documented in the changelog.

**Comment by VVD** [comment]
> that was documented in the changelog.

Total agree with this:
> Such changes are better implemented in the planned minor miniupnpc version update 2.3.0

**Comment by AMDmi3** [comment]
I'd rather say **do not break API in patch version**. You've broken a lot of consumers here.
