### ISSUE TITLE
miniupnpd: PCP client nonces (security feature) listable via UPnP IGD

### ISSUE THREAD

**Issue by Self-Hosting-Group** [miniupnp/miniupnp#759]
The UPnP IGD port mapping listing functions `GetListOfPortMappings` from IGDv2 and `GetSpecificPortMappingEntry` from IGDv1 can be used to get the PCP client nonces of active IPv4 port maps of all PCP clients (in the local network) in the `PortMappingDescription` field, which is not ideal from a security point of view. This can also be done by clients that are not allowed by the client permission rules.

*About PCP nonces*
PCP nonces, a security feature, prevent multiple client software (on the same device) from deleting/renewing each other's port maps. Also, as PCP uses UDP packets, these can be spoofed by other clients, so nonces are useful.

*Details*
These PCP nonces should not be accessible to clients, but must be kept by the daemon to validate PCP port map renewals and deletions. Currently, the PCP nonce is added internally to the description field, rather than being a separate field, as it is handled when using IGDv2 and IPv6 (pinhole's UniqueID), in which case it is a separate uid field in the lease file.

*Suggestion*
The PCP client nonce should also be separated from the description so that it cannot be listed via UPnP IGD. Probably the best solution would be a combined port map ID field that can hold the PCP client's port map nonce (96 bit) or the daemon's IGDv2 IPv6 port map UniqueID (32 bit) in the IPv4 and IPv6 lease files.

*PCP nonces are defined in RFC 6887 std., sections 11.2 and 11.3*
https://datatracker.ietf.org/doc/html/rfc6887#section-11.2

**Comment by miniupnp** [comment]
the fix is just to remove the Nonce from the response to `GetListOfPortMappings` and `GetSpecificPortMappingEntry`

**Comment by miniupnp** [comment]
another "fix" is to disable UPNP ...

**Comment by miniupnp** [comment]
@Self-Hosting-Group could you test the commit db26e82e22d5a315e1c0554a757d775631807b2d from the branch `759-hide-pcp-nonce-values-from-upnp-clients`, please ?

**Comment by miniupnp** [comment]
> > @Self-Hosting-Group could you test the commit [db26e82](https://github.com/miniupnp/miniupnp/commit/db26e82e22d5a315e1c0554a757d775631807b2d) from the branch `759-hide-pcp-nonce-values-from-upnp-clients`, please ?
> 
> None of the suggestions have been implemented, and the replacement with `x` seems unsightly. I therefore abstain from a review.

OK. 

> Why not use this first commit [d3b64dd](https://github.com/miniupnp/miniupnp/commit/d3b64dd28d95f0fced82277b7780f2357add976a)? And this also gives us the ability (even with IGD for IPv4) to always see the protocol used to create the port maps first in the description field visible in the router's web interface, which is great.

Because it is not compliant with the UPnP Standard. You can't change the UPnP Description just to please you...
