### ISSUE TITLE
miniupnpd: Improve UPnP IGD compatibility mode configuration option

### ISSUE THREAD

**Issue by Self-Hosting-Group** [miniupnp/miniupnp#760]
backward compatible. This will allow new modes and auto-build with `IGD_V2` and `ENABLE_IPV6` defined (more uniform builds), but with IGDv2 disabled by configuration by default, best when PR https://github.com/miniupnp/miniupnp/pull/714 is merged in a future (possibly 2.4.0) release. This would also bring the default miniupnpd builds/configuration into line with how most router projects actually use them.

*Proposed miniupnpd.conf documentation:*

```
# UPnP IGD compatibility mode (default igdv1)
# Available modes: igdv1 (IPv4-only), igdv2 and
# igdv2std (without known incompatible IGDv1 client workaround).
# IGDv1 by default as some IGDv1 clients still incompatible with IGDv2 routers.
# The incompatible Microsoft IGDv1 client always gets IGDv1 except with igd2std.
#upnp_igd_compat=igdv1
```

PR can be provided, where the old configuration option also allowed (`force_igd_desc_v1` with `yes` or `no`).

**Comment by miniupnp** [comment]
I just don't get what is the improvement.

Also what do you mean by "[...] how most router projects actually use them." ?
What are "most router projects" ?

**Comment by miniupnp** [comment]
the configuration option will be changed if "more and better" IGD compatibility modes are implemented.

The name does describe what it does.
