### ISSUE TITLE
miniupnpd: Build and config more inline with actual usage

### ISSUE THREAD

**Issue by Self-Hosting-Group** [miniupnp/miniupnp#763]
of the daemon for a more consistent behaviour and easier cross-distribution bug reporting by updating the initial configure defaults/configuration from 2005 with the next planned minor update (2.4.0) to the more current usage in 2024 on various router OSs.

Sometimes it took a long time, e.g. the UPnP IGD secure mode has not been enabled by default since its introduction in 2008, and was enabled very late in the project due to multiple user feedback in commit https://github.com/miniupnp/miniupnp/commit/f91a32ff02769701baa1f46c5751c0eb1b8f2f8d in May 2023, but routers had been doing this much earlier for strong security reasons (e.g. pfSense 2016/OpenWrt 2018).

### Use of miniupnpd in various router and general-purpose OSs

| OS                               | Router OS | IPv6 | UPnP IGDv2 | IGDv1 compat. by config | Lease file | Port in use | IPv6/IGDv2 inline with project | PCP/NAT-PMP by config inline with project | Version |
| ---------------------------------- | ----------- | ------ | ------------ | ------------------------- | ------------ | ------------- | -------------------------------- | ------------------------------------------- | --------- |
| OpenWrt                          | ✔️      | ✔️ | ✔️       | ✔️                    | ✔️       | ✔️        | ❌                             | ❌                                        | 2.3.6   |
| AsusWrt-Merlin                   | ✔️      | ✔️ | ✔️       | ✔️                    | ✔️       | ✔️        | ❌                             | ❌                                        | 2.3.6   |
| FreshTomato                      | ✔️      | ✔️ | ❌         | ❌ (unset, disabled)    | ✔️       | ✔️        | ❌                             | ❌                                        | 2.3.6   |
| OPNsense/pfSense (FreeBSD ports) | ✔️      | ✔️ | ❌         | ❌ (unset, disabled)    | ❌         | ✔️        | ❌                             | ❌                                        | 2.3.6   |
| Debian and derivates             | ❌        | ✔️ | ✔️       | ✔️ (asks)             | ✔️       | ✔️        | ❌                             | ✔️ (unset, disabled)                    | 2.3.7   |
| Fedora and derivates             | ❌        | ✔️ | ✔️       | ❌ (unset, disabled)    | ❌         | ❌          | ❌                             | ✔️ (unset, disabled)                    | 2.3.6   |
| Alpine                           | ❌        | ✔️ | ✔️       | ❌ (unset, disabled)    | ✔️       | ❌          | ❌                             | ✔️ (unset, disabled)                    | 2.3.3   |
| Chimera                          | ❌        | ✔️ | ✔️       | ❌ (unset, disabled)    | ✔️       | ✔️        | ❌                             | ✔️ (unset, disabled)                    | 2.3.6   |
| Miniupnpd project defaults       | ❌        | ❌   | ❌         | ❌                      | ❌         | ❌          | (disabled)                     | (disabled)                                |         |

### Recommendations

1. Enable IPv6 support by default at build time, and keep it enabled by default config as IPv6 is enabled everywhere.
2. Enable PCP/NAT-PMP protocol support by default config, allows IPv6 port maps with PCP even if IGDv2 is disabled for compatibility, like all router OSs.
3. Enable UPnP IGDv2 support by default at build time, and disable it by default for compatiblity by the UPnP IGD compatiblity mode configuration at runtime as there are still issues but allow users to easily change the mode. Follow the router OSs (compiled in but disabled by config) defaults.
4. The often used leasefile/portinuse support can possibly be enabled at the same time.

This allows the increasingly necessary IPv6 support for port maps to be more widely available with the new PCP enabled by default, and IPv6 for IGD (IGDv2) can be easily enabled with the (runtime) configuration option. Once adapted, all the above OSes (and many more) will have/maintain IPv6 support, but additonally with PCP/NAT-PMP by default, and the builds will be inline with the project's IPv6/IGDv2.

**Comment by miniupnp** [comment]
changing any default is likely to cause annoyance for packagers as I have experienced with c0a50ce33e3b99ce8a96fd43049bb5b53ffac62f :(

**Comment by miniupnp** [comment]
You may have noticed I don't have much time to spend for miniupnp.
So I prefer to focus on important issues (#768 #761 #759 #747).
Changing default build settings is unnecessary.

If  you don't agree with these priorities, you could read the license and start a fork.
