### ISSUE TITLE
miniupnpd: Port map listing broken since version 2.3.6

### ISSUE THREAD

**Issue by Self-Hosting-Group** [miniupnp/miniupnp#768]
Functions always return a `NewInternalPort` of `0` with IGDv2's `GetListOfPortMappings` and IGDv1's `GetSpecificPortMappingEntry`. Tested on Linux with nftables backend. After some analysis, commit 90fb7801ebb4c8358ee56814279097292d6c2458 was found to have introduced the bug.

**Comment by miniupnp** [comment]
@Self-Hosting-Group could you check if the commit 792757f of the branch `768-fix-nft-parse_rule_nat` fixes the issue ?
