### ISSUE TITLE
Project main download mirror `miniupnp.free.fr` was down for 20 days

### ISSUE THREAD

**Issue by Self-Hosting-Group** [miniupnp/miniupnp#770]
after the secondary (HTTPS-enabled) mirror `miniupnp.tuxfamily.org` was last down for 13 days starting 22 May. Issue previously reported in April 2024 #722. For a short time both mirrors were affected (21 July), see [uptimerobot.com](https://stats.uptimerobot.com/DwGDxUB914). As all tested distributions use only one mirror for building, this resulted in 14/15% failed builds over the last 90 days, or 47% over 30 days for `miniupnp.free.fr`.

![uptime-screenshot](https://github.com/user-attachments/assets/6c409631-ab51-4c06-9321-ea0136568b0c)

**Comment by miniupnp** [comment]
I'm very sorry for the website downtime.
There are 2 websites, so the probability both are down at the same time is low.

**Comment by miniupnp** [comment]
to add an asset to github : 
https://docs.github.com/en/rest/releases/assets?apiVersion=2022-11-28#update-a-release-asset

**Comment by miniupnp** [comment]
now I have everything in place to upload assets to github.
- https://github.com/miniupnp/miniupnp/releases/tag/miniupnpd_2_3_7
- https://github.com/miniupnp/miniupnp/releases/tag/miniupnpc_2_2_8
