### ISSUE TITLE
Is there a way to add limited time port forwarding without specifying IP.

### ISSUE THREAD

**Issue by gorucci** [miniupnp/miniupnp#788]
Hello. Thanks for the great project.

Backstory: Recently I've discovered the greatness of UPnP IGD (I can't believe there is no unicode slowpoke emoji yet). I've decided to transfer my static port forwardings from the router to the exposed service's docker compose (better encapsulation, and all this stuff).

```upnpc -e "super-secure-homelab-service" -r 40000 40000 TCP``` worked like a charm. It creates infinite port forwarding. However, this "lease" doesn't survive the router reboot. Moreover, in case of service stop, I should remove forwarding manually (perhaps it would not survive 24h, but have been tested only for 8h). So, I've decided to go with short-durated leases. Unfortunately, ```-r``` doesn't support duration parameter. According to the man page, the only two keys that support duration are ```-a``` and ```-n```, but both of them require an IP address. While I saw the workaround in #104, it doesn't look... perfect.

So, my question is: _Is there a way to create a lease with a predefined duration without specifying an IP address?_

**Comment by miniupnp** [comment]
there is no man page for `upnpc`.

however : 
```
$ upnpc -h
upnpc: miniupnpc library test client, version 2.2.8.
 (c) 2005-2024 Thomas Bernard.
More information at https://miniupnp.tuxfamily.org/ or http://miniupnp.free.fr/
[...]
Notes:
  protocol is UDP or TCP.
  Use "" for any remote_host and 0 for any remote_port.
  @ can be used in option -a, -n, -A and -G to represent local LAN address.

**Comment by gorucci** [comment]
> there is no man page for `upnpc`.

I was talking about https://manpages.debian.org/unstable/miniupnpc/upnpc.1.en.html. I saw the same text after `man upnpc` in ubuntu. Well, I'm noob in linux and don't differentiate between `man some-utill` and `some-util -h`. This case served me well. 

Ironically, aforementioned man page was good enough so I didn't make error, and didn't see your help text. Saw it only during (wrong) passing  of environment variables to upnpc.

**Comment by miniupnp** [comment]
It is possible this man page is added by the debian package.

**Comment by gorucci** [comment]
Yeah, I think it is. Thanks for your replies.
