### ISSUE TITLE
Lease file not created

### ISSUE THREAD

**Issue by sslevil** [miniupnp/miniupnp#82]
The lease file is not automatically created on service startup , in debug mode " miniupnpd: could not open lease file: /var/log/upnp.leases" shows up  , if the service is stooped the file is automatically deleted , as a workaround you can pre-touch  /var/log/upnp.leases before service start .

**Comment by miniupnp** [comment]
make sure the miniupnpd process has the right to create the  /var/log/upnp.leases file.

The lease file is NOT created on service startup, but when the first port mapping is added
