### ISSUE TITLE
AddPortMapping() failed with code 402 (Invalid Args)

### ISSUE THREAD

**Issue by yoch** [miniupnp/miniupnp#92]
I try to add redirection with upnpc for ipcamera, but I got the following error : AddPortMapping() failed with code 402. That a bit strange, because I added some redirections for my raspberry pi without any problem.

**$ upnpc -a 192.168.1.4 4001 4001 TCP**
upnpc : miniupnpc library test client. (c) 2006-2010 Thomas Bernard
Go to http://miniupnp.free.fr/ or http://miniupnp.tuxfamily.org/
for more information.
List of UPNP devices found on the network :
 desc: http://192.168.1.254:5678/desc/root
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

Found valid IGD : http://192.168.1.254:5678/control/wan_ip_connection
Local LAN ip address : 192.168.1.6
ExternalIPAddress = x.x.x.x
**AddPortMapping(4001, 4001, 192.168.1.4) failed with code 402 (Invalid Args)**
GetSpecificPortMappingEntry() failed with code 714 (NoSuchEntryInArray)

**Comment by khag7** [comment]
Figured it out!

Turns out some routers have limits on how many entries can be listed for UPnP. If you are getting error 402 try clearing out 1 or more entries and try again.
